CREATE  TABLE OPLQTSAP(
    REFERENCE_REVISION VARCHAR(36) NOT NULL,
    REFERENCE VARCHAR(36) NOT NULL,
    REVISION VARCHAR(36) NOT NULL
); 
ALTER TABLE OPLQTSAP ADD CONSTRAINT CONSTRAINT_SAP PRIMARY KEY(REFERENCE_REVISION); 

CREATE TABLE OPLQTFCT (EFCT_EDS_ID VARCHAR(36),EFCT_SAP_REFERENCE VARCHAR(36));
ALTER TABLE OPLQTFCT ADD CONSTRAINT EDS96_ID_FCT_FK FOREIGN KEY(EFCT_EDS_ID) REFERENCES OPLQTEDS(EDS_ID);  
ALTER TABLE OPLQTFCT ADD CONSTRAINT SAP96_REF_FCT_FK FOREIGN KEY(EFCT_SAP_REFERENCE) REFERENCES OPLQTSAP(REFERENCE_REVISION); 

CREATE TABLE OPLQTFNR (EFNR_EDS_ID VARCHAR(36),EFNR_SAP_REFERENCE VARCHAR(36));
ALTER TABLE OPLQTFNR ADD CONSTRAINT EDS96_ID_FNR_FK FOREIGN KEY(EFNR_EDS_ID) REFERENCES OPLQTEDS(EDS_ID);  
ALTER TABLE OPLQTFNR ADD CONSTRAINT SAP96_REF_FNR_FK FOREIGN KEY(EFNR_SAP_REFERENCE) REFERENCES OPLQTSAP(REFERENCE_REVISION); 
