-- Update the type
ALTER TABLE OPLQTSPP ADD (CSPP_XY_DATA_TMP CLOB);
UPDATE OPLQTSPP SET CSPP_XY_DATA_TMP = TO_CLOB(CSPP_XY_DATA);

ALTER TABLE OPLQTSPP DROP COLUMN CSPP_XY_DATA;
ALTER TABLE OPLQTSPP RENAME COLUMN CSPP_XY_DATA_TMP TO CSPP_XY_DATA;