
-- CHS table
CREATE  TABLE OPLQTCHS (
    COMPONENT_ID VARCHAR(255) NOT NULL,
    PART_NUMBER VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    USER_REF1 VARCHAR(255),
    USER_REF2 VARCHAR(255)
);
ALTER TABLE OPLQTCHS ADD CONSTRAINT CONSTRAINT_CHS PRIMARY KEY(COMPONENT_ID);

-- CHS's cavity table
CREATE  TABLE OPLQTCAV (
    ID VARCHAR(36) NOT NULL,
    CAVITY_ID VARCHAR(255),
    CONNECTION_NAME VARCHAR(255),
    CAVITY VARCHAR(255),
    PIN_TYPE VARCHAR(255),
    COMPONENT_ID VARCHAR(255) NOT NULL
);
ALTER TABLE OPLQTCAV ADD CONSTRAINT CONSTRAINT_CAV PRIMARY KEY(ID);
ALTER TABLE OPLQTCAV ADD CONSTRAINT COMPONENT_ID_FNR_FK FOREIGN KEY(COMPONENT_ID) REFERENCES OPLQTCHS(COMPONENT_ID);
