  -- Table OPLQT Eds (Pin)Type Comment
  CREATE TABLE "OPL"."OPLQTETC" 
   ( ID_COMMENT INTEGER NOT NULL ENABLE,
    EDS_ID VARCHAR2(36 BYTE) NOT NULL ENABLE, 
     PIN_TYPE VARCHAR(255) NOT NULL ENABLE,
     MESSAGE VARCHAR(255) );
     
    ALTER TABLE OPLQTETC ADD CONSTRAINT CONSTRAINT_ETC_PK PRIMARY KEY(EDS_ID,PIN_TYPE);
    ALTER TABLE OPLQTETC ADD CONSTRAINT CONSTRAINT_ETC_FK Foreign KEY(EDS_ID) REFERENCES OPLQTEDS (EDS_ID);
     
  -- Table OPLQT Eds Pin Connectivity
  CREATE TABLE "OPL"."OPLQTEPC" 
   ( 
     ID_COMMENT INTEGER NOT NULL ENABLE,
     EDS_ID VARCHAR2(36 BYTE) NOT NULL ENABLE, 
     CAVITY VARCHAR(255) NOT NULL ENABLE,
     PIN_TYPE VARCHAR(255) NOT NULL ENABLE,
     MESSAGE VARCHAR(255) );
     
    ALTER TABLE OPLQTEPC ADD CONSTRAINT CONSTRAINT_EPC_PK PRIMARY KEY(EDS_ID,CAVITY,PIN_TYPE);
    ALTER TABLE OPLQTEPC ADD CONSTRAINT CONSTRAINT_EPC_FK Foreign KEY(EDS_ID) REFERENCES OPLQTEDS (EDS_ID);