
  -- Table OPLQTBSX Eds BSX
  CREATE TABLE OPLQTBSX (
     BSX_UID  VARCHAR(36) NOT NULL,
     BSX_ID   VARCHAR(36) NOT NULL,
     BSX_NAME VARCHAR(255),
     BSX_PATH VARCHAR(255),
     BSX_COMMENT VARCHAR(255),
     EDS_ID   VARCHAR(36) NOT NULL
  );
  
  ALTER TABLE OPLQTBSX ADD CONSTRAINT CONSTRAINT_BSX_PK PRIMARY KEY(BSX_UID);
  ALTER TABLE OPLQTBSX ADD CONSTRAINT CONSTRAINT_BSX_FK FOREIGN KEY(EDS_ID) REFERENCES OPLQTEDS (EDS_ID);
  
  -- Table OPLQTBPN Eds BSX pin
  CREATE TABLE OPLQTBPN ( 
     BSXPIN_UID  VARCHAR(36)  NOT NULL,
     BSXPIN_NAME VARCHAR(255) NOT NULL,
     BSXPIN_TYPE VARCHAR(4)   NOT NULL,
     BSX_UID     VARCHAR(36)  NOT NULL
  );
     
  ALTER TABLE OPLQTBPN ADD CONSTRAINT CONSTRAINT_BPN_PK PRIMARY KEY(BSXPIN_UID);
  ALTER TABLE OPLQTBPN ADD CONSTRAINT CONSTRAINT_BPN_FK FOREIGN KEY(BSX_UID) REFERENCES OPLQTBSX (BSX_UID);
  