ALTER TABLE OPLQTEPC ADD SEDS_ID varchar(255);
ALTER TABLE OPLQTEPC ADD CONSTRAINT CONSTRAINT_SEDS_FK FOREIGN KEY(SEDS_ID) REFERENCES OPLQTSUY (SEDS_ID);    
ALTER TABLE OPLQTEPC ADD WI_NAME varchar(255);
ALTER TABLE OPLQTEPC ADD SP_NAME varchar(255);
ALTER TABLE OPLQTEPC ADD CP_NAME varchar(255);
ALTER TABLE OPLQTEPC ADD CP_COMMENT varchar(255);


-- Cavity Wired Properties
    CREATE TABLE "OPL"."OPLQTCWP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TIME NUMBER NOT NULL ENABLE,
     PROPERTY_CURRENT NUMBER NOT NULL ENABLE ); 
    
ALTER TABLE OPLQTCWP ADD CONSTRAINT CONSTRAINT_WI_PK PRIMARY KEY(ID);

-- Cavity Complex Profile
    CREATE TABLE "OPL"."OPLQTCCP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TIME NUMBER NOT NULL ENABLE,
     PROPERTY_CURRENT NUMBER NOT NULL ENABLE );
     
     
ALTER TABLE OPLQTCCP ADD CONSTRAINT CONSTRAINT_CCP_PK PRIMARY KEY(ID);

-- Eds Complex Propertie
    CREATE TABLE "OPL"."OPLQTECP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TYPE INTEGER NOT NULL ENABLE, 
     PROPERTY_VALUE NUMBER NOT NULL ENABLE,
     PROPERTY_COMMENT varchar(255));
     
     
ALTER TABLE OPLQTECP ADD CONSTRAINT CONSTRAINT_ECP_WI_PK PRIMARY KEY(ID);

-- Eds Simple Profile
    CREATE TABLE "OPL"."OPLQTESP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TYPE INTEGER NOT NULL ENABLE, 
     PROPERTY_VALUE NUMBER,
     USERNAME VARCHAR(255),
     COMMENTS  VARCHAR(255));
     
ALTER TABLE OPLQTESP ADD CONSTRAINT CONSTRAINT_ESP_WI_PK PRIMARY KEY(ID);
