-- Delete Data
delete from OPLQTETC;
delete from OPLQTEPC;
delete from OPLQTBPN;
delete from OPLQTBSX;
delete from OPLQTCWP;
delete from OPLQTCCP;
delete from OPLQTECP;
delete from OPLQTESP;
-- Drop the old tables
drop table OPLQTETC;
drop table OPLQTEPC;
drop table OPLQTBPN;
drop table OPLQTBSX;
drop table OPLQTCWP;
drop table OPLQTCCP;
drop table OPLQTECP;
drop table OPLQTESP;

-- SPRINT10_B

  -- Table OPLQT Eds (Pin)Type Comment
  CREATE TABLE "OPL"."OPLQTETC" 
   ( ID_COMMENT INTEGER NOT NULL ENABLE,
    EDS_ID VARCHAR2(36 BYTE) NOT NULL ENABLE, 
     PIN_TYPE VARCHAR(255) NOT NULL ENABLE,
     MESSAGE VARCHAR(255) );
     
    ALTER TABLE OPLQTETC ADD CONSTRAINT CONSTRAINT_ETC_PK PRIMARY KEY(EDS_ID,PIN_TYPE);
    ALTER TABLE OPLQTETC ADD CONSTRAINT CONSTRAINT_ETC_FK Foreign KEY(EDS_ID) REFERENCES OPLQTEDS (EDS_ID);
     
  -- Table OPLQT Eds Pin Connectivity
  CREATE TABLE "OPL"."OPLQTEPC" 
   ( 
     ID_COMMENT INTEGER NOT NULL ENABLE,
     EDS_ID VARCHAR2(36 BYTE) NOT NULL ENABLE, 
     CAVITY VARCHAR(255) NOT NULL ENABLE,
     PIN_TYPE VARCHAR(255) NOT NULL ENABLE,
     MESSAGE VARCHAR(255) );
     
    ALTER TABLE OPLQTEPC ADD CONSTRAINT CONSTRAINT_EPC_PK PRIMARY KEY(EDS_ID,CAVITY,PIN_TYPE);
    ALTER TABLE OPLQTEPC ADD CONSTRAINT CONSTRAINT_EPC_FK Foreign KEY(EDS_ID) REFERENCES OPLQTEDS (EDS_ID);
    
-- SPRINT11_A


  -- Table OPLQTBSX Eds BSX
  CREATE TABLE OPLQTBSX (
     BSX_UID  VARCHAR(36) NOT NULL,
     BSX_ID   VARCHAR(36) NOT NULL,
     BSX_NAME VARCHAR(255),
     BSX_PATH VARCHAR(255),
     BSX_COMMENT VARCHAR(255),
     EDS_ID   VARCHAR(36) NOT NULL
  );
  
  ALTER TABLE OPLQTBSX ADD CONSTRAINT CONSTRAINT_BSX_PK PRIMARY KEY(BSX_UID);
  ALTER TABLE OPLQTBSX ADD CONSTRAINT CONSTRAINT_BSX_FK FOREIGN KEY(EDS_ID) REFERENCES OPLQTEDS (EDS_ID);
  
  -- Table OPLQTBPN Eds BSX pin
  CREATE TABLE OPLQTBPN ( 
     BSXPIN_UID  VARCHAR(36)  NOT NULL,
     BSXPIN_NAME VARCHAR(255) NOT NULL,
     BSXPIN_TYPE VARCHAR(4)   NOT NULL,
     BSX_UID     VARCHAR(36)  NOT NULL
  );
     
  ALTER TABLE OPLQTBPN ADD CONSTRAINT CONSTRAINT_BPN_PK PRIMARY KEY(BSXPIN_UID);
  ALTER TABLE OPLQTBPN ADD CONSTRAINT CONSTRAINT_BPN_FK FOREIGN KEY(BSX_UID) REFERENCES OPLQTBSX (BSX_UID);
  
-- SPRINT11_B

ALTER TABLE OPLQTEPC ADD SEDS_ID varchar(255);
ALTER TABLE OPLQTEPC ADD CONSTRAINT CONSTRAINT_SEDS_FK FOREIGN KEY(SEDS_ID) REFERENCES OPLQTSUY (SEDS_ID);    
ALTER TABLE OPLQTEPC ADD WI_NAME varchar(255);
ALTER TABLE OPLQTEPC ADD SP_NAME varchar(255);
ALTER TABLE OPLQTEPC ADD CP_NAME varchar(255);
ALTER TABLE OPLQTEPC ADD CP_COMMENT varchar(255);


-- Cavity Wired Properties
    CREATE TABLE "OPL"."OPLQTCWP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TIME NUMBER NOT NULL ENABLE,
     PROPERTY_CURRENT NUMBER NOT NULL ENABLE ); 
    
ALTER TABLE OPLQTCWP ADD CONSTRAINT CONSTRAINT_WI_PK PRIMARY KEY(ID);

-- Cavity Complex Profile
    CREATE TABLE "OPL"."OPLQTCCP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TIME NUMBER NOT NULL ENABLE,
     PROPERTY_CURRENT NUMBER NOT NULL ENABLE );
     
     
ALTER TABLE OPLQTCCP ADD CONSTRAINT CONSTRAINT_CCP_PK PRIMARY KEY(ID);

-- Eds Complex Propertie
    CREATE TABLE "OPL"."OPLQTECP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TYPE INTEGER NOT NULL ENABLE, 
     PROPERTY_VALUE NUMBER NOT NULL ENABLE,
     PROPERTY_COMMENT varchar(255));
     
     
ALTER TABLE OPLQTECP ADD CONSTRAINT CONSTRAINT_ECP_WI_PK PRIMARY KEY(ID);

-- Eds Simple Profile
    CREATE TABLE "OPL"."OPLQTESP" 
   ( 
     ID INTEGER NOT NULL ENABLE,
     WI_ID INTEGER NOT NULL ENABLE, 
     PROPERTY_TYPE INTEGER NOT NULL ENABLE, 
     PROPERTY_VALUE NUMBER,
     USERNAME VARCHAR(255),
     COMMENTS  VARCHAR(255));
     
ALTER TABLE OPLQTESP ADD CONSTRAINT CONSTRAINT_ESP_WI_PK PRIMARY KEY(ID);

-- SPRINT12_A

ALTER TABLE OPLQTEPC ADD R_MAX NUMBER;
ALTER TABLE OPLQTEPC ADD MIN_SECTION varchar(255);
ALTER TABLE OPLQTETC ADD T_MAX NUMBER;
ALTER TABLE OPLQTETC ADD T_MIN NUMBER;

-- SPRINT12_B

ALTER TABLE OPLQTEPC ADD IF_IMPEDANCE NUMBER;
