

set DEFINE OFF;


CREATE  TABLE EDS_GLOBAL_CONF(
    CONF_KEY VARCHAR(32) NOT NULL,
    CONF_VALUE_TYPE VARCHAR(32) NOT NULL,
    CONF_VALUE VARCHAR(512)
);       
 

ALTER TABLE EDS_GLOBAL_CONF ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY(CONF_KEY);  
-- 3 +/- SELECT COUNT(*) FROM EDS_GLOBAL_CONF;         
CREATE  TABLE EDS_PROJECT(
    P_ID VARCHAR(36) NOT NULL,
    P_NAME VARCHAR(1024) NOT NULL,
    P_DATE_FIRST_STAGE TIMESTAMP,
    P_W_ID_FIRST_STAGE VARCHAR(36),
    P_DATE_SECOND_STAGE TIMESTAMP,
    P_W_ID_SECOND_STAGE VARCHAR(36),
    P_DATE_THIRD_STAGE TIMESTAMP,
    P_W_ID_THIRD_STAGE VARCHAR(36),
    P_DATE_FOURTH_STAGE TIMESTAMP,
    P_W_ID_FOURTH_STAGE VARCHAR(36),
    P_INDEX INT NOT NULL
);   



          
ALTER TABLE EDS_PROJECT ADD CONSTRAINT CONSTRAINT_BC PRIMARY KEY(P_ID);         
-- 84 +/- SELECT COUNT(*) FROM EDS_PROJECT;            
CREATE  TABLE EDS_COMPONENT_TYPE(
    CT_ID VARCHAR(36) NOT NULL,
    CT_NAME VARCHAR(36) NOT NULL,
    CT_INDEX INT NOT NULL,
    CT_BTTBT_OK_FORMSET VARCHAR(512),
    CT_BTTBT_KO_FORMSET VARCHAR(512)
);     


ALTER TABLE EDS_COMPONENT_TYPE ADD CONSTRAINT CONSTRAINT_B4 PRIMARY KEY(CT_ID); 
-- 10 +/- SELECT COUNT(*) FROM EDS_COMPONENT_TYPE;     
CREATE  TABLE EDS_PROJECT_EDS(
    PEDS_ID VARCHAR(36) NOT NULL,
    PEDS_P_ID VARCHAR(36) NOT NULL,
    PEDS_EDS_ID VARCHAR(36) NOT NULL,
    PEDS_RECONDUCTION_DATE TIMESTAMP,
    PEDS_COUNT INT,
    PEDS_RECONDUCT_WITH_MODIF INT
);   




     
ALTER TABLE EDS_PROJECT_EDS ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY(PEDS_ID);   
-- 559 +/- SELECT COUNT(*) FROM EDS_PROJECT_EDS;       
CREATE  TABLE EDS_NUMBER_96K(
    N_ID VARCHAR(36) NOT NULL,
    N_VALUE VARCHAR(36) NOT NULL
); 
ALTER TABLE EDS_NUMBER_96K ADD CONSTRAINT CONSTRAINT_A9 PRIMARY KEY(N_ID);      
-- 96 +/- SELECT COUNT(*) FROM EDS_NUMBER_96K;         
CREATE  TABLE EDS_EDS_NUMBER_96K(
    EDSN_EDS_ID VARCHAR(36) NOT NULL,
    EDSN_N_ID VARCHAR(36) NOT NULL
);    
ALTER TABLE EDS_EDS_NUMBER_96K ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(EDSN_EDS_ID, EDSN_N_ID); 
-- 88 +/- SELECT COUNT(*) FROM EDS_EDS_NUMBER_96K;     
CREATE  TABLE EDS_QCF(
    QCF_ID VARCHAR(36) NOT NULL,
    QCF_1 INTEGER,
    QCF_2 INTEGER,
    QCF_3 INTEGER,
    QCF_C1 INTEGER,
    QCF_C2 INTEGER,
    QCF_C3 INTEGER,
    QCF_C4 INTEGER
);               
ALTER TABLE EDS_QCF ADD CONSTRAINT CONSTRAINT_BAD5 PRIMARY KEY(QCF_ID);         
-- 307 +/- SELECT COUNT(*) FROM EDS_QCF;               
CREATE  TABLE EDS_PRIMARY_CURENT(
    PCEDS_ID VARCHAR(36) NOT NULL,
    PCEDS_EDS_ID VARCHAR(36) NOT NULL,
    PC_COMMENT VARCHAR(1024),
    PC_IMAGE VARCHAR(225)
);           
ALTER TABLE EDS_PRIMARY_CURENT ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY(PCEDS_ID);               
-- 459 +/- SELECT COUNT(*) FROM EDS_PRIMARY_CURENT;    
CREATE  TABLE EDS_PROJECT_PRIMARY_CURENT(
    PPC_P_ID VARCHAR(36) NOT NULL,
    PPC_PCEDS_ID VARCHAR(36) NOT NULL
);            
ALTER TABLE EDS_PROJECT_PRIMARY_CURENT ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY(PPC_P_ID, PPC_PCEDS_ID);         
-- 0 +/- SELECT COUNT(*) FROM EDS_PROJECT_PRIMARY_CURENT;              
CREATE  TABLE EDS_SUPPLY(
    SEDS_ID VARCHAR(36) NOT NULL,
    SEDS_EDS_ID VARCHAR(36) NOT NULL,
    S_PCEDS_ID VARCHAR(36),
    S_PSEDS_ID VARCHAR(36),
    S_RCEDS_ID VARCHAR(36),
    S_RSEDS_ID VARCHAR(36),
    S_CCEDS_ID VARCHAR(36),
    S_CSEDS_ID VARCHAR(36),
    S_PMSEDS_ID VARCHAR(36),
    S_PMCEDS_ID VARCHAR(36),
    SEDS_SUPPLY_NAME VARCHAR(225)
);         
ALTER TABLE EDS_SUPPLY ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(SEDS_ID);        
-- 653 +/- SELECT COUNT(*) FROM EDS_SUPPLY;            
CREATE  TABLE EDS_PRIMARY_SUPPLY(
    PSEDS_ID VARCHAR(36) NOT NULL,
    PSEDS_REF VARCHAR(36) NOT NULL,
    PSEDS_W_ID VARCHAR(36) NOT NULL,
    PS_RANK INTEGER,
    PSEDS_SUPPLY_NAME VARCHAR(225),
    PSEDS_TBT_BT VARCHAR(3),
    PSEDS_I_VEILLE REAL,
    PSEDS_I_REVEILLE_INACTIF REAL,
    PSEDS_I_NOM_STAB REAL,
    PSEDS_I_PIRECAS_STAB REAL,
    PSEDS_SUPPLY_NAME_IFORM_BY VARCHAR(1024),
    PSEDS_SUP_TYPE_SUP_NAM_IF_BY VARCHAR(1024),
    PSEDS_I_VEILLE_IFORM_BY VARCHAR(1024),
    PSEDS_REVEILLE_IFORM_BY VARCHAR(1024),
    PSEDS_I_NOM_STAB_IFORM_BY VARCHAR(1024),
    PSEDS_I_PIRECAS_STAB_IF_BY VARCHAR(1024),
    PSEDS_SUPPLY_NAME_COMMENT VARCHAR(1024),
    PSEDS_SUP_TYPE_SUP_NAM_COM VARCHAR(1024),
    PSEDS_I_VEILLE_COMMENT VARCHAR(1024),
    PSEDS_REVEILLE_COMMENT VARCHAR(1024),
    PSEDS_I_NOM_STAB_COMMENT VARCHAR(1024),
    PSEDS_I_PIRECAS_COMMENT VARCHAR(1024)
); 
ALTER TABLE EDS_PRIMARY_SUPPLY ADD CONSTRAINT CONSTRAINT_AEA PRIMARY KEY(PSEDS_ID);             
-- 621 +/- SELECT COUNT(*) FROM EDS_PRIMARY_SUPPLY;    
CREATE  TABLE EDS_CRT_APPELLE_ACTIVATION(
    CAAEDS_ID VARCHAR(36) NOT NULL,
    CAAEDS_TMIN_IMAX_PULSE REAL,
    CAAEDS_TMOY_IMAX_PULSE REAL,
    CAAEDS_TMAX_IMAX_PULSE REAL,
    CAAEDS_TMOY_IMAX_PULSE_COM VARCHAR(1024),
    CAAEDS_TMIN_DT_PULSE REAL,
    CAAEDS_TMOY_DT_PULSE REAL,
    CAAEDS_TMAX_DT_PULSE REAL,
    CAAEDS_TMOY_DT_PULSE_COMMENT VARCHAR(1024),
    CAAEDS_TITRE VARCHAR(1024),
    CAAEDS_REMOVE INT
);             
ALTER TABLE EDS_CRT_APPELLE_ACTIVATION ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(CAAEDS_ID);      
-- 760 +/- SELECT COUNT(*) FROM EDS_CRT_APPELLE_ACTIVATION;            
CREATE  TABLE EDS_GROUND_ROBUST_CURENT(
    GRC_ID VARCHAR(36) NOT NULL,
    GSEDS_TITRE_MASSE VARCHAR(1024),
    GSEDS_I_VEILLE REAL,
    GSEDS_I_REVEILLE_INACTIF REAL,
    GSEDS_I_NOM_STAB REAL,
    GSEDS_I_PIRECAS_STAB REAL,
    GSEDS_I_MST REAL,
    GSEDS_I_DELTA_T_MST REAL,
    GSEDS_I_PIC REAL,
    GSEDS_T_IPIC REAL,
    GSEDS_I_VEILLE_IFORM_BY VARCHAR(1024),
    GSEDS_REVEILLE_IFORM_BY VARCHAR(1024),
    GSEDS_I_NOM_STAB_IFORM_BY VARCHAR(1024),
    GSEDS_I_PIRECAS_STAB_IF_BY VARCHAR(1024),
    GSEDS_I_PIC_IFORM_BY VARCHAR(1024),
    GSEDS_T_IPIC_IFORM_BY VARCHAR(1024),
    GSEDS_I_VEILLE_COMMENT VARCHAR(1024),
    GSEDS_REVEILLE_COMMENT VARCHAR(1024),
    GSEDS_I_NOM_STAB_COMMENT VARCHAR(1024),
    GSEDS_I_PIRECAS_COMMENT VARCHAR(1024),
    GSEDS_I_PIC_COMMENT VARCHAR(1024),
    GSEDS_T_IPIC_COMMENT VARCHAR(1024)
);               
ALTER TABLE EDS_GROUND_ROBUST_CURENT ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY(GRC_ID);           
-- 302 +/- SELECT COUNT(*) FROM EDS_GROUND_ROBUST_CURENT;              
CREATE  TABLE EDS_PROJECT_ROBUST_CURENT(
    PRC_P_ID VARCHAR(36) NOT NULL,
    PRC_RCEDS_ID VARCHAR(36) NOT NULL
);             
ALTER TABLE EDS_PROJECT_ROBUST_CURENT ADD CONSTRAINT CONSTRAINT_90 PRIMARY KEY(PRC_P_ID, PRC_RCEDS_ID);         
-- 0 +/- SELECT COUNT(*) FROM EDS_PROJECT_ROBUST_CURENT;               
CREATE  TABLE EDS_ROBUST_SUPPLY(
    RSEDS_ID VARCHAR(36) NOT NULL,
    RSEDS_REF VARCHAR(36) NOT NULL,
    RSEDS_W_ID VARCHAR(36) NOT NULL,
    RSEDS_SUPPLY_NAME VARCHAR(225),
    RSEDS_TBT_BT VARCHAR(3),
    RSEDS_U_CARAC_NAME VARCHAR(25),
    RSEDS_I_VEILLE REAL,
    RSEDS_I_REVEILLE_INACTIF REAL,
    RSEDS_I_NOM_STAB REAL,
    RSEDS_I_PIRECAS_STAB REAL,
    RSEDS_U_MIN REAL,
    RSEDS_U_MOY REAL,
    RSEDS_U_MAX REAL,
    RSEDS_I_MAX REAL,
    RSEDS_T_IMAX REAL,
    RSEDS_U_CARAC_VALUE REAL,
    RSEDS_SUPPLY_NAME_IFORM_BY VARCHAR(1024),
    RSEDS_SUP_TYPE_SUP_NAM_IF_BY VARCHAR(1024),
    RSEDS_I_VEILLE_IFORM_BY VARCHAR(1024),
    RSEDS_REVEILLE_IFORM_BY VARCHAR(1024),
    RSEDS_I_NOM_STAB_IFORM_BY VARCHAR(1024),
    RSEDS_I_PIRECAS_STAB_IF_BY VARCHAR(1024),
    RSEDS_U_MIN_INFORM_BY VARCHAR(1024),
    RSEDS_U_MOY_INFORM_BY VARCHAR(1024),
    RSEDS_U_MAX_INFORM_BY VARCHAR(1024),
    RSEDS_I_MAX_INFORM_BY VARCHAR(1024),
    RSEDS_T_IMAX_INFORM_BY VARCHAR(1024),
    RSEDS_U_CARAC_INFORM_BY VARCHAR(1024),
    RSEDS_SUPPLY_NAME_COMMENT VARCHAR(1024),
    RSEDS_SUP_TYPE_SUP_NAM_COM VARCHAR(1024),
    RSEDS_I_VEILLE_COMMENT VARCHAR(1024),
    RSEDS_REVEILLE_COMMENT VARCHAR(1024),
    RSEDS_I_NOM_STAB_COMMENT VARCHAR(1024),
    RSEDS_I_PIRECAS_COMMENT VARCHAR(1024),
    RSEDS_U_MIN_COMMENT VARCHAR(1024),
    RSEDS_U_MOY_COMMENT VARCHAR(1024),
    RSEDS_U_MAX_COMMENT VARCHAR(1024),
    RSEDS_I_MAX_COMMENT VARCHAR(1024),
    RSEDS_T_IMAX_COMMENT VARCHAR(1024),
    RSEDS_U_CARAC_COMMENT VARCHAR(1024),
    RSEDS_I_CONSO_PARC REAL,
    RSEDS_I_CONSO_PARC_INFORM_BY VARCHAR(1024),
    RSEDS_I_CONSO_PARC_COMMENT VARCHAR(1024),
    RSEDS_ORGANE VARCHAR(1024)
);     
ALTER TABLE EDS_ROBUST_SUPPLY ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(RSEDS_ID);
-- 524 +/- SELECT COUNT(*) FROM EDS_ROBUST_SUPPLY;     
CREATE  TABLE EDS_GROUND(
    GEDS_ID VARCHAR(36) NOT NULL,
    G_GRCEDS_ID VARCHAR(36),
    G_RCEDS_ID VARCHAR(36)
);           
ALTER TABLE EDS_GROUND ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY(GEDS_ID);        
-- 302 +/- SELECT COUNT(*) FROM EDS_GROUND;            
CREATE  TABLE EDS_RVROI(
    RVROIEDS_ID VARCHAR(36) NOT NULL,
    RVROIEDS_MIN_IV_MOT_NO_T REAL,
    RVROIEDS_MOY_IV_MOT_NO_T REAL,
    RVROIEDS_MAX_IV_MOT_NO_T REAL,
    RVEDS_MIN_IV_8H_MOT_NO_T REAL,
    RVEDS_MOY_IV_8H_MOT_NO_T REAL,
    RVEDS_MAX_IV_8H_MOT_NO_T REAL,
    RVEDS_MIN_IV_21H_EN_NO_T REAL,
    RVEDS_MOY_IV_21H_EN_NO_T REAL,
    RVEDS_MAX_IV_21H_EN_NO_T REAL,
    RVEDS_MIN_IV_30H_EN_NO_T REAL,
    RVEDS_MOY_IV_30H_EN_NO_T REAL,
    RVEDS_MAX_IV_30H_EN_NO_T REAL,
    RVEDS_MIN_IREV_IN_EN_NO_T REAL,
    RVEDS_MOY_IREV_IN_EN_NO_T REAL,
    RVEDS_MAX_IREV_IN_EN_NO_T REAL,
    RVEDS_MIN_I_ECO_MOT_NO_T REAL,
    RVEDS_MOY_I_ECO_MOT_NO_T REAL,
    RVEDS_MAX_I_ECO_MOT_NO_T REAL,
    RVEDS_MIN_IREV_IN_10V_EN_T REAL,
    RVEDS_MIN_IREV_IN_13V_EN_T REAL,
    RVEDS_MIN_IREV_IN_15V_EN_T REAL,
    RVEDS_MOY_IREV_IN_10V_EN_T REAL,
    RVEDS_MOY_IREV_IN_13V_EN_T REAL,
    RVEDS_MOY_IREV_IN_15V_EN_T REAL,
    RVEDS_MAX_IREV_IN_10V_EN_T REAL,
    RVEDS_MAX_IREV_IN_13V_EN_T REAL,
    RVEDS_MAX_IREV_IN_15V_EN_T REAL,
    RVEDS_IV_MOT_NO_TOURANT_COM VARCHAR(1024),
    RVEDS_IV_8H_EN_NO_TOURANT_COM VARCHAR(1024),
    RVEDS_IV_21H_EN_NO_ON_COM VARCHAR(1024),
    RVEDS_IV_30H_EN_NO_ON_COM VARCHAR(1024),
    RVEDS_IREV_INA_EN_NO_ON_COM VARCHAR(1024),
    RVEDS_I_ECO_EN_NO_TOURANT_COM VARCHAR(1024),
    RVEDS_IREV_INA_10V_EN_ON_COM VARCHAR(1024),
    RVEDS_IREV_INA_13V_EN_ON_COM VARCHAR(1024),
    RVEDS_IREV_INA_15V_EN_ON_COM VARCHAR(1024)
); 
ALTER TABLE EDS_RVROI ADD CONSTRAINT CONSTRAINT_D PRIMARY KEY(RVROIEDS_ID);     
-- 612 +/- SELECT COUNT(*) FROM EDS_RVROI;             
CREATE  TABLE EDS_MODE_PARC(
    MPEDS_ID VARCHAR(36) NOT NULL,
    MPEDS_QCF1 VARCHAR(5),
    MPEDS_TMOY_MODE_PARC REAL,
    MPEDS_TMAX_MODE_PARC REAL,
    MPEDS_TMOY_MODE_PARC_COMMENT VARCHAR(1024)
);       
ALTER TABLE EDS_MODE_PARC ADD CONSTRAINT CONSTRAINT_71 PRIMARY KEY(MPEDS_ID);   
-- 12 +/- SELECT COUNT(*) FROM EDS_MODE_PARC;          
CREATE  TABLE EDS_MODE_MONTAGE(
    MMEDS_ID VARCHAR(36) NOT NULL,
    MMEDS_TMOY_MODE_MONTAGE REAL,
    MMEDS_TMOY_MODE_MONTAGE_COM VARCHAR(1024),
    MMEDS_MODE_MONTAGE_TITRE VARCHAR(1024),
    MMEDS_REMOVE INTEGER
);      
ALTER TABLE EDS_MODE_MONTAGE ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY(MMEDS_ID); 
-- 0 +/- SELECT COUNT(*) FROM EDS_MODE_MONTAGE;        
CREATE  TABLE EDS_COURANT_MISE_SOUS_TENSION(
    CMSTEDS_ID VARCHAR(36) NOT NULL,
    CMSTEDS_TPIRECAS_IMST REAL,
    CMSTEDS_TPIRECAS_DT REAL,
    CMSTEDS_TPIRECAS_IMST_COM VARCHAR(1024),
    CMSTEDS_TPIRECAS_DT_COMMENT VARCHAR(1024)
);    
ALTER TABLE EDS_COURANT_MISE_SOUS_TENSION ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY(CMSTEDS_ID);  
-- 612 +/- SELECT COUNT(*) FROM EDS_COURANT_MISE_SOUS_TENSION;         
CREATE  TABLE EDS_COURANT_CYCLE(
    CCEDS_ID VARCHAR(36) NOT NULL,
    CCEDS_NAME VARCHAR(1024),
    CCEDS_TCYCLE REAL,
    CCEDS_COMENT VARCHAR(1024),
    CCEDS_REMOVE INT,
    CCEDS_WITH_MODIF INTEGER
);   
ALTER TABLE EDS_COURANT_CYCLE ADD CONSTRAINT CONSTRAINT_65 PRIMARY KEY(CCEDS_ID);               
-- 2 +/- SELECT COUNT(*) FROM EDS_COURANT_CYCLE;       
CREATE  TABLE EDS_CRT_NOMINALE_ACTIVATION(
    CNAEDS_ID VARCHAR(36) NOT NULL,
    CNEDS_NAME VARCHAR(1024),
    CNAEDS_REMOVE INT,
    CNAEDS_I_EFFICACE INT,
    CNAEDS_TMIN_STAB_MNT REAL,
    CNAEDS_IMIN_STAB_MNT REAL,
    CNAEDS_TMOY_STAB_MNT REAL,
    CNAEDS_IMOY_STAB_MNT REAL,
    CNAEDS_TMAX_STAB_MNT REAL,
    CNAEDS_IMAX_STAB_MNT REAL,
    CNAEDS_STAB_MNT_COMMENT VARCHAR(1024),
    CNAEDS_TMIN_PIRE_CAS_MNT REAL,
    CNAEDS_IMIN_PIRE_CAS_MNT REAL,
    CNAEDS_TMOY_PIRE_CAS_MNT REAL,
    CNAEDS_IMOY_PIRE_CAS_MNT REAL,
    CNAEDS_TMAX_PIRE_CAS_MNT REAL,
    CNAEDS_IMAX_PIRE_CAS_MNT REAL,
    CNAEDS_PIRE_CAS_MNT_COMMENT VARCHAR(1024),
    CNAEDS_TMIN_STAB_10_MT REAL,
    CNAEDS_IMIN_STAB_10_MT REAL,
    CNAEDS_TMOY_STAB_10_MT REAL,
    CNAEDS_IMOY_STAB_10_MT REAL,
    CNAEDS_TMAX_STAB_10_MT REAL,
    CNAEDS_IMAX_STAB_10_MT REAL,
    CNAEDS_STAB_10_MT_COMMENT VARCHAR(1024),
    CNAEDS_TMIN_STAB_13_MT REAL,
    CNAEDS_IMIN_STAB_13_MT REAL,
    CNAEDS_TMOY_STAB_13_MT REAL,
    CNAEDS_IMOY_STAB_13_MT REAL,
    CNAEDS_TMAX_STAB_13_MT REAL,
    CNAEDS_IMAX_STAB_13_MT REAL,
    CNAEDS_STAB_13_MT_COMMENT VARCHAR(1024),
    CNAEDS_TMIN_STAB_15_MT REAL,
    CNAEDS_IMIN_STAB_15_MT REAL,
    CNAEDS_TMOY_STAB_15_MT REAL,
    CNAEDS_IMOY_STAB_15_MT REAL,
    CNAEDS_TMAX_STAB_15_MT REAL,
    CNAEDS_IMAX_STAB_15_MT REAL,
    CNAEDS_STAB_15_MT_COMMENT VARCHAR(1024),
    CNAEDS_MIN_PI_CAS_10_MT REAL,
    CNAEDS_IMIN_PI_CAS_10_MT REAL,
    CNAEDS_MOY_PI_CAS_10_MT REAL,
    CNAEDS_IMOY_PI_CAS_10_MT REAL,
    CNAEDS_MAX_PI_CAS_10_MT REAL,
    CNAEDS_IMAX_PI_CAS_10_MT REAL,
    CNAEDS_PIRE_CAS_10_MT_COM VARCHAR(1024),
    CNAEDS_MIN_PI_CAS_13_MT REAL,
    CNAEDS_IMIN_PI_CAS_13_MT REAL,
    CNAEDS_MOY_PI_CAS_13_MT REAL,
    CNAEDS_IMOY_PI_CAS_13_MT REAL,
    CNAEDS_MAX_PI_CAS_13_MT REAL,
    CNAEDS_IMAX_PI_CAS_13_MT REAL,
    CNAEDS_PIRE_CAS_13_MT_COM VARCHAR(1024),
    CNAEDS_MIN_PI_CAS_15_MT REAL,
    CNAEDS_IMIN_PI_CAS_15_MT REAL,
    CNAEDS_MOY_PI_CAS_15_MT REAL,
    CNAEDS_IMOY_PI_CAS_15_MT REAL,
    CNAEDS_MAX_PI_CAS_15_MT REAL,
    CNAEDS_IMAX_PI_CAS_15_MT REAL,
    CNAEDS_PIRE_CAS_15_MT_COM VARCHAR(1024),
    CNAEDS_TMOY_DEM REAL,
    CNAEDS_IMOY_DEM REAL,
    CNAEDS_DEM_COMMENT VARCHAR(1024),
    CNAEDS_CE_ID VARCHAR(36) NOT NULL
);             
ALTER TABLE EDS_CRT_NOMINALE_ACTIVATION ADD CONSTRAINT CONSTRAINT_87 PRIMARY KEY(CNAEDS_ID);    
-- 817 +/- SELECT COUNT(*) FROM EDS_CRT_NOMINALE_ACTIVATION;           
CREATE  TABLE EDS_COURANT_EFFICACE(
    CEEDS_ID VARCHAR(36) NOT NULL,
    CEEDS_TMIN_IEFF12 REAL,
    CEEDS_TMIN_TEFF12 REAL,
    CEEDS_TMOY_IEFF12 REAL,
    CEEDS_TMOY_TEFF12 REAL,
    CEEDS_TMAX_IEFF12 REAL,
    CEEDS_TMAX_TEFF12 REAL,
    CEEDS_COM_12V VARCHAR(1024),
    CEEDS_TMIN_IEFF10 REAL,
    CEEDS_TMOY_IEFF10 REAL,
    CEEDS_TMAX_IEFF10 REAL,
    CEEDS_COM_10V VARCHAR(1024),
    CEEDS_TMIN_IEFF13 REAL,
    CEEDS_TMOY_IEFF13 REAL,
    CEEDS_TMAX_IEFF13 REAL,
    CEEDS_COM_13V VARCHAR(1024),
    CEEDS_TMIN_IEFF15 REAL,
    CEEDS_TMOY_IEFF15 REAL,
    CEEDS_TMAX_IEFF15 REAL,
    CEEDS_COM_15V VARCHAR(1024)
); 
ALTER TABLE EDS_COURANT_EFFICACE ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY(CEEDS_ID);             
-- 817 +/- SELECT COUNT(*) FROM EDS_COURANT_EFFICACE;  
CREATE  TABLE EDS_USER(
    U_ID VARCHAR(36) NOT NULL,
    U_S_ID VARCHAR(36),
    U_PE_ID VARCHAR(36),
    U_RO_ID VARCHAR(36),
    U_PSA_ID VARCHAR(32) NOT NULL,
    U_FIRSTNAME VARCHAR(128) NOT NULL,
    U_LASTNAME VARCHAR(128) NOT NULL,
    U_SERVICE VARCHAR(256),
    U_CONF CLOB,
    U_ACTIVE INT NOT NULL
);     

         
ALTER TABLE EDS_USER ADD CONSTRAINT CONSTRAINT_9F PRIMARY KEY(U_ID);            
-- 232 +/- SELECT COUNT(*) FROM EDS_USER;              
CREATE INDEX X_USER_PSA_ACTIVE ON EDS_USER(U_PSA_ID, U_ACTIVE DESC);            
CREATE  TABLE EDS_PROJECT_COURANT_CYCLE(
    PCC_P_ID VARCHAR(36) NOT NULL,
    PCC_CCEDS_ID VARCHAR(36) NOT NULL
);             
ALTER TABLE EDS_PROJECT_COURANT_CYCLE ADD CONSTRAINT CONSTRAINT_D3 PRIMARY KEY(PCC_P_ID, PCC_CCEDS_ID);         
-- 4 +/- SELECT COUNT(*) FROM EDS_PROJECT_COURANT_CYCLE;               
CREATE  TABLE SCHEMA_VERSION(
    VERSION VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(100),
    TYPE VARCHAR(10) NOT NULL,
    SCRIPT VARCHAR(200) NOT NULL,
    CHECKSUM INT,
    INSTALLED_BY VARCHAR(30) NOT NULL,
    INSTALLED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXECUTION_TIME INT,
    STATE VARCHAR(15) NOT NULL,
    CURRENT_VERSION INT NOT NULL
);      
ALTER TABLE SCHEMA_VERSION ADD CONSTRAINT CONSTRAINT_DE PRIMARY KEY(VERSION);   
-- 12 +/- SELECT COUNT(*) FROM SCHEMA_VERSION;         
CREATE INDEX SCHEMA_VERS_CURRENT_INDEX ON SCHEMA_VERSION(CURRENT_VERSION);      
CREATE  TABLE EDS_CONS_CURENT_FORM_DATA(
    CCEDS_ID VARCHAR(36) NOT NULL,
    CCEDS_EDS_ID VARCHAR(36) NOT NULL,
    PCC_CCM_ID VARCHAR(36),
    CC_COMMENT VARCHAR(1024)
);   
ALTER TABLE EDS_CONS_CURENT_FORM_DATA ADD CONSTRAINT CONSTRAINT_17 PRIMARY KEY(CCEDS_ID);       
-- 459 +/- SELECT COUNT(*) FROM EDS_CONS_CURENT_FORM_DATA;             
CREATE  TABLE EDS_PROJECT_CONS_CURENT(
    PCC_P_ID VARCHAR(36) NOT NULL,
    PCC_CCEDS_ID VARCHAR(36) NOT NULL
);               
ALTER TABLE EDS_PROJECT_CONS_CURENT ADD CONSTRAINT CONSTRAINT_BD PRIMARY KEY(PCC_P_ID, PCC_CCEDS_ID);           
-- 0 +/- SELECT COUNT(*) FROM EDS_PROJECT_CONS_CURENT; 
CREATE  TABLE EDS_CONSOLIDATE_SUPPLY(
    CSEDS_ID VARCHAR(36) NOT NULL,
    CSEDS_REF VARCHAR(36) NOT NULL,
    CSEDS_CST_ID VARCHAR(36) NOT NULL,
    CSMEDS_CSM_ID VARCHAR(36) NOT NULL,
    CSEDS_W_ID VARCHAR(36) NOT NULL,
    CSEDS_SUPPLY_NAME VARCHAR(225),
    CSEDS_TBT_BT VARCHAR(3),
    CSEDS_QCF VARCHAR(36) NOT NULL
);          
ALTER TABLE EDS_CONSOLIDATE_SUPPLY ADD CONSTRAINT CONSTRAINT_5A PRIMARY KEY(CSEDS_ID);          
-- 305 +/- SELECT COUNT(*) FROM EDS_CONSOLIDATE_SUPPLY;
CREATE  TABLE EDS_GROUND_CONSOLIDATE_CURENT(
    GCC_ID VARCHAR(36) NOT NULL,
    GCC_CHOIX_MASSE INT,
    GCC_UMAX FLOAT
);     
ALTER TABLE EDS_GROUND_CONSOLIDATE_CURENT ADD CONSTRAINT CONSTRAINT_39 PRIMARY KEY(GCC_ID);     
-- 459 +/- SELECT COUNT(*) FROM EDS_GROUND_CONSOLIDATE_CURENT;         
CREATE  TABLE EDS_GROUND_CONSOLIDATE(
    GEDS_ID VARCHAR(36) NOT NULL,
    GEDS_TITLE VARCHAR(225),
    GC_RCEDS_ID VARCHAR(36)
);              
ALTER TABLE EDS_GROUND_CONSOLIDATE ADD CONSTRAINT CONSTRAINT_E8 PRIMARY KEY(GEDS_ID);           
-- 134 +/- SELECT COUNT(*) FROM EDS_GROUND_CONSOLIDATE;
CREATE  TABLE EDS_J_CONS_GROUND_CRT_MST(
    JCGCMSTEDS_ID VARCHAR(36) NOT NULL,
    JCGCMSTEDS_CMST_ID VARCHAR(36) NOT NULL
);  
ALTER TABLE EDS_J_CONS_GROUND_CRT_MST ADD CONSTRAINT CONSTRAINT_92 PRIMARY KEY(JCGCMSTEDS_ID, JCGCMSTEDS_CMST_ID);              
-- 0 +/- SELECT COUNT(*) FROM EDS_J_CONS_GROUND_CRT_MST;               
CREATE  TABLE EDS_J_CONS_GROUND_CAA(
    JCGCAAEDS_ID VARCHAR(36) NOT NULL,
    JCGCAAEDS_CAA_ID VARCHAR(36) NOT NULL
);         
ALTER TABLE EDS_J_CONS_GROUND_CAA ADD CONSTRAINT CONSTRAINT_35 PRIMARY KEY(JCGCAAEDS_ID, JCGCAAEDS_CAA_ID);     
-- 134 +/- SELECT COUNT(*) FROM EDS_J_CONS_GROUND_CAA; 
CREATE  TABLE EDS_J_CONS_GROUND_CBCD(
    JCGCBCDEDS_ID VARCHAR(36) NOT NULL,
    JCGCBCDEDS_CBCD_ID VARCHAR(36) NOT NULL
);     
ALTER TABLE EDS_J_CONS_GROUND_CBCD ADD CONSTRAINT CONSTRAINT_7D PRIMARY KEY(JCGCBCDEDS_ID, JCGCBCDEDS_CBCD_ID); 
-- 134 +/- SELECT COUNT(*) FROM EDS_J_CONS_GROUND_CBCD;
CREATE  TABLE EDS_J_CONS_GROUND_CNA(
    JCGCNAEDS_ID VARCHAR(36) NOT NULL,
    JCGCNAEDS_CNA_ID VARCHAR(36) NOT NULL
);         
ALTER TABLE EDS_J_CONS_GROUND_CNA ADD CONSTRAINT CONSTRAINT_359 PRIMARY KEY(JCGCNAEDS_ID, JCGCNAEDS_CNA_ID);    
-- 135 +/- SELECT COUNT(*) FROM EDS_J_CONS_GROUND_CNA; 
CREATE  TABLE EDS_CONS_SUP_TH(
    CSTEDS_ID VARCHAR(36) NOT NULL,
    CSEDS_TMIN REAL,
    CSEDS_TMAX REAL,
    CSEDS_TMIN_IFORM_BY VARCHAR(1024),
    CSEDS_TMAX_IFORM_BY VARCHAR(1024),
    CSEDS_TMIN_COMMENT VARCHAR(1024),
    CSEDS_TMAX_COMMENT VARCHAR(1024)
);         
ALTER TABLE EDS_CONS_SUP_TH ADD CONSTRAINT CONSTRAINT_1D PRIMARY KEY(CSTEDS_ID);
-- 305 +/- SELECT COUNT(*) FROM EDS_CONS_SUP_TH;       
CREATE  TABLE EDS_J_CONS_SUP_TH_RVROI(
    JCSTRVROIEDS_ID VARCHAR(36) NOT NULL,
    JCSTRVROIEDS_RVROI_ID VARCHAR(36) NOT NULL
);               
ALTER TABLE EDS_J_CONS_SUP_TH_RVROI ADD CONSTRAINT CONSTRAINT_20 PRIMARY KEY(JCSTRVROIEDS_ID, JCSTRVROIEDS_RVROI_ID);           
-- 305 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_RVROI;               
CREATE  TABLE EDS_J_CONS_SUP_TH_MODE_PARC(
    JCSTMPEDS_ID VARCHAR(36) NOT NULL,
    JCSTMPEDS_MP_ID VARCHAR(36) NOT NULL
);    
ALTER TABLE EDS_J_CONS_SUP_TH_MODE_PARC ADD CONSTRAINT CONSTRAINT_45 PRIMARY KEY(JCSTMPEDS_ID, JCSTMPEDS_MP_ID);
-- 6 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_MODE_PARC;             
CREATE  TABLE EDS_J_CONS_SUP_TH_MODE_MONT(
    JCSTMMEDS_ID VARCHAR(36) NOT NULL,
    JCSTMMEDS_MM_ID VARCHAR(36) NOT NULL
);    
ALTER TABLE EDS_J_CONS_SUP_TH_MODE_MONT ADD CONSTRAINT CONSTRAINT_29 PRIMARY KEY(JCSTMMEDS_ID, JCSTMMEDS_MM_ID);
-- 0 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_MODE_MONT;             
CREATE  TABLE EDS_J_CONS_SUP_TH_CRT_MST(
    JCSTCMSTEDS_ID VARCHAR(36) NOT NULL,
    JCSTCMSTEDS_CMST_ID VARCHAR(36) NOT NULL
);
ALTER TABLE EDS_J_CONS_SUP_TH_CRT_MST ADD CONSTRAINT CONSTRAINT_61 PRIMARY KEY(JCSTCMSTEDS_ID, JCSTCMSTEDS_CMST_ID);            
-- 305 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_CRT_MST;             
CREATE  TABLE EDS_J_CONS_SUP_TH_CAA(
    JCSTCAAEDS_ID VARCHAR(36) NOT NULL,
    JCSTCAAEDS_CAA_ID VARCHAR(36) NOT NULL
);       
ALTER TABLE EDS_J_CONS_SUP_TH_CAA ADD CONSTRAINT CONSTRAINT_6C PRIMARY KEY(JCSTCAAEDS_ID, JCSTCAAEDS_CAA_ID);   
-- 310 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_CAA; 
CREATE  TABLE EDS_J_CONS_SUP_TH_CNA(
    JCSTCNAEDS_ID VARCHAR(36) NOT NULL,
    JCSTCNAEDS_CNA_ID VARCHAR(36) NOT NULL
);       
ALTER TABLE EDS_J_CONS_SUP_TH_CNA ADD CONSTRAINT CONSTRAINT_6C7 PRIMARY KEY(JCSTCNAEDS_ID, JCSTCNAEDS_CNA_ID);  
-- 318 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_CNA; 
CREATE  TABLE EDS_J_CONS_SUP_TH_CBCD(
    JCSTCBCDEDS_ID VARCHAR(36) NOT NULL,
    JCSTCBCDEDS_CBCD_ID VARCHAR(36) NOT NULL
);   
ALTER TABLE EDS_J_CONS_SUP_TH_CBCD ADD CONSTRAINT CONSTRAINT_22 PRIMARY KEY(JCSTCBCDEDS_ID, JCSTCBCDEDS_CBCD_ID);               
-- 305 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_TH_CBCD;
CREATE  TABLE EDS_CONSOLIDATE_SUPPLY_MESURE(
    CSMEDS_ID VARCHAR(36) NOT NULL,
    CSMEDS_TMIN REAL,
    CSMEDS_TMAX REAL,
    CSMEDS_NBR_PIECE_TEST REAL,
    CSMEDS_ECHANTILLON_DE_TEST VARCHAR(25),
    CSMEDS_TMIN_IFORM_BY VARCHAR(1024),
    CSMEDS_TMAX_IFORM_BY VARCHAR(1024),
    CSMEDS_NBR_PIECE_TEST_IF_BY VARCHAR(1024),
    CSMEDS_ECHAN_DE_TEST_IF_BY VARCHAR(1024),
    CSMEDS_TMIN_COMMENT VARCHAR(1024),
    CSMEDS_TMAX_COMMENT VARCHAR(1024),
    CSMEDS_NBR_PIECE_TEST_COM VARCHAR(1024),
    CSMEDS_ECHAN_DE_TEST_COM VARCHAR(1024)
);   
ALTER TABLE EDS_CONSOLIDATE_SUPPLY_MESURE ADD CONSTRAINT CONSTRAINT_BDD PRIMARY KEY(CSMEDS_ID); 
-- 305 +/- SELECT COUNT(*) FROM EDS_CONSOLIDATE_SUPPLY_MESURE;         
CREATE  TABLE EDS_J_CONS_SUP_MES_RVROI(
    JCSMRVROIEDS_ID VARCHAR(36) NOT NULL,
    JCSMRVROIEDS_RVROI_ID VARCHAR(36) NOT NULL
);              
ALTER TABLE EDS_J_CONS_SUP_MES_RVROI ADD CONSTRAINT CONSTRAINT_55 PRIMARY KEY(JCSMRVROIEDS_ID, JCSMRVROIEDS_RVROI_ID);          
-- 305 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_RVROI;              
CREATE  TABLE EDS_J_CONS_SUP_MES_MODE_PARC(
    JCSMMPEDS_ID VARCHAR(36) NOT NULL,
    JCSMMPEDS_MP_ID VARCHAR(36) NOT NULL
);   
ALTER TABLE EDS_J_CONS_SUP_MES_MODE_PARC ADD CONSTRAINT CONSTRAINT_63 PRIMARY KEY(JCSMMPEDS_ID, JCSMMPEDS_MP_ID);               
-- 6 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_MODE_PARC;            
CREATE  TABLE EDS_J_CONS_SUP_MES_MODE_MONT(
    JCSMMMEDS_ID VARCHAR(36) NOT NULL,
    JCSMMMEDS_MM_ID VARCHAR(36) NOT NULL
);   
ALTER TABLE EDS_J_CONS_SUP_MES_MODE_MONT ADD CONSTRAINT CONSTRAINT_E0 PRIMARY KEY(JCSMMMEDS_ID, JCSMMMEDS_MM_ID);               
-- 0 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_MODE_MONT;            
CREATE  TABLE EDS_J_CONS_SUP_MES_CRT_MST(
    JCSMCMSTEDS_ID VARCHAR(36) NOT NULL,
    JCSMCMSTEDS_CMST_ID VARCHAR(36) NOT NULL
);               
ALTER TABLE EDS_J_CONS_SUP_MES_CRT_MST ADD CONSTRAINT CONSTRAINT_D5 PRIMARY KEY(JCSMCMSTEDS_ID, JCSMCMSTEDS_CMST_ID);           
-- 305 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_CRT_MST;            
CREATE  TABLE EDS_J_CONS_SUP_MES_CAA(
    JCSMCAAEDS_ID VARCHAR(36) NOT NULL,
    JCSMCAAEDS_CAA_ID VARCHAR(36) NOT NULL
);      
ALTER TABLE EDS_J_CONS_SUP_MES_CAA ADD CONSTRAINT CONSTRAINT_3A PRIMARY KEY(JCSMCAAEDS_ID, JCSMCAAEDS_CAA_ID);  
-- 314 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_CAA;
CREATE  TABLE EDS_J_CONS_SUP_MES_CNA(
    JCSMCNAEDS_ID VARCHAR(36) NOT NULL,
    JCSMCNAEDS_CNA_ID VARCHAR(36) NOT NULL
);      
ALTER TABLE EDS_J_CONS_SUP_MES_CNA ADD CONSTRAINT CONSTRAINT_3AB PRIMARY KEY(JCSMCNAEDS_ID, JCSMCNAEDS_CNA_ID); 
-- 362 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_CNA;
CREATE  TABLE EDS_J_CONS_SUP_MES_CBCD(
    JCSMCBCDEDS_ID VARCHAR(36) NOT NULL,
    JCSMCBCDEDS_CBCD_ID VARCHAR(36) NOT NULL
);  
ALTER TABLE EDS_J_CONS_SUP_MES_CBCD ADD CONSTRAINT CONSTRAINT_1B PRIMARY KEY(JCSMCBCDEDS_ID, JCSMCBCDEDS_CBCD_ID);              
-- 306 +/- SELECT COUNT(*) FROM EDS_J_CONS_SUP_MES_CBCD;               
CREATE  TABLE EDS_PSA_MESURE_SUPPLY(
    PMSEDS_ID VARCHAR(36) NOT NULL,
    PMSEDS_REF VARCHAR(36) NOT NULL,
    PMSEDS_SUPPLY_NAME VARCHAR(225),
    PMSEDS_SUPPLY_TYPE VARCHAR(25),
    PMSEDS_TBT_BT VARCHAR(3),
    PMSEDS_QCF VARCHAR(36) NOT NULL
);      
ALTER TABLE EDS_PSA_MESURE_SUPPLY ADD CONSTRAINT CONSTRAINT_6A PRIMARY KEY(PMSEDS_ID);          
-- 2 +/- SELECT COUNT(*) FROM EDS_PSA_MESURE_SUPPLY;   
CREATE  TABLE EDS_J_PSA_MES_SUP_RVROI(
    JPMSRVROIEDS_ID VARCHAR(36) NOT NULL,
    JPMSRVROIEDS_RVROI_ID VARCHAR(36) NOT NULL
);               
ALTER TABLE EDS_J_PSA_MES_SUP_RVROI ADD CONSTRAINT CONSTRAINT_EF PRIMARY KEY(JPMSRVROIEDS_ID, JPMSRVROIEDS_RVROI_ID);           
-- 2 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_RVROI; 
CREATE  TABLE EDS_J_PSA_MES_SUP_MODE_PARC(
    JPMSMPEDS_ID VARCHAR(36) NOT NULL,
    JPMSMPEDS_MP_ID VARCHAR(36) NOT NULL
);    
ALTER TABLE EDS_J_PSA_MES_SUP_MODE_PARC ADD CONSTRAINT CONSTRAINT_F0 PRIMARY KEY(JPMSMPEDS_ID, JPMSMPEDS_MP_ID);
-- 0 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_MODE_PARC;             
CREATE  TABLE EDS_J_PSA_MES_SUP_MODE_MONT(
    JPMSMMEDS_ID VARCHAR(36) NOT NULL,
    JPMSMMEDS_MM_ID VARCHAR(36) NOT NULL
);    
ALTER TABLE EDS_J_PSA_MES_SUP_MODE_MONT ADD CONSTRAINT CONSTRAINT_BADF PRIMARY KEY(JPMSMMEDS_ID, JPMSMMEDS_MM_ID);              
-- 0 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_MODE_MONT;             
CREATE  TABLE EDS_J_PSA_MES_SUP_CRT_MST(
    JPMSCMSTEDS_ID VARCHAR(36) NOT NULL,
    JPMSCMSTEDS_CMST_ID VARCHAR(36) NOT NULL
);
ALTER TABLE EDS_J_PSA_MES_SUP_CRT_MST ADD CONSTRAINT CONSTRAINT_5A2 PRIMARY KEY(JPMSCMSTEDS_ID, JPMSCMSTEDS_CMST_ID);           
-- 2 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_CRT_MST;               
CREATE  TABLE EDS_J_PSA_MES_SUP_CAA(
    JPMSCAAEDS_ID VARCHAR(36) NOT NULL,
    JPMSCAAEDS_CAA_ID VARCHAR(36) NOT NULL
);       
ALTER TABLE EDS_J_PSA_MES_SUP_CAA ADD CONSTRAINT CONSTRAINT_48 PRIMARY KEY(JPMSCAAEDS_ID, JPMSCAAEDS_CAA_ID);   
-- 2 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_CAA;   
CREATE  TABLE EDS_J_PSA_MES_SUP_CNA(
    JPMSCNAEDS_ID VARCHAR(36) NOT NULL,
    JPMSCNAEDS_CNA_ID VARCHAR(36) NOT NULL
);       
ALTER TABLE EDS_J_PSA_MES_SUP_CNA ADD CONSTRAINT CONSTRAINT_48B PRIMARY KEY(JPMSCNAEDS_ID, JPMSCNAEDS_CNA_ID);  
-- 2 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_CNA;   
CREATE  TABLE EDS_J_PSA_MES_SUP_CBCD(
    JPMSCBCDEDS_ID VARCHAR(36) NOT NULL,
    JPMSCBCDEDS_CBCD_ID VARCHAR(36) NOT NULL
);   
ALTER TABLE EDS_J_PSA_MES_SUP_CBCD ADD CONSTRAINT CONSTRAINT_CD PRIMARY KEY(JPMSCBCDEDS_ID, JPMSCBCDEDS_CBCD_ID);               
-- 2 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_CBCD;  
CREATE  TABLE EDS_J_PSA_MES_SUP_CRT_CYCLE(
    JPMSCCDEDS_ID VARCHAR(36) NOT NULL,
    JPMSCCEDS_CC_ID VARCHAR(36) NOT NULL
);   
ALTER TABLE EDS_J_PSA_MES_SUP_CRT_CYCLE ADD CONSTRAINT CONSTRAINT_C7 PRIMARY KEY(JPMSCCDEDS_ID, JPMSCCEDS_CC_ID);               
-- 2 +/- SELECT COUNT(*) FROM EDS_J_PSA_MES_SUP_CRT_CYCLE;             
CREATE  TABLE EDS_CONSD_SUP_VOLT_FORM_DATA(
    CSV_ID VARCHAR(36) NOT NULL,
    CSV_VAL_TEN_INIT VARCHAR(256),
    CSV_VAL_TEN_MIN_FCT_NOM VARCHAR(256),
    CSV_VAL_TEN_MAX_FCT_NOM VARCHAR(256),
    CSV_VALEUR_TENSION_COUTURE VARCHAR(256),
    CSV_VAL_TEN_REHAB VARCHAR(256),
    CSV_VALEUR_TENSION_RESET VARCHAR(256),
    CSV_EDS_ID VARCHAR(36) NOT NULL
);           
ALTER TABLE EDS_CONSD_SUP_VOLT_FORM_DATA ADD CONSTRAINT CONSTRAINT_FC PRIMARY KEY(CSV_ID);      
-- 378 +/- SELECT COUNT(*) FROM EDS_CONSD_SUP_VOLT_FORM_DATA;          
CREATE  TABLE EDS_PREL_SUP_VOLT_FORM_DATA(
    PSV_ID VARCHAR(36) NOT NULL,
    PSV_VAL_TEN_MIN_FCT_INIT VARCHAR(256),
    PSV_VAL_TEN_MIN_FCT_NOM VARCHAR(256),
    PSV_VAL_TEN_MAX_FCT_NOM VARCHAR(256),
    PSV_VAL_TEN_MAX_FCT_REHAB VARCHAR(256),
    PSV_OR_DATA_TEN_MIN_FCT_INIT VARCHAR(36),
    PSV_OR_DATA_TEN_MIN_FCT_NOM VARCHAR(36),
    PSV_OR_DATA_TEN_MAX_FCT_NOM VARCHAR(36),
    PSV_OR_DATA_TEN_MAX_FCT_REHAB VARCHAR(36),
    PSV_EDS_ID VARCHAR(36) NOT NULL
);             
ALTER TABLE EDS_PREL_SUP_VOLT_FORM_DATA ADD CONSTRAINT CONSTRAINT_82 PRIMARY KEY(PSV_ID);       
-- 378 +/- SELECT COUNT(*) FROM EDS_PREL_SUP_VOLT_FORM_DATA;           
CREATE  TABLE EDS_MISSION_ACTN_FORM_DATA(
    MAFD_ID VARCHAR(36) NOT NULL,
    MAFD_COMMENTAIRE VARCHAR(2048),
    MAFD_EDS_ID VARCHAR(36) NOT NULL
);          
ALTER TABLE EDS_MISSION_ACTN_FORM_DATA ADD CONSTRAINT CONSTRAINT_CB PRIMARY KEY(MAFD_ID);       
-- 433 +/- SELECT COUNT(*) FROM EDS_MISSION_ACTN_FORM_DATA;            
CREATE  TABLE EDS_CRT_BLOQUE_CRT_DYSF(
    CBCDEDS_ID VARCHAR(36) NOT NULL,
    CBCDEDS_TMIN_IDYS REAL,
    CBCDEDS_TMOY_IDYS REAL,
    CBCDEDS_TMAX_IDYS REAL,
    CBCDEDS_TMIN_TDYS REAL,
    CBCDEDS_TMOY_TDYS REAL,
    CBCDEDS_TMAX_TDYS REAL,
    CBCDEDS_OCC_DEFAILLENCE INT,
    CBCDEDS_OCC_DEFLLENCE_TDYS INT,
    CBCDEDS_COMMENT VARCHAR(1024),
    CBCDEDS_TITRE VARCHAR(1024),
    CBCDEDS_REMOVE INT
);     


ALTER TABLE EDS_CRT_BLOQUE_CRT_DYSF ADD CONSTRAINT CONSTRAINT_D9 PRIMARY KEY(CBCDEDS_ID);       
-- 747 +/- SELECT COUNT(*) FROM EDS_CRT_BLOQUE_CRT_DYSF;               
CREATE  TABLE EDS_MISSION_PROFIL(
    MP_ID VARCHAR(36) NOT NULL,
    MP_RANK INTEGER,
    MP_NOMBRE_ACTIVATION FLOAT,
    MP_UNIT INTEGER,
    MP_COMMENTAIRE VARCHAR(2048),
    MP_DOCS_INFOS_URLS VARCHAR(256),
    MP_NOM_PROFIL VARCHAR(256),
    MP_MPFD_ID VARCHAR(36)
); 
ALTER TABLE EDS_MISSION_PROFIL ADD CONSTRAINT CONSTRAINT_DA PRIMARY KEY(MP_ID); 
-- 341 +/- SELECT COUNT(*) FROM EDS_MISSION_PROFIL;    
CREATE  TABLE EDS_MISSION_PROFIL_FORM_DATA(
    MPFD_ID VARCHAR(36) NOT NULL,
    MPFD_EDS_ID VARCHAR(36) NOT NULL
);            
ALTER TABLE EDS_MISSION_PROFIL_FORM_DATA ADD CONSTRAINT CONSTRAINT_1A PRIMARY KEY(MPFD_ID);     
-- 434 +/- SELECT COUNT(*) FROM EDS_MISSION_PROFIL_FORM_DATA;          
CREATE  TABLE EDS_DVR_FORM_DATA(
    DVRFD_ID VARCHAR(36) NOT NULL,
    DVRFD_OC_TO_FL_OG_CS_AD_VI_M VARCHAR(256),
    DVRFD_CUR_COP_CS_AD_VINT_MAH VARCHAR(256),
    DVRFD_COM_CONS_AD_VINT_MAH VARCHAR(2048),
    DVRFD_IS_PLUS_VINT_MAH INT,
    DVRFD_OCC_TOT_FL_ORG_MAIN_NET VARCHAR(256),
    DVRFD_CUR_CORESP_MAINT_NET VARCHAR(256),
    DVRFD_COMAIRE_MAINT_NET VARCHAR(2048),
    DVRFD_IS_MAINTIEN_RESEAUX INT,
    DVRFD_OCC_TOT_FL_ORG_REV_INT VARCHAR(256),
    DVRFD_CUR_CORESP_REV_INT VARCHAR(256),
    DVRFD_COMAIRE_REV_INT VARCHAR(2048),
    DVRFD_IS_REVEIL_INTEMPSIF INT,
    DVRFD_OCC_TOT_FL_ORG_MAINT_AL VARCHAR(256),
    DVRFD_CUR_CORESP_MAINT_ALIM VARCHAR(256),
    DVRFD_COMAIRE_MAINT_ALIM VARCHAR(2048),
    DVRFD_IS_MAINTIEN_ALIMENTATION INT,
    DVRFD_OCC_TOT_FL_ORG_REIM_ALI VARCHAR(256),
    DVRFD_CUR_CORESP_REALIM_ALIM VARCHAR(256),
    DVRFD_COMAIRE_REALIM_ALIM VARCHAR(2048),
    DVRFD_IS_REALIM_ALIM INT,
    DVRFD_EDS_ID VARCHAR(36) NOT NULL
);            
ALTER TABLE EDS_DVR_FORM_DATA ADD CONSTRAINT CONSTRAINT_43 PRIMARY KEY(DVRFD_ID);               
-- 72 +/- SELECT COUNT(*) FROM EDS_DVR_FORM_DATA;      
CREATE  TABLE EDS_CMPTT_ROB_FORM_DATA(
    CRFD_ID VARCHAR(36) NOT NULL,
    CRFD_SYNOPTIQUE_FCT_IMAGE VARCHAR(256),
    CRFD_SYNOPTIQUE_FCT_COMAIRE VARCHAR(2048),
    CRFD_SYNOPTIQUE_ELEC_IMAGE VARCHAR(256),
    CRFD_SYNOPTIQUE_ELEC_COMAIRE VARCHAR(2048),
    CRFD_SYNOPTIQUE_ELEC_URLS VARCHAR(256),
    CRFD_SYNOPTIQUE_FCT_URLS VARCHAR(256),
    CRFD_EDS_ID VARCHAR(36) NOT NULL
);  
ALTER TABLE EDS_CMPTT_ROB_FORM_DATA ADD CONSTRAINT CONSTRAINT_DF PRIMARY KEY(CRFD_ID);          
-- 452 +/- SELECT COUNT(*) FROM EDS_CMPTT_ROB_FORM_DATA;               
CREATE  TABLE EDS_CMPT_CONS_FORM_DATA(
    COCOFD_ID VARCHAR(36) NOT NULL,
    COCOFD_TYPE_PILOTAGE VARCHAR(256),
    COCOFD_PLAGE_FREQUENCE VARCHAR(256),
    COCOFD_MODELE_RLC_IMAGE VARCHAR(256),
    COCOFD_MODELE_RCL_COM VARCHAR(2048),
    COCOFD_MODELE_SABER_IMAGE VARCHAR(256),
    COCOFD_MODELE_SABER_COM VARCHAR(2048),
    COCOFD_MODELE_RCL_URLS VARCHAR(256),
    COCOFD_MODELE_SABER_URLS VARCHAR(256),
    COCOFD_EDS_ID VARCHAR(36) NOT NULL
);               
ALTER TABLE EDS_CMPT_CONS_FORM_DATA ADD CONSTRAINT CONSTRAINT_F5 PRIMARY KEY(COCOFD_ID);        
-- 452 +/- SELECT COUNT(*) FROM EDS_CMPT_CONS_FORM_DATA;               
CREATE  TABLE EDS_VALIDATION(
    V_ID VARCHAR(36) NOT NULL,
    V_STATUS INT NOT NULL,
    V_VALIDATOR_ID VARCHAR(36),
    V_VALIDATION_DATE TIMESTAMP,
    V_COMMENT1_ID VARCHAR(36),
    V_COMMENT2 VARCHAR(1024)
);    
ALTER TABLE EDS_VALIDATION ADD CONSTRAINT CONSTRAINT_15 PRIMARY KEY(V_ID);      
-- 2845 +/- SELECT COUNT(*) FROM EDS_VALIDATION;       
CREATE  TABLE EDS_HIGH_VALIDATION_FORM_DATA(
    HVFD_ID VARCHAR(36) NOT NULL,
    HVFD_EDS_ID VARCHAR(36) NOT NULL,
    HVFD_RS_PRIMARY_ID VARCHAR(36) NOT NULL,
    HVFD_RE_ROBUST_ID VARCHAR(36) NOT NULL,
    HVFD_RE_CONSOLIDATE_ID VARCHAR(36) NOT NULL,
    HVFD_RE_CLOSED_ID VARCHAR(36) NOT NULL,
    HVFD_DBEES_CONSOLIDATE_ID VARCHAR(36) NOT NULL,
    HVFD_DBEES_CLOSED_ID VARCHAR(36) NOT NULL,
    HVFD_DBEED_CONSOLIDATE_ID VARCHAR(36) NOT NULL,
    HVFD_DBEED_CLOSED_ID VARCHAR(36) NOT NULL,
    HVFD_CADE_CONSOLIDATE_ID VARCHAR(36) NOT NULL,
    HVFD_CADE_CLOSED_ID VARCHAR(36) NOT NULL,
    HVFD_SUPPLIER_DATA_ID VARCHAR(36) NOT NULL,
    HVFD_STAGE INT NOT NULL
); 
ALTER TABLE EDS_HIGH_VALIDATION_FORM_DATA ADD CONSTRAINT CONSTRAINT_37 PRIMARY KEY(HVFD_ID);    
-- 80 +/- SELECT COUNT(*) FROM EDS_HIGH_VALIDATION_FORM_DATA;          
CREATE  TABLE EDS_LOW_VALIDATION_FORM_DATA(
    LVFD_ID VARCHAR(36) NOT NULL,
    LVFD_EDS_ID VARCHAR(36) NOT NULL,
    LVFD_PRELIMINARY_ID VARCHAR(36) NOT NULL,
    LVFD_ROBUST_ID VARCHAR(36) NOT NULL,
    LVFD_CONSOLIDATED_ID VARCHAR(36) NOT NULL,
    LVFD_CLOSED_ID VARCHAR(36) NOT NULL,
    LVFD_SUPPLIER_DATA_ID VARCHAR(36) NOT NULL,
    LVFD_STAGE INT NOT NULL
);
ALTER TABLE EDS_LOW_VALIDATION_FORM_DATA ADD CONSTRAINT CONSTRAINT_9B PRIMARY KEY(LVFD_ID);     
-- 393 +/- SELECT COUNT(*) FROM EDS_LOW_VALIDATION_FORM_DATA;          
CREATE  TABLE EDS_CSE_FORM_DATA(
    CSE_ID VARCHAR(36) NOT NULL,
    CSE_EDS_ID VARCHAR(36) NOT NULL
);         
ALTER TABLE EDS_CSE_FORM_DATA ADD CONSTRAINT CONSTRAINT_637 PRIMARY KEY(CSE_ID);
-- 175 +/- SELECT COUNT(*) FROM EDS_CSE_FORM_DATA;     
CREATE  TABLE EDS_CSE_LINE(
    CSEL_ID VARCHAR(36) NOT NULL,
    CSEL_CSE_ID VARCHAR(36) NOT NULL,
    CSEL_NUMBER INT NOT NULL,
    CSEL_DATANAME VARCHAR(128) NOT NULL,
    CSEL_LOWER_BOUND REAL,
    CSEL_UPPER_BOUND REAL,
    CSEL_UNIT VARCHAR(32),
    CSEL_COMMENT VARCHAR(256)
);     
ALTER TABLE EDS_CSE_LINE ADD CONSTRAINT CONSTRAINT_AA PRIMARY KEY(CSEL_ID);     
-- 642 +/- SELECT COUNT(*) FROM EDS_CSE_LINE;          
CREATE  TABLE EDS_DRIFT_INFO(
    DI_ID VARCHAR(36) NOT NULL,
    DI_EDS_ID VARCHAR(36) NOT NULL,
    DI_DATA_TYPE INTEGER NOT NULL,
    DI_ALIM_NAME VARCHAR(36) NOT NULL,
    DI_REF_STAGE INTEGER NOT NULL,
    DI_REF_VALUE REAL,
    DI_TARGET_STAGE INTEGER NOT NULL,
    DI_TARGET_VALUE REAL
);          
ALTER TABLE EDS_DRIFT_INFO ADD CONSTRAINT CONSTRAINT_75 PRIMARY KEY(DI_ID);     
-- 0 +/- SELECT COUNT(*) FROM EDS_DRIFT_INFO;          
CREATE  TABLE EDS_ATTACHMENT_FORM_DATA(
    AFD_ID VARCHAR(36) NOT NULL,
    AFD_EDS_ID VARCHAR(36) NOT NULL
);  
ALTER TABLE EDS_ATTACHMENT_FORM_DATA ADD CONSTRAINT CONSTRAINT_A8 PRIMARY KEY(AFD_ID);          
-- 459 +/- SELECT COUNT(*) FROM EDS_ATTACHMENT_FORM_DATA;              
CREATE  TABLE EDS_ATTACHMENT(
    A_ID VARCHAR(36) NOT NULL,
    A_AFD_ID VARCHAR(36) NOT NULL,
    A_LINK VARCHAR(512) NOT NULL,
    A_COMMENT VARCHAR(1024)
); 
ALTER TABLE EDS_ATTACHMENT ADD CONSTRAINT CONSTRAINT_A2 PRIMARY KEY(A_ID);      
-- 227 +/- SELECT COUNT(*) FROM EDS_ATTACHMENT;        
CREATE  TABLE EDS_SUPPLIER(
    S_ID VARCHAR(36) NOT NULL,
    S_NAME VARCHAR(1024) NOT NULL,
    S_ACTIVE INT NOT NULL
);      

 
ALTER TABLE EDS_SUPPLIER ADD CONSTRAINT CONSTRAINT_A4 PRIMARY KEY(S_ID);        
-- 75 +/- SELECT COUNT(*) FROM EDS_SUPPLIER;           
CREATE  TABLE EDS_PERIMETER(
    PE_ID VARCHAR(36) NOT NULL,
    PE_NAME VARCHAR(1024) NOT NULL,
    PE_ACTIVE INT NOT NULL
);   


ALTER TABLE EDS_PERIMETER ADD CONSTRAINT CONSTRAINT_9A PRIMARY KEY(PE_ID);      
-- 6 +/- SELECT COUNT(*) FROM EDS_PERIMETER;           
CREATE  TABLE EDS_EDS_PERIMETER(
    EDSPE_EDS_ID VARCHAR(36) NOT NULL,
    EDSPE_PE_ID VARCHAR(36) NOT NULL
);  
ALTER TABLE EDS_EDS_PERIMETER ADD CONSTRAINT CONSTRAINT_A5 PRIMARY KEY(EDSPE_EDS_ID, EDSPE_PE_ID);              
-- 12 +/- SELECT COUNT(*) FROM EDS_EDS_PERIMETER;      
CREATE  TABLE EDS_PROJECT_PERIMETER(
    PPE_P_ID VARCHAR(36) NOT NULL,
    PPE_PE_ID VARCHAR(36) NOT NULL
);    
ALTER TABLE EDS_PROJECT_PERIMETER ADD CONSTRAINT CONSTRAINT_9E PRIMARY KEY(PPE_P_ID, PPE_PE_ID);
-- 10 +/- SELECT COUNT(*) FROM EDS_PROJECT_PERIMETER;  
CREATE  TABLE EDS_CURRENT_STATEMENT(
    CS_ID VARCHAR(36) NOT NULL,
    CS_MAFD_ID VARCHAR(36) NOT NULL,
    CS_SEDS_ID VARCHAR(36) NOT NULL,
    CS_NAME VARCHAR(128) NOT NULL,
    CS_XY_DATA VARCHAR(2048),
    CS_COMMENT VARCHAR(1024),
    CS_DOC_INFO_URL VARCHAR(1024),
    CS_USER_ID VARCHAR(36),
    CS_STATEMENT_TYPE INTEGER
);    
ALTER TABLE EDS_CURRENT_STATEMENT ADD CONSTRAINT CONSTRAINT_FD PRIMARY KEY(CS_ID);              
-- 134 +/- SELECT COUNT(*) FROM EDS_CURRENT_STATEMENT; 
CREATE  TABLE EDS_ROLE(
    RO_ID VARCHAR(36) NOT NULL,
    RO_NAME VARCHAR(1024) NOT NULL,
    RO_ACTIVE INT NOT NULL,
    RO_TYPE INT,
    RO_RIGHTS CLOB,
    RO_FORM_RIGHTS CLOB
);   



     
ALTER TABLE EDS_ROLE ADD CONSTRAINT CONSTRAINT_9FDC PRIMARY KEY(RO_ID);         
-- 12 +/- SELECT COUNT(*) FROM EDS_ROLE;               
CREATE  TABLE EDS_WORDING(
    W_ID VARCHAR(36) NOT NULL,
    W_VALUE VARCHAR(1024) NOT NULL,
    W_TYPE VARCHAR(36) NOT NULL,
    W_INDEX INT NOT NULL
);       


ALTER TABLE EDS_WORDING ADD CONSTRAINT CONSTRAINT_299 PRIMARY KEY(W_ID);        
-- 47 +/- SELECT COUNT(*) FROM EDS_WORDING;            
CREATE INDEX X_WORDING_TYPES ON EDS_WORDING(W_ID, W_TYPE);      
CREATE  TABLE EDS_SUBSCRIPTION(
    SUB_ID VARCHAR(36) NOT NULL,
    SUB_U_ID VARCHAR(36) NOT NULL,
    SUB_EDS_REF VARCHAR(32) NOT NULL
);      
ALTER TABLE EDS_SUBSCRIPTION ADD CONSTRAINT CONSTRAINT_69 PRIMARY KEY(SUB_ID);  
-- 14 +/- SELECT COUNT(*) FROM EDS_SUBSCRIPTION;       
CREATE INDEX X_USER_SUBSCRIPTIONS ON EDS_SUBSCRIPTION(SUB_U_ID, SUB_EDS_REF);   
CREATE  TABLE EDS_WS_SESSION_TOKEN(
    WST_ID VARCHAR(36) NOT NULL,
    WST_EXPIRATION_DATE TIMESTAMP NOT NULL,
    WST_REMOTE_ADDRESS VARCHAR(45) NOT NULL,
    WST_U_ID VARCHAR(36)
);        
ALTER TABLE EDS_WS_SESSION_TOKEN ADD CONSTRAINT CONSTRAINT_52 PRIMARY KEY(WST_ID);              
-- 24 +/- SELECT COUNT(*) FROM EDS_WS_SESSION_TOKEN;   
CREATE  TABLE EDS_ROBUST_CURENT_FORM_DATA(
    RCEDS_ID VARCHAR(36) NOT NULL,
    RCEDS_EDS_ID VARCHAR(36) NOT NULL,
    RC_COMMENT VARCHAR(1024),
    RC_CHOIX_MASSE INT
);     
ALTER TABLE EDS_ROBUST_CURENT_FORM_DATA ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(RCEDS_ID);      
-- 459 +/- SELECT COUNT(*) FROM EDS_ROBUST_CURENT_FORM_DATA;           
CREATE  TABLE EDS_EDS(
    EDS_ID VARCHAR(36) NOT NULL,
    EDS_P_ID VARCHAR(36) NOT NULL,
    EDS_CT_ID VARCHAR(36) NOT NULL,
    EDS_S_ID VARCHAR(36),
    EDS_W_ID VARCHAR(36),
    EDS_ADMIN_ID VARCHAR(36),
    EDS_MANAGER_ID VARCHAR(36),
    EDS_OFFICER_ID VARCHAR(36),
    EDS_DRIFT_VALIDATOR_ID VARCHAR(36),
    EDS_REF VARCHAR(32) NOT NULL,
    EDS_MAJOR_VERSION INT NOT NULL,
    EDS_MINOR_VERSION INT NOT NULL,
    EDS_CREA_USER_ID VARCHAR(36) NOT NULL,
    EDS_CREA_DATE TIMESTAMP NOT NULL,
    EDS_MODIF_DATE TIMESTAMP NOT NULL,
    EDS_MODIF_USER_ID VARCHAR(36),
    EDS_DRIFT_VALIDATION_DATE TIMESTAMP,
    EDS_NAME VARCHAR(256) NOT NULL,
    EDS_VALID_LVL INT,
    EDS_SUBTYPE_1 INT,
    EDS_SUBTYPE_2 INT,
    EDS_IS_BTTBT INT NOT NULL,
    EDS_STATE INT NOT NULL,
    EDS_P_LAUNCH_COUNT INT,
    EDS_COMMENTS VARCHAR(2048),
    EDS_HAS_DRIFT INT NOT NULL,
    EDS_AFF_USER_ID VARCHAR(36)
);  
ALTER TABLE EDS_EDS ADD CONSTRAINT CONSTRAINT_BA PRIMARY KEY(EDS_ID);           
-- 461 +/- SELECT COUNT(*) FROM EDS_EDS;               
CREATE INDEX X_EDS_VERSION ON EDS_EDS(EDS_REF, EDS_STATE, EDS_MAJOR_VERSION DESC, EDS_MINOR_VERSION DESC); 

