ALTER TABLE EDS_EDS ADD EDS_ALT_FUNC_ID VARCHAR2(36 char);
alter table EDS_EDS add constraint EDS_ALT_FUNC_ID_FK foreign key (EDS_ALT_FUNC_ID) references EDS_WORDING(W_ID);

ALTER TABLE EDS_EDS ADD EDS_ALT_SYS_ID VARCHAR2(36 char);
alter table EDS_EDS add constraint EDS_ALT_SYS_ID_FK foreign key (EDS_ALT_SYS_ID) references EDS_WORDING(W_ID);

ALTER TABLE EDS_EDS ADD EDS_BAT_FUNC_ID VARCHAR2(36 char);
alter table EDS_EDS add constraint EDS_BAT_FUNC_ID_FK foreign key (EDS_BAT_FUNC_ID) references EDS_WORDING(W_ID);

ALTER TABLE EDS_EDS ADD EDS_BAT_SYS_ID VARCHAR2(36 char);
alter table EDS_EDS add constraint EDS_BAT_SYS_ID_FK foreign key (EDS_BAT_SYS_ID) references EDS_WORDING(W_ID);

TRUNCATE TABLE EDS_WS_SESSION_TOKEN;

ALTER TABLE EDS_WS_SESSION_TOKEN ADD WST_SOURCE VARCHAR2(10 char) NOT NULL;
