-- [Ex_Fich_22]
-- Structure in IHM of a power supply of the robust stage
ALTER TABLE EDS_ROBUST_SUPPLY ADD (RSEDS_USE_CASE_NAME VARCHAR2(255));
CREATE TABLE EDS_ROBUST_SUP_USECASE (
	RSUC_ID VARCHAR2(36) NOT NULL,
	RSUC_RS_ID VARCHAR2(36) NOT NULL,
	RSUC_USECASE_NAME VARCHAR2(255) NOT NULL,
	RSUC_REMOVE NUMBER,
	RSUC_I_VEILLE FLOAT(23),
	RSUC_I_VEILLE_IFORM_BY VARCHAR2(1024),
	RSUC_I_VEILLE_COMMENT VARCHAR2(1024),
	RSUC_I_REVEIL_INACTIF FLOAT(23),
	RSUC_I_REVEIL_INACTIF_IFORM_BY VARCHAR2(1024),
	RSUC_I_REVEIL_COMMENT VARCHAR2(1024),
	RSUC_I_NOM_STAB FLOAT(23),
	RSUC_I_NOM_STAB_IFORM_BY VARCHAR2(1024),
	RSUC_I_NOM_STAB_COMMENT VARCHAR2(1024),
	RSUC_I_PIRECAS_STAB FLOAT(23),
	RSUC_I_PIRECAS_STAB_IFORM_BY VARCHAR2(1024),
	RSUC_I_PIRECAS_COMMENT VARCHAR2(1024),
	RSUC_U_MIN FLOAT(23),
	RSUC_U_MIN_INFORM_BY VARCHAR2(1024),
	RSUC_U_MIN_COMMENT VARCHAR2(1024),
	RSUC_U_MOY FLOAT(23),
	RSUC_U_MOY_INFORM_BY VARCHAR2(1024),
	RSUC_U_MOY_COMMENT VARCHAR2(1024),
	RSUC_U_MAX FLOAT(23),
	RSUC_U_MAX_INFORM_BY VARCHAR2(1024),
	RSUC_U_MAX_COMMENT VARCHAR2(1024),
	RSUC_I_MAX FLOAT(23),
	RSUC_I_MAX_INFORM_BY VARCHAR2(1024),
	RSUC_I_MAX_COMMENT VARCHAR2(1024),
	RSUC_T_IMAX FLOAT(23),
	RSUC_T_IMAX_INFORM_BY VARCHAR2(1024),
	RSUC_T_IMAX_COMMENT VARCHAR2(1024),
	RSUC_U_CARAC_VALUE FLOAT(23),
	RSUC_U_CARAC_INFORM_BY VARCHAR2(1024),
	RSUC_U_CARAC_COMMENT VARCHAR2(1024),
	RSUC_I_CONSO_PARC FLOAT(23),
	RSUC_I_CONSO_PARC_INFORM_BY VARCHAR2(1024),
	RSUC_I_CONSO_PARC_COMMENT VARCHAR2(1024)
);
ALTER TABLE EDS_ROBUST_SUP_USECASE ADD CONSTRAINT EDS_ROBUST_SUP_USECASE_PK PRIMARY KEY (RSUC_ID);
ALTER TABLE EDS_ROBUST_SUP_USECASE ADD CONSTRAINT EDS_ROBUST_SUP_USECASE_CON FOREIGN KEY (RSUC_RS_ID) REFERENCES EDS_ROBUST_SUPPLY (RSEDS_ID);


-- [Ex_Gene_36]
-- Administration - Hierarchisation of the projects
CREATE TABLE EDS_PROJECT_NODE (
    EDSPN_ID VARCHAR(36) NOT NULL,
    EDSPN_NAME VARCHAR(36) NOT NULL,
    EDSPN_PARENT_ID VARCHAR(36)
);
ALTER TABLE EDS_PROJECT_NODE ADD CONSTRAINT CONSTRAINT_PROJECT_NODE_ID PRIMARY KEY(EDSPN_ID);
ALTER TABLE EDS_PROJECT_NODE ADD CONSTRAINT CONSTRAINT_P_NODE_PARENT_ID FOREIGN KEY(EDSPN_PARENT_ID) REFERENCES EDS_PROJECT_NODE(EDSPN_ID);
ALTER TABLE EDS_PROJECT ADD P_EDSPN_ID VARCHAR(36);
ALTER TABLE EDS_PROJECT ADD CONSTRAINT CONSTRAINT_P_NODE_ID FOREIGN KEY(P_EDSPN_ID) REFERENCES EDS_PROJECT_NODE(EDSPN_ID);


-- [Ex_Fich_23]
-- Association diagram at the robust stage
ALTER TABLE EDS_ROBUST_CURENT_FORM_DATA ADD RC_IMAGE VARCHAR(225);


-- [Ex_Fich_30]
-- Update of the data to be informed at the robust stage in the supplies and grounds
ALTER TABLE EDS_ROBUST_SUPPLY ADD (
	RSEDS_T_NOM_STAB FLOAT(23),
	RSEDS_T_PIRE_CAS FLOAT(23),
	RSEDS_I_DYSF FLOAT(23),
	RSEDS_T_DYSF FLOAT(23),
	RSEDS_I_MST FLOAT(23),
	RSEDS_T_MST FLOAT(23),
	RSEDS_T_NOM_STAB_INFORM_BY VARCHAR2(1024),
	RSEDS_T_PIRE_CAS_INFORM_BY VARCHAR2(1024),
	RSEDS_I_DYSF_INFORM_BY VARCHAR2(1024),
	RSEDS_T_DYSF_INFORM_BY VARCHAR2(1024),
	RSEDS_I_MST_INFORM_BY VARCHAR2(1024),
	RSEDS_T_MST_INFORM_BY VARCHAR2(1024),
	RSEDS_T_NOM_STAB_COMMENT VARCHAR2(1024),
	RSEDS_T_PIRE_CAS_COMMENT VARCHAR2(1024),
	RSEDS_I_DYSF_COMMENT VARCHAR2(1024),
	RSEDS_T_DYSF_COMMENT VARCHAR2(1024),
	RSEDS_I_MST_COMMENT VARCHAR2(1024),
	RSEDS_T_MST_COMMENT VARCHAR2(1024)
);
ALTER TABLE EDS_ROBUST_SUP_USECASE ADD (
	RSUC_T_NOM_STAB FLOAT(23),
	RSUC_T_PIRE_CAS FLOAT(23),
	RSUC_I_DYSF FLOAT(23),
	RSUC_T_DYSF FLOAT(23),
	RSUC_I_MST FLOAT(23),
	RSUC_T_MST FLOAT(23),
	RSUC_T_NOM_STAB_INFORM_BY VARCHAR2(1024),
	RSUC_T_PIRE_CAS_INFORM_BY VARCHAR2(1024),
	RSUC_I_DYSF_INFORM_BY VARCHAR2(1024),
	RSUC_T_DYSF_INFORM_BY VARCHAR2(1024),
	RSUC_I_MST_INFORM_BY VARCHAR2(1024),
	RSUC_T_MST_INFORM_BY VARCHAR2(1024),
	RSUC_T_NOM_STAB_COMMENT VARCHAR2(1024),
	RSUC_T_PIRE_CAS_COMMENT VARCHAR2(1024),
	RSUC_I_DYSF_COMMENT VARCHAR2(1024),
	RSUC_T_DYSF_COMMENT VARCHAR2(1024),
	RSUC_I_MST_COMMENT VARCHAR2(1024),
	RSUC_T_MST_COMMENT VARCHAR2(1024)
);
ALTER TABLE EDS_GROUND_ROBUST_CURENT ADD (
	GSEDS_T_NOM_STAB FLOAT(23),
	GSEDS_T_PIRE_CAS FLOAT(23),
	GSEDS_I_DYSF FLOAT(23),
	GSEDS_T_DYSF FLOAT(23),
	GSEDS_T_MST FLOAT(23),
	GSEDS_T_NOM_STAB_INFORM_BY VARCHAR2(1024),
	GSEDS_T_PIRE_CAS_INFORM_BY VARCHAR2(1024),
	GSEDS_I_DYSF_INFORM_BY VARCHAR2(1024),
	GSEDS_T_DYSF_INFORM_BY VARCHAR2(1024),
	GSEDS_I_MST_INFORM_BY VARCHAR2(1024),
	GSEDS_T_MST_INFORM_BY VARCHAR2(1024),
	GSEDS_T_NOM_STAB_COMMENT VARCHAR2(1024),
	GSEDS_T_PIRE_CAS_COMMENT VARCHAR2(1024),
	GSEDS_I_DYSF_COMMENT VARCHAR2(1024),
	GSEDS_T_DYSF_COMMENT VARCHAR2(1024),
	GSEDS_I_MST_COMMENT VARCHAR2(1024),
	GSEDS_T_MST_COMMENT VARCHAR2(1024)
);


-- [Ex_Gene_31]
-- Administration - application Rights around the administration
UPDATE EDS_ROLE SET RO_RIGHTS = 'app-dashboard-menu-abort-eds;app-eds-freeze-eds;app-eds-menu-export-eds;app-eds-menu-export-tab-view;app-eds-modify-setter-project;app-eds-reconduct-eds-with-modif;app-eds-reconduct-eds-without-modif;app-eds-reconsult-eds;app-eds-remove-follower-project;app-eds-see-primary-organs;app-eds-see-secondary-organs;app-eds-see-type-organe;app-eds-validate-drift;app-eds-validate-high-level-2;app-eds-validate-high-level-3;app-eds-validate-high-level-4;app-eds-validate-high-level-5;app-eds-validate-low-cloture;app-eds-validate-low-consolide;app-eds-validate-preliminaire;app-eds-validate-robuste;app-eds-validate-supplier-data;app-general-access-admin;app-general-access-dashboard;app-general-access-eds;app-general-access-project;app-general-be-eds-admin;app-general-be-eds-affectation;app-general-be-eds-manager;app-general-be-eds-notifisation-cd;app-project-menu-export-eds;app-project-menu-export-simulation;app-project-menu-new-eds;app-project-menu-recover-eds;app-project-menu-subscribe-eds;app-general-access-admin-project;app-general-access-admin-access;app-general-access-admin-rights;' WHERE RO_ID = '59abd4b0-ed1e-11e0-be50-0800200c9aaa' ;
