-- [EX_FICH_37]
-- tensions table.
DROP TABLE "CONS_SUP_EDS_TENSION";


CREATE TABLE "CONS_SUP_EDS_TENSION"
  (
     "CSEDSU_ID"          VARCHAR2(36) NOT NULL ENABLE,
     "CSEDSU_NAME"        VARCHAR2(1024),
     "CSEDS_UMIN"         FLOAT(126),
     "CSEDS_UMOY"         FLOAT(126),
     "CSEDS_UMAX"         FLOAT(126),
     "CSEDS_UMIN_COMMENT" VARCHAR2(1024),
     "CSEDS_UMOY_COMMENT" VARCHAR2(1024),
     "CSEDS_UMAX_COMMENT" VARCHAR2(1024),
     PRIMARY KEY ("CSEDSU_ID") ENABLE
  );

CREATE TABLE "EDS_J_CONS_SUP_MES_TENSIONS"
  (
     "JCSMU_CSMEDS_ID" VARCHAR2(36) NOT NULL ENABLE,
     "JCSU_CSU_ID"     VARCHAR2(36) NOT NULL ENABLE,
     PRIMARY KEY ("JCSMU_CSMEDS_ID", "JCSU_CSU_ID") ENABLE,
     UNIQUE ("JCSU_CSU_ID") ENABLE
  );

ALTER TABLE "EDS_J_CONS_SUP_MES_TENSIONS"
  ADD CONSTRAINT "FK671A24449E53F603" FOREIGN KEY ("JCSMU_CSMEDS_ID") REFERENCES
  "EDS_CONSOLIDATE_SUPPLY_MESURE" ("CSMEDS_ID") ENABLE;

ALTER TABLE "EDS_J_CONS_SUP_MES_TENSIONS"
  ADD CONSTRAINT "FK671A2444AA1C3903" FOREIGN KEY ("JCSU_CSU_ID") REFERENCES
  "CONS_SUP_EDS_TENSION" ("CSEDSU_ID") ENABLE;

CREATE TABLE "EDS_J_CONS_SUP_THE_TENSIONS"
  (
     "JCSTU_CSTEDS_ID" VARCHAR2(36) NOT NULL ENABLE,
     "JCSU_CSU_ID"     VARCHAR2(36) NOT NULL ENABLE,
     PRIMARY KEY ("JCSTU_CSTEDS_ID", "JCSU_CSU_ID") ENABLE,
     UNIQUE ("JCSU_CSU_ID") ENABLE
  );

ALTER TABLE "EDS_J_CONS_SUP_THE_TENSIONS"
  ADD CONSTRAINT "FKFF9F926E68E5782F" FOREIGN KEY ("JCSTU_CSTEDS_ID") REFERENCES
  "EDS_CONS_SUP_TH" ("CSTEDS_ID") ENABLE;

ALTER TABLE "EDS_J_CONS_SUP_THE_TENSIONS"
  ADD CONSTRAINT "FKFF9F926EAA1C3903" FOREIGN KEY ("JCSU_CSU_ID") REFERENCES
  "CONS_SUP_EDS_TENSION" ("CSEDSU_ID") ENABLE; 
