-- [EX_FICH_34]
-- Add operating mode name column
ALTER TABLE EDS_RVROI ADD RVROIEDS_NAME VARCHAR2(255);
ALTER TABLE EDS_MODE_PARC ADD MPEDS_NAME VARCHAR2(255);
ALTER TABLE EDS_COURANT_MISE_SOUS_TENSION ADD CMSTEDS_NAME VARCHAR2(255);
-- [EX_FICH_36]
-- Add new data Tmoy and Tmoy_comment
ALTER TABLE EDS_CONS_SUP_TH ADD (CSEDS_TMOY REAL, CSEDS_TMOY_COMMENT VARCHAR2(1024));
ALTER TABLE EDS_CONSOLIDATE_SUPPLY_MESURE ADD (CSMEDS_TMOY REAL, CSMEDS_TMOY_COMMENT VARCHAR2(1024));
-- [EX_FICH_37]
-- Create new table to hold tensions
CREATE TABLE CONS_SUP_EDS_TENSION(
    CSEDSU_ID VARCHAR2(36) NOT NULL,
    CSTEDS_ID VARCHAR2(36) NOT NULL, 
    CSEDSU_NAME VARCHAR2(1024),
    CSEDS_UMIN FLOAT(23),
    CSEDS_UMOY FLOAT(23),
    CSEDS_UMAX FLOAT(23),
    CSEDS_UMIN_COMMENT VARCHAR2(1024),
    CSEDS_UMOY_COMMENT VARCHAR2(1024),
    CSEDS_UMAX_COMMENT VARCHAR2(1024),
    CONSTRAINT CONS_SUP_EDS_TENSION_PK PRIMARY KEY (CSEDSU_ID),
    CONSTRAINT CSTEDS_ID_FK FOREIGN KEY (CSTEDS_ID) REFERENCES EDS_CONS_SUP_TH(CSTEDS_ID)
);


-- [Ex_Fich_42]
-- Profile insertion: Type of profile in consolidated and enclosed
create table EDS_CONS_SUP_PROFILE (
    CSP_ID varchar2(36) not null,
    CSP_NAME varchar2(255) not null,
    CSP_TYPE varchar2(255) not null,
    CSP_COMMENT varchar2(1024)
);
alter table EDS_CONS_SUP_PROFILE add constraint EDS_CONS_SUP_PROFILE_PK primary key (CSP_ID);

create table EDS_J_CONS_SUP_MES_PROFILE (
    JCSP_CSMEDS_ID varchar2(36) not null,   -- refers to EDS_CONSOLIDATE_SUPPLY_MESURE.CSMEDS_ID
    JCSP_CSP_ID varchar2(36) not null       -- refers to EDS_CONS_SUP_PROFILE.CSP_ID (PK)
);

alter table EDS_J_CONS_SUP_MES_PROFILE
    add constraint EDS_J_CONS_SUP_MES_PROFILE_PK primary key(JCSP_CSP_ID);
alter table EDS_J_CONS_SUP_MES_PROFILE
    add constraint EDS_J_CONS_SUP_MES_PROFILE_FK1 foreign key(JCSP_CSP_ID) references EDS_CONS_SUP_PROFILE(CSP_ID);
alter table EDS_J_CONS_SUP_MES_PROFILE
    add constraint EDS_J_CONS_SUP_MES_PROFILE_FK2 foreign key(JCSP_CSMEDS_ID) references EDS_CONSOLIDATE_SUPPLY_MESURE(CSMEDS_ID);
    
-- [Ex_Fich_43]
-- List of points
CREATE TABLE EDS_CONS_SUP_PROFILE_POINTS (
    CSPP_ID varchar2(36) NOT null,
    CSPP_XY_DATA VARCHAR2(2048),
    CSPP_MESURE_TEMP FLOAT,
    CSPP_Y_AXIS_VALUE FLOAT,
    CSPP_TIME_AXIS_VALUE FLOAT,
    CSPP_SOURCE_IMPEDANCE FLOAT,
    CSP_ID varchar2(36) NOT null
);

ALTER TABLE EDS_CONS_SUP_PROFILE_POINTS ADD CONSTRAINT EDS_CSP_POINTS_PK PRIMARY KEY(CSPP_ID);
ALTER TABLE EDS_CONS_SUP_PROFILE_POINTS ADD CONSTRAINT EDS_CSP_POINTS_FK1 FOREIGN KEY(CSP_ID) REFERENCES EDS_CONS_SUP_PROFILE(CSP_ID);

-- [Ex_Fich_46]
-- Addition of profile of consumption: To import an image
ALTER TABLE EDS_CONS_SUP_PROFILE ADD CSP_IMAGE varchar2(225);
