-- [Ex_Fich_1] Tables names modification in EDS database
ALTER TABLE CONS_SUP_EDS_TENSION RENAME TO OPLQTSET ;
ALTER TABLE EDS_ATTACHMENT RENAME TO OPLQTATT ;
ALTER TABLE EDS_ATTACHMENT_FORM_DATA RENAME TO OPLQTATD ;
ALTER TABLE EDS_COMPONENT_TYPE RENAME TO OPLQTCOT ;
ALTER TABLE EDS_CMPT_CONS_FORM_DATA RENAME TO OPLQTCCD ;
ALTER TABLE EDS_CMPTT_ROB_FORM_DATA RENAME TO OPLQTCRD ;
ALTER TABLE EDS_CONS_CURENT_FORM_DATA RENAME TO OPLQTOCD ;
ALTER TABLE EDS_CONSD_SUP_VOLT_FORM_DATA RENAME TO OPLQTSVD ;
ALTER TABLE EDS_CONSOLIDATE_SUPPLY RENAME TO OPLQTCOS ;
ALTER TABLE EDS_CONSOLIDATE_SUPPLY_MESURE RENAME TO OPLQTCSM ;
ALTER TABLE EDS_CONS_SUP_TH RENAME TO OPLQTCST ;
ALTER TABLE EDS_CONS_SUP_PROFILE RENAME TO OPLQTCSP ;
ALTER TABLE EDS_CONS_SUP_PROFILE_POINTS RENAME TO OPLQTSPP ;
ALTER TABLE EDS_CRT_APPELLE_ACTIVATION RENAME TO OPLQTCAA ;
ALTER TABLE EDS_CRT_BLOQUE_CRT_DYSF RENAME TO OPLQTBCD ;
ALTER TABLE EDS_COURANT_CYCLE RENAME TO OPLQTCOC ;
ALTER TABLE EDS_COURANT_EFFICACE RENAME TO OPLQTCOE ;
ALTER TABLE EDS_COURANT_MISE_SOUS_TENSION RENAME TO OPLQTMST ;
ALTER TABLE EDS_CRT_NOMINALE_ACTIVATION RENAME TO OPLQTCNA ;
ALTER TABLE EDS_CSE_FORM_DATA RENAME TO OPLQTCSD ;
ALTER TABLE EDS_CSE_LINE RENAME TO OPLQTCSL ;
ALTER TABLE EDS_CURRENT_STATEMENT RENAME TO OPLQTCUS ;
ALTER TABLE EDS_DVR_FORM_DATA RENAME TO OPLQTDVD ;
ALTER TABLE EDS_DRIFT_INFO RENAME TO OPLQTDRI ;
ALTER TABLE EDS_EDS RENAME TO OPLQTEDS ;
ALTER TABLE EDS_GROUND RENAME TO OPLQTGRO ;
ALTER TABLE EDS_GROUND_CONSOLIDATE RENAME TO OPLQTGRC ;
ALTER TABLE EDS_GROUND_CONSOLIDATE_CURENT RENAME TO OPLQTGCC ;
ALTER TABLE EDS_GROUND_ROBUST_CURENT RENAME TO OPLQTRRC ;
ALTER TABLE EDS_HIGH_VALIDATION_FORM_DATA RENAME TO OPLQTHVD ;
ALTER TABLE EDS_LOW_VALIDATION_FORM_DATA RENAME TO OPLQTLVD ;
ALTER TABLE EDS_MISSION_ACTN_FORM_DATA RENAME TO OPLQTMAD ;
ALTER TABLE EDS_MISSION_PROFIL RENAME TO OPLQTMIP ;
ALTER TABLE EDS_MISSION_PROFIL_FORM_DATA RENAME TO OPLQTMPD ;
ALTER TABLE EDS_MODE_MONTAGE RENAME TO OPLQTMOM ;
ALTER TABLE EDS_MODE_PARC RENAME TO OPLQTMOP ;
ALTER TABLE EDS_NUMBER_96K RENAME TO OPLQTNUN ;
ALTER TABLE EDS_EDS_NUMBER_96K RENAME TO OPLQTENN ;
ALTER TABLE EDS_PERIMETER RENAME TO OPLQTPER ;
ALTER TABLE EDS_EDS_PERIMETER RENAME TO OPLQTEPE ;
ALTER TABLE EDS_PREL_SUP_VOLT_FORM_DATA RENAME TO OPLQTPVD ;
ALTER TABLE EDS_PRIMARY_CURENT RENAME TO OPLQTPRC ;
ALTER TABLE EDS_PRIMARY_SUPPLY RENAME TO OPLQTPRS ;
ALTER TABLE EDS_PROJECT RENAME TO OPLQTPRO ;
ALTER TABLE EDS_PROJECT_EDS RENAME TO OPLQTPRE ;
ALTER TABLE EDS_PROJECT_NODE RENAME TO OPLQTPRN ;
ALTER TABLE EDS_PSA_MESURE_SUPPLY RENAME TO OPLQTPMS ;
ALTER TABLE EDS_QCF RENAME TO OPLQTQCF ;
ALTER TABLE EDS_RVROI RENAME TO OPLQTRVR ;
ALTER TABLE EDS_ROBUST_CURENT_FORM_DATA RENAME TO OPLQTRCD ;
ALTER TABLE EDS_ROBUST_SUPPLY RENAME TO OPLQTROS ;
ALTER TABLE EDS_ROBUST_SUP_USECASE RENAME TO OPLQTRSU ;
ALTER TABLE EDS_ROLE RENAME TO OPLQTROL ;
ALTER TABLE EDS_SUBSCRIPTION RENAME TO OPLQTSUB ;
ALTER TABLE EDS_SUPPLIER RENAME TO OPLQTSUR ;
ALTER TABLE EDS_SUPPLY RENAME TO OPLQTSUY ;
ALTER TABLE EDS_USER RENAME TO OPLQTUSE ;
ALTER TABLE EDS_VALIDATION RENAME TO OPLQTVAL ;
ALTER TABLE EDS_WORDING RENAME TO OPLQTWOR ;
ALTER TABLE EDS_GLOBAL_CONF RENAME TO OPLQTGLC ;
ALTER TABLE EDS_J_CONS_GROUND_CAA RENAME TO OPLQTCGC ;
ALTER TABLE EDS_J_CONS_GROUND_CBCD RENAME TO OPLQTOGC ;
ALTER TABLE EDS_J_CONS_GROUND_CNA RENAME TO OPLQTNGC ;
ALTER TABLE EDS_J_CONS_GROUND_CRT_MST RENAME TO OPLQTGCM ;
ALTER TABLE EDS_J_CONS_SUP_MES_CAA RENAME TO OPLQTSMC ;
ALTER TABLE EDS_J_CONS_SUP_MES_CBCD RENAME TO OPLQTUMC ;
ALTER TABLE EDS_J_CONS_SUP_MES_CNA RENAME TO OPLQTPMC ;
ALTER TABLE EDS_J_CONS_SUP_MES_CRT_MST RENAME TO OPLQTMCM ;
ALTER TABLE EDS_J_CONS_SUP_MES_MODE_MONT RENAME TO OPLQTMMM ;
ALTER TABLE EDS_J_CONS_SUP_MES_MODE_PARC RENAME TO OPLQTMMP ;
ALTER TABLE EDS_J_CONS_SUP_MES_PROFILE RENAME TO OPLQTSMP ;
ALTER TABLE EDS_J_CONS_SUP_MES_RVROI RENAME TO OPLQTSMR ;
ALTER TABLE EDS_J_CONS_SUP_MES_TENSIONS RENAME TO OPLQTSMT ;
ALTER TABLE EDS_J_CONS_SUP_THE_TENSIONS RENAME TO OPLQTSTT ;
ALTER TABLE EDS_J_CONS_SUP_TH_CAA RENAME TO OPLQTSTC ;
ALTER TABLE EDS_J_CONS_SUP_TH_CBCD RENAME TO OPLQTUTC ;
ALTER TABLE EDS_J_CONS_SUP_TH_CNA RENAME TO OPLQTPTC ;
ALTER TABLE EDS_J_CONS_SUP_TH_CRT_MST RENAME TO OPLQTTCM ;
ALTER TABLE EDS_J_CONS_SUP_TH_MODE_MONT RENAME TO OPLQTTMM ;
ALTER TABLE EDS_J_CONS_SUP_TH_MODE_PARC RENAME TO OPLQTTMP ;
ALTER TABLE EDS_J_CONS_SUP_TH_RVROI RENAME TO OPLQTSTR ;
ALTER TABLE EDS_J_PSA_MES_SUP_CAA RENAME TO OPLQTMSC ;
ALTER TABLE EDS_J_PSA_MES_SUP_CBCD RENAME TO OPLQTESC ;
ALTER TABLE EDS_J_PSA_MES_SUP_CNA RENAME TO OPLQTSSC ;
ALTER TABLE EDS_J_PSA_MES_SUP_CRT_CYCLE RENAME TO OPLQTSCC ;
ALTER TABLE EDS_J_PSA_MES_SUP_CRT_MST RENAME TO OPLQTSCM ;
ALTER TABLE EDS_J_PSA_MES_SUP_MODE_MONT RENAME TO OPLQTSMM ;
ALTER TABLE EDS_J_PSA_MES_SUP_MODE_PARC RENAME TO OPLQTUMP ;
ALTER TABLE EDS_J_PSA_MES_SUP_RVROI RENAME TO OPLQTMSR ;
ALTER TABLE EDS_PROJECT_CONS_CURENT RENAME TO OPLQTPCC ;
ALTER TABLE EDS_PROJECT_COURANT_CYCLE RENAME TO OPLQTRCC ;
ALTER TABLE EDS_PROJECT_PERIMETER RENAME TO OPLQTPRP ;
ALTER TABLE EDS_PROJECT_PRIMARY_CURENT RENAME TO OPLQTPPC ;
ALTER TABLE EDS_PROJECT_ROBUST_CURENT RENAME TO OPLQTORC ;
ALTER TABLE EDS_WS_SESSION_TOKEN RENAME TO OPLQTWST ;
ALTER TABLE SCHEMA_VERSION RENAME TO OPLQTSCV ;


-- Update the existing values
UPDATE OPLQTROS SET RSEDS_USE_CASE_NAME = '-' WHERE RSEDS_USE_CASE_NAME IS NULL;


-- [Ex_Fich_42]
-- Profile insertion: Type of profile in consolidated and enclosed
create table OPLQTSTP (
    JCSP_CSTEDS_ID varchar2(36) not null,   -- refers to OPLQTCST.CSTEDS_ID
    JCSP_CSP_ID varchar2(36) not null       -- refers to OPLQTCSP.CSP_ID (PK)
);

alter table OPLQTSTP add constraint OPLQTSTP_PK primary key(JCSP_CSP_ID);
alter table OPLQTSTP add constraint OPLQTSTP_FK1 foreign key(JCSP_CSP_ID) references OPLQTCSP(CSP_ID);
alter table OPLQTSTP add constraint OPLQTSTP_FK2 foreign key(JCSP_CSTEDS_ID) references OPLQTCST(CSTEDS_ID);

create table OPLQTPMP (
    JCSP_PMSEDS_ID varchar2(36) not null,   -- refers to OPLQTPMS.PMSEDS_ID
    JCSP_CSP_ID varchar2(36) not null       -- refers to OPLQTCSP.CSP_ID (PK)
);

alter table OPLQTPMP add constraint OPLQTPMP_PK primary key(JCSP_CSP_ID);
alter table OPLQTPMP add constraint OPLQTPMP_FK1 foreign key(JCSP_CSP_ID) references OPLQTCSP(CSP_ID);
alter table OPLQTPMP add constraint OPLQTPMP_FK2 foreign key(JCSP_PMSEDS_ID) references OPLQTPMS(PMSEDS_ID);
