CREATE TABLE COPQTGPI (

    ID              BIGINT(20)  UNIQUE NOT NULL AUTO_INCREMENT ,    
    LABEL   		VARCHAR(255),
    HELPTEXT     	VARCHAR(255),
    ORDER_NUMBER	INT(11),
	DATATYPE     	VARCHAR(255),
	UNIT			VARCHAR(255),
	AUTH_COMMENT    BOOLEAN,
    MANDATORY     	BOOLEAN,
    CHECKLIST_ID    BIGINT(20) 
);