CREATE TABLE COPQTSDL (
  ID 					BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  ARRIVAL_DATE 			DATE    ,
  PREPARATION_DATE 		DATE	,
  CONDITIONING_DATE		DATE	,
  TEST_BEGINNING_DATE	DATE	,
  RESTITUTION_DATE		DATE	,
  ARCHIVING_DATE		DATE	
);