CREATE TABLE COPQTCDP (

	ID              BIGINT(20)  UNIQUE NOT NULL AUTO_INCREMENT ,    
    LOWER_SYMBOL   	VARCHAR(255),
    LOWER_LIMIT     DOUBLE(49,4),
    HIGHER_SYMBOL   VARCHAR(255),
    HIGHER_LIMIT    DOUBLE(49,4),
    FUELTYPE_ID     INT(11) 
);
    
    