CREATE TABLE COPQTSCP (
   ID           			 BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
   UNCERTAINTY_FACTOR        DOUBLE(49,4),
   LIMIT1  				     DOUBLE(49,4),
   LIMIT2     				 DOUBLE(49,4),
   LIMIT3 					 DOUBLE(49,4),
   LIMIT4					 DOUBLE(49,4),
   SAMPLE_MAXIMUM_SIZE		 INT(11),
   POLLUTANT_GAS_ID		     BIGINT(20),
   STATISTICAL_RULE_ID		 BIGINT(20)
  );
