-- Preparation Result
CREATE TABLE COPQTPRT (
  ID 					BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  PREP_CHECKLIST_ID		BIGINT(20)		,
  CONFORMITY			TINYINT(1)	 	,
  VALUE					VARCHAR(255)	,
  COMMENT				VARCHAR(255)	,
  LABEL					VARCHAR(255)	,
  DATA_TYPE				VARCHAR(255)	,
  UNIT					VARCHAR(255)	,
  ORDER_NUMBER			INT(11)			,
  HELP_TEXT				VARCHAR(1000)	,
  MANDATORY				TINYINT(1)		,
  AUTHORIZED_COMMENT	TINYINT(1)		,
  CREATION_DATE			DATETIME NOT NULL,
  UPDATION_DATE			DATETIME NOT NULL
 );