CREATE TABLE COPQTVHF (
  ID 					BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  OPACITY_RESULT_ID		BIGINT(20)		,
  VEHICLE_ID			BIGINT(20)		,
  VFILE_STATUS_ID		BIGINT(20) 		,
  PREVIOUS_VF_STATUS_ID BIGINT(20)      ,
  BASKET_ID             BIGINT(20)      ,
  SCHEDULE_ID			BIGINT(20)		,
  RECEPTION_FILE_ID 	BIGINT(20)		,
  RESTITUTION_FILE_ID	BIGINT(20)		,
  TYPE_TEST_ID		    BIGINT(20)		,
  ARCHIVE_BOX_ID		BIGINT(20)		,
  STATISTICAL_DECISION	VARCHAR(255)	,
  SANTORIN_REFERENCE    VARCHAR(255)	,
  CREATION_DATE 		DATE  			,
  UPDATE_DATE 			DATE            
);