CREATE TABLE COPQTGPC (

    ID              	BIGINT(20)  UNIQUE NOT NULL AUTO_INCREMENT ,    
    LABEL   			VARCHAR(255),
    DESCRIPTION     	VARCHAR(255),
    ORDER_NUMBER		INT(11),
    ENABLED     		BOOLEAN,
    FILE_STRUCTURE_ID   BIGINT(20) 
);