CREATE TABLE COPQTPCL (
  ID 					BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  LABEL					VARCHAR(255)	,
  ENABLED				TINYINT(1) 		,
  ORDER_NUMBER			INT(11)			,
  TYPE_OF_LIST			INT(11)			,
  DESCRIPTION			VARCHAR(255)	,
  PREPARATION_FILE_ID	BIGINT(20)		 
);