CREATE TABLE COPQTVHL (
  ID 					BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT ,
  TECHINICAL_CASE_ID	BIGINT(20)   ,
  PARKING_LOT_ID		BIGINT(20)   ,
  VEHICLE_FACTORY_ID	BIGINT(20)   ,
  CORVET_DATA_ID        BIGINT(20)   ,
  COUNTRY_ID	        BIGINT(20)   ,
  VIN					VARCHAR(255) ,
  COUNTERMARK			VARCHAR(255) ,
  REGISTRATION_NUMBER	VARCHAR(255) ,
  CHASIS_NUMBER			VARCHAR(255) ,
  DESCRIPTION			VARCHAR(255) ,
  FLOW_TYPE				VARCHAR(255) ,
  PRIORITY_INDICATOR	VARCHAR(255) ,
  MODEL_YEAR			VARCHAR(255) ,
  MCO2_I				DOUBLE
);