-- Preparation File
CREATE TABLE COPQTPRF (
  ID 						BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT ,
  VEHICLE_FILE_ID			BIGINT(20),
  PREP_FILE_STRUCTURE_ID 	BIGINT(20),
  USER_ID                   BIGINT(20),
  CREATION_DATE				DATETIME NOT NULL,
  MODIFICATION_DATE 		DATETIME NOT NULL
);