CREATE TABLE COPQTOPR (
  ID 					BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  FUEL_TYPE_ID          INT(11)      ,
  MEASURE_1				DOUBLE			,
  MEASURE_2				DOUBLE			,	
  MEASURE_3				DOUBLE			,
  MEASURE_4				DOUBLE			,
  MEASURE_AVERAGE		DOUBLE			,
  OPACITY_DECISION		VARCHAR(255)	,
  VALUE					VARCHAR(255)	,
  COMMENT				VARCHAR(255)	,
  CREATION_DATE 		DATE   			,
  UPDATE_DATE 			DATE 
);