package com.inetpsa.eds.dao.model;

// Generated 29 oct. 2012 15:24:19 by Hibernate Tools 3.2.1.GA

import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsAttachment generated by hbm2java
 */
@XmlType
public class EdsAttachment implements java.io.Serializable {
    /**
     * String Variable to hold the value of Attachment Id for Column A_ID of Table OPLQTATT
     */
    private String AId;
    /**
     * Variable to hold the value of Attachment Form Data for Column A_AFD_ID of Table OPLQTATT
     */
    private EdsAttachmentFormData edsAttachmentFormData;
    /**
     * String Variable to hold the value for Column A_LINK of Table OPLQTATT
     */
    private String ALink;
    /**
     * String Variable to hold the value for Column A_COMMENT of Table OPLQTATT
     */
    private String AComment;

    /**
     * Default Constructor
     */
    public EdsAttachment() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param otherAttachement Eds attachment
     * @param attachmentFormData
     */
    public EdsAttachment(EdsAttachment otherAttachement, EdsAttachmentFormData attachmentFormData) {
        this(UUID.randomUUID().toString(), attachmentFormData, otherAttachement.ALink, otherAttachement.AComment);
    }

    /**
     * Parameterized Constructor
     * 
     * @param AId Id
     * @param edsAttachmentFormData Eds attached form data
     * @param ALink Link
     */
    public EdsAttachment(String AId, EdsAttachmentFormData edsAttachmentFormData, String ALink) {
        this.AId = AId;
        this.edsAttachmentFormData = edsAttachmentFormData;
        this.ALink = ALink;
    }

    /**
     * Parameterized Constructor
     * 
     * @param AId Id
     * @param edsAttachmentFormData Eds attached form data
     * @param ALink Link
     * @param AComment Comment
     */
    public EdsAttachment(String AId, EdsAttachmentFormData edsAttachmentFormData, String ALink, String AComment) {
        this.AId = AId;
        this.edsAttachmentFormData = edsAttachmentFormData;
        this.ALink = ALink;
        this.AComment = AComment;
    }

    /**
     * Function to get AId
     * 
     * @return Attachment ID
     */
    @XmlTransient
    public String getAId() {
        return this.AId;
    }

    /**
     * Function to set AId
     * 
     * @param AId
     */
    public void setAId(String AId) {
        this.AId = AId;
    }

    /**
     * Function to get edsAttachmentFormData
     * 
     * @return EdsAttachmentFormData
     */
    @XmlTransient
    public EdsAttachmentFormData getEdsAttachmentFormData() {
        return this.edsAttachmentFormData;
    }

    /**
     * Function to set edsAttachmentFormData
     * 
     * @param edsAttachmentFormData
     */
    public void setEdsAttachmentFormData(EdsAttachmentFormData edsAttachmentFormData) {
        this.edsAttachmentFormData = edsAttachmentFormData;
    }

    /**
     * Function to get ALink
     * 
     * @return Attachment link
     */
    @XmlElement(name = "link")
    public String getALink() {
        return this.ALink;
    }

    /**
     * Function to set ALink
     * 
     * @param ALink
     */
    public void setALink(String ALink) {
        this.ALink = ALink;
    }

    /**
     * Function to get AComment
     * 
     * @return Comment
     */
    @XmlElement(name = "comment")
    public String getAComment() {
        return this.AComment;
    }

    /**
     * Function to set AComment
     * 
     * @param AComment
     */
    public void setAComment(String AComment) {
        this.AComment = AComment;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsAttachment other = (EdsAttachment) obj;
        if ((this.ALink == null) ? (other.ALink != null) : !this.ALink.equals(other.ALink)) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + (this.ALink != null ? this.ALink.hashCode() : 0);
        return hash;
    }
}
