package com.inetpsa.eds.dao.model;

// Generated 22 sept. 2012 13:59:42 by Hibernate Tools 3.2.1.GA

import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

import com.inetpsa.eds.tools.EDSTools;

/**
 * EdsCourantMiseSousTension generated by hbm2java
 */
public class EdsCourantMiseSousTension implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column CMSTEDS_ID of Table OPLQTMST
     */
    private String cmstedsId;
    /**
     * Float Variable to hold the value for Column CMSTEDS_TPIRECAS_IMST of Table OPLQTMST
     */
    private Float cmstedsTpirecasImst;
    /**
     * Float Variable to hold the value for Column CMSTEDS_TPIRECAS_DT of Table OPLQTMST
     */
    private Float cmstedsTpirecasDt;
    /**
     * String Variable to hold the value for Column CMSTEDS_TPIRECAS_IMST_COMMENT of Table OPLQTMST
     */
    private String cmstedsTpirecasImstComment;
    /**
     * String Variable to hold the value for Column CMSTEDS_TPIRECAS_DT_COMMENT of Table OPLQTMST
     */
    private String cmstedsTpirecasDtComment;

    /**
     * String Variable to hold the value for Column CMSTEDS_NAME of Table OPLQTMST
     */
    private String cmstedsName;

    /**
     * Default Constructor
     */
    public EdsCourantMiseSousTension() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param cmstedsId
     */
    public EdsCourantMiseSousTension(String cmstedsId) {
        this.cmstedsId = cmstedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param cmstedsId Id
     * @param cmstedsTpirecasImst TWorst case Imst
     * @param cmstedsTpirecasDt Tworst case Dt
     * @param cmstedsTpirecasImstComment Tworstcase Imst comment
     * @param cmstedsTpirecasDtComment Tworstcase Dt comment
     */
    public EdsCourantMiseSousTension(String cmstedsId, Float cmstedsTpirecasImst, Float cmstedsTpirecasDt, String cmstedsTpirecasImstComment,
            String cmstedsTpirecasDtComment) {
        this.cmstedsId = cmstedsId;
        this.cmstedsTpirecasImst = cmstedsTpirecasImst;
        this.cmstedsTpirecasDt = cmstedsTpirecasDt;
        this.cmstedsTpirecasImstComment = cmstedsTpirecasImstComment;
        this.cmstedsTpirecasDtComment = cmstedsTpirecasDtComment;
    }

    /**
     * Parameterized Constructor
     * 
     * @param srcCourantMiseSousTension EdsCourantMiseSousTension
     */
    public EdsCourantMiseSousTension(EdsCourantMiseSousTension srcCourantMiseSousTension) {
        this.cmstedsId = UUID.randomUUID().toString();
        this.cmstedsTpirecasImst = srcCourantMiseSousTension.cmstedsTpirecasImst;
        this.cmstedsTpirecasDt = srcCourantMiseSousTension.cmstedsTpirecasDt;
        this.cmstedsTpirecasImstComment = srcCourantMiseSousTension.cmstedsTpirecasImstComment;
        this.cmstedsTpirecasDtComment = srcCourantMiseSousTension.cmstedsTpirecasDtComment;
    }

    /**
     * Function to set cmstedsId
     * 
     * @return Id
     */
    @XmlAttribute(name = "id")
    public String getCmstedsId() {
        return this.cmstedsId;
    }

    /**
     * Function to set cmstedsId
     * 
     * @param cmstedsId ID
     */
    public void setCmstedsId(String cmstedsId) {
        this.cmstedsId = cmstedsId;
    }

    /**
     * Function to get cmstedsTpirecasImst
     * 
     * @return Tworstcase Imst
     */
    @XmlElement(name = "TpirecasImst")
    public Float getCmstedsTpirecasImst() {
        return this.cmstedsTpirecasImst;
    }

    /**
     * Function to set cmstedsTpirecasImst
     * 
     * @param cmstedsTpirecasImst Tworstcase Imst
     */
    public void setCmstedsTpirecasImst(Float cmstedsTpirecasImst) {
        this.cmstedsTpirecasImst = cmstedsTpirecasImst;
    }

    /**
     * Function to get cmstedsTpirecasDt
     * 
     * @return Tworstcase Dt
     */
    @XmlElement(name = "TpirecasDt")
    public Float getCmstedsTpirecasDt() {
        return this.cmstedsTpirecasDt;
    }

    /**
     * Function to set cmstedsTpirecasDt
     * 
     * @param cmstedsTpirecasDt Tworstcase Dt
     */
    public void setCmstedsTpirecasDt(Float cmstedsTpirecasDt) {
        this.cmstedsTpirecasDt = cmstedsTpirecasDt;
    }

    /**
     * Function to get cmstedsTpirecasImstComment
     * 
     * @return Tworstcase Ismt comment
     */
    public String getCmstedsTpirecasImstComment() {
        return this.cmstedsTpirecasImstComment;
    }

    /**
     * Function to set cmstedsTpirecasImstComment
     * 
     * @param cmstedsTpirecasImstComment Tworstcase Imst comment
     */
    public void setCmstedsTpirecasImstComment(String cmstedsTpirecasImstComment) {
        this.cmstedsTpirecasImstComment = cmstedsTpirecasImstComment;
    }

    /**
     * Function to get cmstedsTpirecasDtComment
     * 
     * @return Tworstcase dt comment
     */
    public String getCmstedsTpirecasDtComment() {
        return this.cmstedsTpirecasDtComment;
    }

    /**
     * Function to set cmstedsTpirecasDtComment
     * 
     * @param cmstedsTpirecasDtComment Tworstcase Dt comment
     */
    public void setCmstedsTpirecasDtComment(String cmstedsTpirecasDtComment) {
        this.cmstedsTpirecasDtComment = cmstedsTpirecasDtComment;
    }

    /**
     * Getter cmstedsName
     * 
     * @return the cmstedsName
     */
    public String getCmstedsName() {
        return cmstedsName;
    }

    /**
     * Setter cmstedsName
     * 
     * @param cmstedsName the cmstedsName to set
     */
    public void setCmstedsName(String cmstedsName) {
        this.cmstedsName = cmstedsName;
    }

    /**
     * Function to set data for Powered on current
     * 
     * @param edsCourantMiseSousTensions Set of EdsCourantMiseSousTension
     */
    public void setSomme(Set<EdsCourantMiseSousTension> edsCourantMiseSousTensions) {
        for (EdsCourantMiseSousTension ecmst : edsCourantMiseSousTensions) {
            this.cmstedsTpirecasImst = EDSTools.Concat(this.cmstedsTpirecasImst, ecmst.cmstedsTpirecasImst);
            this.cmstedsTpirecasDt = EDSTools.Concat(this.cmstedsTpirecasDt, ecmst.cmstedsTpirecasDt);
        }
    }
}
