package com.inetpsa.eds.dao.model;

// Generated 27 sept. 2012 18:58:17 by Hibernate Tools 3.2.1.GA

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;

import com.inetpsa.eds.dao.I_DriftableSupply;

/**
 * EdsConsolidateSupplyTheoritic generated by hbm2java
 */

public class EdsConsolidateSupplyTheoritic implements java.io.Serializable, I_DriftableSupply {
    /**
     * Serial UID
     */
    private static final long serialVersionUID = -5002906856202886297L;

    /**
     * EdsConsolidateSupply parent Consolidate supply
     */
    private EdsConsolidateSupply edsConsolidateSupply;

    /**
     * String Variable to hold the value for Column CSTEDS_ID of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private String cstedsId;

    /**
     * Float variable to hold value of Column CSEDS_TMIN of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private Float csedsTmin;

    /**
     * Float variable to hold value of Column CSEDS_TMOY of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private Float csedsTmoy;

    /**
     * Float variable to hold value of Column CSEDS_TMAX of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private Float csedsTmax;

    /**
     * String Variable to hold the value for Column CSEDS_TMIN_IFORM_BY of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private String csedsTminIformBy;

    /**
     * String Variable to hold the value for Column CSEDS_TMAX_IFORM_BY of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private String csedsTmaxIformBy;

    /**
     * String Variable to hold the value for Column CSEDS_TMIN_COMMENT of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private String csedsTminComment;

    /**
     * String Variable to hold the value for Column CSEDS_TMOY_COMMENT of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private String csedsTmoyComment;

    /**
     * String Variable to hold the value for Column CSEDS_TMAX_COMMENT of Table EDS_CONSOLIDATED_SUPPLY_THEORITIC
     */
    private String csedsTmaxComment;

    /**
     * Set variable to hold values of {@link EdsConsSupProfile}
     */
    private Set<EdsConsSupProfile> edsConsolidateSupplyProfile = new LinkedHashSet<EdsConsSupProfile>(0);

    /**
     * variable to hold value of set of EdsCourantBloqueCourantDysfonctionnement.
     */
    private Set<EdsCourantBloqueCourantDysfonctionnement> edsCourantBloqueCourantDysfonctionnements = new LinkedHashSet<EdsCourantBloqueCourantDysfonctionnement>(
            0);

    /**
     * variable to hold value of set of EdsModeParc.
     */
    private Set<EdsModeParc> edsModeParcs = new LinkedHashSet<EdsModeParc>(0);

    /**
     * variable to hold value of set of EdsReseauVeilleReveilleOrganeInactif.
     */
    private Set<EdsReseauVeilleReveilleOrganeInactif> edsReseauVeilleReveilleOrganeInactifs = new LinkedHashSet<EdsReseauVeilleReveilleOrganeInactif>(
            0);

    /**
     * variable to hold value of set of EdsCourantMiseSousTension.
     */
    private Set<EdsCourantMiseSousTension> edsCourantMiseSousTensions = new LinkedHashSet<EdsCourantMiseSousTension>(0);

    /**
     * variable to hold value of set of EdsModeMontage.
     */
    private Set<EdsModeMontage> edsModeMontages = new LinkedHashSet<EdsModeMontage>(0);

    /**
     * variable to hold value of set of EdsCourantNominaleActivation.
     */
    private Set<EdsCourantNominaleActivation> edsCourantNominaleActivations = new LinkedHashSet<EdsCourantNominaleActivation>(0);

    /**
     * variable to hold value of set of EdsCourantAppelleActivation.
     */
    private Set<EdsCourantAppelleActivation> edsCourantAppelleActivations = new LinkedHashSet<EdsCourantAppelleActivation>(0);

    /**
     * variable to hold value of set of ConsolidateSupplyEdsTension.
     */
    private Set<ConsolidateSupplyEdsTension> consolidateSupplyEdsTensions = new LinkedHashSet<ConsolidateSupplyEdsTension>(0);

    /**
     * Default constructor
     */
    public EdsConsolidateSupplyTheoritic() {
    }

    /**
     * Parameterized constructor
     * 
     * @param cstedsId Consolidate Supply Theoritic Id
     */
    public EdsConsolidateSupplyTheoritic(String cstedsId) {
        this.cstedsId = cstedsId;
    }

    /**
     * Parameterized constructor
     * 
     * @param ecst EdsConsolidateSupplyTheoritic
     */
    public EdsConsolidateSupplyTheoritic(EdsConsolidateSupplyTheoritic ecst) {
        this.cstedsId = UUID.randomUUID().toString();
        this.csedsTmax = ecst.csedsTmax;
        this.csedsTmaxComment = ecst.csedsTmaxComment;
        this.csedsTmaxIformBy = ecst.csedsTmaxIformBy;
        this.csedsTmin = ecst.csedsTmin;
        this.csedsTminComment = ecst.csedsTminComment;
        this.csedsTmoy = ecst.csedsTmoy;
        this.csedsTmoyComment = ecst.csedsTmoyComment;
        this.csedsTminIformBy = ecst.csedsTminIformBy;

        for (EdsCourantAppelleActivation source : ecst.edsCourantAppelleActivations) {
            edsCourantAppelleActivations.add(new EdsCourantAppelleActivation(source));
        }
        for (EdsReseauVeilleReveilleOrganeInactif source : ecst.edsReseauVeilleReveilleOrganeInactifs) {
            edsReseauVeilleReveilleOrganeInactifs.add(new EdsReseauVeilleReveilleOrganeInactif(source));
        }
        for (EdsCourantNominaleActivation source : ecst.edsCourantNominaleActivations) {
            edsCourantNominaleActivations.add(new EdsCourantNominaleActivation(source));
        }
        for (EdsCourantMiseSousTension source : ecst.edsCourantMiseSousTensions) {
            edsCourantMiseSousTensions.add(new EdsCourantMiseSousTension(source));
        }
        for (EdsModeParc source : ecst.edsModeParcs) {
            edsModeParcs.add(new EdsModeParc(source));
        }
        for (EdsModeMontage source : ecst.edsModeMontages) {
            edsModeMontages.add(new EdsModeMontage(source));
        }
        for (EdsCourantBloqueCourantDysfonctionnement source : ecst.edsCourantBloqueCourantDysfonctionnements) {
            edsCourantBloqueCourantDysfonctionnements.add(new EdsCourantBloqueCourantDysfonctionnement(source));
        }

        for (ConsolidateSupplyEdsTension source : ecst.consolidateSupplyEdsTensions) {
            consolidateSupplyEdsTensions.add(new ConsolidateSupplyEdsTension(source));
        }

    }

    /**
     * Function to get Consolidate supply theoritic id
     * 
     * @return Consolidate supply theoritic id
     */
    @XmlAttribute(name = "id")
    public String getCstedsId() {
        return this.cstedsId;
    }

    /**
     * Function to set Consolidate supply theoritic id
     * 
     * @param cstedsId Consolidate supply theoritic id
     */
    public void setCstedsId(String cstedsId) {
        this.cstedsId = cstedsId;
    }

    /**
     * Function returns parent Consolidate supply
     * 
     * @return Consolidate supply
     */
    @XmlTransient
    public EdsConsolidateSupply getCsmedsConsolidateSupply() {
        return this.edsConsolidateSupply;
    }

    /**
     * Function set parent Consolidate supply
     * 
     * @param edsConsolidateSupply Parent Consolidate supply
     */
    public void setCsmedsConsolidateSupply(EdsConsolidateSupply edsConsolidateSupply) {
        this.edsConsolidateSupply = edsConsolidateSupply;
    }

    /**
     * Function to get Consolidate supply theoritic Tmin
     * 
     * @return Consolidate supply theoritic Tmin
     */
    @XmlElement(name = "Tmin")
    public Float getCsedsTmin() {
        return this.csedsTmin;
    }

    /**
     * Function to set Consolidate supply theoritic Tmin
     * 
     * @param csedsTmin Consolidate supply theoritic Tmin
     */
    public void setCsedsTmin(Float csedsTmin) {
        this.csedsTmin = csedsTmin;
    }

    /**
     * Getter csedsTmoy
     * 
     * @return the csedsTmoy
     */
    @XmlElement(name = "Tmoy")
    public Float getCsedsTmoy() {
        return csedsTmoy;
    }

    /**
     * Setter csedsTmoy
     * 
     * @param csedsTmoy the csedsTmoy to set
     */
    public void setCsedsTmoy(Float csedsTmoy) {
        this.csedsTmoy = csedsTmoy;
    }

    /**
     * Function to get Consolidate supply theoritic Tmax
     * 
     * @return Consolidate supply theoritic Tmax
     */
    @XmlElement(name = "Tmax")
    public Float getCsedsTmax() {
        return this.csedsTmax;
    }

    /**
     * Function to set Consolidate supply theoritic Tmax
     * 
     * @param csedsTmax Consolidate supply theoritic Tmax
     */
    public void setCsedsTmax(Float csedsTmax) {
        this.csedsTmax = csedsTmax;
    }

    /**
     * Function to get Consolidate supply theoritic Tmin Iform by
     * 
     * @return Consolidate supply theoritic Tmin Iform by
     */
    @XmlTransient
    public String getCsedsTminIformBy() {
        return this.csedsTminIformBy;
    }

    /**
     * Function to set Consolidate supply theoritic Tmin Iform by
     * 
     * @param csedsTminIformBy Consolidate supply theoritic Tmin Iform by
     */
    public void setCsedsTminIformBy(String csedsTminIformBy) {
        this.csedsTminIformBy = csedsTminIformBy;
    }

    /**
     * Function to get Consolidate supply theoritic Tmax Iform by
     * 
     * @return Consolidate supply theoritic Tmax Iform by
     */
    @XmlTransient
    public String getCsedsTmaxIformBy() {
        return this.csedsTmaxIformBy;
    }

    /**
     * Function to set Consolidate supply theoritic Tmax Iform by
     * 
     * @param csedsTmaxIformBy Consolidate supply theoritic Tmax Iform by
     */
    public void setCsedsTmaxIformBy(String csedsTmaxIformBy) {
        this.csedsTmaxIformBy = csedsTmaxIformBy;
    }

    /**
     * Function returns Consolidate supply theoritic Tmin comment
     * 
     * @return Consolidate supply theoritic Tmin comment
     */
    @XmlElement(name = "TminThComment")
    public String getCsedsTminComment() {
        return this.csedsTminComment;
    }

    /**
     * Function set Consolidate supply theoritic Tmin comment
     * 
     * @param csedsTminComment Consolidate supply theoritic Tmin comment
     */
    public void setCsedsTminComment(String csedsTminComment) {
        this.csedsTminComment = csedsTminComment;
    }

    /**
     * Function returns Consolidate supply theoritic Tmax comment
     * 
     * @return Consolidate supply theoritic Tmax comment
     */
    @XmlElement(name = "TmaxThComment")
    public String getCsedsTmaxComment() {
        return this.csedsTmaxComment;
    }

    /**
     * Getter csedsTmoyComment
     * 
     * @return the csedsTmoyComment
     */
    public String getCsedsTmoyComment() {
        return csedsTmoyComment;
    }

    /**
     * Setter csedsTmoyComment
     * 
     * @param csedsTmoyComment the csedsTmoyComment to set
     */
    public void setCsedsTmoyComment(String csedsTmoyComment) {
        this.csedsTmoyComment = csedsTmoyComment;
    }

    /**
     * Function set Consolidate supply theoritic Tmax comment
     * 
     * @param csedsTmaxComment Consolidate supply theoritic Tmax comment
     */
    public void setCsedsTmaxComment(String csedsTmaxComment) {
        this.csedsTmaxComment = csedsTmaxComment;
    }

    /**
     * Function return the set of EdsReseauVeilleReveilleOrganeInactif
     * 
     * @return set of EdsReseauVeilleReveilleOrganeInactif
     */
    @XmlElementWrapper(name = "ReseauVeilleReveilleOrganeInactifs")
    @XmlElement(name = "ReseauVeilleReveilleOrganeInactif")
    public Set<EdsReseauVeilleReveilleOrganeInactif> getEdsReseauVeilleReveilleOrganeInactifs() {
        return edsReseauVeilleReveilleOrganeInactifs;
    }

    /**
     * Function set the set of EdsReseauVeilleReveilleOrganeInactif
     * 
     * @param edsReseauVeilleReveilleOrganeInactifs set of EdsReseauVeilleReveilleOrganeInactif
     */
    public void setEdsReseauVeilleReveilleOrganeInactifs(Set<EdsReseauVeilleReveilleOrganeInactif> edsReseauVeilleReveilleOrganeInactifs) {
        this.edsReseauVeilleReveilleOrganeInactifs = edsReseauVeilleReveilleOrganeInactifs;
    }

    /**
     * Function returns set of EdsModeMontage
     * 
     * @return set of EdsModeMontage
     */
    @XmlElementWrapper(name = "ModeMontages")
    @XmlElement(name = "ModeMontage")
    public Set<EdsModeMontage> getEdsModeMontages() {
        return edsModeMontages;
    }

    /**
     * Function set the set of EdsModeMontage
     * 
     * @param edsModeMontages set of EdsModeMontage
     */
    public void setEdsModeMontages(Set<EdsModeMontage> edsModeMontages) {
        this.edsModeMontages = edsModeMontages;
    }

    /**
     * Function returns set of EdsCourantAppelleActivation
     * 
     * @return set of EdsCourantAppelleActivation
     */
    @XmlElementWrapper(name = "CourantsAppelleActivation")
    @XmlElement(name = "CourantAppelleActivation")
    public Set<EdsCourantAppelleActivation> getEdsCourantAppelleActivations() {
        return edsCourantAppelleActivations;
    }

    /**
     * Function set the set of EdsCourantAppelleActivation
     * 
     * @param edsCourantAppelleActivations set of EdsCourantAppelleActivation
     */
    public void setEdsCourantAppelleActivations(Set<EdsCourantAppelleActivation> edsCourantAppelleActivations) {
        this.edsCourantAppelleActivations = edsCourantAppelleActivations;
    }

    /**
     * Function returns set of EdsCourantBloqueCourantDysfonctionnement
     * 
     * @return set of EdsCourantBloqueCourantDysfonctionnement
     */
    @XmlElementWrapper(name = "CourantsBloqueCourantDysfonctionnement")
    @XmlElement(name = "CourantBloqueCourantDysfonctionnement")
    public Set<EdsCourantBloqueCourantDysfonctionnement> getEdsCourantBloqueCourantDysfonctionnements() {
        return edsCourantBloqueCourantDysfonctionnements;
    }

    /**
     * Function set the set of EdsCourantBloqueCourantDysfonctionnement
     * 
     * @param edsCourantBloqueCourantDysfonctionnements set of EdsCourantBloqueCourantDysfonctionnement
     */
    public void setEdsCourantBloqueCourantDysfonctionnements(Set<EdsCourantBloqueCourantDysfonctionnement> edsCourantBloqueCourantDysfonctionnements) {
        this.edsCourantBloqueCourantDysfonctionnements = edsCourantBloqueCourantDysfonctionnements;
    }

    /**
     * Function returns the set of EdsCourantMiseSousTension
     * 
     * @return set of EdsCourantMiseSousTension
     */
    @XmlElementWrapper(name = "CourantsMiseSousTension")
    @XmlElement(name = "CourantMiseSousTension")
    public Set<EdsCourantMiseSousTension> getEdsCourantMiseSousTensions() {
        return edsCourantMiseSousTensions;
    }

    /**
     * Getter consolidateSupplyEdsTensions
     * 
     * @return the consolidateSupplyEdsTensions
     */
    @XmlTransient
    public Set<ConsolidateSupplyEdsTension> getConsolidateSupplyEdsTensions() {
        return consolidateSupplyEdsTensions;
    }

    /**
     * Setter consolidateSupplyEdsTensions
     * 
     * @param consolidateSupplyEdsTensions the consolidateSupplyEdsTensions to set
     */
    public void setConsolidateSupplyEdsTensions(Set<ConsolidateSupplyEdsTension> consolidateSupplyEdsTensions) {
        this.consolidateSupplyEdsTensions = consolidateSupplyEdsTensions;
    }

    /**
     * Function set the set of EdsCourantMiseSousTension
     * 
     * @param edsCourantMiseSousTensions set of EdsCourantMiseSousTension
     */
    public void setEdsCourantMiseSousTensions(Set<EdsCourantMiseSousTension> edsCourantMiseSousTensions) {
        this.edsCourantMiseSousTensions = edsCourantMiseSousTensions;
    }

    /**
     * Function return set of EdsCourantNominaleActivation
     * 
     * @return set of EdsCourantNominaleActivation
     */
    @XmlElementWrapper(name = "CourantsNominaleActivation")
    @XmlElement(name = "CourantNominaleActivation")
    public Set<EdsCourantNominaleActivation> getEdsCourantNominaleActivations() {
        return edsCourantNominaleActivations;
    }

    /**
     * Function set the set of EdsCourantNominaleActivation
     * 
     * @param edsCourantNominaleActivations set of EdsCourantNominaleActivation
     */
    public void setEdsCourantNominaleActivations(Set<EdsCourantNominaleActivation> edsCourantNominaleActivations) {
        this.edsCourantNominaleActivations = edsCourantNominaleActivations;
    }

    /**
     * Function returns set of EdsModeParc
     * 
     * @return set of EdsModeParc
     */
    @XmlElementWrapper(name = "ModeParcs")
    @XmlElement(name = "ModeParc")
    public Set<EdsModeParc> getEdsModeParcs() {
        return edsModeParcs;
    }

    /**
     * Function set the set of EdsModeParc
     * 
     * @param edsModeParcs set of EdsModeParc
     */
    public void setEdsModeParcs(Set<EdsModeParc> edsModeParcs) {
        this.edsModeParcs = edsModeParcs;
    }

    /**
     * This method is used for retrieving 'Iasleep' data
     * 
     * @return Sleep current for milestone.
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getISleepCurrent()
     */
    @XmlElement(name = "i-sleep")
    public Float getISleepCurrent() {
        Float value = null;
        if (!getEdsReseauVeilleReveilleOrganeInactifs().isEmpty()) {
            value = getEdsReseauVeilleReveilleOrganeInactifs().iterator().next().getRvroiedsTmoyIveilleMoteurNonTourant();
        }
        return value;
    }

    /**
     * The method is used for retrieving 'Non functioning 12,5V awake current' data
     * 
     * @return 12,5V awake current for milestone.
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIAwake12_5()
     */
    @XmlElement(name = "i-awake-12_5")
    public Float getIAwake12_5() {
        Float value = null;
        if (!getEdsReseauVeilleReveilleOrganeInactifs().isEmpty()) {
            value = getEdsReseauVeilleReveilleOrganeInactifs().iterator().next().getRvroiedsTmoyIreveilleInactifMoteurNonTourant();
        }
        return value;
    }

    /**
     * The method is used for retrieving 'Non functioning 13,5V awake current' data
     * 
     * @return 13,5V awake current for milestone
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIAwake13_5()
     */
    @XmlElement(name = "i-awake-13_5")
    public Float getIAwake13_5() {
        Float value = null;
        if (!getEdsReseauVeilleReveilleOrganeInactifs().isEmpty()) {
            value = getEdsReseauVeilleReveilleOrganeInactifs().iterator().next().getRvroiedsTmoyIreveilleInactif13vMoteurTourant();
        }
        return value;
    }

    /**
     * The method is used for retrieving 'Inom Stab 12,5V (GMP OFF)' data
     * 
     * @return 12,5V normal current(GMP OFF) for milestone.
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getINomStab12_5()
     */
    @XmlElement(name = "i-nom-stab-12_5")
    public Float getINomStab12_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivations().isEmpty()) {
            value = getEdsCourantNominaleActivations().iterator().next().getCnaedsImoyStabMnt();
        }
        return value;
    }

    /**
     * The method is used for retrieving 'Inom Stab 13,5V (GMP ON)' data
     * 
     * @return 13,5V normal current(GMP ON) for milestone.
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getINomStab13_5()
     */
    @XmlElement(name = "i-nom-stab-13_5")
    public Float getINomStab13_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivations().isEmpty()) {
            value = getEdsCourantNominaleActivations().iterator().next().getCnaedsImoyStab13Mt();
        }
        return value;
    }

    /**
     * The method is used for retrieving 'Iworstcase Stab 12,5V (GMP OFF)' data
     * 
     * @return 12,5V worst-case current(GMP OFF) for milestone.
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIWorstStab12_5()
     */
    @XmlElement(name = "i-worst-stab-12_5")
    public Float getIWorstStab12_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivations().isEmpty()) {
            value = getEdsCourantNominaleActivations().iterator().next().getCnaedsImoyPireCasMnt();
        }
        return value;
    }

    /**
     * The method is used for retrieving 'Iworstcase Stab 13,5V (GMP ON)' data
     * 
     * @return 13,5V worst-case current(GMP ON) for milestone.
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIWorstStab13_5()
     */
    @XmlElement(name = "i-worst-stab-13_5")
    public Float getIWorstStab13_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivations().isEmpty()) {
            value = getEdsCourantNominaleActivations().iterator().next().getCnaedsImoyPireCas13Mt();
        }
        return value;
    }

    /**
     * Getter edsConsolidateSupplyProfile
     * 
     * @return the edsConsolidateSupplyProfile
     */
    @XmlElementWrapper(name = "ConsumptionProfiles")
    @XmlElement(name = "ConsumptionProfile")
    public Set<EdsConsSupProfile> getEdsConsolidateSupplyProfile() {
        return edsConsolidateSupplyProfile;
    }

    /**
     * Setter edsConsolidateSupplyProfile
     * 
     * @param edsConsolidateSupplyProfile the edsConsolidateSupplyProfile to set
     */
    public void setEdsConsolidateSupplyProfile(Set<EdsConsSupProfile> edsConsolidateSupplyProfile) {
        this.edsConsolidateSupplyProfile = edsConsolidateSupplyProfile;
    }
}
