package com.inetpsa.eds.dao.model;

// Generated 24 sept. 2012 15:50:47 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.dao.I_FormData;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EdsConsolidatedSupplyVoltageFormData generated by hbm2java
 */
@XmlRootElement(name = "consolidated-supply-voltage-form")
public class EdsConsolidatedSupplyVoltageFormData implements java.io.Serializable, I_FormData {
    /**
     * String Variable to hold the value for Column CSV_ID of Table EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvId;
    /**
     * Variable to hold the value for Column CSV_EDS_ID of Table EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private EdsEds edsEds;
    /**
     * String Variable to hold the value for Column CSV_VALEUR_TENSION_INITIALISATION of Table EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvValeurTensionInitialisation;
    /**
     * String Variable to hold the value for Column CSV_VALEUR_TENSION_MINIMALE_FONCTIONNEMENT_NOMINALE of Table
     * EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvValeurTensionMinimaleFonctionnementNominale;
    /**
     * String Variable to hold the value for Column CSV_VALEUR_TENSION_MAXIMAL_FONCTIONNEMENT_NOMINALE of Table
     * EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvValeurTensionMaximalFonctionnementNominale;
    /**
     * String Variable to hold the value for Column CSV_VALEUR_TENSION_COUTURE of Table EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvValeurTensionCouture;
    /**
     * String Variable to hold the value for Column CSV_VALEUR_TENSION_REHABILISATION of Table EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvValeurTensionRehabilisation;
    /**
     * String Variable to hold the value for Column CSV_VALEUR_TENSION_RESET of Table EDS_CONSOLIDATED_SUPPLY_VOLTAGE_FORM_DATA
     */
    private String csvValeurTensionReset;

    /**
     * Default Constructor
     */
    public EdsConsolidatedSupplyVoltageFormData() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param csvId ID
     * @param edsEds EdsEds
     */
    public EdsConsolidatedSupplyVoltageFormData(String csvId, EdsEds edsEds) {
        this.csvId = csvId;
        this.edsEds = edsEds;
    }

    /**
     * Parameterized Constructor
     * 
     * @param csvId ID
     * @param edsEds EdsEds
     * @param csvValeurTensionInitialisation initialize voltage value
     * @param csvValeurTensionMinimaleFonctionnementNominale nominal function minimum voltage value
     * @param csvValeurTensionMaximalFonctionnementNominale Maximum voltage allowed for a normal functioning
     * @param csvValeurTensionCouture High disconnection voltage
     * @param csvValeurTensionRehabilisation restoration voltage value
     * @param csvValeurTensionReset Reset voltage value
     */
    public EdsConsolidatedSupplyVoltageFormData(String csvId, EdsEds edsEds, String csvValeurTensionInitialisation,
            String csvValeurTensionMinimaleFonctionnementNominale, String csvValeurTensionMaximalFonctionnementNominale,
            String csvValeurTensionCouture, String csvValeurTensionRehabilisation, String csvValeurTensionReset) {
        this.csvId = csvId;
        this.edsEds = edsEds;
        this.csvValeurTensionInitialisation = csvValeurTensionInitialisation;
        this.csvValeurTensionMinimaleFonctionnementNominale = csvValeurTensionMinimaleFonctionnementNominale;
        this.csvValeurTensionMaximalFonctionnementNominale = csvValeurTensionMaximalFonctionnementNominale;
        this.csvValeurTensionCouture = csvValeurTensionCouture;
        this.csvValeurTensionRehabilisation = csvValeurTensionRehabilisation;
        this.csvValeurTensionReset = csvValeurTensionReset;
    }

    /**
     * Function to get csvId
     * 
     * @return Id
     */
    @XmlTransient
    public String getCsvId() {
        return this.csvId;
    }

    /**
     * Function to set csvId
     * 
     * @param csvId Id
     */
    public void setCsvId(String csvId) {
        this.csvId = csvId;
    }

    /**
     * Function to get edsEds
     * 
     * @return EdsEds
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return this.edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds EdsEds
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function to get csvValeurTensionInitialisation
     * 
     * @return initialize voltage value
     */
    @XmlElement(name = "init-voltage-value")
    public String getCsvValeurTensionInitialisation() {
        return this.csvValeurTensionInitialisation;
    }

    /**
     * Function to set csvValeurTensionInitialisation
     * 
     * @param csvValeurTensionInitialisation initialize voltage value
     */
    public void setCsvValeurTensionInitialisation(String csvValeurTensionInitialisation) {
        this.csvValeurTensionInitialisation = csvValeurTensionInitialisation;
    }

    /**
     * Function to get csvValeurTensionMinimaleFonctionnementNominale
     * 
     * @return nominal function minimum voltage value
     */
    @XmlElement(name = "nominal-func-min-voltage-value")
    public String getCsvValeurTensionMinimaleFonctionnementNominale() {
        return this.csvValeurTensionMinimaleFonctionnementNominale;
    }

    /**
     * Function to set csvValeurTensionMinimaleFonctionnementNominale
     * 
     * @param csvValeurTensionMinimaleFonctionnementNominale nominal function minimum voltage value
     */
    public void setCsvValeurTensionMinimaleFonctionnementNominale(String csvValeurTensionMinimaleFonctionnementNominale) {
        this.csvValeurTensionMinimaleFonctionnementNominale = csvValeurTensionMinimaleFonctionnementNominale;
    }

    /**
     * Function to get csvValeurTensionMaximalFonctionnementNominale
     * 
     * @return Maximum voltage allowed for a normal functioning
     */
    @XmlElement(name = "nominal-func-max-voltage-value")
    public String getCsvValeurTensionMaximalFonctionnementNominale() {
        return this.csvValeurTensionMaximalFonctionnementNominale;
    }

    /**
     * Function to set csvValeurTensionMaximalFonctionnementNominale
     * 
     * @param csvValeurTensionMaximalFonctionnementNominale Maximum voltage allowed for a normal functioning
     */
    public void setCsvValeurTensionMaximalFonctionnementNominale(String csvValeurTensionMaximalFonctionnementNominale) {
        this.csvValeurTensionMaximalFonctionnementNominale = csvValeurTensionMaximalFonctionnementNominale;
    }

    /**
     * Function to get csvValeurTensionCouture
     * 
     * @return High disconnection voltage
     */
    @XmlElement(name = "disconnection-voltage-value")
    public String getCsvValeurTensionCouture() {
        return this.csvValeurTensionCouture;
    }

    /**
     * Function to set csvValeurTensionCouture
     * 
     * @param csvValeurTensionCouture High disconnection voltage
     */
    public void setCsvValeurTensionCouture(String csvValeurTensionCouture) {
        this.csvValeurTensionCouture = csvValeurTensionCouture;
    }

    /**
     * Function to get csvValeurTensionRehabilisation
     * 
     * @return restoration voltage value
     */
    @XmlElement(name = "rehabilitation-voltage-value")
    public String getCsvValeurTensionRehabilisation() {
        return this.csvValeurTensionRehabilisation;
    }

    /**
     * Function to set csvValeurTensionRehabilisation
     * 
     * @param csvValeurTensionRehabilisation restoration voltage value
     */
    public void setCsvValeurTensionRehabilisation(String csvValeurTensionRehabilisation) {
        this.csvValeurTensionRehabilisation = csvValeurTensionRehabilisation;
    }

    /**
     * Function to get csvValeurTensionReset
     * 
     * @return Reset voltage value
     */
    @XmlElement(name = "reset-voltage-value")
    public String getCsvValeurTensionReset() {
        return this.csvValeurTensionReset;
    }

    /**
     * Function to set csvValeurTensionReset
     * 
     * @param csvValeurTensionReset Reset voltage value
     */
    public void setCsvValeurTensionReset(String csvValeurTensionReset) {
        this.csvValeurTensionReset = csvValeurTensionReset;
    }

    /**
     * Function to get copy of Supply voltage for Consolidated stage
     * 
     * @param eds Eds details
     * @param copiesMap Map of Id and Project specific data
     * @return EdsConsolidatedSupplyVoltageFormData
     */
    public I_FormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsConsolidatedSupplyVoltageFormData copy = new EdsConsolidatedSupplyVoltageFormData(UUID.randomUUID().toString(), eds);

        copy.csvValeurTensionCouture = this.csvValeurTensionCouture;
        copy.csvValeurTensionInitialisation = this.csvValeurTensionInitialisation;
        copy.csvValeurTensionMaximalFonctionnementNominale = this.csvValeurTensionMaximalFonctionnementNominale;
        copy.csvValeurTensionMinimaleFonctionnementNominale = this.csvValeurTensionMinimaleFonctionnementNominale;
        copy.csvValeurTensionRehabilisation = this.csvValeurTensionRehabilisation;
        copy.csvValeurTensionReset = this.csvValeurTensionReset;

        return copy;
    }

    /**
     * Function to get all saved items
     * 
     * @return All saved items
     */
    public List<Object> getAllItemsToSave() {
        return Collections.singletonList((Object) this);
    }
}
