package com.inetpsa.eds.dao.model;

// Generated 13 ao�t 2012 13:31:01 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.dao.I_FormData;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EdsComportementConsolideFormData generated by hbm2java
 */
@XmlRootElement(name = "consolidated-behavior-form")
public class EdsComportementConsolideFormData implements java.io.Serializable, I_FormData {
    /**
     * String Variable to hold the value for Column COCOFD_ID of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdId;
    /**
     * Variable to hold the value for Column COCOFD_EDS_ID of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private EdsEds edsEds;
    /**
     * String Variable to hold the value for Column COCOFD_TYPE_PILOTAGE of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdTypePilotage;
    /**
     * String Variable to hold the value for Column COCOFD_PLAGE_FREQUENCE of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdPlageFrequence;
    /**
     * String Variable to hold the value for Column COCOFD_MODELE_RLC_IMAGE of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdModeleRlcImage;
    /**
     * String Variable to hold the value for Column COCOFD_MODELE_RCL_COMMENTAIRE of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdModeleRclCommentaire;
    /**
     * String Variable to hold the value for Column COCOFD_MODELE_SABER_IMAGE of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdModeleSaberImage;
    /**
     * String Variable to hold the value for Column COCOFD_MODELE_SABER_COMMENTAIRE of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdModeleSaberCommentaire;
    /**
     * String Variable to hold the value for Column COCOFD_MODELE_RCL_URLS of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdModeleRclUrls;
    /**
     * String Variable to hold the value for Column COCOFD_MODELE_SABER_URLS of Table EDS_COMPORTEMENT_CONSOLIDE_FORM_DATA
     */
    private String cocofdModeleSaberUrls;

    /**
     * Default Constructor
     */
    public EdsComportementConsolideFormData() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param cocofdId Id
     * @param edsEds
     */
    public EdsComportementConsolideFormData(String cocofdId, EdsEds edsEds) {
        this.cocofdId = cocofdId;
        this.edsEds = edsEds;
    }

    /**
     * Parameterized Constructor
     * 
     * @param cocofdId Id
     * @param edsEds Eds details
     * @param cocofdTypePilotage Control type
     * @param cocofdPlageFrequence Frequency control range
     * @param cocofdModeleRlcImage Model Rcl image
     * @param cocofdModeleRclCommentaire Model Rcl comment
     * @param cocofdModeleSaberImage Model Saber Image
     * @param cocofdModeleSaberCommentaire Model Saber comment
     * @param cocofdModeleRclUrls Model Rcl Urls
     * @param cocofdModeleSaberUrls Model Saber Urls
     */
    public EdsComportementConsolideFormData(String cocofdId, EdsEds edsEds, String cocofdTypePilotage, String cocofdPlageFrequence,
            String cocofdModeleRlcImage, String cocofdModeleRclCommentaire, String cocofdModeleSaberImage, String cocofdModeleSaberCommentaire,
            String cocofdModeleRclUrls, String cocofdModeleSaberUrls) {
        this.cocofdId = cocofdId;
        this.edsEds = edsEds;
        this.cocofdTypePilotage = cocofdTypePilotage;
        this.cocofdPlageFrequence = cocofdPlageFrequence;
        this.cocofdModeleRlcImage = cocofdModeleRlcImage;
        this.cocofdModeleRclCommentaire = cocofdModeleRclCommentaire;
        this.cocofdModeleSaberImage = cocofdModeleSaberImage;
        this.cocofdModeleSaberCommentaire = cocofdModeleSaberCommentaire;
        this.cocofdModeleRclUrls = cocofdModeleRclUrls;
        this.cocofdModeleSaberUrls = cocofdModeleSaberUrls;
    }

    /**
     * Function to get the Compartment Consolidate Form Data Id
     * 
     * @return Compartment Consolidate Form Data Id
     */
    @XmlTransient
    public String getCocofdId() {
        return this.cocofdId;
    }

    /**
     * Function to set cocofdId
     * 
     * @param cocofdId
     */
    public void setCocofdId(String cocofdId) {
        this.cocofdId = cocofdId;
    }

    /**
     * Function to get edsEds
     * 
     * @return Eds details
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return this.edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function to get cocofdTypePilotage
     * 
     * @return cocofdTypePilotage
     */
    @XmlElement(name = "driver-type")
    public String getCocofdTypePilotage() {
        return this.cocofdTypePilotage;
    }

    /**
     * Function to set cocofdTypePilotage
     * 
     * @param cocofdTypePilotage
     */
    public void setCocofdTypePilotage(String cocofdTypePilotage) {
        this.cocofdTypePilotage = cocofdTypePilotage;
    }

    /**
     * Function to get cocofdPlageFrequence
     * 
     * @return getCocofdPlageFrequence
     */
    @XmlElement(name = "waveband")
    public String getCocofdPlageFrequence() {
        return this.cocofdPlageFrequence;
    }

    /**
     * Function to set cocofdPlageFrequence
     * 
     * @param cocofdPlageFrequence Frequency range
     */
    public void setCocofdPlageFrequence(String cocofdPlageFrequence) {
        this.cocofdPlageFrequence = cocofdPlageFrequence;
    }

    /**
     * Function to get cocofdModeleRlcImage
     * 
     * @return Model Rlc Image
     */
    @XmlTransient
    public String getCocofdModeleRlcImage() {
        return this.cocofdModeleRlcImage;
    }

    /**
     * Function to set cocofdModeleRlcImage
     * 
     * @param cocofdModeleRlcImage Model Rlc Image
     */
    public void setCocofdModeleRlcImage(String cocofdModeleRlcImage) {
        this.cocofdModeleRlcImage = cocofdModeleRlcImage;
    }

    /**
     * Function to get cocofdModeleRclCommentaire
     * 
     * @return Model Rlc Comment
     */
    @XmlElement(name = "rlc-model-comment")
    public String getCocofdModeleRclCommentaire() {
        return this.cocofdModeleRclCommentaire;
    }

    /**
     * Function to set cocofdModeleRclCommentaire
     * 
     * @param cocofdModeleRclCommentaire Model Rlc comment
     */
    public void setCocofdModeleRclCommentaire(String cocofdModeleRclCommentaire) {
        this.cocofdModeleRclCommentaire = cocofdModeleRclCommentaire;
    }

    /**
     * Function to get cocofdModeleSaberImage
     * 
     * @return Model Saber Image
     */
    @XmlTransient
    public String getCocofdModeleSaberImage() {
        return this.cocofdModeleSaberImage;
    }

    /**
     * Function to set cocofdModeleSaberImage
     * 
     * @param cocofdModeleSaberImage Model Saber Image
     */
    public void setCocofdModeleSaberImage(String cocofdModeleSaberImage) {
        this.cocofdModeleSaberImage = cocofdModeleSaberImage;
    }

    /**
     * Function to get cocofdModeleSaberCommentaire
     * 
     * @return Model saber comment
     */
    @XmlElement(name = "saber-model-comment")
    public String getCocofdModeleSaberCommentaire() {
        return this.cocofdModeleSaberCommentaire;
    }

    /**
     * Function to set cocofdModeleSaberCommentaire
     * 
     * @param cocofdModeleSaberCommentaire Model saber comment
     */
    public void setCocofdModeleSaberCommentaire(String cocofdModeleSaberCommentaire) {
        this.cocofdModeleSaberCommentaire = cocofdModeleSaberCommentaire;
    }

    /**
     * Function to get cocofdModeleRclUrls
     * 
     * @return Model Rlc Url
     */
    @XmlTransient
    public String getCocofdModeleRclUrls() {
        return this.cocofdModeleRclUrls;
    }

    /**
     * Function to set cocofdModeleRclUrls
     * 
     * @param cocofdModeleRclUrls Model Rlc Url
     */
    public void setCocofdModeleRclUrls(String cocofdModeleRclUrls) {
        this.cocofdModeleRclUrls = cocofdModeleRclUrls;
    }

    /**
     * Function to get cocofdModeleSaberUrls
     * 
     * @return Model saber comment
     */
    @XmlTransient
    public String getCocofdModeleSaberUrls() {
        return this.cocofdModeleSaberUrls;
    }

    /**
     * Function to set cocofdModeleSaberUrls
     * 
     * @param cocofdModeleSaberUrls Model saber comment
     */
    public void setCocofdModeleSaberUrls(String cocofdModeleSaberUrls) {
        this.cocofdModeleSaberUrls = cocofdModeleSaberUrls;
    }

    /**
     * Function to get the Copy of EdsComportementConsolideFormData
     * 
     * @param eds Eds details
     * @param copiesMap Map of ID and EdsEds
     * @return EdsComportementConsolideFormData
     */
    public I_FormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsComportementConsolideFormData copy = new EdsComportementConsolideFormData(UUID.randomUUID().toString(), eds);
        copy.cocofdModeleRclCommentaire = this.cocofdModeleRclCommentaire;
        copy.cocofdModeleRclUrls = this.cocofdModeleRclUrls;
        copy.cocofdModeleRlcImage = cocofdModeleRlcImage;
        copy.cocofdModeleSaberCommentaire = this.cocofdModeleSaberCommentaire;
        copy.cocofdModeleSaberImage = this.cocofdModeleSaberImage;
        copy.cocofdModeleSaberUrls = this.cocofdModeleSaberUrls;
        copy.cocofdPlageFrequence = this.cocofdPlageFrequence;
        copy.cocofdTypePilotage = this.cocofdTypePilotage;
        return copy;
    }

    /**
     * Function to get all saved items
     * 
     * @return All saved items
     */
    public List<Object> getAllItemsToSave() {
        return Collections.singletonList((Object) this);
    }
}
