package com.inetpsa.eds.dao.model;

// Generated 7 nov. 2012 10:07:45 by Hibernate Tools 3.2.1.GA

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;

import com.inetpsa.eds.dao.I_DriftableSupply;

/**
 * EdsConsolidateSupplyMesure generated by hbm2java
 */
public class EdsConsolidateSupplyMesure implements java.io.Serializable, I_DriftableSupply {

    /**
     * Serial UID
     */
    private static final long serialVersionUID = -4659899389671253427L;

    /**
     * EdsConsolidateSupply parent Consolidate supply
     */
    private EdsConsolidateSupply edsConsolidateSupply;

    /**
     * String Variable to hold the value for Column CSMEDS_ID of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsId;

    /**
     * Variable to hold the value for Column CSMEDS_TMIN of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private Float csmedsTmin;

    /**
     * Variable to hold the value for Column CSMEDS_TMOY of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private Float csmedsTmoy;

    /**
     * Variable to hold the value for Column CSMEDS_TMAX of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private Float csmedsTmax;

    /**
     * Variable to hold the value for Column CSMEDS_NOMBRE_PIECE_TESTER of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private Float csmedsNombrePieceTester;

    /**
     * String Variable to hold the value for Column CSMEDS_ECHANTILLON_DE_TEST of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsEchantillonDeTest;

    /**
     * String Variable to hold the value for Column CSMEDS_TMIN_IFORM_BY of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsTminIformBy;

    /**
     * String Variable to hold the value for Column CSMEDS_TMAX_IFORM_BY of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsTmaxIformBy;

    /**
     * String Variable to hold the value for Column CSMEDS_NOMBRE_PIECE_TESTER_IFORM_BY of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsNombrePieceTesterIformBy;

    /**
     * String Variable to hold the value for Column CSMEDS_ECHANTILLON_DE_TEST_IFORM_BY of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsEchantillonDeTestIformBy;

    /**
     * String Variable to hold the value for Column CSMEDS_TMIN_COMMENT of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsTminComment;

    /**
     * String Variable to hold the value for Column CSMEDS_TMOY_COMMENT of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsTmoyComment;

    /**
     * String Variable to hold the value for Column CSMEDS_TMAX_COMMENT of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsTmaxComment;

    /**
     * String Variable to hold the value for Column CSMEDS_NOMBRE_PIECE_TESTER_COMMENT of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsNombrePieceTesterComment;

    /**
     * String Variable to hold the value for Column CSMEDS_ECHANTILLON_DE_TEST__COMMENT of Table EDS_CONSOLIDATE_SUPPLY_MEASURE
     */
    private String csmedsEchantillonDeTestComment;

    /**
     * Set variable to hold values of {@link EdsConsSupProfile}
     */
    private Set<EdsConsSupProfile> edsConsolidateSupplyProfile = new LinkedHashSet<EdsConsSupProfile>(0);

    /**
     * Set variable to hold value of {@link EdsCourantBloqueCourantDysfonctionnement}
     */
    private Set<EdsCourantBloqueCourantDysfonctionnement> edsCourantBloqueCourantDysfonctionnementMesures = new LinkedHashSet<EdsCourantBloqueCourantDysfonctionnement>(
            0);

    /**
     * Set variable to hold value of {@link EdsModeMontage}
     */
    private Set<EdsModeMontage> edsModeMontageMesures = new LinkedHashSet<EdsModeMontage>(0);

    /**
     * Set variable to hold value of {@link EdsCourantNominaleActivation}
     */
    private Set<EdsCourantNominaleActivation> edsCourantNominaleActivationMesures = new LinkedHashSet<EdsCourantNominaleActivation>(0);

    /**
     * Set variable to hold value of {@link EdsCourantAppelleActivation}
     */
    private Set<EdsCourantAppelleActivation> edsCourantAppelleActivationMesures = new LinkedHashSet<EdsCourantAppelleActivation>(0);

    /**
     * Set variable to hold value of {@link EdsCourantMiseSousTension}
     */
    private Set<EdsCourantMiseSousTension> edsCourantMiseSousTensionMesures = new LinkedHashSet<EdsCourantMiseSousTension>(0);

    /**
     * Set variable to hold value of {@link EdsReseauVeilleReveilleOrganeInactif}
     */
    private Set<EdsReseauVeilleReveilleOrganeInactif> edsReseauVeilleReveilleOrganeInactifMesures = new LinkedHashSet<EdsReseauVeilleReveilleOrganeInactif>(
            0);

    /**
     * Set variable to hold value of {@link EdsModeParc}
     */
    private Set<EdsModeParc> edsModeParcMesures = new LinkedHashSet<EdsModeParc>(0);

    /**
     * variable to hold value of set of ConsolidateSupplyEdsTension.
     */
    private Set<ConsolidateSupplyEdsTension> consolidateSupplyEdsTensions = new LinkedHashSet<ConsolidateSupplyEdsTension>(0);

    /**
     * Default constructor
     */
    public EdsConsolidateSupplyMesure() {
    }

    /**
     * Parameterized constructor
     * 
     * @param csmedsId Consolidate supply measure ID
     */
    public EdsConsolidateSupplyMesure(String csmedsId) {
        this.csmedsId = csmedsId;
    }

    /**
     * Parameterized constructor
     * 
     * @param ecsm EdsConsolidateSupplyMesure
     */
    public EdsConsolidateSupplyMesure(EdsConsolidateSupplyMesure ecsm) {
        this.csmedsId = UUID.randomUUID().toString();
        this.csmedsEchantillonDeTest = ecsm.csmedsEchantillonDeTest;
        this.csmedsEchantillonDeTestComment = ecsm.csmedsEchantillonDeTestComment;
        this.csmedsEchantillonDeTestIformBy = ecsm.csmedsEchantillonDeTestIformBy;
        this.csmedsNombrePieceTester = ecsm.csmedsNombrePieceTester;
        this.csmedsNombrePieceTesterComment = ecsm.csmedsNombrePieceTesterComment;
        this.csmedsNombrePieceTesterIformBy = ecsm.csmedsNombrePieceTesterIformBy;
        this.csmedsTmax = ecsm.csmedsTmax;
        this.csmedsTmaxComment = ecsm.csmedsTmaxComment;
        this.csmedsTmaxIformBy = ecsm.csmedsTmaxIformBy;
        this.csmedsTmin = ecsm.csmedsTmin;
        this.csmedsTminComment = ecsm.csmedsTminComment;
        this.csmedsTminIformBy = ecsm.csmedsTminIformBy;

        for (EdsCourantAppelleActivation source : ecsm.edsCourantAppelleActivationMesures) {
            edsCourantAppelleActivationMesures.add(new EdsCourantAppelleActivation(source));
        }
        for (EdsReseauVeilleReveilleOrganeInactif source : ecsm.edsReseauVeilleReveilleOrganeInactifMesures) {
            edsReseauVeilleReveilleOrganeInactifMesures.add(new EdsReseauVeilleReveilleOrganeInactif(source));
        }
        for (EdsCourantNominaleActivation source : ecsm.edsCourantNominaleActivationMesures) {
            edsCourantNominaleActivationMesures.add(new EdsCourantNominaleActivation(source));
        }
        for (EdsCourantMiseSousTension source : ecsm.edsCourantMiseSousTensionMesures) {
            edsCourantMiseSousTensionMesures.add(new EdsCourantMiseSousTension(source));
        }
        for (EdsModeParc source : ecsm.edsModeParcMesures) {
            edsModeParcMesures.add(new EdsModeParc(source));
        }
        for (EdsModeMontage source : ecsm.edsModeMontageMesures) {
            edsModeMontageMesures.add(new EdsModeMontage(source));
        }
        for (EdsCourantBloqueCourantDysfonctionnement source : ecsm.edsCourantBloqueCourantDysfonctionnementMesures) {
            edsCourantBloqueCourantDysfonctionnementMesures.add(new EdsCourantBloqueCourantDysfonctionnement(source));
        }
        for (EdsConsSupProfile source : ecsm.edsConsolidateSupplyProfile) {
            edsConsolidateSupplyProfile.add(new EdsConsSupProfile(source));
        }
        for (ConsolidateSupplyEdsTension source : ecsm.consolidateSupplyEdsTensions) {
            consolidateSupplyEdsTensions.add(new ConsolidateSupplyEdsTension(source));
        }

    }

    /**
     * Function returns parent Consolidate supply
     * 
     * @return Consolidate supply
     */
    @XmlTransient
    public EdsConsolidateSupply getCsmedsConsolidateSupply() {
        return this.edsConsolidateSupply;
    }

    /**
     * Function set parent Consolidate supply
     * 
     * @param edsConsolidateSupply Parent Consolidate supply
     */
    public void setCsmedsConsolidateSupply(EdsConsolidateSupply edsConsolidateSupply) {
        this.edsConsolidateSupply = edsConsolidateSupply;
    }

    /**
     * Function returns Consolidate supply measure id
     * 
     * @return Consolidate supply measure id
     */
    @XmlAttribute(name = "id")
    public String getCsmedsId() {
        return this.csmedsId;
    }

    /**
     * Function set Consolidate supply measure id
     * 
     * @param csmedsId Consolidate supply measure id
     */
    public void setCsmedsId(String csmedsId) {
        this.csmedsId = csmedsId;
    }

    /**
     * Function returns Consolidate supply measure Tmin
     * 
     * @return Consolidate supply measure Tmin
     */
    @XmlElement(name = "Tmin")
    public Float getCsmedsTmin() {
        return this.csmedsTmin;
    }

    /**
     * Function set Consolidate supply measure Tmin
     * 
     * @param csmedsTmin Consolidate supply measure Tmin
     */
    public void setCsmedsTmin(Float csmedsTmin) {
        this.csmedsTmin = csmedsTmin;
    }

    /**
     * Getter csmedsTmoy
     * 
     * @return the csmedsTmoy
     */
    @XmlElement(name = "Tmoy")
    public Float getCsmedsTmoy() {
        return csmedsTmoy;
    }

    /**
     * Setter csmedsTmoy
     * 
     * @param csmedsTmoy the csmedsTmoy to set
     */
    public void setCsmedsTmoy(Float csmedsTmoy) {
        this.csmedsTmoy = csmedsTmoy;
    }

    /**
     * Function return Consolidate supply measure Tmax
     * 
     * @return Consolidate supply measure Tmax
     */
    @XmlElement(name = "Tmax")
    public Float getCsmedsTmax() {
        return this.csmedsTmax;
    }

    /**
     * Function sets Consolidate supply measure Tmax
     * 
     * @param csmedsTmax Consolidate supply measure Tmax
     */
    public void setCsmedsTmax(Float csmedsTmax) {
        this.csmedsTmax = csmedsTmax;
    }

    /**
     * Function returns Consolidate supply measure Tmin Iform by
     * 
     * @return Consolidate supply measure Tmin Iform by
     */
    @XmlTransient
    public String getCsmedsTminIformBy() {
        return this.csmedsTminIformBy;
    }

    /**
     * function set Consolidate supply measure Tmin Iform by
     * 
     * @param csmedsTminIformBy Consolidate supply measure Tmin Iform by
     */
    public void setCsmedsTminIformBy(String csmedsTminIformBy) {
        this.csmedsTminIformBy = csmedsTminIformBy;
    }

    /**
     * Function returns Consolidate supply measure Tmax Iform by
     * 
     * @return Consolidate supply measure Tmax Iform by
     */
    @XmlTransient
    public String getCsmedsTmaxIformBy() {
        return this.csmedsTmaxIformBy;
    }

    /**
     * Function set Consolidate supply measure Tmax Iform by
     * 
     * @param csmedsTmaxIformBy Consolidate supply measure Tmax Iform by
     */
    public void setCsmedsTmaxIformBy(String csmedsTmaxIformBy) {
        this.csmedsTmaxIformBy = csmedsTmaxIformBy;
    }

    /**
     * Function returns Consolidate supply measure Tmin comment
     * 
     * @return Consolidate supply measure Tmin comment
     */
    @XmlElement(name = "TminMesComment")
    public String getCsmedsTminComment() {
        return this.csmedsTminComment;
    }

    /**
     * Function set Consolidate supply measure Tmin comment
     * 
     * @param csmedsTminComment Consolidate supply measure Tmin comment
     */
    public void setCsmedsTminComment(String csmedsTminComment) {
        this.csmedsTminComment = csmedsTminComment;
    }

    /**
     * Getter csmedsTmoyComment
     * 
     * @return the csmedsTmoyComment
     */
    public String getCsmedsTmoyComment() {
        return csmedsTmoyComment;
    }

    /**
     * Setter csmedsTmoyComment
     * 
     * @param csmedsTmoyComment the csmedsTmoyComment to set
     */
    public void setCsmedsTmoyComment(String csmedsTmoyComment) {
        this.csmedsTmoyComment = csmedsTmoyComment;
    }

    /**
     * Function returns Consolidate supply measure Tmax comment
     * 
     * @return Consolidate supply measure Tmax comment
     */
    @XmlElement(name = "TmaxMesComment")
    public String getCsmedsTmaxComment() {
        return this.csmedsTmaxComment;
    }

    /**
     * Function set Consolidate supply measure Tmax comment
     * 
     * @param csmedsTmaxComment Consolidate supply measure Tmax comment
     */
    public void setCsmedsTmaxComment(String csmedsTmaxComment) {
        this.csmedsTmaxComment = csmedsTmaxComment;
    }

    /**
     * Function returns Consolidate supply measure EchantillonDeTest
     * 
     * @return Consolidate supply measure EchantillonDeTest
     */
    @XmlElement(name = "EchantillonDeTest")
    public String getCsmedsEchantillonDeTest() {
        return csmedsEchantillonDeTest;
    }

    /**
     * Function set Consolidate supply measure EchantillonDeTest
     * 
     * @param csmedsEchantillonDeTest Consolidate supply measure EchantillonDeTest
     */
    public void setCsmedsEchantillonDeTest(String csmedsEchantillonDeTest) {
        this.csmedsEchantillonDeTest = csmedsEchantillonDeTest;
    }

    /**
     * Function returns Consolidate supply measure EchantillonDeTest comment
     * 
     * @return Consolidate supply measure EchantillonDeTest comment
     */
    @XmlTransient
    public String getCsmedsEchantillonDeTestComment() {
        return csmedsEchantillonDeTestComment;
    }

    /**
     * Function set Consolidate supply measure EchantillonDeTest comment
     * 
     * @param csmedsEchantillonDeTestComment Consolidate supply measure EchantillonDeTest comment
     */
    public void setCsmedsEchantillonDeTestComment(String csmedsEchantillonDeTestComment) {
        this.csmedsEchantillonDeTestComment = csmedsEchantillonDeTestComment;
    }

    /**
     * Function returns Consolidate supply measure EchantillonDeTest Iform by
     * 
     * @return Consolidate supply measure EchantillonDeTest Iform by
     */
    @XmlTransient
    public String getCsmedsEchantillonDeTestIformBy() {
        return csmedsEchantillonDeTestIformBy;
    }

    /**
     * This function set Consolidate supply measure EchantillonDeTest Iform by
     * 
     * @param csmedsEchantillonDeTestIformBy Consolidate supply measure EchantillonDeTest Iform by
     */
    public void setCsmedsEchantillonDeTestIformBy(String csmedsEchantillonDeTestIformBy) {
        this.csmedsEchantillonDeTestIformBy = csmedsEchantillonDeTestIformBy;
    }

    /**
     * Function return Consolidate supply measure NombrePieceTester
     * 
     * @return Consolidate supply measure NombrePieceTester
     */
    @XmlElement(name = "NombrePieceTester")
    public Float getCsmedsNombrePieceTester() {
        return csmedsNombrePieceTester;
    }

    /**
     * Function set Consolidate supply measure NombrePieceTester
     * 
     * @param csmedsNombrePieceTester Consolidate supply measure NombrePieceTester
     */
    public void setCsmedsNombrePieceTester(Float csmedsNombrePieceTester) {
        this.csmedsNombrePieceTester = csmedsNombrePieceTester;
    }

    /**
     * Function returns Consolidate supply measure NombrePieceTester comment
     * 
     * @return Consolidate supply measure NombrePieceTester comment
     */
    @XmlTransient
    public String getCsmedsNombrePieceTesterComment() {
        return csmedsNombrePieceTesterComment;
    }

    /**
     * Function set Consolidate supply measure NombrePieceTester comment
     * 
     * @param csmedsNombrePieceTesterComment Consolidate supply measure NombrePieceTester comment
     */
    public void setCsmedsNombrePieceTesterComment(String csmedsNombrePieceTesterComment) {
        this.csmedsNombrePieceTesterComment = csmedsNombrePieceTesterComment;
    }

    /**
     * Function returns Consolidate supply measure NombrePieceTester Iform by
     * 
     * @return Consolidate supply measure NombrePieceTester Iform by
     */
    @XmlTransient
    public String getCsmedsNombrePieceTesterIformBy() {
        return csmedsNombrePieceTesterIformBy;
    }

    /**
     * Function set Consolidate supply measure NombrePieceTester Iform by
     * 
     * @param csmedsNombrePieceTesterIformBy Consolidate supply measure NombrePieceTester Iform by
     */
    public void setCsmedsNombrePieceTesterIformBy(String csmedsNombrePieceTesterIformBy) {
        this.csmedsNombrePieceTesterIformBy = csmedsNombrePieceTesterIformBy;
    }

    /**
     * Function returns set of EdsModeMontage
     * 
     * @return set of EdsModeMontage
     */
    @XmlElementWrapper(name = "ModeMontages")
    @XmlElement(name = "ModeMontage")
    public Set<EdsModeMontage> getEdsModeMontageMesures() {
        return edsModeMontageMesures;
    }

    /**
     * Function set the set of EdsModeMontage
     * 
     * @param edsModeMontageMesures set of EdsModeMontage
     */
    public void setEdsModeMontageMesures(Set<EdsModeMontage> edsModeMontageMesures) {
        this.edsModeMontageMesures = edsModeMontageMesures;
    }

    /**
     * Function returns set of EdsReseauVeilleReveilleOrganeInactif
     * 
     * @return set of EdsReseauVeilleReveilleOrganeInactif
     */
    @XmlElementWrapper(name = "ReseauVeilleReveilleOrganeInactifs")
    @XmlElement(name = "ReseauVeilleReveilleOrganeInactif")
    public Set<EdsReseauVeilleReveilleOrganeInactif> getEdsReseauVeilleReveilleOrganeInactifMesures() {
        return edsReseauVeilleReveilleOrganeInactifMesures;
    }

    /**
     * Function set the set of set of EdsReseauVeilleReveilleOrganeInactif
     * 
     * @param edsReseauVeilleReveilleOrganeInactifMesures set of EdsReseauVeilleReveilleOrganeInactif
     */
    public void setEdsReseauVeilleReveilleOrganeInactifMesures(Set<EdsReseauVeilleReveilleOrganeInactif> edsReseauVeilleReveilleOrganeInactifMesures) {
        this.edsReseauVeilleReveilleOrganeInactifMesures = edsReseauVeilleReveilleOrganeInactifMesures;
    }

    /**
     * Function returns set of EdsCourantAppelleActivation
     * 
     * @return set of EdsCourantAppelleActivation
     */
    @XmlElementWrapper(name = "CourantsAppelleActivation")
    @XmlElement(name = "CourantAppelleActivation")
    public Set<EdsCourantAppelleActivation> getEdsCourantAppelleActivationMesures() {
        return edsCourantAppelleActivationMesures;
    }

    /**
     * Function set the set of EdsCourantAppelleActivation
     * 
     * @param edsCourantAppelleActivationMesures set of EdsCourantAppelleActivation
     */
    public void setEdsCourantAppelleActivationMesures(Set<EdsCourantAppelleActivation> edsCourantAppelleActivationMesures) {
        this.edsCourantAppelleActivationMesures = edsCourantAppelleActivationMesures;
    }

    /**
     * Function returns the set of EdsCourantBloqueCourantDysfonctionnement
     * 
     * @return set of EdsCourantBloqueCourantDysfonctionnement
     */
    @XmlElementWrapper(name = "CourantsBloqueCourantDysfonctionnement")
    @XmlElement(name = "CourantBloqueCourantDysfonctionnement")
    public Set<EdsCourantBloqueCourantDysfonctionnement> getEdsCourantBloqueCourantDysfonctionnementMesures() {
        return edsCourantBloqueCourantDysfonctionnementMesures;
    }

    /**
     * Function set the set of EdsCourantBloqueCourantDysfonctionnement
     * 
     * @param edsCourantBloqueCourantDysfonctionnementMesures set of EdsCourantBloqueCourantDysfonctionnement
     */
    public void setEdsCourantBloqueCourantDysfonctionnementMesures(
            Set<EdsCourantBloqueCourantDysfonctionnement> edsCourantBloqueCourantDysfonctionnementMesures) {
        this.edsCourantBloqueCourantDysfonctionnementMesures = edsCourantBloqueCourantDysfonctionnementMesures;
    }

    /**
     * Function return set of EdsCourantMiseSousTension
     * 
     * @return set of EdsCourantMiseSousTension
     */
    @XmlElementWrapper(name = "CourantsMiseSousTension")
    @XmlElement(name = "CourantMiseSousTension")
    public Set<EdsCourantMiseSousTension> getEdsCourantMiseSousTensionMesures() {
        return edsCourantMiseSousTensionMesures;
    }

    /**
     * This function set the set of EdsCourantMiseSousTension
     * 
     * @param edsCourantMiseSousTensionMesures set of EdsCourantMiseSousTension
     */
    public void setEdsCourantMiseSousTensionMesures(Set<EdsCourantMiseSousTension> edsCourantMiseSousTensionMesures) {
        this.edsCourantMiseSousTensionMesures = edsCourantMiseSousTensionMesures;
    }

    /**
     * Function returns set of EdsCourantNominaleActivation
     * 
     * @return set of EdsCourantNominaleActivation
     */
    @XmlElementWrapper(name = "CourantsNominaleActivation")
    @XmlElement(name = "CourantNominaleActivation")
    public Set<EdsCourantNominaleActivation> getEdsCourantNominaleActivationMesures() {
        return edsCourantNominaleActivationMesures;
    }

    /**
     * Function set the set of EdsCourantNominaleActivation
     * 
     * @param edsCourantNominaleActivationMesures set of EdsCourantNominaleActivation
     */
    public void setEdsCourantNominaleActivationMesures(Set<EdsCourantNominaleActivation> edsCourantNominaleActivationMesures) {
        this.edsCourantNominaleActivationMesures = edsCourantNominaleActivationMesures;
    }

    /**
     * Function returns set of EdsModeParc
     * 
     * @return set of EdsModeParc
     */
    @XmlElementWrapper(name = "ModeParcs")
    @XmlElement(name = "ModeParc")
    public Set<EdsModeParc> getEdsModeParcMesures() {
        return edsModeParcMesures;
    }

    /**
     * Function set the set of EdsModeParc
     * 
     * @param edsModeParcMesures set of EdsModeParc
     */
    public void setEdsModeParcMesures(Set<EdsModeParc> edsModeParcMesures) {
        this.edsModeParcMesures = edsModeParcMesures;
    }

    /**
     * Getter edsConsolidateSupplyProfile
     * 
     * @return the edsConsolidateSupplyProfile
     */
    @XmlElementWrapper(name = "ConsumptionProfiles")
    @XmlElement(name = "ConsumptionProfile")
    public Set<EdsConsSupProfile> getEdsConsolidateSupplyProfile() {
        return edsConsolidateSupplyProfile;
    }

    /**
     * Setter edsConsolidateSupplyProfile
     * 
     * @param edsConsolidateSupplyProfile the edsConsolidateSupplyProfile to set
     */
    public void setEdsConsolidateSupplyProfile(Set<EdsConsSupProfile> edsConsolidateSupplyProfile) {
        this.edsConsolidateSupplyProfile = edsConsolidateSupplyProfile;
    }

    /**
     * Getter consolidateSupplyEdsTensions
     * 
     * @return the consolidateSupplyEdsTensions
     */
    @XmlTransient
    public Set<ConsolidateSupplyEdsTension> getConsolidateSupplyEdsTensions() {
        return consolidateSupplyEdsTensions;
    }

    /**
     * Setter consolidateSupplyEdsTensions
     * 
     * @param consolidateSupplyEdsTensions the consolidateSupplyEdsTensions to set
     */
    public void setConsolidateSupplyEdsTensions(Set<ConsolidateSupplyEdsTension> consolidateSupplyEdsTensions) {
        this.consolidateSupplyEdsTensions = consolidateSupplyEdsTensions;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getISleepCurrent()
     */
    @Override
    @XmlElement(name = "i-sleep")
    public Float getISleepCurrent() {
        Float value = null;
        if (!getEdsReseauVeilleReveilleOrganeInactifMesures().isEmpty()) {
            value = getEdsReseauVeilleReveilleOrganeInactifMesures().iterator().next().getRvroiedsTmoyIveilleMoteurNonTourant();
        }
        return value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIAwake12_5()
     */
    @Override
    @XmlElement(name = "i-awake-12_5")
    public Float getIAwake12_5() {
        Float value = null;
        if (!getEdsReseauVeilleReveilleOrganeInactifMesures().isEmpty()) {
            value = getEdsReseauVeilleReveilleOrganeInactifMesures().iterator().next().getRvroiedsTmoyIreveilleInactifMoteurNonTourant();
        }
        return value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIAwake13_5()
     */
    @Override
    @XmlElement(name = "i-awak-13_5")
    public Float getIAwake13_5() {
        Float value = null;
        if (!getEdsReseauVeilleReveilleOrganeInactifMesures().isEmpty()) {
            value = getEdsReseauVeilleReveilleOrganeInactifMesures().iterator().next().getRvroiedsTmoyIreveilleInactif13vMoteurTourant();
        }
        return value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getINomStab12_5()
     */
    @Override
    @XmlElement(name = "i-nom-stab-12_5")
    public Float getINomStab12_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivationMesures().isEmpty()) {
            value = getEdsCourantNominaleActivationMesures().iterator().next().getCnaedsImoyStabMnt();
        }
        return value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getINomStab13_5()
     */
    @Override
    @XmlElement(name = "i-nom-stab-13_5")
    public Float getINomStab13_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivationMesures().isEmpty()) {
            value = getEdsCourantNominaleActivationMesures().iterator().next().getCnaedsImoyStab13Mt();
        }
        return value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIWorstStab12_5()
     */
    @Override
    @XmlElement(name = "i-nom-stab-12_5")
    public Float getIWorstStab12_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivationMesures().isEmpty()) {
            value = getEdsCourantNominaleActivationMesures().iterator().next().getCnaedsImoyPireCasMnt();
        }
        return value;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.inetpsa.eds.dao.I_DriftableSupply#getIWorstStab13_5()
     */
    @Override
    @XmlElement(name = "i-worst-stab-13_5")
    public Float getIWorstStab13_5() {
        Float value = null;
        if (!getEdsCourantNominaleActivationMesures().isEmpty()) {
            value = getEdsCourantNominaleActivationMesures().iterator().next().getCnaedsImoyPireCas13Mt();
        }
        return value;
    }
}
