package com.inetpsa.eds.dao.model;

// Generated 24 sept. 2012 16:19:42 by Hibernate Tools 3.2.1.GA

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsCurrentSupply generated by hbm2java
 */
@XmlType
public class EdsCurrentStatement implements java.io.Serializable {
    /**
     * Constant to hold value of DOC_INFO_STATEMENT
     */
    public final static int DOC_INFO_STATEMENT = 0;
    /**
     * Constant to hold value of CHART_STATEMENT
     */
    public final static int CHART_STATEMENT = 1;
    /**
     * String Variable to hold the value for Column CS_ID of Table OPLQTCUS
     */
    private String csId;
    /**
     * Variable to hold the value for Column CS_SEDS_ID of Table OPLQTCUS
     */
    private EdsSupply edsSupply;
    /**
     * Variable to hold the value for Column CS_USER_ID of Table OPLQTCUS
     */
    private EdsUser edsUserId;
    /**
     * Variable to hold the value for Column CS_MAFD_ID of Table OPLQTCUS
     */
    private EdsMissionActivationFormData edsMissionActivationFormData;
    /**
     * String Variable to hold the value for Column CS_NAME of Table OPLQTCUS
     */
    private String csName;
    /**
     * String Variable to hold the value for Column CS_XY_DATA of Table OPLQTCUS
     */
    private String csXyData;
    /**
     * String Variable to hold the value for Column CS_COMMENT of Table OPLQTCUS
     */
    private String csComment;
    /**
     * String Variable to hold the value for Column CS_DOC_INFO_URL of Table OPLQTCUS
     */
    private String csDocInfoUrl;
    /**
     * Integer Variable to hold the value for Column CS_STATEMENT_TYPE of Table OPLQTCUS
     */
    private Integer csStatementType;

    /**
     * Default Constructor
     */
    public EdsCurrentStatement() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param csId Id
     * @param edsSupply EdsSupply
     * @param edsMissionActivationFormData EdsMissionActivationFormData
     * @param csName Name
     */
    public EdsCurrentStatement(String csId, EdsSupply edsSupply, EdsMissionActivationFormData edsMissionActivationFormData, String csName) {
        this.csId = csId;
        this.edsSupply = edsSupply;
        this.edsMissionActivationFormData = edsMissionActivationFormData;
        this.csName = csName;
    }

    /**
     * Parameterized Constructor
     * 
     * @param csId Id
     * @param edsSupply EdsSupply
     * @param edsUserId EdsUser
     * @param edsMissionActivationFormData EdsMissionActivationFormData
     * @param csName Name
     * @param csXyData Xy data
     * @param csComment Comment
     * @param csDocInfoUrl Doc info Url
     * @param csStatementType Statement type
     */
    public EdsCurrentStatement(String csId, EdsSupply edsSupply, EdsUser edsUserId, EdsMissionActivationFormData edsMissionActivationFormData,
            String csName, String csXyData, String csComment, String csDocInfoUrl, Integer csStatementType) {
        this.csId = csId;
        this.edsSupply = edsSupply;
        this.edsUserId = edsUserId;
        this.edsMissionActivationFormData = edsMissionActivationFormData;
        this.csName = csName;
        this.csXyData = csXyData;
        this.csComment = csComment;
        this.csDocInfoUrl = csDocInfoUrl;
        this.csStatementType = csStatementType;
    }

    /**
     * Function to get csId
     * 
     * @return ID
     */
    @XmlTransient
    public String getCsId() {
        return this.csId;
    }

    /**
     * Function to set csId
     * 
     * @param csId Id
     */
    public void setCsId(String csId) {
        this.csId = csId;
    }

    /**
     * Function returns EdsSupplyName
     * 
     * @return Eds supply name
     */
    @XmlElement(name = "supply-name")
    public String getEdsSupplyName() {
        return this.edsSupply.getSedsSupplyName();
    }

    /**
     * Function to set EdsSupplyName
     * 
     * @param edsSupply EdsSupply
     */
    public void setEdsSupplyName(EdsSupply edsSupply) {
        // Do nothing
    }

    /**
     * Function to get edsSupply
     * 
     * @return EdsSupply
     */
    @XmlTransient
    public EdsSupply getEdsSupply() {
        return this.edsSupply;
    }

    /**
     * Function to set edsSupply
     * 
     * @param edsSupply
     */
    public void setEdsSupply(EdsSupply edsSupply) {
        this.edsSupply = edsSupply;
    }

    /**
     * Function to get edsMissionActivationFormData
     * 
     * @return EdsMissionActivationFormData
     */
    @XmlTransient
    public EdsMissionActivationFormData getEdsMissionActivationFormData() {
        return this.edsMissionActivationFormData;
    }

    /**
     * Function to set edsMissionActivationFormData
     * 
     * @param edsMissionActivationFormData EdsMissionActivationFormData
     */
    public void setEdsMissionActivationFormData(EdsMissionActivationFormData edsMissionActivationFormData) {
        this.edsMissionActivationFormData = edsMissionActivationFormData;
    }

    /**
     * Function to get csName
     * 
     * @return Current statement name
     */
    @XmlElement(name = "name")
    public String getCsName() {
        return this.csName;
    }

    /**
     * Function to set csName
     * 
     * @param csName Name
     */
    public void setCsName(String csName) {
        this.csName = csName;
    }

    /**
     * Function to get csXyData
     * 
     * @return XY data
     */
    @XmlElement(name = "statement-value")
    public String getCsXyData() {
        return this.csXyData;
    }

    /**
     * Function to set csXyData
     * 
     * @param csXyData Xy data
     */
    public void setCsXyData(String csXyData) {
        this.csXyData = csXyData;
    }

    /**
     * Function to get edsUserId
     * 
     * @return EdsUser
     */
    @XmlTransient
    public EdsUser getEdsUserId() {
        return this.edsUserId;
    }

    /**
     * Function to set edsUserId
     * 
     * @param edsUserId EdsUser
     */
    public void setEdsUserId(EdsUser edsUserId) {
        this.edsUserId = edsUserId;
    }

    /**
     * Function to get csComment
     * 
     * @return Comment
     */
    @XmlElement(name = "comment")
    public String getCsComment() {
        return this.csComment;
    }

    /**
     * Function to set csComment
     * 
     * @param csComment comment
     */
    public void setCsComment(String csComment) {
        this.csComment = csComment;
    }

    /**
     * Function to get csDocInfoUrl
     * 
     * @return Document information URL
     */
    @XmlElement(name = "doc-info-url")
    public String getCsDocInfoUrl() {
        return csDocInfoUrl;
    }

    /**
     * Function to set csDocInfoUrl
     * 
     * @param csDocInfoUrl Doc info Url
     */
    public void setCsDocInfoUrl(String csDocInfoUrl) {
        this.csDocInfoUrl = csDocInfoUrl;
    }

    /**
     * Function to get csStatementType
     * 
     * @return Statement Type
     */
    @XmlElement(name = "type")
    public Integer getCsStatementType() {
        return csStatementType;
    }

    /**
     * Function to set csStatementType
     * 
     * @param csStatementType Statement type
     */
    public void setCsStatementType(Integer csStatementType) {
        this.csStatementType = csStatementType;
    }

    /**
     * Function to get the Copy of EdsCurrentStatement
     * 
     * @param eds Eds details
     * @param copiesMap Map of ID and EdsSupply
     * @return EdsCurrentStatement
     */
    public EdsCurrentStatement getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsCurrentStatement copy = new EdsCurrentStatement();
        copy.csName = this.csName;
        copy.csComment = this.csComment;
        copy.edsUserId = this.edsUserId;
        copy.csId = UUID.randomUUID().toString();
        copy.csXyData = this.csXyData;
        copy.csDocInfoUrl = this.csDocInfoUrl;
        copy.csStatementType = this.csStatementType;
        if (!copiesMap.containsKey(edsSupply.getSedsId())) {
            copiesMap.put(edsSupply.getSedsId(), edsSupply.getCopy(eds, copiesMap));
        }
        copy.edsSupply = (EdsSupply) copiesMap.get(edsSupply.getSedsId());

        return copy;
    }

    /**
     * Function to get all saved items
     * 
     * @return All saved items
     */
    public List<Object> getAllItemsToSave() {
        return Collections.EMPTY_LIST;
    }
}
