package com.inetpsa.eds.dao.model;

// Generated 13 juil. 2012 16:42:27 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.dao.I_FormData;
import com.inetpsa.eds.dao.I_ReconsultableFormData;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EdsComportementRobusteFormData generated by hbm2java
 */
@XmlRootElement(name = "robust-behavior-form")
public class EdsComportementRobusteFormData implements java.io.Serializable, I_FormData, I_ReconsultableFormData {
    /**
     * String Variable to hold the value for Column CRFD_ID of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdId;
    /**
     * Variable to hold the value for Column CRFD_EDS_ID of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private EdsEds edsEds;
    /**
     * String Variable to hold the value for Column CRFD_SYNOPTIQUE_FONCTIONNEL_IMAGE of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdSynoptiqueFonctionnelImage;
    /**
     * String Variable to hold the value for Column CRFD_SYNOPTIQUE_FONCTIONNEL_COMMENTAIRE of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdSynoptiqueFonctionnelCommentaire;
    /**
     * String Variable to hold the value for Column CRFD_SYNOPTIQUE_ELECTRIQUE_IMAGE of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdSynoptiqueElectriqueImage;
    /**
     * String Variable to hold the value for Column CRFD_SYNOPTIQUE_ELECTRIQUE_COMMENTAIRE of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdSynoptiqueElectriqueCommentaire;
    /**
     * String Variable to hold the value for Column CRFD_SYNOPTIQUE_ELECTRIQUE_URLS of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdSynoptiqueElectriqueUrls;
    /**
     * String Variable to hold the value for Column CRFD_SYNOPTIQUE_FONCTIONNEL_URLS of Table EDS_COMPORTEMENT_ROBUSTE_FORM_DATA
     */
    private String crfdSynoptiqueFonctionnelUrls;

    /**
     * Default Constructor
     */
    public EdsComportementRobusteFormData() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param crfdId Id
     * @param edsEds EdsEds
     */
    public EdsComportementRobusteFormData(String crfdId, EdsEds edsEds) {
        this.crfdId = crfdId;
        this.edsEds = edsEds;
    }

    /**
     * Parameterized Constructor
     * 
     * @param crfdId Id
     * @param edsEds EdsEds
     * @param crfdSynoptiqueFonctionnelImage Functional synoptic Image
     * @param crfdSynoptiqueFonctionnelCommentaire Functional synoptic comment
     * @param crfdSynoptiqueElectriqueImage Electrical synoptic Image
     * @param crfdSynoptiqueElectriqueCommentaire Electrical synoptic comment
     * @param crfdSynoptiqueElectriqueUrls Electrical synoptic Urls
     * @param crfdSynoptiqueFonctionnelUrls Functional synoptic Urls
     */
    public EdsComportementRobusteFormData(String crfdId, EdsEds edsEds, String crfdSynoptiqueFonctionnelImage,
            String crfdSynoptiqueFonctionnelCommentaire, String crfdSynoptiqueElectriqueImage, String crfdSynoptiqueElectriqueCommentaire,
            String crfdSynoptiqueElectriqueUrls, String crfdSynoptiqueFonctionnelUrls) {
        this.crfdId = crfdId;
        this.edsEds = edsEds;
        this.crfdSynoptiqueFonctionnelImage = crfdSynoptiqueFonctionnelImage;
        this.crfdSynoptiqueFonctionnelCommentaire = crfdSynoptiqueFonctionnelCommentaire;
        this.crfdSynoptiqueElectriqueImage = crfdSynoptiqueElectriqueImage;
        this.crfdSynoptiqueElectriqueCommentaire = crfdSynoptiqueElectriqueCommentaire;
        this.crfdSynoptiqueElectriqueUrls = crfdSynoptiqueElectriqueUrls;
        this.crfdSynoptiqueFonctionnelUrls = crfdSynoptiqueFonctionnelUrls;
    }

    /**
     * Function to get crfdId
     * 
     * @return Id
     */
    @XmlTransient
    public String getCrfdId() {
        return this.crfdId;
    }

    /**
     * Function to get crfdId
     * 
     * @param crfdId Id
     */
    public void setCrfdId(String crfdId) {
        this.crfdId = crfdId;
    }

    /**
     * Function to get edsEds
     * 
     * @return EdsEds
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return this.edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds EdsEds
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function to get crfdSynoptiqueFonctionnelImage
     * 
     * @return Functional synoptic Image
     */
    @XmlTransient
    public String getCrfdSynoptiqueFonctionnelImage() {
        return this.crfdSynoptiqueFonctionnelImage;
    }

    /**
     * Function to set crfdSynoptiqueFonctionnelImage
     * 
     * @param crfdSynoptiqueFonctionnelImage Functional synoptic Image
     */
    public void setCrfdSynoptiqueFonctionnelImage(String crfdSynoptiqueFonctionnelImage) {
        this.crfdSynoptiqueFonctionnelImage = crfdSynoptiqueFonctionnelImage;
    }

    /**
     * Function to get crfdSynoptiqueFonctionnelCommentaire
     * 
     * @return Functional synoptic comment
     */
    @XmlElement(name = "functional-synoptic-comment")
    public String getCrfdSynoptiqueFonctionnelCommentaire() {
        return this.crfdSynoptiqueFonctionnelCommentaire;
    }

    /**
     * Function to set crfdSynoptiqueFonctionnelCommentaire
     * 
     * @param crfdSynoptiqueFonctionnelCommentaire Functional synoptic comment
     */
    public void setCrfdSynoptiqueFonctionnelCommentaire(String crfdSynoptiqueFonctionnelCommentaire) {
        this.crfdSynoptiqueFonctionnelCommentaire = crfdSynoptiqueFonctionnelCommentaire;
    }

    /**
     * Function to get crfdSynoptiqueElectriqueImage
     * 
     * @return Electrical synoptic Image
     */
    @XmlTransient
    public String getCrfdSynoptiqueElectriqueImage() {
        return this.crfdSynoptiqueElectriqueImage;
    }

    /**
     * Function to set crfdSynoptiqueElectriqueImage
     * 
     * @param crfdSynoptiqueElectriqueImage Electrical synoptic Image
     */
    public void setCrfdSynoptiqueElectriqueImage(String crfdSynoptiqueElectriqueImage) {
        this.crfdSynoptiqueElectriqueImage = crfdSynoptiqueElectriqueImage;
    }

    /**
     * Function to get crfdSynoptiqueElectriqueCommentaire
     * 
     * @return Electrical synoptic comment
     */
    @XmlElement(name = "electric-synoptic-comment")
    public String getCrfdSynoptiqueElectriqueCommentaire() {
        return this.crfdSynoptiqueElectriqueCommentaire;
    }

    /**
     * Function to set crfdSynoptiqueElectriqueCommentaire
     * 
     * @param crfdSynoptiqueElectriqueCommentaire Electrical synoptic comment
     */
    public void setCrfdSynoptiqueElectriqueCommentaire(String crfdSynoptiqueElectriqueCommentaire) {
        this.crfdSynoptiqueElectriqueCommentaire = crfdSynoptiqueElectriqueCommentaire;
    }

    /**
     * Function to get crfdSynoptiqueElectriqueUrls
     * 
     * @return Electrical synoptic URLs
     */
    @XmlElement(name = "electric-synoptic-urls")
    public String getCrfdSynoptiqueElectriqueUrls() {
        return this.crfdSynoptiqueElectriqueUrls;
    }

    /**
     * Function to set crfdSynoptiqueElectriqueUrls
     * 
     * @param crfdSynoptiqueElectriqueUrls Electrical synoptic Urls
     */
    public void setCrfdSynoptiqueElectriqueUrls(String crfdSynoptiqueElectriqueUrls) {
        this.crfdSynoptiqueElectriqueUrls = crfdSynoptiqueElectriqueUrls;
    }

    /**
     * Function to get crfdSynoptiqueFonctionnelUrls
     * 
     * @return Functional synoptic Urls
     */
    @XmlElement(name = "functional-synoptic-urls")
    public String getCrfdSynoptiqueFonctionnelUrls() {
        return this.crfdSynoptiqueFonctionnelUrls;
    }

    /**
     * Function to set crfdSynoptiqueFonctionnelUrls
     * 
     * @param crfdSynoptiqueFonctionnelUrls Functional synoptic Urls
     */
    public void setCrfdSynoptiqueFonctionnelUrls(String crfdSynoptiqueFonctionnelUrls) {
        this.crfdSynoptiqueFonctionnelUrls = crfdSynoptiqueFonctionnelUrls;
    }

    /**
     * Function to get Copy of EdsComportementRobusteFormData
     * 
     * @param eds Eds details
     * @param copiesMap Map of Id and Project specific data
     * @return EdsComportementRobusteFormData
     */
    public I_FormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsComportementRobusteFormData copy = new EdsComportementRobusteFormData(UUID.randomUUID().toString(), eds);
        copy.crfdSynoptiqueElectriqueCommentaire = this.crfdSynoptiqueElectriqueCommentaire;
        copy.crfdSynoptiqueElectriqueImage = this.crfdSynoptiqueElectriqueImage;
        copy.crfdSynoptiqueElectriqueUrls = this.crfdSynoptiqueElectriqueUrls;
        copy.crfdSynoptiqueFonctionnelCommentaire = this.crfdSynoptiqueFonctionnelCommentaire;
        copy.crfdSynoptiqueFonctionnelImage = this.crfdSynoptiqueFonctionnelImage;
        copy.crfdSynoptiqueFonctionnelUrls = this.crfdSynoptiqueFonctionnelUrls;
        return copy;
    }

    /**
     * Function to get all saved items
     * 
     * @return All saved items
     */
    public List<Object> getAllItemsToSave() {
        return Collections.singletonList((Object) this);
    }

    /**
     * Function to get Copy of EdsComportementRobusteFormData
     * 
     * @param eds Eds details
     * @param copiesMap Map of ID and ReconsultableForm
     * @return EdsComportementRobusteFormData
     */
    public I_FormData getReconsultableCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsComportementRobusteFormData copy = new EdsComportementRobusteFormData(UUID.randomUUID().toString(), eds);
        copy.crfdSynoptiqueElectriqueCommentaire = this.crfdSynoptiqueElectriqueCommentaire;
        copy.crfdSynoptiqueElectriqueImage = this.crfdSynoptiqueElectriqueImage;
        copy.crfdSynoptiqueElectriqueUrls = this.crfdSynoptiqueElectriqueUrls;
        copy.crfdSynoptiqueFonctionnelCommentaire = this.crfdSynoptiqueFonctionnelCommentaire;
        copy.crfdSynoptiqueFonctionnelImage = this.crfdSynoptiqueFonctionnelImage;
        copy.crfdSynoptiqueFonctionnelUrls = this.crfdSynoptiqueFonctionnelUrls;
        return copy;
    }
}
