package com.inetpsa.eds.dao.model;

// Generated 27 sept. 2012 18:58:17 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.tools.EDSTools;
import java.util.Set;
import java.util.UUID;

/**
 * EdsCourantBloqueCourantDysfonctionnement generated by hbm2java
 */
public class EdsCourantBloqueCourantDysfonctionnement implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column CBCDEDS_ID of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private String cbcdedsId;
    /**
     * Float Variable to hold the value for Column CBCDEDS_TMIN_IDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsTminIdys;
    /**
     * Float Variable to hold the value for Column CBCDEDS_TMOY_IDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsTmoyIdys;
    /**
     * Float Variable to hold the value for Column CBCDEDS_TMAX_IDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsTmaxIdys;
    /**
     * Float Variable to hold the value for Column CBCDEDS_TMIN_TDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsTminTdys;
    /**
     * Float Variable to hold the value for Column CBCDEDS_TMOY_TDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsTmoyTdys;
    /**
     * Float Variable to hold the value for Column CBCDEDS_TMAX_TDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsTmaxTdys;
    /**
     * boolean Variable to hold the value for Column CBCDEDS_OCCURENCE_DEFAILLENCE of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private boolean cbcdedsOccurenceDefaillence;
    /**
     * Float Variable to hold the value for Column CBCDEDS_OCCURENCE_DEFAILLENCE_TDYS of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Float cbcdedsOccurenceDefaillenceTdys;
    /**
     * String Variable to hold the value for Column CBCDEDS_COMMENT of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private String cbcdedsComment;
    /**
     * String Variable to hold the value for Column CBCDEDS_TITRE of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private String cbcdedsTitre;
    /**
     * boolean Variable to hold the value for Column CBCDEDS_REMOVE of Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private boolean cbcdedsRemove;

    /**
     * Default Constructor
     */
    public EdsCourantBloqueCourantDysfonctionnement() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param cbcdedsId
     */
    public EdsCourantBloqueCourantDysfonctionnement(String cbcdedsId) {
        this.cbcdedsId = cbcdedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param cbcdedsId Id
     * @param cbcdedsTminIdys Tmin Idys
     * @param cbcdedsTmoyIdys Tmoy Idys
     * @param cbcdedsTmaxIdys Tmax Idys
     * @param cbcdedsTminTdys Tmin Tdys
     * @param cbcdedsTmoyTdys Tmoy Tdys
     * @param cbcdedsTmaxTdys Tmax Tdys
     * @param cbcdedsOccurenceDefaillence Occurrences
     * @param cbcdedsTmoyIdysComment Tmoy Idys comment
     */
    public EdsCourantBloqueCourantDysfonctionnement(String cbcdedsId, Float cbcdedsTminIdys, Float cbcdedsTmoyIdys, Float cbcdedsTmaxIdys,
            Float cbcdedsTminTdys, Float cbcdedsTmoyTdys, Float cbcdedsTmaxTdys, boolean cbcdedsOccurenceDefaillence, String cbcdedsTmoyIdysComment) {
        this.cbcdedsId = cbcdedsId;
        this.cbcdedsTminIdys = cbcdedsTminIdys;
        this.cbcdedsTmoyIdys = cbcdedsTmoyIdys;
        this.cbcdedsTmaxIdys = cbcdedsTmaxIdys;
        this.cbcdedsTminTdys = cbcdedsTminTdys;
        this.cbcdedsTmoyTdys = cbcdedsTmoyTdys;
        this.cbcdedsTmaxTdys = cbcdedsTmaxTdys;
        this.cbcdedsOccurenceDefaillence = cbcdedsOccurenceDefaillence;
    }

    /**
     * Parameterized Constructor
     * 
     * @param srcCourantBloqueCourantDysfonctionnement
     */
    public EdsCourantBloqueCourantDysfonctionnement(EdsCourantBloqueCourantDysfonctionnement srcCourantBloqueCourantDysfonctionnement) {
        this.cbcdedsId = UUID.randomUUID().toString();
        this.cbcdedsTminIdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsTminIdys;
        this.cbcdedsTmoyIdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsTmoyIdys;
        this.cbcdedsTmaxIdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsTmaxIdys;
        this.cbcdedsTminTdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsTminTdys;
        this.cbcdedsTmoyTdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsTmoyTdys;
        this.cbcdedsTmaxTdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsTmaxTdys;
        this.cbcdedsOccurenceDefaillence = srcCourantBloqueCourantDysfonctionnement.cbcdedsOccurenceDefaillence;
        this.cbcdedsComment = srcCourantBloqueCourantDysfonctionnement.cbcdedsComment;
        this.cbcdedsOccurenceDefaillenceTdys = srcCourantBloqueCourantDysfonctionnement.cbcdedsOccurenceDefaillenceTdys;
        this.cbcdedsRemove = srcCourantBloqueCourantDysfonctionnement.cbcdedsRemove;
        this.cbcdedsTitre = srcCourantBloqueCourantDysfonctionnement.cbcdedsTitre;
    }

    /**
     * Function to get cbcdedsId
     * 
     * @return ID
     */
    public String getCbcdedsId() {
        return this.cbcdedsId;
    }

    /**
     * Function to set cbcdedsId
     * 
     * @param cbcdedsId Id
     */
    public void setCbcdedsId(String cbcdedsId) {
        this.cbcdedsId = cbcdedsId;
    }

    /**
     * Function to get cbcdedsTminIdys
     * 
     * @return Tmin Tdys
     */
    public Float getCbcdedsTminIdys() {
        return this.cbcdedsTminIdys;
    }

    /**
     * Function to set cbcdedsTminIdys
     * 
     * @param cbcdedsTminIdys Tmin Idys
     */
    public void setCbcdedsTminIdys(Float cbcdedsTminIdys) {
        this.cbcdedsTminIdys = cbcdedsTminIdys;
    }

    /**
     * Function to get cbcdedsTmoyIdys
     * 
     * @return Tmoy Idys
     */
    public Float getCbcdedsTmoyIdys() {
        return this.cbcdedsTmoyIdys;
    }

    /**
     * Function to set cbcdedsTmoyIdys
     * 
     * @param cbcdedsTmoyIdys Tmoy Idys
     */
    public void setCbcdedsTmoyIdys(Float cbcdedsTmoyIdys) {
        this.cbcdedsTmoyIdys = cbcdedsTmoyIdys;
    }

    /**
     * Function to get cbcdedsTmaxIdys
     * 
     * @return Tmax Idys
     */
    public Float getCbcdedsTmaxIdys() {
        return this.cbcdedsTmaxIdys;
    }

    /**
     * Function to set cbcdedsTmaxIdys
     * 
     * @param cbcdedsTmaxIdys Tmax Idys
     */
    public void setCbcdedsTmaxIdys(Float cbcdedsTmaxIdys) {
        this.cbcdedsTmaxIdys = cbcdedsTmaxIdys;
    }

    /**
     * Function to get cbcdedsTminTdys
     * 
     * @return Tmin Tdys
     */
    public Float getCbcdedsTminTdys() {
        return this.cbcdedsTminTdys;
    }

    /**
     * Function to set cbcdedsTminTdys
     * 
     * @param cbcdedsTminTdys Tmin Tdys
     */
    public void setCbcdedsTminTdys(Float cbcdedsTminTdys) {
        this.cbcdedsTminTdys = cbcdedsTminTdys;
    }

    /**
     * Function to get cbcdedsTmoyTdys
     * 
     * @return Tmoy Tdys
     */
    public Float getCbcdedsTmoyTdys() {
        return this.cbcdedsTmoyTdys;
    }

    /**
     * Function to set cbcdedsTmoyTdys
     * 
     * @param cbcdedsTmoyTdys Tmoy Tdys
     */
    public void setCbcdedsTmoyTdys(Float cbcdedsTmoyTdys) {
        this.cbcdedsTmoyTdys = cbcdedsTmoyTdys;
    }

    /**
     * Function to get cbcdedsTmaxTdys
     * 
     * @return Tmax Tdys
     */
    public Float getCbcdedsTmaxTdys() {
        return this.cbcdedsTmaxTdys;
    }

    /**
     * Function to set cbcdedsTmaxTdys
     * 
     * @param cbcdedsTmaxTdys Tmax Tdys
     */
    public void setCbcdedsTmaxTdys(Float cbcdedsTmaxTdys) {
        this.cbcdedsTmaxTdys = cbcdedsTmaxTdys;
    }

    /**
     * Function to get cbcdedsOccurenceDefaillence
     * 
     * @return Occurrences
     */
    public boolean getCbcdedsOccurenceDefaillence() {
        return this.cbcdedsOccurenceDefaillence;
    }

    /**
     * Function to set cbcdedsOccurenceDefaillence
     * 
     * @param cbcdedsOccurenceDefaillence Occurrences
     */
    public void setCbcdedsOccurenceDefaillence(boolean cbcdedsOccurenceDefaillence) {
        this.cbcdedsOccurenceDefaillence = cbcdedsOccurenceDefaillence;
    }

    /**
     * Function to get cbcdedsOccurenceDefaillenceTdys
     * 
     * @return Occurrences Tdys
     */
    public Float getCbcdedsOccurenceDefaillenceTdys() {
        return cbcdedsOccurenceDefaillenceTdys;
    }

    /**
     * Function to set cbcdedsOccurenceDefaillenceTdys
     * 
     * @param cbcdedsOccurenceDefaillenceTdys Occurrences Tdys
     */
    public void setCbcdedsOccurenceDefaillenceTdys(Float cbcdedsOccurenceDefaillenceTdys) {
        this.cbcdedsOccurenceDefaillenceTdys = cbcdedsOccurenceDefaillenceTdys;
    }

    /**
     * Function to get cbcdedsComment
     * 
     * @return comment
     */
    public String getCbcdedsComment() {
        return cbcdedsComment;
    }

    /**
     * Function to set cbcdedsComment
     * 
     * @param cbcdedsTmoyTdysComment Tmoy Tdys comment
     */
    public void setCbcdedsComment(String cbcdedsTmoyTdysComment) {
        this.cbcdedsComment = cbcdedsTmoyTdysComment;
    }

    /**
     * Function to get cbcdedsRemove
     * 
     * @return check if removabable
     */
    public boolean isCbcdedsRemove() {
        return cbcdedsRemove;
    }

    /**
     * Function to set cbcdedsRemove
     * 
     * @param cbcdedsRemove Boolean to specify removable
     */
    public void setCbcdedsRemove(boolean cbcdedsRemove) {
        this.cbcdedsRemove = cbcdedsRemove;
    }

    /**
     * Function to get cbcdedsTitre
     * 
     * @return Title
     */
    public String getCbcdedsTitre() {
        return cbcdedsTitre;
    }

    /**
     * Function to set cbcdedsTitre
     * 
     * @param cbcdedsTitre Title
     */
    public void setCbcdedsTitre(String cbcdedsTitre) {
        this.cbcdedsTitre = cbcdedsTitre;
    }

    /**
     * Function to set data for blocked couple current
     * 
     * @param edsCourantBloqueCourantDysfonctionnements set of EdsCourantBloqueCourantDysfonctionnement
     */
    public void setSomme(Set<EdsCourantBloqueCourantDysfonctionnement> edsCourantBloqueCourantDysfonctionnements) {
        // this.cbcdedsTminIdys = 0f;
        // this.cbcdedsTmoyIdys = 0f;
        // this.cbcdedsTmaxIdys = 0f;
        // this.cbcdedsTminTdys = 0f;
        // this.cbcdedsTmoyTdys = 0f;
        // this.cbcdedsTmaxTdys = 0f;

        for (EdsCourantBloqueCourantDysfonctionnement ecbcd : edsCourantBloqueCourantDysfonctionnements) {
            this.cbcdedsTminIdys = EDSTools.Concat(this.cbcdedsTminIdys, ecbcd.cbcdedsTminIdys);
            this.cbcdedsTmoyIdys = EDSTools.Concat(this.cbcdedsTmoyIdys, ecbcd.cbcdedsTmoyIdys);
            this.cbcdedsTmaxIdys = EDSTools.Concat(this.cbcdedsTmaxIdys, ecbcd.cbcdedsTmaxIdys);
            this.cbcdedsTminTdys = EDSTools.Concat(this.cbcdedsTminTdys, ecbcd.cbcdedsTminTdys);
            this.cbcdedsTmoyTdys = EDSTools.Concat(this.cbcdedsTmoyTdys, ecbcd.cbcdedsTmoyTdys);
            this.cbcdedsTmaxTdys = EDSTools.Concat(this.cbcdedsTmaxTdys, ecbcd.cbcdedsTmaxTdys);
        }
    }
}
