package com.inetpsa.eds.dao.model;

// Generated 17 mai 2013 10:30:24 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * EdsCourantEfficace generated by hbm2java
 */
public class EdsCourantEfficace implements java.io.Serializable {

    /**
     * String Variable to hold the value for Column CEEDS_ID of Table OPLQTCOE
     */
    private String ceedsId;
    /**
     * Float Variable to hold the value for Column CEEDS_TMIN_IEFF12 of Table OPLQTCOE
     */
    private Float ceedsTminIeff12;
    /**
     * Float Variable to hold the value for Column CEEDS_TMIN_TEFF12 of Table OPLQTCOE
     */
    private Float ceedsTminTeff12;
    /**
     * Float Variable to hold the value for Column CEEDS_TMOY_IEFF12 of Table OPLQTCOE
     */
    private Float ceedsTmoyIeff12;
    /**
     * Float Variable to hold the value for Column CEEDS_TMOY_TEFF12 of Table OPLQTCOE
     */
    private Float ceedsTmoyTeff12;
    /**
     * Float Variable to hold the value for Column CEEDS_TMAX_IEFF12 of Table OPLQTCOE
     */
    private Float ceedsTmaxIeff12;
    /**
     * Float Variable to hold the value for Column CEEDS_TMAX_TEFF12 of Table OPLQTCOE
     */
    private Float ceedsTmaxTeff12;
    /**
     * String Variable to hold the value for Column CEEDS_COM_12V of Table OPLQTCOE
     */
    private String ceedsCom12v;
    /**
     * Float Variable to hold the value for Column CEEDS_TMIN_IEFF10 of Table OPLQTCOE
     */
    private Float ceedsTminIeff10;
    /**
     * Float Variable to hold the value for Column CEEDS_TMOY_IEFF10 of Table OPLQTCOE
     */
    private Float ceedsTmoyIeff10;
    /**
     * Float Variable to hold the value for Column CEEDS_TMAX_IEFF10 of Table OPLQTCOE
     */
    private Float ceedsTmaxIeff10;
    /**
     * String Variable to hold the value for Column CEEDS_COM_10V of Table OPLQTCOE
     */
    private String ceedsCom10v;
    /**
     * Float Variable to hold the value for Column CEEDS_TMIN_IEFF13 of Table OPLQTCOE
     */
    private Float ceedsTminIeff13;
    /**
     * Float Variable to hold the value for Column CEEDS_TMOY_IEFF13 of Table OPLQTCOE
     */
    private Float ceedsTmoyIeff13;
    /**
     * Float Variable to hold the value for Column CEEDS_TMAX_IEFF13 of Table OPLQTCOE
     */
    private Float ceedsTmaxIeff13;
    /**
     * String Variable to hold the value for Column CEEDS_COM_13V of Table OPLQTCOE
     */
    private String ceedsCom13v;
    /**
     * Float Variable to hold the value for Column CEEDS_TMIN_IEFF15 of Table OPLQTCOE
     */
    private Float ceedsTminIeff15;
    /**
     * Float Variable to hold the value for Column CEEDS_TMOY_IEFF15 of Table OPLQTCOE
     */
    private Float ceedsTmoyIeff15;
    /**
     * Float Variable to hold the value for Column CEEDS_TMAX_IEFF15 of Table OPLQTCOE
     */
    private Float ceedsTmaxIeff15;
    /**
     * String Variable to hold the value for Column CEEDS_COM_15V of Table OPLQTCOE
     */
    private String ceedsCom15v;

    /**
     * Default Constructor
     */
    public EdsCourantEfficace() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param ceedsId
     */
    public EdsCourantEfficace(String ceedsId) {
        this.ceedsId = ceedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param ece EdsCourantEfficace
     */
    public EdsCourantEfficace(EdsCourantEfficace ece) {
        this.ceedsId = UUID.randomUUID().toString();
        this.ceedsTminIeff12 = ece.ceedsTminIeff12;
        this.ceedsTminTeff12 = ece.ceedsTminTeff12;
        this.ceedsTmoyIeff12 = ece.ceedsTmoyIeff12;
        this.ceedsTmoyTeff12 = ece.ceedsTmoyTeff12;
        this.ceedsTmaxIeff12 = ece.ceedsTmaxIeff12;
        this.ceedsTmaxTeff12 = ece.ceedsTmaxTeff12;
        this.ceedsCom12v = ece.ceedsCom12v;
        this.ceedsTminIeff10 = ece.ceedsTminIeff10;
        this.ceedsTmoyIeff10 = ece.ceedsTmoyIeff10;
        this.ceedsTmaxIeff10 = ece.ceedsTmaxIeff10;
        this.ceedsCom10v = ece.ceedsCom10v;
        this.ceedsTminIeff13 = ece.ceedsTminIeff13;
        this.ceedsTmoyIeff13 = ece.ceedsTmoyIeff13;
        this.ceedsTmaxIeff13 = ece.ceedsTmaxIeff13;
        this.ceedsCom13v = ece.ceedsCom13v;
        this.ceedsTminIeff15 = ece.ceedsTminIeff15;
        this.ceedsTmoyIeff15 = ece.ceedsTmoyIeff15;
        this.ceedsTmaxIeff15 = ece.ceedsTmaxIeff15;
        this.ceedsCom15v = ece.ceedsCom15v;
    }

    /**
     * Parameterized Constructor
     * 
     * @param ceedsId Id
     * @param ceedsTminIeff12 Tmin Ieff12
     * @param ceedsTminTeff12 Tmin Teff12
     * @param ceedsTmoyIeff12 Tmoy Ieff12
     * @param ceedsTmoyTeff12 Tmoy Teff12
     * @param ceedsTmaxIeff12 Tmax Ieff12
     * @param ceedsTmaxTeff12 Tmax Teff12
     * @param ceedsCom12v Comment 12 v
     * @param ceedsTminIeff10 Tmin Ieff10
     * @param ceedsTmoyIeff10 Tmoy Ieff10
     * @param ceedsTmaxIeff10 Tmax Ieff10
     * @param ceedsCom10v Comment 10v
     * @param ceedsTminIeff13 Tmin Ieff13
     * @param ceedsTmoyIeff13 Tmoy Ieff13
     * @param ceedsTmaxIeff13 Tmax Ieff13
     * @param ceedsCom13v Comment 13 v
     * @param ceedsTminIeff15 Tmin Ieff15
     * @param ceedsTmoyIeff15 Tmoy Ieff15
     * @param ceedsTmaxIeff15 Tmax Ieff15
     * @param ceedsCom15v Cooment 15 v
     */
    public EdsCourantEfficace(String ceedsId, Float ceedsTminIeff12, Float ceedsTminTeff12, Float ceedsTmoyIeff12, Float ceedsTmoyTeff12,
            Float ceedsTmaxIeff12, Float ceedsTmaxTeff12, String ceedsCom12v, Float ceedsTminIeff10, Float ceedsTmoyIeff10, Float ceedsTmaxIeff10,
            String ceedsCom10v, Float ceedsTminIeff13, Float ceedsTmoyIeff13, Float ceedsTmaxIeff13, String ceedsCom13v, Float ceedsTminIeff15,
            Float ceedsTmoyIeff15, Float ceedsTmaxIeff15, String ceedsCom15v) {
        this.ceedsId = ceedsId;
        this.ceedsTminIeff12 = ceedsTminIeff12;
        this.ceedsTminTeff12 = ceedsTminTeff12;
        this.ceedsTmoyIeff12 = ceedsTmoyIeff12;
        this.ceedsTmoyTeff12 = ceedsTmoyTeff12;
        this.ceedsTmaxIeff12 = ceedsTmaxIeff12;
        this.ceedsTmaxTeff12 = ceedsTmaxTeff12;
        this.ceedsCom12v = ceedsCom12v;
        this.ceedsTminIeff10 = ceedsTminIeff10;
        this.ceedsTmoyIeff10 = ceedsTmoyIeff10;
        this.ceedsTmaxIeff10 = ceedsTmaxIeff10;
        this.ceedsCom10v = ceedsCom10v;
        this.ceedsTminIeff13 = ceedsTminIeff13;
        this.ceedsTmoyIeff13 = ceedsTmoyIeff13;
        this.ceedsTmaxIeff13 = ceedsTmaxIeff13;
        this.ceedsCom13v = ceedsCom13v;
        this.ceedsTminIeff15 = ceedsTminIeff15;
        this.ceedsTmoyIeff15 = ceedsTmoyIeff15;
        this.ceedsTmaxIeff15 = ceedsTmaxIeff15;
        this.ceedsCom15v = ceedsCom15v;
    }

    /**
     * Function to get ceedsId
     * 
     * @return ID
     */
    public String getCeedsId() {
        return this.ceedsId;
    }

    /**
     * Function to set ceedsId
     * 
     * @param ceedsId Id
     */
    public void setCeedsId(String ceedsId) {
        this.ceedsId = ceedsId;
    }

    /**
     * Function to get ceedsTminIeff12
     * 
     * @return Tmin Ieff12
     */
    public Float getCeedsTminIeff12() {
        return this.ceedsTminIeff12;
    }

    /**
     * Function to set ceedsTminIeff12
     * 
     * @param ceedsTminIeff12 Tmin Ieff12
     */
    public void setCeedsTminIeff12(Float ceedsTminIeff12) {
        this.ceedsTminIeff12 = ceedsTminIeff12;
    }

    /**
     * Function to get ceedsTminTeff12
     * 
     * @return Tmin Teff12
     */
    public Float getCeedsTminTeff12() {
        return this.ceedsTminTeff12;
    }

    /**
     * Function to set ceedsTminTeff12
     * 
     * @param ceedsTminTeff12 Tmin Teff12
     */
    public void setCeedsTminTeff12(Float ceedsTminTeff12) {
        this.ceedsTminTeff12 = ceedsTminTeff12;
    }

    /**
     * Function to get ceedsTmoyIeff12
     * 
     * @return Tmoy Ieff12
     */
    public Float getCeedsTmoyIeff12() {
        return this.ceedsTmoyIeff12;
    }

    /**
     * Function to set ceedsTmoyIeff12
     * 
     * @param ceedsTmoyIeff12 Tmoy Ieff12
     */
    public void setCeedsTmoyIeff12(Float ceedsTmoyIeff12) {
        this.ceedsTmoyIeff12 = ceedsTmoyIeff12;
    }

    /**
     * Function to get ceedsTmoyTeff12
     * 
     * @return Tmoy teff12
     */
    public Float getCeedsTmoyTeff12() {
        return this.ceedsTmoyTeff12;
    }

    /**
     * Function to set ceedsTmoyTeff12
     * 
     * @param ceedsTmoyTeff12 Tmoy Teff12
     */
    public void setCeedsTmoyTeff12(Float ceedsTmoyTeff12) {
        this.ceedsTmoyTeff12 = ceedsTmoyTeff12;
    }

    /**
     * Function to get ceedsTmaxIeff12
     * 
     * @return Tmax Ieff12
     */
    public Float getCeedsTmaxIeff12() {
        return this.ceedsTmaxIeff12;
    }

    /**
     * Function to set ceedsTmaxIeff12
     * 
     * @param ceedsTmaxIeff12 Tmax Ieff12
     */
    public void setCeedsTmaxIeff12(Float ceedsTmaxIeff12) {
        this.ceedsTmaxIeff12 = ceedsTmaxIeff12;
    }

    /**
     * Function to get ceedsTmaxTeff12
     * 
     * @return Tmax Teff12
     */
    public Float getCeedsTmaxTeff12() {
        return this.ceedsTmaxTeff12;
    }

    /**
     * Function to set ceedsTmaxTeff12
     * 
     * @param ceedsTmaxTeff12 Tmax Teff12
     */
    public void setCeedsTmaxTeff12(Float ceedsTmaxTeff12) {
        this.ceedsTmaxTeff12 = ceedsTmaxTeff12;
    }

    /**
     * Function to get ceedsCom12v
     * 
     * @return Comment 12 v
     */
    public String getCeedsCom12v() {
        return this.ceedsCom12v;
    }

    /**
     * Function to set ceedsCom12v
     * 
     * @param ceedsCom12v Comment 12 v
     */
    public void setCeedsCom12v(String ceedsCom12v) {
        this.ceedsCom12v = ceedsCom12v;
    }

    /**
     * Function to get ceedsTminIeff10
     * 
     * @return Tmin Ieff10
     */
    public Float getCeedsTminIeff10() {
        return this.ceedsTminIeff10;
    }

    /**
     * Function to set ceedsTminIeff10
     * 
     * @param ceedsTminIeff10 Tmin Ieff10
     */
    public void setCeedsTminIeff10(Float ceedsTminIeff10) {
        this.ceedsTminIeff10 = ceedsTminIeff10;
    }

    /**
     * Function to get ceedsTmoyIeff10
     * 
     * @return Tmoy Ieff10
     */
    public Float getCeedsTmoyIeff10() {
        return this.ceedsTmoyIeff10;
    }

    /**
     * Function to set ceedsTmoyIeff10
     * 
     * @param ceedsTmoyIeff10 Tmoy Ieff10
     */
    public void setCeedsTmoyIeff10(Float ceedsTmoyIeff10) {
        this.ceedsTmoyIeff10 = ceedsTmoyIeff10;
    }

    /**
     * Function to get ceedsTmaxIeff10
     * 
     * @return Tmax Ieff10
     */
    public Float getCeedsTmaxIeff10() {
        return this.ceedsTmaxIeff10;
    }

    /**
     * Function to set ceedsTmaxIeff10
     * 
     * @param ceedsTmaxIeff10 Tmax Ieff10
     */
    public void setCeedsTmaxIeff10(Float ceedsTmaxIeff10) {
        this.ceedsTmaxIeff10 = ceedsTmaxIeff10;
    }

    /**
     * Function to get ceedsCom10v
     * 
     * @return comment 10 v
     */
    public String getCeedsCom10v() {
        return this.ceedsCom10v;
    }

    /**
     * Function to set ceedsCom10v
     * 
     * @param ceedsCom10v Cooment 10 v
     */
    public void setCeedsCom10v(String ceedsCom10v) {
        this.ceedsCom10v = ceedsCom10v;
    }

    /**
     * Function to get ceedsTminIeff13
     * 
     * @return Tmin Ieff13
     */
    public Float getCeedsTminIeff13() {
        return this.ceedsTminIeff13;
    }

    /**
     * Function to set ceedsTminIeff13
     * 
     * @param ceedsTminIeff13 Tmin Ieff13
     */
    public void setCeedsTminIeff13(Float ceedsTminIeff13) {
        this.ceedsTminIeff13 = ceedsTminIeff13;
    }

    /**
     * Function to get ceedsTmoyIeff13
     * 
     * @return Tmoy Ieff13
     */
    public Float getCeedsTmoyIeff13() {
        return this.ceedsTmoyIeff13;
    }

    /**
     * Function to set ceedsTmoyIeff13
     * 
     * @param ceedsTmoyIeff13 Tmoy Ieff13
     */
    public void setCeedsTmoyIeff13(Float ceedsTmoyIeff13) {
        this.ceedsTmoyIeff13 = ceedsTmoyIeff13;
    }

    /**
     * Function to get ceedsTmaxIeff13
     * 
     * @return Tmax Ieff13
     */
    public Float getCeedsTmaxIeff13() {
        return this.ceedsTmaxIeff13;
    }

    /**
     * Function to set ceedsTmaxIeff13
     * 
     * @param ceedsTmaxIeff13 Tmax Ieff13
     */
    public void setCeedsTmaxIeff13(Float ceedsTmaxIeff13) {
        this.ceedsTmaxIeff13 = ceedsTmaxIeff13;
    }

    /**
     * Function to get ceedsCom13v
     * 
     * @return Cooment 13 v
     */
    public String getCeedsCom13v() {
        return this.ceedsCom13v;
    }

    /**
     * Function to set ceedsCom13v
     * 
     * @param ceedsCom13v comment 13 v
     */
    public void setCeedsCom13v(String ceedsCom13v) {
        this.ceedsCom13v = ceedsCom13v;
    }

    /**
     * Function to get ceedsTminIeff15
     * 
     * @return Tmin Ieff 15
     */
    public Float getCeedsTminIeff15() {
        return this.ceedsTminIeff15;
    }

    /**
     * Function to set ceedsTminIeff15
     * 
     * @param ceedsTminIeff15 Tmin Ieff 15
     */
    public void setCeedsTminIeff15(Float ceedsTminIeff15) {
        this.ceedsTminIeff15 = ceedsTminIeff15;
    }

    /**
     * Function to get ceedsTmoyIeff15
     * 
     * @return Tmoy Ieff 15
     */
    public Float getCeedsTmoyIeff15() {
        return this.ceedsTmoyIeff15;
    }

    /**
     * Function to set ceedsTmoyIeff15
     * 
     * @param ceedsTmoyIeff15 Tmoy Ieff 15
     */
    public void setCeedsTmoyIeff15(Float ceedsTmoyIeff15) {
        this.ceedsTmoyIeff15 = ceedsTmoyIeff15;
    }

    /**
     * Function to get ceedsTmaxIeff15
     * 
     * @return Tmax Ieff 15
     */
    public Float getCeedsTmaxIeff15() {
        return this.ceedsTmaxIeff15;
    }

    /**
     * Function to set ceedsTmaxIeff15
     * 
     * @param ceedsTmaxIeff15 Tmax Ieff 15
     */
    public void setCeedsTmaxIeff15(Float ceedsTmaxIeff15) {
        this.ceedsTmaxIeff15 = ceedsTmaxIeff15;
    }

    /**
     * Function to get ceedsCom15v
     * 
     * @return Comment 15 v
     */
    public String getCeedsCom15v() {
        return this.ceedsCom15v;
    }

    /**
     * Function to set ceedsCom15v
     * 
     * @param ceedsCom15v Comment 15 v
     */
    public void setCeedsCom15v(String ceedsCom15v) {
        this.ceedsCom15v = ceedsCom15v;
    }

}
