package com.inetpsa.eds.dao.model;

// Generated 27 sept. 2012 18:58:17 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.tools.EDSTools;
import java.util.Set;
import java.util.UUID;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EdsCourantAppelleActivation generated by hbm2java
 */
public class EdsCourantAppelleActivation implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column CAAEDS_ID of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private String caaedsId;
    /**
     * Float Variable to hold the value for Column CAAEDS_TMIN_IMAX_PULSE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Float caaedsTminImaxPulse;
    /**
     * Float Variable to hold the value for Column CAAEDS_TMOY_IMAX_PULSE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Float caaedsTmoyImaxPulse;
    /**
     * Float Variable to hold the value for Column CAAEDS_TMAX_IMAX_PULSE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Float caaedsTmaxImaxPulse;
    /**
     * String Variable to hold the value for Column CAAEDS_TMOY_IMAX_PULSE_COMMENT of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private String caaedsTmoyImaxPulseComment;
    /**
     * Float Variable to hold the value for Column CAAEDS_TMIN_DT_PULSE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Float caaedsTminDtPulse;
    /**
     * Float Variable to hold the value for Column CAAEDS_TMOY_DT_PULSE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Float caaedsTmoyDtPulse;
    /**
     * Float Variable to hold the value for Column CAAEDS_TMAX_DT_PULSE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Float caaedsTmaxDtPulse;
    /**
     * String Variable to hold the value for Column CAAEDS_TMOY_DT_PULSE_COMMENT of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private String caaedsTmoyDtPulseComment;
    /**
     * boolean Variable to hold the value for Column CAAEDS_REMOVE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private boolean caaedsRemove;
    /**
     * String Variable to hold the value for Column CAAEDS_TITRE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private String caaedsTitre;

    /**
     * Default Constructor
     */
    public EdsCourantAppelleActivation() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param caaedsId
     */
    public EdsCourantAppelleActivation(String caaedsId) {
        this.caaedsId = caaedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param caaedsId ID
     * @param caaedsTminImaxPulse Tmin Imax
     * @param caaedsTmoyImaxPulse Tmoy Imax
     * @param caaedsTmaxImaxPulse Tmax Imax
     * @param caaedsTmoyImaxPulseComment Tmoy Imax comment
     * @param caaedsTminDtPulse Tmin Dt
     * @param caaedsTmoyDtPulse Tmoy Dt
     * @param caaedsTmaxDtPulse Tmax Dt
     * @param caaedsTmoyDtPulseComment Tmoy Dt comment
     */
    public EdsCourantAppelleActivation(String caaedsId, Float caaedsTminImaxPulse, Float caaedsTmoyImaxPulse, Float caaedsTmaxImaxPulse,
            String caaedsTmoyImaxPulseComment, Float caaedsTminDtPulse, Float caaedsTmoyDtPulse, Float caaedsTmaxDtPulse,
            String caaedsTmoyDtPulseComment) {
        this.caaedsId = caaedsId;
        this.caaedsTminImaxPulse = caaedsTminImaxPulse;
        this.caaedsTmoyImaxPulse = caaedsTmoyImaxPulse;
        this.caaedsTmaxImaxPulse = caaedsTmaxImaxPulse;
        this.caaedsTmoyImaxPulseComment = caaedsTmoyImaxPulseComment;
        this.caaedsTminDtPulse = caaedsTminDtPulse;
        this.caaedsTmoyDtPulse = caaedsTmoyDtPulse;
        this.caaedsTmaxDtPulse = caaedsTmaxDtPulse;
        this.caaedsTmoyDtPulseComment = caaedsTmoyDtPulseComment;
    }

    /**
     * Parameterized Constructor
     * 
     * @param source
     */
    public EdsCourantAppelleActivation(EdsCourantAppelleActivation source) {
        this.caaedsId = UUID.randomUUID().toString();
        this.caaedsTminImaxPulse = source.caaedsTminImaxPulse;
        this.caaedsTmoyImaxPulse = source.caaedsTmoyImaxPulse;
        this.caaedsTmaxImaxPulse = source.caaedsTmaxImaxPulse;
        this.caaedsTmoyImaxPulseComment = source.caaedsTmoyImaxPulseComment;
        this.caaedsTminDtPulse = source.caaedsTminDtPulse;
        this.caaedsTmoyDtPulse = source.caaedsTmoyDtPulse;
        this.caaedsTmaxDtPulse = source.caaedsTmaxDtPulse;
        this.caaedsTmoyDtPulseComment = source.caaedsTmoyDtPulseComment;
        this.caaedsRemove = source.caaedsRemove;
        this.caaedsTitre = source.caaedsTitre;
    }

    /**
     * Function to get caaedsId
     * 
     * @return ID
     */
    @XmlAttribute(name = "id")
    public String getCaaedsId() {
        return this.caaedsId;
    }

    /**
     * Function to set caaedsId
     * 
     * @param caaedsId Id
     */
    public void setCaaedsId(String caaedsId) {
        this.caaedsId = caaedsId;
    }

    /**
     * Function to get caaedsTminImaxPulse
     * 
     * @return Tmin Imax
     */
    @XmlElement(name = "TminImaxPulse")
    public Float getCaaedsTminImaxPulse() {
        return this.caaedsTminImaxPulse;
    }

    /**
     * Function to set caaedsTminImaxPulse
     * 
     * @param caaedsTminImaxPulse Tmin Imax
     */
    public void setCaaedsTminImaxPulse(Float caaedsTminImaxPulse) {
        this.caaedsTminImaxPulse = caaedsTminImaxPulse;
    }

    /**
     * Function to get caaedsTmoyImaxPulse
     * 
     * @return Tmoy Imax
     */
    @XmlElement(name = "TmoyImaxPulse")
    public Float getCaaedsTmoyImaxPulse() {
        return this.caaedsTmoyImaxPulse;
    }

    /**
     * Function to set caaedsTmoyImaxPulse
     * 
     * @param caaedsTmoyImaxPulse Tmoy Imax
     */
    public void setCaaedsTmoyImaxPulse(Float caaedsTmoyImaxPulse) {
        this.caaedsTmoyImaxPulse = caaedsTmoyImaxPulse;
    }

    /**
     * Function to get caaedsTmaxImaxPulse
     * 
     * @return Tmax Imax
     */
    @XmlElement(name = "TmaxImaxPulse")
    public Float getCaaedsTmaxImaxPulse() {
        return this.caaedsTmaxImaxPulse;
    }

    /**
     * Function to set caaedsTmaxImaxPulse
     * 
     * @param caaedsTmaxImaxPulse Tmax Imax
     */
    public void setCaaedsTmaxImaxPulse(Float caaedsTmaxImaxPulse) {
        this.caaedsTmaxImaxPulse = caaedsTmaxImaxPulse;
    }

    /**
     * Function to get caaedsTmoyImaxPulseComment
     * 
     * @return Tmoy Imax comment
     */
    public String getCaaedsTmoyImaxPulseComment() {
        return this.caaedsTmoyImaxPulseComment;
    }

    /**
     * Function to set caaedsTmoyImaxPulseComment
     * 
     * @param caaedsTmoyImaxPulseComment Tmoy Imax comment
     */
    public void setCaaedsTmoyImaxPulseComment(String caaedsTmoyImaxPulseComment) {
        this.caaedsTmoyImaxPulseComment = caaedsTmoyImaxPulseComment;
    }

    /**
     * Function to caaedsTminDtPulse
     * 
     * @return Tmin Dt
     */
    @XmlElement(name = "TminDtPulse")
    public Float getCaaedsTminDtPulse() {
        return this.caaedsTminDtPulse;
    }

    /**
     * Function to set caaedsTminDtPulse
     * 
     * @param caaedsTminDtPulse Tmin Dt
     */
    public void setCaaedsTminDtPulse(Float caaedsTminDtPulse) {
        this.caaedsTminDtPulse = caaedsTminDtPulse;
    }

    /**
     * Function to get caaedsTmoyDtPulse
     * 
     * @return Tmoy Dt
     */
    @XmlElement(name = "TmoyDtPulse")
    public Float getCaaedsTmoyDtPulse() {
        return this.caaedsTmoyDtPulse;
    }

    /**
     * Function to set caaedsTmoyDtPulse
     * 
     * @param caaedsTmoyDtPulse Tmoy Dt
     */
    public void setCaaedsTmoyDtPulse(Float caaedsTmoyDtPulse) {
        this.caaedsTmoyDtPulse = caaedsTmoyDtPulse;
    }

    /**
     * Function to get caaedsTmaxDtPulse
     * 
     * @return Tmax Dt comment
     */
    @XmlElement(name = "TmaxDtPulse")
    public Float getCaaedsTmaxDtPulse() {
        return this.caaedsTmaxDtPulse;
    }

    /**
     * Function to set caaedsTmaxDtPulse
     * 
     * @param caaedsTmaxDtPulse Tmax Dt comment
     */
    public void setCaaedsTmaxDtPulse(Float caaedsTmaxDtPulse) {
        this.caaedsTmaxDtPulse = caaedsTmaxDtPulse;
    }

    /**
     * Function to get caaedsTmoyDtPulseComment
     * 
     * @return Tmoy Dt comment
     */
    public String getCaaedsTmoyDtPulseComment() {
        return this.caaedsTmoyDtPulseComment;
    }

    /**
     * Function to set caaedsTmoyDtPulseComment
     * 
     * @param caaedsTmoyDtPulseComment Tmoy Dt comment
     */
    public void setCaaedsTmoyDtPulseComment(String caaedsTmoyDtPulseComment) {
        this.caaedsTmoyDtPulseComment = caaedsTmoyDtPulseComment;
    }

    /**
     * Function to get caaedsRemove
     * 
     * @return check if removable
     */
    @XmlTransient
    public boolean isCaaedsRemove() {
        return caaedsRemove;
    }

    /**
     * Function to set caaedsRemove
     * 
     * @param caaedsRemove Boolean to specify removable
     */
    public void setCaaedsRemove(boolean caaedsRemove) {
        this.caaedsRemove = caaedsRemove;
    }

    /**
     * Function to get caaedsRemove
     * 
     * @return Title
     */
    public String getCaaedsTitre() {
        return caaedsTitre;
    }

    /**
     * Function to get caaedsTitre
     * 
     * @param caaedsTitre Title
     */
    public void setCaaedsTitre(String caaedsTitre) {
        this.caaedsTitre = caaedsTitre;
    }

    /**
     * Function to set data for Activation inrush current
     * 
     * @param edsCourantAppelleActivations Set of EdsCourantAppelleActivation
     */
    public void setSomme(Set<EdsCourantAppelleActivation> edsCourantAppelleActivations) {
        // this.caaedsTminImaxPulse = 0f;
        // this.caaedsTmoyImaxPulse = 0f;
        // this.caaedsTmaxImaxPulse = 0f;
        // this.caaedsTminDtPulse = 0f;
        // this.caaedsTmoyDtPulse = 0f;
        // this.caaedsTmaxDtPulse = 0f;

        for (EdsCourantAppelleActivation ecaa : edsCourantAppelleActivations) {
            this.caaedsTminImaxPulse = EDSTools.Concat(this.caaedsTminImaxPulse, ecaa.caaedsTminImaxPulse);
            this.caaedsTmoyImaxPulse = EDSTools.Concat(this.caaedsTmoyImaxPulse, ecaa.caaedsTmoyImaxPulse);
            this.caaedsTmaxImaxPulse = EDSTools.Concat(this.caaedsTmaxImaxPulse, ecaa.caaedsTmaxImaxPulse);
            this.caaedsTminDtPulse = EDSTools.Concat(this.caaedsTminDtPulse, ecaa.caaedsTminDtPulse);
            this.caaedsTmoyDtPulse = EDSTools.Concat(this.caaedsTmoyDtPulse, ecaa.caaedsTmoyDtPulse);
            this.caaedsTmaxDtPulse = EDSTools.Concat(this.caaedsTmaxDtPulse, ecaa.caaedsTmaxDtPulse);
        }
    }
}
