package com.inetpsa.eds.dao.model;

// Generated 17 juil. 2012 10:54:56 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.dao.I_FormData;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EdsDefaillanceVeilleReveilFormData generated by hbm2java
 */
@XmlRootElement(name = "standby-wakeup-failure-form")
public class EdsDefaillanceVeilleReveilFormData implements java.io.Serializable, I_FormData {
    /**
     * String Variable to hold the value for Column DVRFD_ID of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdId;
    /**
     * Variable to hold the value for Column DVRFD_EDS_ID of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private EdsEds edsEds;
    /**
     * String Variable to hold the value for Column DVRFD_OCCURENCE_TOTAL_DEFAILLANCE_ORGANE_CONSOMMATION_PLUS_VINT_MAH of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah;
    /**
     * String Variable to hold the value for Column DVRFD_COURANT_CORRESPONDANT_CONSOMMATION_PLUS_VINT_MAH of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCourantCorrespondantConsommationPlusVintMah;
    /**
     * String Variable to hold the value for Column DVRFD_COMMENTAIRE_CONSOMMATION_PLUS_VINT_MAH of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCommentaireConsommationPlusVintMah;
    /**
     * Integer Variable to hold the value for Column DVRFD_IS_PLUS_VINT_MAH of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private Integer dvrfdIsPlusVintMah;
    /**
     * String Variable to hold the value for Column DVRFD_OCCURENCE_TOTAL_DEFAILLANCE_ORGANE_MAINTIEN_RESEAUX of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux;
    /**
     * String Variable to hold the value for Column DVRFD_COURANT_CORRESPONDANT_MAINTIEN_RESEAUX of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCourantCorrespondantMaintienReseaux;
    /**
     * String Variable to hold the value for Column DVRFD_COMMENTAIRE_MAINTIEN_RESEAUX of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCommentaireMaintienReseaux;
    /**
     * Integer Variable to hold the value for Column DVRFD_IS_MAINTIEN_RESEAUX of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private Integer dvrfdIsMaintienReseaux;
    /**
     * String Variable to hold the value for Column DVRFD_OCCURENCE_TOTAL_DEFAILLANCE_ORGANE_REVEIL_INTEMPESTIF of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif;
    /**
     * String Variable to hold the value for Column DVRFD_COURANT_CORRESPONDANT_REVEIL_INTEMPESTIF of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCourantCorrespondantReveilIntempestif;
    /**
     * String Variable to hold the value for Column DVRFD_COMMENTAIRE_REVEIL_INTEMPESTIF of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCommentaireReveilIntempestif;
    /**
     * Integer Variable to hold the value for Column DVRFD_IS_REVEIL_INTEMPSIF of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private Integer dvrfdIsReveilIntempsif;
    /**
     * String Variable to hold the value for Column DVRFD_OCCURENCE_TOTAL_DEFAILLANCE_ORGANE_MAINTIEN_ALIMENTAION of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion;
    /**
     * String Variable to hold the value for Column DVRFD_COURANT_CORRESPONDANT_MAINTIEN_ALIMENTAION of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCourantCorrespondantMaintienAlimentaion;
    /**
     * String Variable to hold the value for Column DVRFD_COMMENTAIRE_MAINTIEN_ALIMENTAION of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCommentaireMaintienAlimentaion;
    /**
     * Integer Variable to hold the value for Column DVRFD_IS_MAINTIEN_ALIMENTATION of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private Integer dvrfdIsMaintienAlimentation;
    /**
     * String Variable to hold the value for Column DVRFD_OCCURENCE_TOTAL_DEFAILLANCE_ORGANE_REALIMENTATION_ALIMENTATION of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation;
    /**
     * String Variable to hold the value for Column DVRFD_COURANT_CORRESPONDANT_REALIMENTATION_ALIMENTATION of Table
     * EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCourantCorrespondantRealimentationAlimentation;
    /**
     * String Variable to hold the value for Column DVRFD_COMMENTAIRE_REALIMENTATION_ALIMENTATION of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private String dvrfdCommentaireRealimentationAlimentation;
    /**
     * Integer Variable to hold the value for Column DVRFD_IS_REALIMENTATION_ALIMENTATION of Table EDS_DEFAILLANCE_VEILLE_REVEIL_FORM_DATA
     */
    private Integer dvrfdIsRealimentationAlimentation;

    /**
     * Default Constructor
     */
    public EdsDefaillanceVeilleReveilFormData() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param dvrfdId ID
     * @param edsEds Eds details
     */
    public EdsDefaillanceVeilleReveilFormData(String dvrfdId, EdsEds edsEds) {
        this.dvrfdId = dvrfdId;
        this.edsEds = edsEds;
    }

    /**
     * Parameterized Constructor
     * 
     * @param dvrfdId ID
     * @param edsEds Eds Details
     * @param dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah consumption over twenty mah more than cse failure total count
     * @param dvrfdCourantCorrespondantConsommationPlusVintMah Total current consumption associated over Cse value
     * @param dvrfdCommentaireConsommationPlusVintMah Comment for consumption
     * @param dvrfdIsPlusVintMah check if 20mAH electrical consumption over the CSE value
     * @param dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux Network holding total failure count
     * @param dvrfdCourantCorrespondantMaintienReseaux Current consumption associated with network holding
     * @param dvrfdCommentaireMaintienReseaux Comment for network holding
     * @param dvrfdIsMaintienReseaux check if Network holding
     * @param dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif network wakes up total failure count
     * @param dvrfdCourantCorrespondantReveilIntempestif Current consumption associated with network wakes up
     * @param dvrfdCommentaireReveilIntempestif Comment for Network wakes up
     * @param dvrfdIsReveilIntempsif Check if network wakes up
     * @param dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion switched power supplies holding total failure current
     * @param dvrfdCourantCorrespondantMaintienAlimentaion Current consumption associated with switched power supplies
     * @param dvrfdCommentaireMaintienAlimentaion comment for switched power supplies
     * @param dvrfdIsMaintienAlimentation check if switched power supplies holding
     * @param dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation switched power supplies reload total failure count
     * @param dvrfdCourantCorrespondantRealimentationAlimentation current consumption associated with switched power supplies reload
     * @param dvrfdCommentaireRealimentationAlimentation Comment for switched power supplies reload
     * @param dvrfdIsRealimentationAlimentation Check if A switched power supplies reload
     */
    public EdsDefaillanceVeilleReveilFormData(String dvrfdId, EdsEds edsEds, String dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah,
            String dvrfdCourantCorrespondantConsommationPlusVintMah, String dvrfdCommentaireConsommationPlusVintMah, Integer dvrfdIsPlusVintMah,
            String dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux, String dvrfdCourantCorrespondantMaintienReseaux,
            String dvrfdCommentaireMaintienReseaux, Integer dvrfdIsMaintienReseaux, String dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif,
            String dvrfdCourantCorrespondantReveilIntempestif, String dvrfdCommentaireReveilIntempestif, Integer dvrfdIsReveilIntempsif,
            String dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion, String dvrfdCourantCorrespondantMaintienAlimentaion,
            String dvrfdCommentaireMaintienAlimentaion, Integer dvrfdIsMaintienAlimentation,
            String dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation, String dvrfdCourantCorrespondantRealimentationAlimentation,
            String dvrfdCommentaireRealimentationAlimentation, Integer dvrfdIsRealimentationAlimentation) {
        this.dvrfdId = dvrfdId;
        this.edsEds = edsEds;
        this.dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah = dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah;
        this.dvrfdCourantCorrespondantConsommationPlusVintMah = dvrfdCourantCorrespondantConsommationPlusVintMah;
        this.dvrfdCommentaireConsommationPlusVintMah = dvrfdCommentaireConsommationPlusVintMah;
        this.dvrfdIsPlusVintMah = dvrfdIsPlusVintMah;
        this.dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux = dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux;
        this.dvrfdCourantCorrespondantMaintienReseaux = dvrfdCourantCorrespondantMaintienReseaux;
        this.dvrfdCommentaireMaintienReseaux = dvrfdCommentaireMaintienReseaux;
        this.dvrfdIsMaintienReseaux = dvrfdIsMaintienReseaux;
        this.dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif = dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif;
        this.dvrfdCourantCorrespondantReveilIntempestif = dvrfdCourantCorrespondantReveilIntempestif;
        this.dvrfdCommentaireReveilIntempestif = dvrfdCommentaireReveilIntempestif;
        this.dvrfdIsReveilIntempsif = dvrfdIsReveilIntempsif;
        this.dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion = dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion;
        this.dvrfdCourantCorrespondantMaintienAlimentaion = dvrfdCourantCorrespondantMaintienAlimentaion;
        this.dvrfdCommentaireMaintienAlimentaion = dvrfdCommentaireMaintienAlimentaion;
        this.dvrfdIsMaintienAlimentation = dvrfdIsMaintienAlimentation;
        this.dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation = dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation;
        this.dvrfdCourantCorrespondantRealimentationAlimentation = dvrfdCourantCorrespondantRealimentationAlimentation;
        this.dvrfdCommentaireRealimentationAlimentation = dvrfdCommentaireRealimentationAlimentation;
        this.dvrfdIsRealimentationAlimentation = dvrfdIsRealimentationAlimentation;
    }

    /**
     * Function to get dvrfdId
     * 
     * @return the Value of dvrfdId
     */
    @XmlTransient
    public String getDvrfdId() {
        return this.dvrfdId;
    }

    /**
     * Function to set dvrfdId
     * 
     * @param dvrfdId
     */
    public void setDvrfdId(String dvrfdId) {
        this.dvrfdId = dvrfdId;
    }

    /**
     * Function to get edsEds
     * 
     * @return the Value of edsEds
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return this.edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds Eds details
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function to get dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah
     * 
     * @return the Value of dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah
     */
    @XmlElement(name = "consumption-over-twenty-mah-more-than-cse-failure-total-count")
    public String getDvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah() {
        return this.dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah;
    }

    /**
     * Function to set dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah
     * 
     * @param dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah
     */
    public void setDvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah(String dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah) {
        this.dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah = dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah;
    }

    /**
     * Function to get dvrfdCourantCorrespondantConsommationPlusVintMah
     * 
     * @return the Value of dvrfdCourantCorrespondantConsommationPlusVintMah
     */
    @XmlElement(name = "consumption-over-twenty-mah-more-than-cse-corresponding-current")
    public String getDvrfdCourantCorrespondantConsommationPlusVintMah() {
        return this.dvrfdCourantCorrespondantConsommationPlusVintMah;
    }

    /**
     * Function to set dvrfdCourantCorrespondantConsommationPlusVintMah
     * 
     * @param dvrfdCourantCorrespondantConsommationPlusVintMah
     */
    public void setDvrfdCourantCorrespondantConsommationPlusVintMah(String dvrfdCourantCorrespondantConsommationPlusVintMah) {
        this.dvrfdCourantCorrespondantConsommationPlusVintMah = dvrfdCourantCorrespondantConsommationPlusVintMah;
    }

    /**
     * Function to get dvrfdCommentaireConsommationPlusVintMah
     * 
     * @return the Value of dvrfdCommentaireConsommationPlusVintMah
     */
    @XmlElement(name = "consumption-over-twenty-mah-more-than-cse-comment")
    public String getDvrfdCommentaireConsommationPlusVintMah() {
        return this.dvrfdCommentaireConsommationPlusVintMah;
    }

    /**
     * Function to set dvrfdCommentaireConsommationPlusVintMah
     * 
     * @param dvrfdCommentaireConsommationPlusVintMah
     */
    public void setDvrfdCommentaireConsommationPlusVintMah(String dvrfdCommentaireConsommationPlusVintMah) {
        this.dvrfdCommentaireConsommationPlusVintMah = dvrfdCommentaireConsommationPlusVintMah;
    }

    /**
     * Function to get dvrfdIsPlusVintMah
     * 
     * @return the Value of dvrfdIsPlusVintMah
     */
    public Integer getDvrfdIsPlusVintMah() {
        return this.dvrfdIsPlusVintMah;
    }

    /**
     * Function to set dvrfdIsPlusVintMah
     * 
     * @param dvrfdIsPlusVintMah
     */
    public void setDvrfdIsPlusVintMah(Integer dvrfdIsPlusVintMah) {
        this.dvrfdIsPlusVintMah = dvrfdIsPlusVintMah;
    }

    /**
     * Function to get dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux
     * 
     * @return the Value of dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux
     */
    @XmlElement(name = "network-preservation-failure-total-count")
    public String getDvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux() {
        return this.dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux;
    }

    /**
     * Function to set dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux
     * 
     * @param dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux
     */
    public void setDvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux(String dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux) {
        this.dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux = dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux;
    }

    /**
     * Function to get dvrfdCourantCorrespondantMaintienReseaux
     * 
     * @return the Value of dvrfdCourantCorrespondantMaintienReseaux
     */
    @XmlElement(name = "network-preservation-corresponding-current")
    public String getDvrfdCourantCorrespondantMaintienReseaux() {
        return this.dvrfdCourantCorrespondantMaintienReseaux;
    }

    /**
     * Function to set dvrfdCourantCorrespondantMaintienReseaux
     * 
     * @param dvrfdCourantCorrespondantMaintienReseaux
     */
    public void setDvrfdCourantCorrespondantMaintienReseaux(String dvrfdCourantCorrespondantMaintienReseaux) {
        this.dvrfdCourantCorrespondantMaintienReseaux = dvrfdCourantCorrespondantMaintienReseaux;
    }

    /**
     * Function to get dvrfdCommentaireMaintienReseaux
     * 
     * @return the Value of dvrfdCommentaireMaintienReseaux
     */
    @XmlElement(name = "network-preservation-comment")
    public String getDvrfdCommentaireMaintienReseaux() {
        return this.dvrfdCommentaireMaintienReseaux;
    }

    /**
     * Function to set dvrfdCommentaireMaintienReseaux
     * 
     * @param dvrfdCommentaireMaintienReseaux
     */
    public void setDvrfdCommentaireMaintienReseaux(String dvrfdCommentaireMaintienReseaux) {
        this.dvrfdCommentaireMaintienReseaux = dvrfdCommentaireMaintienReseaux;
    }

    /**
     * Function to get dvrfdIsMaintienReseaux
     * 
     * @return the Value of dvrfdIsMaintienReseaux
     */
    public Integer getDvrfdIsMaintienReseaux() {
        return this.dvrfdIsMaintienReseaux;
    }

    /**
     * Function to set dvrfdIsMaintienReseaux
     * 
     * @param dvrfdIsMaintienReseaux
     */
    public void setDvrfdIsMaintienReseaux(Integer dvrfdIsMaintienReseaux) {
        this.dvrfdIsMaintienReseaux = dvrfdIsMaintienReseaux;
    }

    /**
     * Function to get dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif
     * 
     * @return the Value of dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif
     */
    @XmlElement(name = "untimely-network-wakeup-failure-total-count")
    public String getDvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif() {
        return this.dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif;
    }

    /**
     * Function to set dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif
     * 
     * @param dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif
     */
    public void setDvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif(String dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif) {
        this.dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif = dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif;
    }

    /**
     * Function to get dvrfdCourantCorrespondantReveilIntempestif
     * 
     * @return the Value of dvrfdCourantCorrespondantReveilIntempestif
     */
    @XmlElement(name = "untimely-network-wakeup-corresponding-current")
    public String getDvrfdCourantCorrespondantReveilIntempestif() {
        return this.dvrfdCourantCorrespondantReveilIntempestif;
    }

    /**
     * Function to set dvrfdCourantCorrespondantReveilIntempestif
     * 
     * @param dvrfdCourantCorrespondantReveilIntempestif
     */
    public void setDvrfdCourantCorrespondantReveilIntempestif(String dvrfdCourantCorrespondantReveilIntempestif) {
        this.dvrfdCourantCorrespondantReveilIntempestif = dvrfdCourantCorrespondantReveilIntempestif;
    }

    /**
     * Function to get dvrfdCommentaireReveilIntempestif
     * 
     * @return the Value of dvrfdCommentaireReveilIntempestif
     */
    @XmlElement(name = "untimely-network-wakeup-comment")
    public String getDvrfdCommentaireReveilIntempestif() {
        return this.dvrfdCommentaireReveilIntempestif;
    }

    /**
     * Function to set dvrfdCommentaireReveilIntempestif
     * 
     * @param dvrfdCommentaireReveilIntempestif
     */
    public void setDvrfdCommentaireReveilIntempestif(String dvrfdCommentaireReveilIntempestif) {
        this.dvrfdCommentaireReveilIntempestif = dvrfdCommentaireReveilIntempestif;
    }

    /**
     * Function to get dvrfdIsReveilIntempsif
     * 
     * @return the Value of dvrfdIsReveilIntempsif
     */
    public Integer getDvrfdIsReveilIntempsif() {
        return this.dvrfdIsReveilIntempsif;
    }

    /**
     * Function to set dvrfdIsReveilIntempsif
     * 
     * @param dvrfdIsReveilIntempsif
     */
    public void setDvrfdIsReveilIntempsif(Integer dvrfdIsReveilIntempsif) {
        this.dvrfdIsReveilIntempsif = dvrfdIsReveilIntempsif;
    }

    /**
     * Function to get dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion
     * 
     * @return the Value of dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion
     */
    @XmlElement(name = "commutated-supply-preservation-failure-total-count")
    public String getDvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion() {
        return this.dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion;
    }

    /**
     * Function to set dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion
     * 
     * @param dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion
     */
    public void setDvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion(String dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion) {
        this.dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion = dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion;
    }

    /**
     * Function to get dvrfdCourantCorrespondantMaintienAlimentaion
     * 
     * @return the Value of dvrfdCourantCorrespondantMaintienAlimentaion
     */
    @XmlElement(name = "commutated-supply-preservation-corresponding-current")
    public String getDvrfdCourantCorrespondantMaintienAlimentaion() {
        return this.dvrfdCourantCorrespondantMaintienAlimentaion;
    }

    /**
     * Function to set dvrfdCourantCorrespondantMaintienAlimentaion
     * 
     * @param dvrfdCourantCorrespondantMaintienAlimentaion
     */
    public void setDvrfdCourantCorrespondantMaintienAlimentaion(String dvrfdCourantCorrespondantMaintienAlimentaion) {
        this.dvrfdCourantCorrespondantMaintienAlimentaion = dvrfdCourantCorrespondantMaintienAlimentaion;
    }

    /**
     * Function to get dvrfdCommentaireMaintienAlimentaion
     * 
     * @return the Value of dvrfdCommentaireMaintienAlimentaion
     */
    @XmlElement(name = "commutated-supply-preservation-comment")
    public String getDvrfdCommentaireMaintienAlimentaion() {
        return this.dvrfdCommentaireMaintienAlimentaion;
    }

    /**
     * Function to set dvrfdCommentaireMaintienAlimentaion
     * 
     * @param dvrfdCommentaireMaintienAlimentaion
     */
    public void setDvrfdCommentaireMaintienAlimentaion(String dvrfdCommentaireMaintienAlimentaion) {
        this.dvrfdCommentaireMaintienAlimentaion = dvrfdCommentaireMaintienAlimentaion;
    }

    /**
     * Function to get dvrfdIsMaintienAlimentation
     * 
     * @return the Value of dvrfdIsMaintienAlimentation
     */
    public Integer getDvrfdIsMaintienAlimentation() {
        return this.dvrfdIsMaintienAlimentation;
    }

    /**
     * Function to set dvrfdIsMaintienAlimentation
     * 
     * @param dvrfdIsMaintienAlimentation
     */
    public void setDvrfdIsMaintienAlimentation(Integer dvrfdIsMaintienAlimentation) {
        this.dvrfdIsMaintienAlimentation = dvrfdIsMaintienAlimentation;
    }

    /**
     * Function to get dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation
     * 
     * @return the Value of dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation
     */
    @XmlElement(name = "commutated-supply-resupply-failure-total-count")
    public String getDvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation() {
        return this.dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation;
    }

    /**
     * Function to set dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation
     * 
     * @param dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation
     */
    public void setDvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation(
            String dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation) {
        this.dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation = dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation;
    }

    /**
     * Function to get dvrfdCourantCorrespondantRealimentationAlimentation
     * 
     * @return the Value of dvrfdCourantCorrespondantRealimentationAlimentation
     */
    @XmlElement(name = "commutated-supply-resupply-corresponding-current")
    public String getDvrfdCourantCorrespondantRealimentationAlimentation() {
        return this.dvrfdCourantCorrespondantRealimentationAlimentation;
    }

    /**
     * Function to set dvrfdCourantCorrespondantRealimentationAlimentation
     * 
     * @param dvrfdCourantCorrespondantRealimentationAlimentation
     */
    public void setDvrfdCourantCorrespondantRealimentationAlimentation(String dvrfdCourantCorrespondantRealimentationAlimentation) {
        this.dvrfdCourantCorrespondantRealimentationAlimentation = dvrfdCourantCorrespondantRealimentationAlimentation;
    }

    /**
     * Function to get dvrfdCommentaireRealimentationAlimentation
     * 
     * @return the Value of dvrfdCommentaireRealimentationAlimentation
     */
    @XmlElement(name = "commutated-supply-resupply-comment")
    public String getDvrfdCommentaireRealimentationAlimentation() {
        return this.dvrfdCommentaireRealimentationAlimentation;
    }

    /**
     * Function to set dvrfdCommentaireRealimentationAlimentation
     * 
     * @param dvrfdCommentaireRealimentationAlimentation
     */
    public void setDvrfdCommentaireRealimentationAlimentation(String dvrfdCommentaireRealimentationAlimentation) {
        this.dvrfdCommentaireRealimentationAlimentation = dvrfdCommentaireRealimentationAlimentation;
    }

    /**
     * Function to get dvrfdIsRealimentationAlimentation
     * 
     * @return the Value of dvrfdIsRealimentationAlimentation
     */
    public Integer getDvrfdIsRealimentationAlimentation() {
        return this.dvrfdIsRealimentationAlimentation;
    }

    /**
     * Function to set dvrfdIsRealimentationAlimentation
     * 
     * @param dvrfdIsRealimentationAlimentation
     */
    public void setDvrfdIsRealimentationAlimentation(Integer dvrfdIsRealimentationAlimentation) {
        this.dvrfdIsRealimentationAlimentation = dvrfdIsRealimentationAlimentation;
    }

    /**
     * Function to get the Copy of EdsDefaillanceVeilleReveilFormData
     * 
     * @param eds Eds details
     * @param copiesMap Map od Id and ProjectSpecificData objects
     * @return the Value of EdsDefaillanceVeilleReveilFormData
     */
    public I_FormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsDefaillanceVeilleReveilFormData copy = new EdsDefaillanceVeilleReveilFormData(UUID.randomUUID().toString(), eds);
        copy.dvrfdCommentaireConsommationPlusVintMah = this.dvrfdCommentaireConsommationPlusVintMah;
        copy.dvrfdCommentaireMaintienAlimentaion = this.dvrfdCommentaireMaintienAlimentaion;
        copy.dvrfdCommentaireMaintienReseaux = this.dvrfdCommentaireMaintienReseaux;
        copy.dvrfdCommentaireRealimentationAlimentation = this.dvrfdCommentaireRealimentationAlimentation;
        copy.dvrfdCommentaireReveilIntempestif = this.dvrfdCommentaireReveilIntempestif;
        copy.dvrfdCourantCorrespondantConsommationPlusVintMah = this.dvrfdCourantCorrespondantConsommationPlusVintMah;
        copy.dvrfdCourantCorrespondantMaintienAlimentaion = this.dvrfdCourantCorrespondantMaintienAlimentaion;
        copy.dvrfdCourantCorrespondantReveilIntempestif = this.dvrfdCourantCorrespondantReveilIntempestif;
        copy.dvrfdIsMaintienAlimentation = this.dvrfdIsMaintienAlimentation;
        copy.dvrfdIsMaintienReseaux = this.dvrfdIsMaintienReseaux;
        copy.dvrfdIsPlusVintMah = this.dvrfdIsPlusVintMah;
        copy.dvrfdIsRealimentationAlimentation = this.dvrfdIsRealimentationAlimentation;
        copy.dvrfdIsReveilIntempsif = this.dvrfdIsReveilIntempsif;
        copy.dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah = this.dvrfdOccurenceTotalDefaillanceOrganeConsommationPlusVintMah;
        copy.dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion = this.dvrfdOccurenceTotalDefaillanceOrganeMaintienAlimentaion;
        copy.dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux = this.dvrfdOccurenceTotalDefaillanceOrganeMaintienReseaux;
        copy.dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation = this.dvrfdOccurenceTotalDefaillanceOrganeRealimentationAlimentation;
        copy.dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif = this.dvrfdOccurenceTotalDefaillanceOrganeReveilIntempestif;
        return copy;

    }

    /**
     * Function to get all saved items
     * 
     * @return All saved items
     */
    @XmlTransient
    public List<Object> getAllItemsToSave() {
        List<Object> itemsToSave = new ArrayList<Object>();
        itemsToSave.add(this);
        return itemsToSave;
    }
}
