package com.inetpsa.eds.dao.model;

// Generated 23 oct. 2012 17:44:10 by Hibernate Tools 3.2.1.GA

import java.util.UUID;

import com.inetpsa.eds.application.content.eds.currentconsumption.driftdriver.SupplyDriftController;

/**
 * EdsDriftInfo generated by hbm2java
 */
public class EdsDriftInfo implements java.io.Serializable, Comparable<EdsDriftInfo> {
    /**
     * String Variable to hold the value for Column DI_ID of Table OPLQTDRI
     */
    private String diId;
    /**
     * String Variable to hold the value for Column DI_ALIM_NAME of Table OPLQTDRI
     */
    private String diAlimName;
    /**
     * int Variable to hold the value for Column DI_DATA_TYPE of Table OPLQTDRI
     */
    private int diDataType;
    /**
     * int Variable to hold the value for Column DI_REF_STAGE of Table OPLQTDRI
     */
    private int diRefStage;
    /**
     * Float Variable to hold the value for Column DI_REF_VALUE of Table OPLQTDRI
     */
    private Float diRefValue;
    /**
     * int Variable to hold the value for Column DI_TARGET_STAGE of Table OPLQTDRI
     */
    private int diTargetStage;
    /**
     * Float Variable to hold the value for Column DI_TARGET_VALUE of Table OPLQTDRI
     */
    private Float diTargetValue;
    /**
     * boolean to hold value for alert
     */
    private boolean alert;
    /**
     * boolean to hold value for warning
     */
    private boolean warning;
    /**
     * Float to hold value of deltaI
     */
    private Float deltaI;
    /**
     * Variable to hold the value for Column DI_EDS_ID of Table OPLQTDRI
     */
    private EdsEds edsEds;

    /**
     * Default Constructor
     */
    public EdsDriftInfo() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param diId Id
     * @param diAlimName Supply name
     * @param diDataType Data type
     * @param diRefStage Reference Stage
     * @param diTargetStage Target stage
     * @param edsEds EdsEDs
     */
    public EdsDriftInfo(String diId, String diAlimName, int diDataType, int diRefStage, int diTargetStage, EdsEds edsEds) {
        this.diId = diId;
        this.diDataType = diDataType;
        this.diAlimName = diAlimName;
        this.diRefStage = diRefStage;
        this.diTargetStage = diTargetStage;
        this.edsEds = edsEds;
        init();
    }

    /**
     * Parameterized Constructor
     * 
     * @param diId Id
     * @param diAlimName Supply name
     * @param diDataType Data type
     * @param diRefStage Reference stage
     * @param diRefValue Reference value
     * @param diTargetStage Target stage
     * @param diTargetValue Target value
     * @param edsEds EdsEds
     */
    public EdsDriftInfo(String diId, String diAlimName, int diDataType, int diRefStage, Float diRefValue, int diTargetStage, Float diTargetValue,
            EdsEds edsEds) {
        this.diId = diId;
        this.diAlimName = diAlimName;
        this.diDataType = diDataType;
        this.diRefStage = diRefStage;
        this.diRefValue = diRefValue;
        this.diTargetStage = diTargetStage;
        this.diTargetValue = diTargetValue;
        this.edsEds = edsEds;
        init();
    }

    /**
     * Parameterized Constructor
     * 
     * @param edsEds EdsEds
     * @param source EdsDriftInfo
     */
    public EdsDriftInfo(EdsEds edsEds, EdsDriftInfo source) {
        this.diId = UUID.randomUUID().toString();
        this.diAlimName = source.diAlimName;
        this.diDataType = source.diDataType;
        this.diRefStage = source.diRefStage;
        this.diRefValue = source.diRefValue;
        this.diTargetStage = source.diTargetStage;
        this.diTargetValue = source.diTargetValue;
        this.edsEds = edsEds;
    }

    /**
     * Function to get diId
     * 
     * @return the Value of diId
     */
    public String getDiId() {
        return this.diId;
    }

    /**
     * Function to get alert
     * 
     * @return the Value of alert
     */
    public boolean isAlert() {
        return alert;
    }

    /**
     * Function to get deltaI
     * 
     * @return the Value of deltaI
     */
    public Float getDeltaI() {
        return deltaI;
    }

    /**
     * Function to get diDataType
     * 
     * @return the Value of diDataType
     */
    public int getDiDataType() {
        return diDataType;
    }

    /**
     * Function to set diDataType
     * 
     * @param diDataType
     */
    public void setDiDataType(int diDataType) {
        this.diDataType = diDataType;
    }

    /**
     * Function to get warning
     * 
     * @return the Value of diDataType
     */
    public boolean isWarning() {
        return warning;
    }

    /**
     * Function to set diId
     * 
     * @param diId
     */
    public void setDiId(String diId) {
        this.diId = diId;
    }

    /**
     * Function to get diAlimName
     * 
     * @return the Value of diAlimName
     */
    public String getDiAlimName() {
        return this.diAlimName;
    }

    /**
     * Function to set diAlimName
     * 
     * @param diAlimName
     */
    public void setDiAlimName(String diAlimName) {
        this.diAlimName = diAlimName;
    }

    /**
     * Function to get diRefStage
     * 
     * @return the Value of diRefStage
     */
    public int getDiRefStage() {
        return this.diRefStage;
    }

    /**
     * Function to set diRefStage
     * 
     * @param diRefStage
     */
    public void setDiRefStage(int diRefStage) {
        this.diRefStage = diRefStage;
    }

    /**
     * Function to get diRefValue
     * 
     * @return the Value of diRefValue
     */
    public Float getDiRefValue() {
        return this.diRefValue;
    }

    /**
     * Function to set diRefValue
     * 
     * @param diRefValue
     */
    public void setDiRefValue(Float diRefValue) {
        this.diRefValue = diRefValue;
    }

    /**
     * Function to get diTargetStage
     * 
     * @return the Value of diTargetStage
     */
    public int getDiTargetStage() {
        return this.diTargetStage;
    }

    /**
     * Function to set diTargetStage
     * 
     * @param diTargetStage
     */
    public void setDiTargetStage(int diTargetStage) {
        this.diTargetStage = diTargetStage;
    }

    /**
     * Function to get diTargetValue
     * 
     * @return the Value of diTargetValue
     */
    public Float getDiTargetValue() {
        return this.diTargetValue;
    }

    /**
     * Function to set diTargetValue
     * 
     * @param diTargetValue
     */
    public void setDiTargetValue(Float diTargetValue) {
        this.diTargetValue = diTargetValue;
    }

    /**
     * Function to get edsEds
     * 
     * @return the Value of edsEds
     */
    public EdsEds getEdsEds() {
        return edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsDriftInfo other = (EdsDriftInfo) obj;
        if ((this.diAlimName == null) ? (other.diAlimName != null) : !this.diAlimName.equals(other.diAlimName)) {
            return false;
        }
        if (this.diRefStage != other.diRefStage) {
            return false;
        }
        if (this.diDataType != other.diDataType) {
            return false;
        }
        if (this.diRefValue != other.diRefValue && (this.diRefValue == null || !this.diRefValue.equals(other.diRefValue))) {
            return false;
        }
        if (this.diTargetStage != other.diTargetStage) {
            return false;
        }
        if (this.diTargetValue != other.diTargetValue && (this.diTargetValue == null || !this.diTargetValue.equals(other.diTargetValue))) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + (this.diAlimName != null ? this.diAlimName.hashCode() : 0);
        hash = 29 * hash + this.diRefStage;
        hash = 29 * hash + this.diDataType;
        hash = 29 * hash + (this.diRefValue != null ? this.diRefValue.hashCode() : 0);
        hash = 29 * hash + this.diTargetStage;
        hash = 29 * hash + (this.diTargetValue != null ? this.diTargetValue.hashCode() : 0);
        return hash;
    }

    /**
     * Initialize EdsDriftInfo
     */
    private void init() {
        // Detecting drift
        this.alert = false;
        this.warning = false;
        this.deltaI = null;
        // No warning if the trend involves Inom Stab (Ex 143), only a warning
        if (diDataType == SupplyDriftController.I_NOM_STAB_12_5 || diDataType == SupplyDriftController.I_NOM_STAB_13_5) {
            if (diTargetValue != null && diRefValue != null) {
                warning = diTargetValue > diRefValue;
                if (warning) {
                    deltaI = diTargetValue - diRefValue;
                }
            }
        } else {
            if (diTargetValue != null && diRefValue != null) {
                alert = diTargetValue > diRefValue;
                if (alert) {
                    deltaI = diTargetValue - diRefValue;
                }
            }
        }
    }

    /**
     * Function to compare two EdsDriftInfo objects
     * 
     * @param o EdsDriftInfo
     * @return Difference EdsDriftInfo objects
     */
    public int compareTo(EdsDriftInfo o) {
        return this.diDataType - o.getDiDataType();
    }
}
