package com.inetpsa.eds.dao.model;

// Generated 15 juin 2012 12:07:59 by Hibernate Tools 3.2.1.GA

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsEds generated by hbm2java
 */
@XmlType
public class EdsEds implements java.io.Serializable {
    /**
     * Constant to hold value of DEFAULT_STATE
     */
    public final static int DEFAULT_STATE = 0;
    /**
     * Constant to hold value of FROZEN_STATE
     */
    public final static int FROZEN_STATE = 1;
    /**
     * Constant to hold value of ABORTED_STATE
     */
    public final static int ABORTED_STATE = 2;
    /**
     * Constant to hold value of FIRST_MAJOR_VERSION
     */
    public final static int FIRST_MAJOR_VERSION = 1;
    /**
     * Constant to hold value of FIRST_MINOR_VERSION
     */
    public final static int FIRST_MINOR_VERSION = 0;
    /**
     * Constant to hold value of VALIDATION_LVL_HIGH
     */
    public final static int VALIDATION_LVL_HIGH = 0;
    /**
     * Constant to hold value of VALIDATION_LVL_LOW
     */
    public final static int VALIDATION_LVL_LOW = 1;
    /**
     * Constant to hold value of IS_NOT_BTTBT
     */
    public final static int IS_NOT_BTTBT = 0;
    /**
     * Constant to hold value of IS_BTTBT
     */
    public final static int IS_BTTBT = 1;
    /**
     * String Variable to hold the value for Column EDS_ID of Table OPLQTEDS
     */
    private String edsId;
    /**
     * Variable to hold the value for Column EDS_MANAGER_ID of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsManagerId;
    /**
     * Variable to hold the value for Column EDS_OFFICER_ID of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsOfficerId;
    /**
     * Variable to hold the value for Column EDS_DRIFT_VALIDATOR_ID of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsDriftValidatorId;
    /**
     * Variable to hold the value for Column EDS_AFF_USER_ID of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsAffectationUserId;
    /**
     * Variable to hold the value for Column EDS_S_ID of Table OPLQTEDS
     */
    private EdsSupplier edsSupplier;
    /**
     * Variable to hold the value for Column EDS_W_ID of Table OPLQTEDS
     */
    private EdsWording edsOrganFamily;
    /**
     * Variable to hold the value for Column EDS_ALT_FUNC_ID of Table OPLQTEDS
     */
    private EdsWording edsAltSubFct;
    /**
     * Variable to hold the value for Column EDS_ALT_FUNC_ID of Table OPLQTEDS
     */
    private EdsWording edsAltSubSys;
    /**
     * Variable to hold the value for Column EDS_ALT_FUNC_ID of Table OPLQTEDS
     */
    private EdsWording edsBatSubFct;
    /**
     * Variable to hold the value for Column EDS_ALT_FUNC_ID of Table OPLQTEDS
     */
    private EdsWording edsBatSubSys;
    /**
     * Variable to hold the value for Column EDS_P_ID of Table OPLQTEDS
     */
    /**
     * Variable to hold the value for Column EDS_P_ID of Table OPLQTEDS
     */
    private EdsProject edsProject;
    /**
     * Variable to hold the value for Column EDS_ADMIN_ID of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsAdminId;
    /**
     * Variable to hold the value for Column EDS_CT_ID of Table OPLQTEDS
     */
    private EdsComponentType edsComponentType;
    /**
     * String Variable to hold the value for Column EDS_REF of Table OPLQTEDS
     */
    private String edsRef;
    /**
     * String Variable to hold the value for Column EDS_MAJOR_VERSION of Table OPLQTEDS
     */
    private int edsMajorVersion;
    /**
     * String Variable to hold the value for Column EDS_MINOR_VERSION of Table OPLQTEDS
     */
    private int edsMinorVersion;
    /**
     * String Variable to hold the value for Column EDS_CREA_DATE of Table OPLQTEDS
     */
    private Date edsCreaDate;
    /**
     * String Variable to hold the value for Column EDS_MODIF_DATE of Table OPLQTEDS
     */
    private Date edsModifDate;
    /**
     * String Variable to hold the value for Column edsUserByEdsModifUserId of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsModifUserId;
    /**
     * String Variable to hold the value for Column edsUserByEdsCreaUserId of Table OPLQTEDS
     */
    private EdsUser edsUserByEdsCreaUserId;
    /**
     * String Variable to hold the value for Column EDS_DRIFT_VALIDATION_DATE of Table OPLQTEDS
     */
    private Date edsDriftValidationDate;
    /**
     * String Variable to hold the value for Column EDS_NAME of Table OPLQTEDS
     */
    private String edsName;
    /**
     * String Variable to hold the value for column EDS_COMMENT of Table OPLQTEDS
     */
    private String edsDescription;
    /**
     * String Variable to hold the value for Column EDS_VALID_LVL of Table OPLQTEDS
     */
    private Integer edsValidLvl;
    /**
     * String Variable to hold the value for Column EDS_SUBTYPE_1 of Table OPLQTEDS
     */
    private Integer edsSubtype1;
    /**
     * String Variable to hold the value for Column EDS_SUBTYPE_2 of Table OPLQTEDS
     */
    private Integer edsSubtype2;
    /**
     * String Variable to hold the value for Column EDS_IS_BTTBT of Table OPLQTEDS
     */
    private int edsIsBttbt;
    /**
     * String Variable to hold the value for Column EDS_STATE of Table OPLQTEDS
     */
    private int edsState;
    /**
     * String Variable to hold the value for Column EDS_P_LAUNCH_COUNT of Table OPLQTEDS
     */
    private Integer edsPLaunchCount;
    /**
     * String Variable to hold the value for Column EDS_COMMENTS of Table OPLQTEDS
     */
    private String edsComments;
    /**
     * String Variable to hold the value for Column EDS_HAS_DRIFT of Table OPLQTEDS
     */
    private int edsHasDrift;
    /**
     * Set Collection to hold the values for Table OPLQTNUN
     */
    private Set<EdsNumber96k> edsNumber96ks = new HashSet<EdsNumber96k>(0);
    /**
     * Set Collection to hold the values for Table OPLQTPER
     */
    private Set<EdsPerimeter> edsPerimeters = new HashSet<EdsPerimeter>(0);
    /**
     * Set Collection to hold the values for Table OPLQTPRE
     */
    private Set<EdsProjectEds> edsProjectEdses = new HashSet<EdsProjectEds>(0);
    /**
     * Set Collection to hold the values for Table OPLQTDRI
     */
    private Set<EdsDriftInfo> edsDriftInfos = new HashSet<EdsDriftInfo>(0);
    /**
     * Set Collection to hold the values for Table OPLQTFCT
     */
    private Set<EdsSAPReference> edsNumber96fcts = new HashSet<EdsSAPReference>(0);
    /**
     * Set Collection to hold the values for Table OPLQTFNR
     */
    private Set<EdsSAPReference> edsNumber96fnrs = new HashSet<EdsSAPReference>(0);
    /**
     * Set Collection to hold the values for Table OPLQTCHS
     */
    private Set<Chs> edsChs = new HashSet<Chs>(0);
    /**
     * Set Collection to hold the values for Table OPLQTEPC
     */
    private Set<EdsPinConnect> edsPinConnect = new HashSet<EdsPinConnect>(0);

    /**
     * Set Collection to hold the values for Table OPLQTETC
     */
    private Set<EdsPinTypeComment> edsTypeComment = new HashSet<EdsPinTypeComment>(0);

    /**
     * Set Collection to hold the values for Table OPLQTBSX
     */
    private Set<EdsBsx> edsBsx = new HashSet<EdsBsx>(0);

    /**
     * Default constructor
     */
    public EdsEds() {
    }

    /**
     * Parameterized constructor
     * 
     * @param sourceEds EdsEds
     */
    public EdsEds(EdsEds sourceEds) {
        this(UUID.randomUUID().toString(), sourceEds.getEdsUserByEdsManagerId(), sourceEds.getEdsUserByEdsOfficerId(), sourceEds
                .getEdsUserByEdsDriftValidatorId(), sourceEds.getEdsSupplier(), sourceEds.getEdsOrganFamily(), sourceEds.getEdsProject(), sourceEds
                .getEdsUserByEdsAdminId(), sourceEds.getEdsComponentType(), sourceEds.getEdsUserByEdsModifUserId(), sourceEds
                .getEdsUserByEdsCreaUserId(), sourceEds.getEdsUserByEdsAffectationUserId(), sourceEds.getEdsRef(), sourceEds.getEdsMajorVersion(),
                sourceEds.getEdsMinorVersion(), sourceEds.getEdsCreaDate(), sourceEds.getEdsModifDate(), sourceEds.getEdsDriftValidationDate(),
                sourceEds.getEdsName(), sourceEds.getEdsDescription(), sourceEds.getEdsValidLvl(), sourceEds.getEdsSubtype1(), sourceEds
                        .getEdsSubtype2(), sourceEds.getEdsIsBttbt(), sourceEds.getEdsState(), sourceEds.getEdsPLaunchCount(), sourceEds
                        .getEdsComments(), sourceEds.getEdsHasDrift(), new HashSet<EdsPerimeter>(sourceEds.getEdsPerimeters()),
                new HashSet<EdsProjectEds>(), new HashSet<EdsDriftInfo>(sourceEds.getEdsDriftInfos()), sourceEds.getEdsAltSubFct(), sourceEds
                        .getEdsAltSubSys(), sourceEds.getEdsBatSubFct(), sourceEds.getEdsBatSubSys());

        // this.edsNumber96ks.addAll( sourceEds.getEdsNumber96ks() );
        for (EdsNumber96k number96k : sourceEds.edsNumber96ks) {
            this.edsNumber96ks.add(new EdsNumber96k(number96k));
        }
        for (EdsSAPReference number96fct : sourceEds.edsNumber96fcts) {
            this.edsNumber96fcts.add(new EdsSAPReference(number96fct));
        }
        for (EdsSAPReference number96fnr : sourceEds.edsNumber96fnrs) {
            this.edsNumber96fnrs.add(new EdsSAPReference(number96fnr));
        }

        for (EdsDriftInfo driftInfo : sourceEds.edsDriftInfos) {
            this.edsDriftInfos.add(new EdsDriftInfo(this, driftInfo));
        }

        for (Object object : sourceEds.getEdsProjectEdses()) {
            EdsProjectEds edsProjectEds = (EdsProjectEds) object;

            this.edsProjectEdses.add(new EdsProjectEds(UUID.randomUUID().toString(), this, edsProjectEds.getEdsProject(), edsProjectEds
                    .getPedsReconductionDate(), edsProjectEds.getPedsCount(), edsProjectEds.getPedsReconductWithModif()));
        }
    }

    /**
     * Parameterized constructor
     * 
     * @param edsId Id
     * @param edsProject EdsProject
     * @param edsComponentType EdsComponentType
     * @param edsUserByEdsCreaUserId EdsUser
     * @param edsRef Eds reference
     * @param edsMajorVersion Major version
     * @param edsMinorVersion minor version
     * @param edsCreaDate Ceate date
     * @param edsModifDate modification date
     * @param edsName Eds name
     * @param edsIsBttbt BT/TBT
     * @param edsState Eds state
     * @param edsHasDrift Check for Eds drift
     */
    public EdsEds(String edsId, EdsProject edsProject, EdsComponentType edsComponentType, EdsUser edsUserByEdsCreaUserId, String edsRef,
            int edsMajorVersion, int edsMinorVersion, Date edsCreaDate, Date edsModifDate, String edsName, String edsDescription, int edsIsBttbt,
            int edsState, int edsHasDrift) {
        this.edsId = edsId;
        this.edsProject = edsProject;
        this.edsComponentType = edsComponentType;
        this.edsUserByEdsCreaUserId = edsUserByEdsCreaUserId;
        this.edsRef = edsRef;
        this.edsMajorVersion = edsMajorVersion;
        this.edsMinorVersion = edsMinorVersion;
        this.edsCreaDate = edsCreaDate;
        this.edsModifDate = edsModifDate;
        this.edsName = edsName;
        this.edsDescription = edsDescription;
        this.edsIsBttbt = edsIsBttbt;
        this.edsState = edsState;
        this.edsHasDrift = edsHasDrift;
    }

    /**
     * Parameterized constructor
     * 
     * @param edsId Eds Id
     * @param edsUserByEdsManagerId Eds User Manager Id
     * @param edsUserByEdsOfficerId Eds User Officer Id
     * @param edsUserByEdsDriftValidatorId Eds User Drift validator Id
     * @param edsSupplier EdsSupplier
     * @param edsOrganFamily EdsWording
     * @param edsAltSubFct EdsWording
     * @param edsAltSubSys EdsWording
     * @param edsBatSubFct EdsWording
     * @param edsBatSubSys EdsWording
     * @param edsProject EdsProject
     * @param edsUserByEdsAdminId Eds User admin Id
     * @param edsComponentType EdsComponentType
     * @param edsUserByEdsModifUserId Eds User by Modified user Id
     * @param edsUserByEdsCreaUserId Eds User by created user Id
     * @param edsUserByEdsAffectationUserId Eds User by affectation user Id
     * @param edsRef Eds reference
     * @param edsMajorVersion Major version
     * @param edsMinorVersion Minor version
     * @param edsCreaDate Create date
     * @param edsModifDate Modification date
     * @param edsDriftValidationDate Drift validation date
     * @param edsName Eds Name
     * @param edsValidLvl Eds validation level
     * @param edsSubtype1 Subtype 1
     * @param edsSubtype2 Subtype 2
     * @param edsIsBttbt Bt/TBT
     * @param edsState EdsState
     * @param edsPLaunchCount Project launch count
     * @param edsComments Comment
     * @param edsHasDrift check if EDS has drift
     * @param edsPerimeters set of EdsPerimetes
     * @param edsProjectEdses Set of EdsProjectEdses
     * @param edsDriftInfos set of EdsDriftInfo
     */
    public EdsEds(String edsId, EdsUser edsUserByEdsManagerId, EdsUser edsUserByEdsOfficerId, EdsUser edsUserByEdsDriftValidatorId,
            EdsSupplier edsSupplier, EdsWording edsOrganFamily, EdsProject edsProject, EdsUser edsUserByEdsAdminId,
            EdsComponentType edsComponentType, EdsUser edsUserByEdsModifUserId, EdsUser edsUserByEdsCreaUserId,
            EdsUser edsUserByEdsAffectationUserId, String edsRef, int edsMajorVersion, int edsMinorVersion, Date edsCreaDate, Date edsModifDate,
            Date edsDriftValidationDate, String edsName, String edsDescription, Integer edsValidLvl, Integer edsSubtype1, Integer edsSubtype2,
            int edsIsBttbt, int edsState, Integer edsPLaunchCount, String edsComments, int edsHasDrift, Set<EdsPerimeter> edsPerimeters,
            Set<EdsProjectEds> edsProjectEdses, Set<?> edsDriftInfos, EdsWording edsAltSubFct, EdsWording edsAltSubSys, EdsWording edsBatSubFct,
            EdsWording edsBatSubSys) {
        this.edsId = edsId;
        this.edsUserByEdsManagerId = edsUserByEdsManagerId;
        this.edsUserByEdsOfficerId = edsUserByEdsOfficerId;
        this.edsUserByEdsDriftValidatorId = edsUserByEdsDriftValidatorId;
        this.edsSupplier = edsSupplier;
        this.edsOrganFamily = edsOrganFamily;
        this.edsProject = edsProject;
        this.edsUserByEdsAdminId = edsUserByEdsAdminId;
        this.edsComponentType = edsComponentType;
        this.edsUserByEdsModifUserId = edsUserByEdsModifUserId;
        this.edsUserByEdsCreaUserId = edsUserByEdsCreaUserId;
        this.edsUserByEdsAffectationUserId = edsUserByEdsAffectationUserId;
        this.edsRef = edsRef;
        this.edsMajorVersion = edsMajorVersion;
        this.edsMinorVersion = edsMinorVersion;
        this.edsCreaDate = edsCreaDate;
        this.edsModifDate = edsModifDate;
        this.edsDriftValidationDate = edsDriftValidationDate;
        this.edsName = edsName;
        this.edsDescription = edsDescription;
        this.edsValidLvl = edsValidLvl;
        this.edsSubtype1 = edsSubtype1;
        this.edsSubtype2 = edsSubtype2;
        this.edsIsBttbt = edsIsBttbt;
        this.edsState = edsState;
        this.edsPLaunchCount = edsPLaunchCount;
        this.edsComments = edsComments;
        this.edsHasDrift = edsHasDrift;
        this.edsPerimeters = edsPerimeters;
        this.edsProjectEdses = edsProjectEdses;
        this.edsAltSubFct = edsAltSubFct;
        this.edsBatSubFct = edsBatSubFct;
        this.edsAltSubSys = edsAltSubSys;
        this.edsBatSubSys = edsBatSubSys;
    }

    /**
     * Function to get EdsId
     * 
     * @return Eds ID
     */
    @XmlTransient
    public String getEdsId() {
        return this.edsId;
    }

    /**
     * Function to set EdsId
     * 
     * @param edsId Eds id to set
     */
    public void setEdsId(String edsId) {
        this.edsId = edsId;
    }

    /**
     * Function to get edsUserByEdsManagerId
     * 
     * @return EdsUser By Manager Id
     */
    @XmlElement(name = "manager")
    public EdsUser getEdsUserByEdsManagerId() {
        return this.edsUserByEdsManagerId;
    }

    /**
     * Function to set edsUserByEdsManagerId
     * 
     * @param edsUserByEdsManagerId EdsUser
     */
    public void setEdsUserByEdsManagerId(EdsUser edsUserByEdsManagerId) {
        this.edsUserByEdsManagerId = edsUserByEdsManagerId;
    }

    /**
     * Function to get edsUserByEdsOfficerId
     * 
     * @return EdsUser By Officer Id
     */
    @XmlElement(name = "officer")
    public EdsUser getEdsUserByEdsOfficerId() {
        return this.edsUserByEdsOfficerId;
    }

    /**
     * Function to set edsUserByEdsOfficerId
     * 
     * @param edsUserByEdsOfficerId EdsUser
     */
    public void setEdsUserByEdsOfficerId(EdsUser edsUserByEdsOfficerId) {
        this.edsUserByEdsOfficerId = edsUserByEdsOfficerId;
    }

    /**
     * Function to get edsUserByEdsDriftValidatorId
     * 
     * @return EdsUser By Drift Validator Id
     */
    @XmlElement(name = "drift-validator")
    public EdsUser getEdsUserByEdsDriftValidatorId() {
        return edsUserByEdsDriftValidatorId;
    }

    /**
     * Function to set edsUserByEdsDriftValidatorId
     * 
     * @param edsUserByEdsDriftValidatorId EdsUser
     */
    public void setEdsUserByEdsDriftValidatorId(EdsUser edsUserByEdsDriftValidatorId) {
        this.edsUserByEdsDriftValidatorId = edsUserByEdsDriftValidatorId;
    }

    /**
     * Function returns EdsSupplier
     * 
     * @return Eds supplier
     */
    @XmlElement(name = "supplier")
    public EdsSupplier getEdsSupplier() {
        return this.edsSupplier;
    }

    /**
     * Function to set EdsSupplier
     * 
     * @param edsSupplier EdsSupplier to set
     */
    public void setEdsSupplier(EdsSupplier edsSupplier) {
        this.edsSupplier = edsSupplier;
    }

    /**
     * Function returns EdsWording
     * 
     * @return EdsWording
     */
    @XmlElement(name = "organ-family")
    public EdsWording getEdsOrganFamily() {
        return edsOrganFamily;
    }

    /**
     * Function set EdsWording
     * 
     * @param edsOrganFamily edsOrganFamily
     */
    public void setEdsOrganFamily(EdsWording edsOrganFamily) {
        this.edsOrganFamily = edsOrganFamily;
    }

    /**
     * Function returns EdsWording
     * 
     * @return EdsWording
     */
    @XmlElement(name = "Alt-sub-function")
    public EdsWording getEdsAltSubFct() {
        return edsAltSubFct;
    }

    /**
     * Function set EdsWording
     * 
     * @param edsAltSubFct edsAltSubFct
     */
    public void setEdsAltSubFct(EdsWording edsAltSubFct) {
        this.edsAltSubFct = edsAltSubFct;
    }

    /**
     * Function returns EdsWording
     * 
     * @return EdsWording
     */
    @XmlElement(name = "Alt-sub-system")
    public EdsWording getEdsAltSubSys() {
        return edsAltSubSys;
    }

    /**
     * Function set EdsWording
     * 
     * @param edsAltSubSys edsAltSubSys
     */
    public void setEdsAltSubSys(EdsWording edsAltSubSys) {
        this.edsAltSubSys = edsAltSubSys;
    }

    /**
     * Function returns EdsWording
     * 
     * @return EdsWording
     */
    @XmlElement(name = "bat-sub-function")
    public EdsWording getEdsBatSubFct() {
        return edsBatSubFct;
    }

    /**
     * Function set EdsWording
     * 
     * @param edsBatSubFct edsBatSubFct
     */
    public void setEdsBatSubFct(EdsWording edsBatSubFct) {
        this.edsBatSubFct = edsBatSubFct;
    }

    /**
     * Function returns EdsWording
     * 
     * @return EdsWording
     */
    @XmlElement(name = "Bat-sub-system")
    public EdsWording getEdsBatSubSys() {
        return edsBatSubSys;
    }

    /**
     * Function set EdsWording
     * 
     * @param edsBatSubSys edsBatSubSys
     */
    public void setEdsBatSubSys(EdsWording edsBatSubSys) {
        this.edsBatSubSys = edsBatSubSys;
    }

    /**
     * Function returns EdsPorject
     * 
     * @return EdsProject
     */
    @XmlElement(name = "project-setter")
    public EdsProject getEdsProject() {
        return this.edsProject;
    }

    /**
     * Function to set EdsProject
     * 
     * @param edsProject EdsProject
     */
    public void setEdsProject(EdsProject edsProject) {
        this.edsProject = edsProject;
    }

    /**
     * Function returns EDS user by admin Id
     * 
     * @return EdsUser by Admin Id
     */
    @XmlElement(name = "admin")
    public EdsUser getEdsUserByEdsAdminId() {
        return this.edsUserByEdsAdminId;
    }

    /**
     * Function to set edsUserByEdsAdminId
     * 
     * @param edsUserByEdsAdminId EdsUser
     */
    public void setEdsUserByEdsAdminId(EdsUser edsUserByEdsAdminId) {
        this.edsUserByEdsAdminId = edsUserByEdsAdminId;
    }

    /**
     * Function returns edsUserByEdsAffectationUserId
     * 
     * @return EdsUser By Affectation User Id
     */
    @XmlElement(name = "affectation")
    public EdsUser getEdsUserByEdsAffectationUserId() {
        return edsUserByEdsAffectationUserId;
    }

    /**
     * Function to set edsUserByEdsAffectationUserId
     * 
     * @param edsUserByEdsAffectationUserId EdsUser
     */
    public void setEdsUserByEdsAffectationUserId(EdsUser edsUserByEdsAffectationUserId) {
        this.edsUserByEdsAffectationUserId = edsUserByEdsAffectationUserId;
    }

    /**
     * Function returns EdsComponentType
     * 
     * @return EdsComponentType
     */
    @XmlElement(name = "record-model")
    // ComponentType == Model Record
    public EdsComponentType getEdsComponentType() {
        return this.edsComponentType;
    }

    /**
     * Function to set EdsComponenetType
     * 
     * @param edsComponentType EdsComponentType
     */
    public void setEdsComponentType(EdsComponentType edsComponentType) {
        this.edsComponentType = edsComponentType;
    }

    /**
     * Function returns edsUserByEdsModifUserId
     * 
     * @return EdsUser By Eds Modified UserId
     */
    @XmlTransient
    public EdsUser getEdsUserByEdsModifUserId() {
        return edsUserByEdsModifUserId;
    }

    /**
     * Function to set edsUserByEdsModifUserId
     * 
     * @param edsUserByEdsModifUserId EdsUser
     */
    public void setEdsUserByEdsModifUserId(EdsUser edsUserByEdsModifUserId) {
        this.edsUserByEdsModifUserId = edsUserByEdsModifUserId;
    }

    /**
     * Function returns edsUserByEdsCreaUserId
     * 
     * @return EdsUser By Eds Created UserId
     */
    @XmlTransient
    public EdsUser getEdsUserByEdsCreaUserId() {
        return edsUserByEdsCreaUserId;
    }

    /**
     * Function to set edsUserByEdsCreaUserId
     * 
     * @param edsUserByEdsCreaUserId EdsUser
     */
    public void setEdsUserByEdsCreaUserId(EdsUser edsUserByEdsCreaUserId) {
        this.edsUserByEdsCreaUserId = edsUserByEdsCreaUserId;
    }

    /**
     * Function returns EDS reference
     * 
     * @return EDS reference
     */
    @XmlElement(name = "ref")
    public String getEdsRef() {
        return this.edsRef;
    }

    /**
     * Function set Eds reference
     * 
     * @param edsRef String specifying eds reference
     */
    public void setEdsRef(String edsRef) {
        this.edsRef = edsRef;
    }

    /**
     * Function returns Eds major version
     * 
     * @return Eds Major version
     */
    @XmlElement(name = "major-version")
    public int getEdsMajorVersion() {
        return edsMajorVersion;
    }

    /**
     * Function to set Eds major version
     * 
     * @param edsMajorVersion Eds Major version
     */
    public void setEdsMajorVersion(int edsMajorVersion) {
        this.edsMajorVersion = edsMajorVersion;
    }

    /**
     * Function returns Eds minor version
     * 
     * @return Eds minor version
     */
    @XmlElement(name = "minor-version")
    public int getEdsMinorVersion() {
        return edsMinorVersion;
    }

    /**
     * Function to set Eds minor version
     * 
     * @param edsMinorVersion Eds minor version
     */
    public void setEdsMinorVersion(int edsMinorVersion) {
        this.edsMinorVersion = edsMinorVersion;
    }

    /**
     * Function returns Eds create date
     * 
     * @return Eds create date
     */
    @XmlElement(name = "crea-date")
    public Date getEdsCreaDate() {
        return this.edsCreaDate;
    }

    /**
     * Function to set EDS create date
     * 
     * @param edsCreaDate Eds create date
     */
    public void setEdsCreaDate(Date edsCreaDate) {
        this.edsCreaDate = edsCreaDate;
    }

    /**
     * Function returns Eds modified date
     * 
     * @return Eds modified date
     */
    @XmlElement(name = "modif-date")
    public Date getEdsModifDate() {
        return this.edsModifDate;
    }

    /**
     * Function to set Eds modified date
     * 
     * @param edsModifDate Eds modified date
     */
    public void setEdsModifDate(Date edsModifDate) {
        this.edsModifDate = edsModifDate;
    }

    /**
     * Function returns edsDriftValidationDate
     * 
     * @return Eds drift validation date
     */
    @XmlElement(name = "drift-validation-date")
    public Date getEdsDriftValidationDate() {
        return edsDriftValidationDate;
    }

    /**
     * Function to set edsDriftValidationDate
     * 
     * @param edsDriftValidationDate Eds drift validation date
     */
    public void setEdsDriftValidationDate(Date edsDriftValidationDate) {
        this.edsDriftValidationDate = edsDriftValidationDate;
    }

    /**
     * Function returns Edsname
     * 
     * @return Eds name
     */
    @XmlElement(name = "name")
    public String getEdsName() {
        return this.edsName;
    }

    /**
     * Function to set Eds name
     * 
     * @param edsName Eds name
     */
    public void setEdsName(String edsName) {
        this.edsName = edsName;
    }

    /**
     * Function returns Eds description
     * 
     * @return Eds description
     */
    @XmlElement(name = "description")
    public String getEdsDescription() {
        return this.edsDescription;
    }

    /**
     * Function to set Eds description
     * 
     * @param edsName Eds description
     */
    public void setEdsDescription(String edsDescription) {
        this.edsDescription = edsDescription;
    }

    /**
     * Function returns Eds validation level
     * 
     * @return Eds validation level
     */
    @XmlElement(name = "validation-level")
    public Integer getEdsValidLvl() {
        return this.edsValidLvl;
    }

    /**
     * Function to set Eds validation level
     * 
     * @param edsValidLvl Eds validation level
     */
    public void setEdsValidLvl(Integer edsValidLvl) {
        this.edsValidLvl = edsValidLvl;
    }

    /**
     * Function returns Subtype 1
     * 
     * @return Subtype 1
     */
    @XmlElement(name = "subtype-1")
    public Integer getEdsSubtype1() {
        return this.edsSubtype1;
    }

    /**
     * Function to set Subtype 1
     * 
     * @param edsSubtype1 Subtype 1
     */
    public void setEdsSubtype1(Integer edsSubtype1) {
        this.edsSubtype1 = edsSubtype1;
    }

    /**
     * Function returns Subtype 2
     * 
     * @return Subtype 2
     */
    @XmlElement(name = "subtype-2")
    public Integer getEdsSubtype2() {
        return this.edsSubtype2;
    }

    /**
     * Function to set Subtype 2
     * 
     * @param edsSubtype2 Subtype 2
     */
    public void setEdsSubtype2(Integer edsSubtype2) {
        this.edsSubtype2 = edsSubtype2;
    }

    /**
     * Function returns BT/TBT
     * 
     * @return int representing BT/TBT
     */
    @XmlElement(name = "is-bttbt")
    public int getEdsIsBttbt() {
        return this.edsIsBttbt;
    }

    /**
     * Function to set BT/TBT
     * 
     * @param edsIsBttbt int representing BT/TBT
     */
    public void setEdsIsBttbt(int edsIsBttbt) {
        this.edsIsBttbt = edsIsBttbt;
    }

    /**
     * Function to check if BT/TBT
     * 
     * @return check if BT/TBT
     */
    public boolean isBttbt() {
        return edsIsBttbt == IS_BTTBT;
    }

    /**
     * Function to get Eds state
     * 
     * @return Eds state
     */
    @XmlElement(name = "state")
    public Integer getEdsState() {
        return this.edsState;
    }

    /**
     * Function to set Eds state
     * 
     * @param edsState Eds state
     */
    public void setEdsState(int edsState) {
        this.edsState = edsState;
    }

    /**
     * Function to get project launch count
     * 
     * @return project launch count
     */
    @XmlElement(name = "project-setter-count")
    public Integer getEdsPLaunchCount() {
        return this.edsPLaunchCount;
    }

    /**
     * Function to set project launch count
     * 
     * @param edsPLaunchCount project launch count
     */
    public void setEdsPLaunchCount(Integer edsPLaunchCount) {
        this.edsPLaunchCount = edsPLaunchCount;
    }

    /**
     * Function to get comment
     * 
     * @return Comment
     */
    @XmlElement(name = "comments")
    public String getEdsComments() {
        return this.edsComments;
    }

    /**
     * Function to set comment
     * 
     * @param edsComments comment
     */
    public void setEdsComments(String edsComments) {
        this.edsComments = edsComments;
    }

    /**
     * Function returns if Eds has drift
     * 
     * @return check if Eds has drift
     */
    @XmlElement(name = "drift")
    public int getEdsHasDrift() {
        return edsHasDrift;
    }

    /**
     * Function to set if Eds having drift
     * 
     * @param edsHasDrift Int value specifying Eds drift
     */
    public void setEdsHasDrift(int edsHasDrift) {
        this.edsHasDrift = edsHasDrift;
    }

    /**
     * Function returns set of EdsNumber96k
     * 
     * @return set of EdsNumber96k
     */
    @XmlElement(name = "number96k")
    @XmlElementWrapper(name = "numbers96k")
    public Set<EdsNumber96k> getEdsNumber96ks() {
        return this.edsNumber96ks;
    }

    /**
     * Function define set of EdsNumber96k
     * 
     * @param edsNumber96ks set of EdsNumber96k
     */
    public void setEdsNumber96ks(Set<EdsNumber96k> edsNumber96ks) {
        this.edsNumber96ks = edsNumber96ks;
    }

    /**
     * Function returns set of EdsNumber96FCT
     * 
     * @return set of EdsNumber96FCT
     */
    @XmlTransient
    public Set<EdsSAPReference> getEdsNumber96fcts() {
        return this.edsNumber96fcts;
    }

    /**
     * Function define set of EdsNumber96FCT
     * 
     * @param edsNumber96ks set of EdsNumber96FCT
     */
    public void setEdsNumber96fcts(Set<EdsSAPReference> edsNumber96fcts) {
        this.edsNumber96fcts = edsNumber96fcts;
    }

    /**
     * Function returns set of EdsNumber96FNR
     * 
     * @return set of EdsNumber96FNR
     */
    @XmlTransient
    public Set<EdsSAPReference> getEdsNumber96fnrs() {
        return this.edsNumber96fnrs;
    }

    /**
     * Function define set of EdsNumber96FNR
     * 
     * @param edsNumber96ks set of EdsNumber96FNR
     */
    public void setEdsNumber96fnrs(Set<EdsSAPReference> edsNumber96fnrs) {
        this.edsNumber96fnrs = edsNumber96fnrs;

    }

    /**
     * Function returns set of EdsPerimeter
     * 
     * @return set of EdsPerimeter
     */
    @XmlElement(name = "perimeter")
    @XmlElementWrapper(name = "perimeters")
    public Set<EdsPerimeter> getEdsPerimeters() {
        return this.edsPerimeters;
    }

    /**
     * Function to define set of EdsPerimeter
     * 
     * @param edsPerimeters set of EdsPerimeter
     */
    public void setEdsPerimeters(Set<EdsPerimeter> edsPerimeters) {
        this.edsPerimeters = edsPerimeters;
    }

    /**
     * Function returns set of EdsProjectEds
     * 
     * @return set of EdsProjectEds
     */
    @XmlElement(name = "follower-project")
    @XmlElementWrapper(name = "follower-projects")
    public Set<EdsProjectEds> getEdsProjectEdses() {
        return this.edsProjectEdses;
    }

    /**
     * Function to define set of EdsProjectEds
     * 
     * @param edsProjectEdses set of EdsProjectEds
     */
    public void setEdsProjectEdses(Set<EdsProjectEds> edsProjectEdses) {
        this.edsProjectEdses = edsProjectEdses;
    }

    /**
     * Function returns set of EdsDriftInfo
     * 
     * @return Set of EdsDriftInfo
     */
    @XmlTransient
    public Set<EdsDriftInfo> getEdsDriftInfos() {
        return edsDriftInfos;
    }

    /**
     * Function to define Set of EdsDriftInfo
     * 
     * @param edsDriftInfos Set of EdsDriftInfo
     */
    public void setEdsDriftInfos(Set<EdsDriftInfo> edsDriftInfos) {
        this.edsDriftInfos = edsDriftInfos;
    }

    /**
     * Function to get short version
     * 
     * @return short version
     */
    public String getVersionShort() {
        return edsMajorVersion + "." + edsMinorVersion;
    }

    /**
     * Function to get long version
     * 
     * @return long version
     */
    public String getVersionLong() {
        return "v" + edsMajorVersion + '.' + edsMinorVersion;
    }

    /**
     * Function returns Eds reference implicitly
     * 
     * @return Eds reference implicitly
     */
    public String toImplicitRef() {
        if (edsState == FROZEN_STATE) {
            return edsRef + " (" + getVersionLong() + ')';
        } else {
            return edsRef;
        }
    }

    /**
     * Function returns Eds reference Explicitly
     * 
     * @return Eds reference Explicitly
     */
    public String toExplicitRef() {
        return edsRef + " (" + getVersionLong() + ')';
    }

    /**
     * Function returns EDS implicit name
     * 
     * @return EDS implicit name
     */
    public String toImplicitName() {
        if (edsState == FROZEN_STATE) {
            return edsName + " (" + getVersionLong() + ')';
        } else {
            return edsName;
        }
    }

    /**
     * Function to get EDS explicit name
     * 
     * @return EDS explicit name
     */
    public String toExplicitName() {
        return edsName + " (" + getVersionLong() + ')';
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsEds other = (EdsEds) obj;
        if ((this.edsId == null) ? (other.edsId != null) : !this.edsId.equals(other.edsId)) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.edsId != null ? this.edsId.hashCode() : 0);
        return hash;
    }

    /**
     * Function returns list of validation levels
     * 
     * @return list of validation levels
     */
    public static List<Integer> getAllValidationLevels() {
        return Arrays.asList(VALIDATION_LVL_LOW, VALIDATION_LVL_HIGH);
    }

    /**
     * Function to get Text representation for validation level
     * 
     * @param validationLevel Validation level
     * @return Text representation for validation level
     */
    public static String getValidationLevelText(int validationLevel) {
        switch (validationLevel) {
        case VALIDATION_LVL_LOW:
            return "eds-validation-level-low";
        case VALIDATION_LVL_HIGH:
            return "eds-validation-level-heigh";
        default:
            return null;
        }
    }

    /**
     * Function to get Text representation for BT/TBT
     * 
     * @param btTbt BT/TBT
     * @return Text representation for BT/TBT
     */
    public static String getBtTbtText(int btTbt) {
        switch (btTbt) {
        case IS_BTTBT:
            return "OUI";
        case IS_NOT_BTTBT:
            return "NON";
        default:
            return null;
        }
    }

    @XmlElement(name = "chs")
    public Set<Chs> getEdsChs() {
        return edsChs;
    }

    public void setEdsChs(Set<Chs> edsChs) {
        this.edsChs = edsChs;
    }

    @XmlElement(name = "pins-connect")
    public Set<EdsPinConnect> getEdsPinConnect() {
        return edsPinConnect;
    }

    public void setEdsPinConnect(Set<EdsPinConnect> edsPinConnect) {
        this.edsPinConnect = edsPinConnect;
    }

    public Set<EdsPinTypeComment> getEdsTypeComment() {
        return edsTypeComment;
    }

    public void setEdsTypeComment(Set<EdsPinTypeComment> edsTypeComment) {
        this.edsTypeComment = edsTypeComment;
    }

    public void setEdsBsx(Set<EdsBsx> bsx) {
        this.edsBsx = bsx;
    }

    @XmlTransient
    public Set<EdsBsx> getEdsBsx() {
        return edsBsx;
    }

    @XmlElement(name = "eds-bsx")
    public EdsBsx getEdsBsxUnique() {
        if (edsBsx.isEmpty())
            return null;
        else
            return edsBsx.iterator().next();
    }

    public void setEdsBsxUnique(EdsBsx bsx) {
        this.edsBsx.clear();
        this.edsBsx.add(bsx);
    }
}
