package com.inetpsa.eds.dao.model;

// Generated 23 avr. 2013 16:19:05 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * EdsGroundConsolidateCurent generated by hbm2java
 */
public class EdsGroundConsolidateCurent implements java.io.Serializable {
    /**
     * Constant to hold value of SOMME_ALIM
     */
    public final static int SOMME_ALIM = 0;
    /**
     * Constant to hold value of COPIE_ALIM
     */
    public final static int COPIE_ALIM = 1;
    /**
     * Constant to hold value of AUTRE
     */
    public final static int AUTRE = 2;
    /**
     * String Variable to hold the value for Column GCC_ID of Table OPLQTGCC
     */
    private String gccId;
    /**
     * String Variable to hold the value for Column GCC_CHOIX_MASSE of Table OPLQTGCC
     */
    private Integer gccChoixMasse;
    /**
     * String Variable to hold the value for Column GCC_UMAX of Table OPLQTGCC
     */
    private Float gccUmax;
    /**
     * Set Collection to hold the values for Table OPLQTGRC
     */
    private Set<EdsGroundConsolidate> edsGroundConsolidates = new HashSet<EdsGroundConsolidate>(0);

    /**
     * Default Constructor
     */
    public EdsGroundConsolidateCurent() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param gccId
     */
    public EdsGroundConsolidateCurent(String gccId) {
        this.gccId = gccId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param curent
     */
    public EdsGroundConsolidateCurent(EdsGroundConsolidateCurent curent) {
        this.gccId = UUID.randomUUID().toString();
        this.gccChoixMasse = curent.gccChoixMasse;
        this.gccUmax = curent.gccUmax;
        for (EdsGroundConsolidate egc : curent.edsGroundConsolidates) {
            this.edsGroundConsolidates.add(new EdsGroundConsolidate(egc));
        }
    }

    /**
     * Function to get gccId
     * 
     * @return the Value of gccId
     */
    public String getGccId() {
        return this.gccId;
    }

    /**
     * Function to set gccId
     * 
     * @param gccId
     */
    public void setGccId(String gccId) {
        this.gccId = gccId;
    }

    /**
     * Function to get gccChoixMasse
     * 
     * @return the Value of gccChoixMasse
     */
    public Integer getGccChoixMasse() {
        return this.gccChoixMasse;
    }

    /**
     * Function to set gccChoixMasse
     * 
     * @param gccChoixMasse
     */
    public void setGccChoixMasse(Integer gccChoixMasse) {
        this.gccChoixMasse = gccChoixMasse;
    }

    /**
     * Function to get gccUmax
     * 
     * @return the Value of gccUmax
     */
    public Float getGccUmax() {
        return this.gccUmax;
    }

    /**
     * Function to set gccUmax
     * 
     * @param gccComment
     */
    public void setGccUmax(Float gccComment) {
        this.gccUmax = gccComment;
    }

    /**
     * Function to get edsGroundConsolidates
     * 
     * @return the Value of
     */
    public Set<EdsGroundConsolidate> getEdsGroundConsolidates() {
        return this.edsGroundConsolidates;
    }

    /**
     * Function to set edsGroundConsolidates
     * 
     * @param edsGroundConsolidates
     */
    public void setEdsGroundConsolidates(Set<EdsGroundConsolidate> edsGroundConsolidates) {
        this.edsGroundConsolidates = edsGroundConsolidates;
    }

    /**
     * Function to check if EdsGroundConsolidate title already exist
     * 
     * @param name Name to check
     * @return check if EdsGroundConsolidate title already exist
     */
    public boolean exist(String name) {
        for (EdsGroundConsolidate egc : edsGroundConsolidates) {
            if (name.equals(egc.getGedsTitle())) {
                return true;
            }
        }
        return false;

    }
}
