package com.inetpsa.eds.dao.model;

// Generated 29 ao�t 2012 15:29:49 by Hibernate Tools 3.2.1.GA

import java.util.UUID;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsGroundRobustCurent generated by hbm2java
 */
@XmlType
public class EdsGroundRobustCurent implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column GRC_ID of Table OPLQTRRC
     */
    private String grcId;
    /**
     * String Variable to hold the value for Column GSEDS_TITRE_MASSE of Table OPLQTRRC
     */
    private String gsedsTitreMasse;
    /**
     * String Variable to hold the value for Column GSEDS_I_VEILLE of Table OPLQTRRC
     */
    private Float gsedsIVeille;
    /**
     * String Variable to hold the value for Column GSEDS_I_REVEILLE_INACTIF of Table OPLQTRRC
     */
    private Float gsedsIReveilleInactif;
    /**
     * String Variable to hold the value for Column GSEDS_I_NOM_STAB of Table OPLQTRRC
     */
    private Float gsedsINomStab;
    /**
     * String Variable to hold the value for Column GSEDS_I_PIRECAS_STAB of Table OPLQTRRC
     */
    private Float gsedsIPirecasStab;
    /**
     * String Variable to hold the value for Column GSEDS_I_MST of Table OPLQTRRC
     */
    private Float gsedsIMst;
    /**
     * String Variable to hold the value for Column GSEDS_I_DELTA_T_MST of Table OPLQTRRC
     */
    private Float gsedsIDeltaTMst;
    /**
     * String Variable to hold the value for Column GSEDS_I_PIC of Table OPLQTRRC
     */
    private Float gsedsIPic;
    /**
     * String Variable to hold the value for Column GSEDS_T_IPIC of Table OPLQTRRC
     */
    private Float gsedsTIpic;
    /**
     * String Variable to hold the value for Column GSEDS_I_VEILLE_IFORM_BY of Table OPLQTRRC
     */
    private String gsedsIVeilleIformBy;
    /**
     * String Variable to hold the value for Column GSEDS_REVEILLE_IFORM_BY of Table OPLQTRRC
     */
    private String gsedsReveilleIformBy;
    /**
     * String Variable to hold the value for Column GSEDS_I_NOM_STAB_IFORM_BY of Table OPLQTRRC
     */
    private String gsedsINomStabIformBy;
    /**
     * String Variable to hold the value for Column GSEDS_I_PIRECAS_STAB_IFORM_BY of Table OPLQTRRC
     */
    private String gsedsIPirecasStabIformBy;
    /**
     * String Variable to hold the value for Column GSEDS_I_PIC_IFORM_BY of Table OPLQTRRC
     */
    private String gsedsIPicIformBy;
    /**
     * String Variable to hold the value for Column GSEDS_T_IPIC_IFORM_BY of Table OPLQTRRC
     */
    private String gsedsTIPicIformBy;
    /**
     * String Variable to hold the value for Column GSEDS_I_VEILLE_COMMENT of Table OPLQTRRC
     */
    private String gsedsIVeilleComment;
    /**
     * String Variable to hold the value for Column GSEDS_REVEILLE_COMMENT of Table OPLQTRRC
     */
    private String gsedsReveilleComment;
    /**
     * String Variable to hold the value for Column GSEDS_I_NOM_STAB_COMMENT of Table OPLQTRRC
     */
    private String gsedsINomStabComment;
    /**
     * String Variable to hold the value for Column GSEDS_I_PIRECAS_COMMENT of Table OPLQTRRC
     */
    private String gsedsIPirecasComment;
    /**
     * String Variable to hold the value for Column GSEDS_I_PIC_COMMENT of Table OPLQTRRC
     */
    private String gsedsIPicComment;
    /**
     * String Variable to hold the value for Column GSEDS_T_IPIC_COMMENT of Table OPLQTRRC
     */
    private String gsedsTIPicComment;

    // New values
    /**
     * Variable to hold the value for Column GSEDS_T_NOM_STAB of Table OPLQTRRC
     */
    private Float gsedsTnomStab;
    /**
     * Variable to hold the value for Column GSEDS_T_PIRE_CAS of Table OPLQTRRC
     */
    private Float gsedsTpireCas;
    /**
     * Variable to hold the value for Column GSEDS_I_DYSF of Table OPLQTRRC
     */
    private Float gsedsIdysf;
    /**
     * Variable to hold the value for Column GSEDS_T_DYSF of Table OPLQTRRC
     */
    private Float gsedsTdysf;
    /**
     * Variable to hold the value for Column GSEDS_I_MST of Table OPLQTRRC
     */
    private Float gsedsImst;
    /**
     * Variable to hold the value for Column GSEDS_T_MST of Table OPLQTRRC
     */
    private Float gsedsTmst;
    /**
     * Variable to hold the value for Column GSEDS_T_NOM_STAB_INFORM_BY of Table OPLQTRRC
     */
    private String gsedsTnomStabInformBy;
    /**
     * Variable to hold the value for Column GSEDS_T_PIRE_CAS_INFORM_BY of Table OPLQTRRC
     */
    private String gsedsTpireCasInformBy;
    /**
     * Variable to hold the value for Column GSEDS_I_DYSF_INFORM_BY of Table OPLQTRRC
     */
    private String gsedsIdysfInformBy;
    /**
     * Variable to hold the value for Column GSEDS_T_DYSF_INFORM_BY of Table OPLQTRRC
     */
    private String gsedsTdysfInformBy;
    /**
     * Variable to hold the value for Column GSEDS_I_MST_INFORM_BY of Table OPLQTRRC
     */
    private String gsedsImstInformBy;
    /**
     * Variable to hold the value for Column GSEDS_T_MST_INFORM_BY of Table OPLQTRRC
     */
    private String gsedsTmstInformBy;
    /**
     * Variable to hold the value for Column GSEDS_T_NOM_STAB_COMMENT of Table OPLQTRRC
     */
    private String gsedsTnomStabComment;
    /**
     * Variable to hold the value for Column GSEDS_T_PIRE_CAS_COMMENT of Table OPLQTRRC
     */
    private String gsedsTpireCasComment;
    /**
     * Variable to hold the value for Column GSEDS_I_DYSF_COMMENT of Table OPLQTRRC
     */
    private String gsedsIdysfComment;
    /**
     * Variable to hold the value for Column GSEDS_T_DYSF_COMMENT of Table OPLQTRRC
     */
    private String gsedsTdysfComment;
    /**
     * Variable to hold the value for Column GSEDS_I_MST_COMMENT of Table OPLQTRRC
     */
    private String gsedsImstComment;
    /**
     * Variable to hold the value for Column GSEDS_T_MST_COMMENT of Table OPLQTRRC
     */
    private String gsedsTmstComment;

    /**
     * Default Constructor
     */
    public EdsGroundRobustCurent() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param grcId
     */
    public EdsGroundRobustCurent(String grcId) {
        this.grcId = grcId;
    }

    /**
     * Parameterized constructor
     */
    public EdsGroundRobustCurent(String grcId, String gsedsTitreMasse, Float gsedsIVeille, Float gsedsIReveilleInactif, Float gsedsINomStab,
            Float gsedsIPirecasStab, Float gsedsIMst, Float gsedsIDeltaTMst, Float gsedsIPic, Float gsedsTIpic, String gsedsIVeilleIformBy,
            String gsedsReveilleIformBy, String gsedsINomStabIformBy, String gsedsIPirecasStabIformBy, String gsedsIPicIformBy,
            String gsedsTIPicIformBy, String gsedsIVeilleComment, String gsedsReveilleComment, String gsedsINomStabComment,
            String gsedsIPirecasComment, String gsedsIPicComment, String gsedsTIPicComment, Float gsedsTnomStab, Float gsedsTpireCas,
            Float gsedsIdysf, Float gsedsTdysf, Float gsedsImst2, Float gsedsTmst, String gsedsTnomStabInformBy, String gsedsTpireCasInformBy,
            String gsedsIdysfInformBy, String gsedsTdysfInformBy, String gsedsImstInformBy, String gsedsTmstInformBy, String gsedsTnomStabComment,
            String gsedsTpireCasComment, String gsedsIdysfComment, String gsedsTdysfComment, String gsedsImstComment, String gsedsTmstComment) {

        this.grcId = grcId;
        this.gsedsTitreMasse = gsedsTitreMasse;
        this.gsedsIVeille = gsedsIVeille;
        this.gsedsIReveilleInactif = gsedsIReveilleInactif;
        this.gsedsINomStab = gsedsINomStab;
        this.gsedsIPirecasStab = gsedsIPirecasStab;
        this.gsedsIMst = gsedsIMst;
        this.gsedsIDeltaTMst = gsedsIDeltaTMst;
        this.gsedsIPic = gsedsIPic;
        this.gsedsTIpic = gsedsTIpic;
        this.gsedsIVeilleIformBy = gsedsIVeilleIformBy;
        this.gsedsReveilleIformBy = gsedsReveilleIformBy;
        this.gsedsINomStabIformBy = gsedsINomStabIformBy;
        this.gsedsIPirecasStabIformBy = gsedsIPirecasStabIformBy;
        this.gsedsIPicIformBy = gsedsIPicIformBy;
        this.gsedsTIPicIformBy = gsedsTIPicIformBy;
        this.gsedsIVeilleComment = gsedsIVeilleComment;
        this.gsedsReveilleComment = gsedsReveilleComment;
        this.gsedsINomStabComment = gsedsINomStabComment;
        this.gsedsIPirecasComment = gsedsIPirecasComment;
        this.gsedsIPicComment = gsedsIPicComment;
        this.gsedsTIPicComment = gsedsTIPicComment;
        this.gsedsTnomStab = gsedsTnomStab;
        this.gsedsTpireCas = gsedsTpireCas;
        this.gsedsIdysf = gsedsIdysf;
        this.gsedsTdysf = gsedsTdysf;
        this.gsedsImst = gsedsImst2;
        this.gsedsTmst = gsedsTmst;
        this.gsedsTnomStabInformBy = gsedsTnomStabInformBy;
        this.gsedsTpireCasInformBy = gsedsTpireCasInformBy;
        this.gsedsIdysfInformBy = gsedsIdysfInformBy;
        this.gsedsTdysfInformBy = gsedsTdysfInformBy;
        this.gsedsImstInformBy = gsedsImstInformBy;
        this.gsedsTmstInformBy = gsedsTmstInformBy;
        this.gsedsTnomStabComment = gsedsTnomStabComment;
        this.gsedsTpireCasComment = gsedsTpireCasComment;
        this.gsedsIdysfComment = gsedsIdysfComment;
        this.gsedsTdysfComment = gsedsTdysfComment;
        this.gsedsImstComment = gsedsImstComment;
        this.gsedsTmstComment = gsedsTmstComment;
    }

    /**
     * Parameterized Constructor
     * 
     * @param otherGround
     */
    public EdsGroundRobustCurent(EdsGroundRobustCurent otherGround) {
        this.grcId = UUID.randomUUID().toString();
        this.gsedsTitreMasse = otherGround.gsedsTitreMasse;
        this.gsedsIVeille = otherGround.gsedsIVeille;
        this.gsedsIReveilleInactif = otherGround.gsedsIReveilleInactif;
        this.gsedsINomStab = otherGround.gsedsINomStab;
        this.gsedsIPirecasStab = otherGround.gsedsIPirecasStab;
        this.gsedsIMst = otherGround.gsedsIMst;
        this.gsedsIDeltaTMst = otherGround.gsedsIDeltaTMst;
        this.gsedsIVeilleIformBy = otherGround.gsedsIVeilleIformBy;
        this.gsedsReveilleIformBy = otherGround.gsedsReveilleIformBy;
        this.gsedsINomStabIformBy = otherGround.gsedsINomStabIformBy;
        this.gsedsIPirecasStabIformBy = otherGround.gsedsIPirecasStabIformBy;
        this.gsedsIVeilleComment = otherGround.gsedsIVeilleComment;
        this.gsedsReveilleComment = otherGround.gsedsReveilleComment;
        this.gsedsINomStabComment = otherGround.gsedsINomStabComment;
        this.gsedsIPirecasComment = otherGround.gsedsIPirecasComment;

        this.gsedsTnomStab = otherGround.gsedsTnomStab;
        this.gsedsTnomStabInformBy = otherGround.gsedsTnomStabInformBy;
        this.gsedsTnomStabComment = otherGround.gsedsTnomStabComment;
        this.gsedsTpireCas = otherGround.gsedsTpireCas;
        this.gsedsTpireCasInformBy = otherGround.gsedsTpireCasInformBy;
        this.gsedsTpireCasComment = otherGround.gsedsTpireCasComment;
        this.gsedsIdysf = otherGround.gsedsIdysf;
        this.gsedsIdysfInformBy = otherGround.gsedsIdysfInformBy;
        this.gsedsIdysfComment = otherGround.gsedsIdysfComment;
        this.gsedsTdysf = otherGround.gsedsTdysf;
        this.gsedsTdysfInformBy = otherGround.gsedsTdysfInformBy;
        this.gsedsTdysfComment = otherGround.gsedsTdysfComment;
        this.gsedsImst = otherGround.gsedsImst;
        this.gsedsImstInformBy = otherGround.gsedsImstInformBy;
        this.gsedsImstComment = otherGround.gsedsImstComment;
        this.gsedsTmst = otherGround.gsedsTmst;
        this.gsedsTmstInformBy = otherGround.gsedsTmstInformBy;
        this.gsedsTmstComment = otherGround.gsedsTmstComment;
    }

    /**
     * Function to get grcId
     * 
     * @return the Value of grcId
     */
    @XmlTransient
    public String getGrcId() {
        return this.grcId;
    }

    /**
     * Function to set grcId
     * 
     * @param grcId Id
     */
    public void setGrcId(String grcId) {
        this.grcId = grcId;
    }

    /**
     * Function to get gsedsTitreMasse
     * 
     * @return the Value of gsedsTitreMasse
     */
    @XmlElement(name = "name")
    public String getGsedsTitreMasse() {
        return this.gsedsTitreMasse;
    }

    /**
     * Function to set gsedsTitreMasse
     * 
     * @param gsedsTitreMasse Ground title
     */
    public void setGsedsTitreMasse(String gsedsTitreMasse) {
        this.gsedsTitreMasse = gsedsTitreMasse;
    }

    /**
     * Function to get gsedsIVeille
     * 
     * @return the Value of gsedsIVeille
     */
    @XmlElement(name = "i-standby")
    public Float getGsedsIVeille() {
        return this.gsedsIVeille;
    }

    /**
     * Function to set gsedsIVeille
     * 
     * @param gsedsIVeille Iasleep
     */
    public void setGsedsIVeille(Float gsedsIVeille) {
        this.gsedsIVeille = gsedsIVeille;
    }

    /**
     * Function to get gsedsIReveilleInactif
     * 
     * @return the Value of gsedsIReveilleInactif
     */
    @XmlElement(name = "i-wakeup-inactive")
    public Float getGsedsIReveilleInactif() {
        return this.gsedsIReveilleInactif;
    }

    /**
     * Function to set gsedsIReveilleInactif
     * 
     * @param gsedsIReveilleInactif Iawake mode non functioning mode
     */
    public void setGsedsIReveilleInactif(Float gsedsIReveilleInactif) {
        this.gsedsIReveilleInactif = gsedsIReveilleInactif;
    }

    /**
     * Function to get gsedsINomStab
     * 
     * @return the Value of gsedsINomStab
     */
    @XmlElement(name = "i-nom-stab")
    public Float getGsedsINomStab() {
        return this.gsedsINomStab;
    }

    /**
     * Function to set gsedsINomStab
     * 
     * @param gsedsINomStab Inom stab
     */
    public void setGsedsINomStab(Float gsedsINomStab) {
        this.gsedsINomStab = gsedsINomStab;
    }

    /**
     * Function to get gsedsIPirecasStab
     * 
     * @return the Value of gsedsIPirecasStab
     */
    @XmlElement(name = "i-worst-stab")
    public Float getGsedsIPirecasStab() {
        return this.gsedsIPirecasStab;
    }

    /**
     * Function to set gsedsIPirecasStab
     * 
     * @param gsedsIPirecasStab Iworst stab
     */
    public void setGsedsIPirecasStab(Float gsedsIPirecasStab) {
        this.gsedsIPirecasStab = gsedsIPirecasStab;
    }

    /**
     * Function to get gsedsIMst
     * 
     * @return the Value of gsedsIMst
     */
    @XmlElement(name = "i-mst")
    public Float getGsedsIMst() {
        return this.gsedsIMst;
    }

    /**
     * Function to set gsedsIMst
     * 
     * @param gsedsIMst Ipowered on
     */
    public void setGsedsIMst(Float gsedsIMst) {
        this.gsedsIMst = gsedsIMst;
    }

    /**
     * Function to get gsedsIDeltaTMst
     * 
     * @return the Value of gsedsIDeltaTMst
     */
    @XmlElement(name = "i-mst-delta-t")
    public Float getGsedsIDeltaTMst() {
        return this.gsedsIDeltaTMst;
    }

    /**
     * Function to set gsedsIDeltaTMst
     * 
     * @param gsedsIDeltaTMst Delta Ipowered on duration
     */
    public void setGsedsIDeltaTMst(Float gsedsIDeltaTMst) {
        this.gsedsIDeltaTMst = gsedsIDeltaTMst;
    }

    /**
     * Function to get gsedsIVeilleIformBy
     * 
     * @return the Value of gsedsIVeilleIformBy
     */
    @XmlTransient
    public String getGsedsIVeilleIformBy() {
        return this.gsedsIVeilleIformBy;
    }

    /**
     * Function to set gsedsIVeilleIformBy
     * 
     * @param gsedsIVeilleIformBy Iasleep Iform By
     */
    public void setGsedsIVeilleIformBy(String gsedsIVeilleIformBy) {
        this.gsedsIVeilleIformBy = gsedsIVeilleIformBy;
    }

    /**
     * Function to get gsedsReveilleIformBy
     * 
     * @return the Value of gsedsReveilleIformBy
     */
    @XmlTransient
    public String getGsedsReveilleIformBy() {
        return this.gsedsReveilleIformBy;
    }

    /**
     * Function to set gsedsReveilleIformBy
     * 
     * @param gsedsReveilleIformBy Iawake mode non functioning mode comment Iform By
     */
    public void setGsedsReveilleIformBy(String gsedsReveilleIformBy) {
        this.gsedsReveilleIformBy = gsedsReveilleIformBy;
    }

    /**
     * Function to get gsedsINomStabIformBy
     * 
     * @return the Value of gsedsINomStabIformBy
     */
    @XmlTransient
    public String getGsedsINomStabIformBy() {
        return this.gsedsINomStabIformBy;
    }

    /**
     * Function to set gsedsINomStabIformBy
     * 
     * @param gsedsINomStabIformBy Inom stab Iform By
     */
    public void setGsedsINomStabIformBy(String gsedsINomStabIformBy) {
        this.gsedsINomStabIformBy = gsedsINomStabIformBy;
    }

    /**
     * Function to get gsedsIPirecasStabIformBy
     * 
     * @return the Value of gsedsIPirecasStabIformBy
     */
    @XmlTransient
    public String getGsedsIPirecasStabIformBy() {
        return this.gsedsIPirecasStabIformBy;
    }

    /**
     * Function to set gsedsIPirecasStabIformBy
     * 
     * @param gsedsIPirecasStabIformBy Iworst stab Iform by
     */
    public void setGsedsIPirecasStabIformBy(String gsedsIPirecasStabIformBy) {
        this.gsedsIPirecasStabIformBy = gsedsIPirecasStabIformBy;
    }

    /**
     * Function to get gsedsIVeilleComment
     * 
     * @return the Value of gsedsIVeilleComment
     */
    @XmlElement(name = "i-standby-comment")
    public String getGsedsIVeilleComment() {
        return this.gsedsIVeilleComment;
    }

    /**
     * Function to set gsedsIVeilleComment
     * 
     * @param gsedsIVeilleComment Iasleep Comment
     */
    public void setGsedsIVeilleComment(String gsedsIVeilleComment) {
        this.gsedsIVeilleComment = gsedsIVeilleComment;
    }

    /**
     * Function to get gsedsReveilleComment
     * 
     * @return the Value of gsedsReveilleComment
     */
    @XmlElement(name = "i-wakeup-inactive-comment")
    public String getGsedsReveilleComment() {
        return this.gsedsReveilleComment;
    }

    /**
     * Function to set gsedsReveilleComment
     * 
     * @param gsedsReveilleComment Iawake mode non functioning mode comment
     */
    public void setGsedsReveilleComment(String gsedsReveilleComment) {
        this.gsedsReveilleComment = gsedsReveilleComment;
    }

    /**
     * Function to get gsedsINomStabComment
     * 
     * @return the Value of gsedsINomStabComment
     */
    @XmlElement(name = "i-nom-stab-comment")
    public String getGsedsINomStabComment() {
        return this.gsedsINomStabComment;
    }

    /**
     * Function to set gsedsINomStabComment
     * 
     * @param gsedsINomStabComment Inom stab comment
     */
    public void setGsedsINomStabComment(String gsedsINomStabComment) {
        this.gsedsINomStabComment = gsedsINomStabComment;
    }

    /**
     * Function to get gsedsIPirecasComment
     * 
     * @return the Value of gsedsIPirecasComment
     */
    @XmlElement(name = "i-worst-stab-comment")
    public String getGsedsIPirecasComment() {
        return this.gsedsIPirecasComment;
    }

    /**
     * Function to set gsedsIPirecasComment
     * 
     * @param gsedsIPirecasComment Iworst stab comment
     */
    public void setGsedsIPirecasComment(String gsedsIPirecasComment) {
        this.gsedsIPirecasComment = gsedsIPirecasComment;
    }

    /**
     * Function to get gsedsIPic
     * 
     * @return the Value of gsedsIPic
     */
    public Float getGsedsIPic() {
        return gsedsIPic;
    }

    /**
     * Function to set gsedsIPic
     * 
     * @param gsedsIPic Ipeak
     */
    public void setGsedsIPic(Float gsedsIPic) {
        this.gsedsIPic = gsedsIPic;
    }

    /**
     * Function to get gsedsIPicComment
     * 
     * @return the Value of gsedsIPicComment
     */
    public String getGsedsIPicComment() {
        return gsedsIPicComment;
    }

    /**
     * Function to set gsedsIPicComment
     * 
     * @param gsedsIPicComment Ipeak comment
     */
    public void setGsedsIPicComment(String gsedsIPicComment) {
        this.gsedsIPicComment = gsedsIPicComment;
    }

    /**
     * Function to get gsedsIPicIformBy
     * 
     * @return the Value of gsedsIPicIformBy
     */
    public String getGsedsIPicIformBy() {
        return gsedsIPicIformBy;
    }

    /**
     * Function to set gsedsIPicIformBy
     * 
     * @param gsedsIPicIformBy Ipeak Iform by
     */
    public void setGsedsIPicIformBy(String gsedsIPicIformBy) {
        this.gsedsIPicIformBy = gsedsIPicIformBy;
    }

    /**
     * Function to get gsedsTIPicComment
     * 
     * @return the Value of gsedsTIPicComment
     */
    public String getGsedsTIPicComment() {
        return gsedsTIPicComment;
    }

    /**
     * Function to set gsedsTIPicComment
     * 
     * @param gsedsTIPicComment TIpeak comment
     */
    public void setGsedsTIPicComment(String gsedsTIPicComment) {
        this.gsedsTIPicComment = gsedsTIPicComment;
    }

    /**
     * Function to get gsedsTIPicIformBy
     * 
     * @return the Value of gsedsTIPicIformBy
     */
    public String getGsedsTIPicIformBy() {
        return gsedsTIPicIformBy;
    }

    /**
     * Function to set gsedsTIPicIformBy
     * 
     * @param gsedsTIPicIformBy TIpeak Iform by
     */
    public void setGsedsTIPicIformBy(String gsedsTIPicIformBy) {
        this.gsedsTIPicIformBy = gsedsTIPicIformBy;
    }

    /**
     * Function to get gsedsTIpic
     * 
     * @return the Value of gsedsTIpic
     */
    public Float getGsedsTIpic() {
        return gsedsTIpic;
    }

    /**
     * Function to set gsedsTIpic
     * 
     * @param gsedsTIpic TIpic
     */
    public void setGsedsTIpic(Float gsedsTIpic) {
        this.gsedsTIpic = gsedsTIpic;
    }

    /**
     * Getter gsedsTnomStab
     * 
     * @return the gsedsTnomStab
     */
    public Float getGsedsTnomStab() {
        return gsedsTnomStab;
    }

    /**
     * Setter gsedsTnomStab
     * 
     * @param gsedsTnomStab the gsedsTnomStab to set
     */
    public void setGsedsTnomStab(Float gsedsTnomStab) {
        this.gsedsTnomStab = gsedsTnomStab;
    }

    /**
     * Getter gsedsTpireCas
     * 
     * @return the gsedsTpireCas
     */
    public Float getGsedsTpireCas() {
        return gsedsTpireCas;
    }

    /**
     * Setter gsedsTpireCas
     * 
     * @param gsedsTpireCas the gsedsTpireCas to set
     */
    public void setGsedsTpireCas(Float gsedsTpireCas) {
        this.gsedsTpireCas = gsedsTpireCas;
    }

    /**
     * Getter gsedsIdysf
     * 
     * @return the gsedsIdysf
     */
    public Float getGsedsIdysf() {
        return gsedsIdysf;
    }

    /**
     * Setter gsedsIdysf
     * 
     * @param gsedsIdysf the gsedsIdysf to set
     */
    public void setGsedsIdysf(Float gsedsIdysf) {
        this.gsedsIdysf = gsedsIdysf;
    }

    /**
     * Getter gsedsTdysf
     * 
     * @return the gsedsTdysf
     */
    public Float getGsedsTdysf() {
        return gsedsTdysf;
    }

    /**
     * Setter gsedsTdysf
     * 
     * @param gsedsTdysf the gsedsTdysf to set
     */
    public void setGsedsTdysf(Float gsedsTdysf) {
        this.gsedsTdysf = gsedsTdysf;
    }

    /**
     * Getter gsedsImst
     * 
     * @return the gsedsImst
     */
    public Float getGsedsImst() {
        return gsedsImst;
    }

    /**
     * Setter gsedsImst
     * 
     * @param gsedsImst the gsedsImst to set
     */
    public void setGsedsImst(Float gsedsImst) {
        this.gsedsImst = gsedsImst;
    }

    /**
     * Getter gsedsTmst
     * 
     * @return the gsedsTmst
     */
    public Float getGsedsTmst() {
        return gsedsTmst;
    }

    /**
     * Setter gsedsTmst
     * 
     * @param gsedsTmst the gsedsTmst to set
     */
    public void setGsedsTmst(Float gsedsTmst) {
        this.gsedsTmst = gsedsTmst;
    }

    /**
     * Getter gsedsTnomStabInformBy
     * 
     * @return the gsedsTnomStabInformBy
     */
    public String getGsedsTnomStabInformBy() {
        return gsedsTnomStabInformBy;
    }

    /**
     * Setter gsedsTnomStabInformBy
     * 
     * @param gsedsTnomStabInformBy the gsedsTnomStabInformBy to set
     */
    public void setGsedsTnomStabInformBy(String gsedsTnomStabInformBy) {
        this.gsedsTnomStabInformBy = gsedsTnomStabInformBy;
    }

    /**
     * Getter gsedsTpireCasInformBy
     * 
     * @return the gsedsTpireCasInformBy
     */
    public String getGsedsTpireCasInformBy() {
        return gsedsTpireCasInformBy;
    }

    /**
     * Setter gsedsTpireCasInformBy
     * 
     * @param gsedsTpireCasInformBy the gsedsTpireCasInformBy to set
     */
    public void setGsedsTpireCasInformBy(String gsedsTpireCasInformBy) {
        this.gsedsTpireCasInformBy = gsedsTpireCasInformBy;
    }

    /**
     * Getter gsedsIdysfInformBy
     * 
     * @return the gsedsIdysfInformBy
     */
    public String getGsedsIdysfInformBy() {
        return gsedsIdysfInformBy;
    }

    /**
     * Setter gsedsIdysfInformBy
     * 
     * @param gsedsIdysfInformBy the gsedsIdysfInformBy to set
     */
    public void setGsedsIdysfInformBy(String gsedsIdysfInformBy) {
        this.gsedsIdysfInformBy = gsedsIdysfInformBy;
    }

    /**
     * Getter gsedsTdysfInformBy
     * 
     * @return the gsedsTdysfInformBy
     */
    public String getGsedsTdysfInformBy() {
        return gsedsTdysfInformBy;
    }

    /**
     * Setter gsedsTdysfInformBy
     * 
     * @param gsedsTdysfInformBy the gsedsTdysfInformBy to set
     */
    public void setGsedsTdysfInformBy(String gsedsTdysfInformBy) {
        this.gsedsTdysfInformBy = gsedsTdysfInformBy;
    }

    /**
     * Getter gsedsImstInformBy
     * 
     * @return the gsedsImstInformBy
     */
    public String getGsedsImstInformBy() {
        return gsedsImstInformBy;
    }

    /**
     * Setter gsedsImstInformBy
     * 
     * @param gsedsImstInformBy the gsedsImstInformBy to set
     */
    public void setGsedsImstInformBy(String gsedsImstInformBy) {
        this.gsedsImstInformBy = gsedsImstInformBy;
    }

    /**
     * Getter gsedsTmstInformBy
     * 
     * @return the gsedsTmstInformBy
     */
    public String getGsedsTmstInformBy() {
        return gsedsTmstInformBy;
    }

    /**
     * Setter gsedsTmstInformBy
     * 
     * @param gsedsTmstInformBy the gsedsTmstInformBy to set
     */
    public void setGsedsTmstInformBy(String gsedsTmstInformBy) {
        this.gsedsTmstInformBy = gsedsTmstInformBy;
    }

    /**
     * Getter gsedsTnomStabComment
     * 
     * @return the gsedsTnomStabComment
     */
    public String getGsedsTnomStabComment() {
        return gsedsTnomStabComment;
    }

    /**
     * Setter gsedsTnomStabComment
     * 
     * @param gsedsTnomStabComment the gsedsTnomStabComment to set
     */
    public void setGsedsTnomStabComment(String gsedsTnomStabComment) {
        this.gsedsTnomStabComment = gsedsTnomStabComment;
    }

    /**
     * Getter gsedsTpireCasComment
     * 
     * @return the gsedsTpireCasComment
     */
    public String getGsedsTpireCasComment() {
        return gsedsTpireCasComment;
    }

    /**
     * Setter gsedsTpireCasComment
     * 
     * @param gsedsTpireCasComment the gsedsTpireCasComment to set
     */
    public void setGsedsTpireCasComment(String gsedsTpireCasComment) {
        this.gsedsTpireCasComment = gsedsTpireCasComment;
    }

    /**
     * Getter gsedsIdysfComment
     * 
     * @return the gsedsIdysfComment
     */
    public String getGsedsIdysfComment() {
        return gsedsIdysfComment;
    }

    /**
     * Setter gsedsIdysfComment
     * 
     * @param gsedsIdysfComment the gsedsIdysfComment to set
     */
    public void setGsedsIdysfComment(String gsedsIdysfComment) {
        this.gsedsIdysfComment = gsedsIdysfComment;
    }

    /**
     * Getter gsedsTdysfComment
     * 
     * @return the gsedsTdysfComment
     */
    public String getGsedsTdysfComment() {
        return gsedsTdysfComment;
    }

    /**
     * Setter gsedsTdysfComment
     * 
     * @param gsedsTdysfComment the gsedsTdysfComment to set
     */
    public void setGsedsTdysfComment(String gsedsTdysfComment) {
        this.gsedsTdysfComment = gsedsTdysfComment;
    }

    /**
     * Getter gsedsImstComment
     * 
     * @return the gsedsImstComment
     */
    public String getGsedsImstComment() {
        return gsedsImstComment;
    }

    /**
     * Setter gsedsImstComment
     * 
     * @param gsedsImstComment the gsedsImstComment to set
     */
    public void setGsedsImstComment(String gsedsImstComment) {
        this.gsedsImstComment = gsedsImstComment;
    }

    /**
     * Getter gsedsTmstComment
     * 
     * @return the gsedsTmstComment
     */
    public String getGsedsTmstComment() {
        return gsedsTmstComment;
    }

    /**
     * Setter gsedsTmstComment
     * 
     * @param gsedsTmstComment the gsedsTmstComment to set
     */
    public void setGsedsTmstComment(String gsedsTmstComment) {
        this.gsedsTmstComment = gsedsTmstComment;
    }

}
