package com.inetpsa.eds.dao.model;

// Generated 26 sept. 2012 11:30:10 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.inetpsa.eds.application.EdsApplicationController;
import com.inetpsa.eds.dao.I_FormData;
import com.inetpsa.eds.dao.I_ValidationFormData;

/**
 * EdsHighValidationFormData generated by hbm2java
 */
@XmlRootElement(name = "validation-form")
public class EdsHighValidationFormData implements I_ValidationFormData, Serializable {
    /**
     * String Variable to hold the value for Column HVFD_ID of Table OPLQTHVD
     */
    private String hvfdId;
    /**
     * Variable to hold the value for Column HVFD_DBEES_CLOSED_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdDbeesClosedId;
    /**
     * Variable to hold the value for Column HVFD_EDS_ID of Table OPLQTHVD
     */
    private EdsEds edsEds;
    /**
     * Variable to hold the value for Column HVFD_DBEED_CLOSED_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdDbeedClosedId;

    /**
     * Variable to hold the value for Column HVFD_DBEES_CONSOLIDATE_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdDbeesConsolidateId;
    /**
     * Variable to hold the value for Column HVFD_RE_ROBUST_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdReRobustId;
    /**
     * Variable to hold the value for Column HVFD_CADE_CLOSED_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdCadeClosedId;
    /**
     * Variable to hold the value for Column HVFD_CADE_CONSOLIDATE_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdCadeConsolidateId;
    /**
     * Variable to hold the value for Column HVFD_DBEED_CONSOLIDATE_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdDbeedConsolidateId;
    /**
     * Variable to hold the value for Column HVFD_RS_PRIMARY_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdRsPrimaryId;
    /**
     * Variable to hold the value for Column HVFD_SUPPLIER_DATA_ID of Table OPLQTHVD
     */
    private EdsValidation edsValidationByHvfdSupplierDataId;
    /**
     * int Variable to hold the value for Column HVFD_STAGE of Table OPLQTHVD
     */
    private int hvfdStage;

    /**
     * Default Constructor
     */
    public EdsHighValidationFormData() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param hvfdId Id
     * @param edsEds Eds details
     */
    public EdsHighValidationFormData(String hvfdId, EdsEds edsEds) {
        this.hvfdId = hvfdId;
        this.edsEds = edsEds;
        this.edsValidationByHvfdDbeesClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdDbeedClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdDbeesConsolidateId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdReRobustId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdCadeClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdCadeConsolidateId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdDbeedConsolidateId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdRsPrimaryId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByHvfdSupplierDataId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.hvfdStage = EdsApplicationController.PRELIM_STAGE;
    }

    /**
     * Parameterized Constructor
     * 
     * @param hvfdId Id
     * @param edsValidationByHvfdDbeesClosedId Closed dbees validation Id
     * @param edsEds Eds details
     * @param edsValidationByHvfdDbeedClosedId Closed dbeed validation Id
     * @param edsValidationByHvfdReConsolidateId Consolidated re validation Id
     * @param edsValidationByHvfdReClosedId Closed re validation Id
     * @param edsValidationByHvfdDbeesConsolidateId Consolidated dbees validation Id
     * @param edsValidationByHvfdReRobustId Robust re validation Id
     * @param edsValidationByHvfdCadeClosedId Closed cade validation Id
     * @param edsValidationByHvfdCadeConsolidateId Consolidated cade validation Id
     * @param edsValidationByHvfdDbeedConsolidateId Consolidated dbeed validation Id
     * @param edsValidationByHvfdRsPrimaryId Primary re validation Id
     * @param edsValidationByHvfdSupplierDataId Supplier data validation ID
     * @param hvfdStage Validation Stage
     */
    public EdsHighValidationFormData(String hvfdId, EdsValidation edsValidationByHvfdDbeesClosedId, EdsEds edsEds,
            EdsValidation edsValidationByHvfdDbeedClosedId, EdsValidation edsValidationByHvfdDbeesConsolidateId,
            EdsValidation edsValidationByHvfdReRobustId, EdsValidation edsValidationByHvfdCadeClosedId,
            EdsValidation edsValidationByHvfdCadeConsolidateId, EdsValidation edsValidationByHvfdDbeedConsolidateId,
            EdsValidation edsValidationByHvfdRsPrimaryId, EdsValidation edsValidationByHvfdSupplierDataId, int hvfdStage) {
        this.hvfdId = hvfdId;
        this.edsValidationByHvfdDbeesClosedId = edsValidationByHvfdDbeesClosedId;
        this.edsEds = edsEds;
        this.edsValidationByHvfdDbeedClosedId = edsValidationByHvfdDbeedClosedId;
        this.edsValidationByHvfdDbeesConsolidateId = edsValidationByHvfdDbeesConsolidateId;
        this.edsValidationByHvfdReRobustId = edsValidationByHvfdReRobustId;
        this.edsValidationByHvfdCadeClosedId = edsValidationByHvfdCadeClosedId;
        this.edsValidationByHvfdCadeConsolidateId = edsValidationByHvfdCadeConsolidateId;
        this.edsValidationByHvfdDbeedConsolidateId = edsValidationByHvfdDbeedConsolidateId;
        this.edsValidationByHvfdRsPrimaryId = edsValidationByHvfdRsPrimaryId;
        this.edsValidationByHvfdSupplierDataId = edsValidationByHvfdSupplierDataId;
        this.hvfdStage = hvfdStage;
    }

    /**
     * Function to get hvfdId
     * 
     * @return the Value of hvfdId
     */
    @XmlTransient
    public String getHvfdId() {
        return this.hvfdId;
    }

    /**
     * Function to set hvfdId
     * 
     * @param hvfdId
     */
    public void setHvfdId(String hvfdId) {
        this.hvfdId = hvfdId;
    }

    /**
     * Function to get edsValidationByHvfdDbeesClosedId
     * 
     * @return the Value of edsValidationByHvfdDbeesClosedId
     */
    @XmlElement(name = "closed-dbees-validation")
    public EdsValidation getEdsValidationByHvfdDbeesClosedId() {
        return this.edsValidationByHvfdDbeesClosedId;
    }

    /**
     * Function to set edsValidationByHvfdDbeesClosedId
     * 
     * @param edsValidationByHvfdDbeesClosedId
     */
    public void setEdsValidationByHvfdDbeesClosedId(EdsValidation edsValidationByHvfdDbeesClosedId) {
        this.edsValidationByHvfdDbeesClosedId = edsValidationByHvfdDbeesClosedId;
    }

    /**
     * Function to get edsEds
     * 
     * @return the Value of edsEds
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return this.edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function to get edsValidationByHvfdDbeedClosedId
     * 
     * @return the Value of edsValidationByHvfdDbeedClosedId
     */
    @XmlElement(name = "closed-dbeed-validation")
    public EdsValidation getEdsValidationByHvfdDbeedClosedId() {
        return this.edsValidationByHvfdDbeedClosedId;
    }

    /**
     * Function to set edsValidationByHvfdDbeedClosedId
     * 
     * @param edsValidationByHvfdDbeedClosedId
     */
    public void setEdsValidationByHvfdDbeedClosedId(EdsValidation edsValidationByHvfdDbeedClosedId) {
        this.edsValidationByHvfdDbeedClosedId = edsValidationByHvfdDbeedClosedId;
    }

    /**
     * Function to get edsValidationByHvfdDbeesConsolidateId
     * 
     * @return the Value of edsValidationByHvfdDbeesConsolidateId
     */
    @XmlElement(name = "consolidated-dbees-validation")
    public EdsValidation getEdsValidationByHvfdDbeesConsolidateId() {
        return this.edsValidationByHvfdDbeesConsolidateId;
    }

    /**
     * Function to set edsValidationByHvfdDbeesConsolidateId
     * 
     * @param edsValidationByHvfdDbeesConsolidateId
     */
    public void setEdsValidationByHvfdDbeesConsolidateId(EdsValidation edsValidationByHvfdDbeesConsolidateId) {
        this.edsValidationByHvfdDbeesConsolidateId = edsValidationByHvfdDbeesConsolidateId;
    }

    /**
     * Function to get edsValidationByHvfdReRobustId
     * 
     * @return the Value of edsValidationByHvfdReRobustId
     */
    @XmlElement(name = "robust-re-validation")
    public EdsValidation getEdsValidationByHvfdReRobustId() {
        return this.edsValidationByHvfdReRobustId;
    }

    /**
     * Function to set edsValidationByHvfdReRobustId
     * 
     * @param edsValidationByHvfdReRobustId
     */
    public void setEdsValidationByHvfdReRobustId(EdsValidation edsValidationByHvfdReRobustId) {
        this.edsValidationByHvfdReRobustId = edsValidationByHvfdReRobustId;
    }

    /**
     * Function to get edsValidationByHvfdCadeClosedId
     * 
     * @return the Value of edsValidationByHvfdCadeClosedId
     */
    @XmlElement(name = "closed-cade-validation")
    public EdsValidation getEdsValidationByHvfdCadeClosedId() {
        return this.edsValidationByHvfdCadeClosedId;
    }

    /**
     * Function to set edsValidationByHvfdCadeClosedId
     * 
     * @param edsValidationByHvfdCadeClosedId
     */
    public void setEdsValidationByHvfdCadeClosedId(EdsValidation edsValidationByHvfdCadeClosedId) {
        this.edsValidationByHvfdCadeClosedId = edsValidationByHvfdCadeClosedId;
    }

    /**
     * Function to get edsValidationByHvfdCadeConsolidateId
     * 
     * @return the Value of edsValidationByHvfdCadeConsolidateId
     */
    @XmlElement(name = "consolidated-cade-validation")
    public EdsValidation getEdsValidationByHvfdCadeConsolidateId() {
        return this.edsValidationByHvfdCadeConsolidateId;
    }

    /**
     * Function to set edsValidationByHvfdCadeConsolidateId
     * 
     * @param edsValidationByHvfdCadeConsolidateId
     */
    public void setEdsValidationByHvfdCadeConsolidateId(EdsValidation edsValidationByHvfdCadeConsolidateId) {
        this.edsValidationByHvfdCadeConsolidateId = edsValidationByHvfdCadeConsolidateId;
    }

    /**
     * Function to get edsValidationByHvfdDbeedConsolidateId
     * 
     * @return the Value of edsValidationByHvfdDbeedConsolidateId
     */
    @XmlElement(name = "consolidated-dbeed-validation")
    public EdsValidation getEdsValidationByHvfdDbeedConsolidateId() {
        return this.edsValidationByHvfdDbeedConsolidateId;
    }

    /**
     * Function to set edsValidationByHvfdDbeedConsolidateId
     * 
     * @param edsValidationByHvfdDbeedConsolidateId
     */
    public void setEdsValidationByHvfdDbeedConsolidateId(EdsValidation edsValidationByHvfdDbeedConsolidateId) {
        this.edsValidationByHvfdDbeedConsolidateId = edsValidationByHvfdDbeedConsolidateId;
    }

    /**
     * Function to get edsValidationByHvfdRsPrimaryId
     * 
     * @return the Value of edsValidationByHvfdRsPrimaryId
     */
    @XmlElement(name = "preliminary-rs-validation")
    public EdsValidation getEdsValidationByHvfdRsPrimaryId() {
        return this.edsValidationByHvfdRsPrimaryId;
    }

    /**
     * Function to set edsValidationByHvfdRsPrimaryId
     * 
     * @param edsValidationByHvfdRsPrimaryId
     */
    public void setEdsValidationByHvfdRsPrimaryId(EdsValidation edsValidationByHvfdRsPrimaryId) {
        this.edsValidationByHvfdRsPrimaryId = edsValidationByHvfdRsPrimaryId;
    }

    /**
     * Function to get edsValidationByHvfdSupplierDataId
     * 
     * @return the Value of edsValidationByHvfdSupplierDataId
     */
    @XmlElement(name = "supplier-data-validation")
    public EdsValidation getEdsValidationByHvfdSupplierDataId() {
        return this.edsValidationByHvfdSupplierDataId;
    }

    /**
     * Function to set edsValidationByHvfdSupplierDataId
     * 
     * @param edsValidationByHvfdSupplierDataId
     */
    public void setEdsValidationByHvfdSupplierDataId(EdsValidation edsValidationByHvfdSupplierDataId) {
        this.edsValidationByHvfdSupplierDataId = edsValidationByHvfdSupplierDataId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.inetpsa.eds.dao.I_ValidationFormData#getPreliminaryStatus()
     */
    @Override
    public int getPreliminaryStatus() {
        return edsValidationByHvfdRsPrimaryId.getVStatus();
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.inetpsa.eds.dao.I_ValidationFormData#getRobustStatus()
     */
    @Override
    public int getRobustStatus() {
        return edsValidationByHvfdReRobustId.getVStatus();
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.inetpsa.eds.dao.I_ValidationFormData#getConsolidatedStatus()
     */
    @Override
    public int getConsolidatedStatus() {
        return Math.min(
                edsValidationByHvfdDbeesConsolidateId.getVStatus(),
                Math.min(edsValidationByHvfdDbeedConsolidateId.getVStatus(),
                        Math.min(edsValidationByHvfdCadeConsolidateId.getVStatus(), edsValidationByHvfdSupplierDataId.getVStatus())));
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.inetpsa.eds.dao.I_ValidationFormData#getClosedStatus()
     */
    @Override
    public int getClosedStatus() {
        return Math.min(edsValidationByHvfdDbeesClosedId.getVStatus(),
                Math.min(edsValidationByHvfdDbeedClosedId.getVStatus(), edsValidationByHvfdCadeClosedId.getVStatus()));
    }

    /**
     * Function returns high validation form data stage
     * 
     * @return high validation form data stage
     */
    @XmlTransient
    public int getHvfdStage() {
        return hvfdStage;
    }

    /**
     * Function to set high validation form data stage
     * 
     * @param hvfdStage high validation form data stage
     */
    public void setHvfdStage(int hvfdStage) {
        this.hvfdStage = hvfdStage;
    }

    /**
     * Function returns validation stage
     * 
     * @return validation stage
     */
    @XmlElement(name = "stage")
    @Override
    public int getValidationStage() {
        return getHvfdStage();
    }

    /**
     * Function reset the closed status
     */
    public void resetClosedStatus() {
        edsValidationByHvfdCadeClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        edsValidationByHvfdDbeedClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        edsValidationByHvfdDbeesClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
    }

    /**
     * Function to get copy of EdsHighValidationFormData
     * 
     * @param eds Eds details
     * @param copiesMap Map of ID and EdsValidation
     * @return EdsHighValidationFormData
     */
    public I_FormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        return new EdsHighValidationFormData(UUID.randomUUID().toString(), new EdsValidation(edsValidationByHvfdDbeesClosedId), eds,
                new EdsValidation(edsValidationByHvfdDbeedClosedId), new EdsValidation(edsValidationByHvfdDbeesConsolidateId), new EdsValidation(
                        edsValidationByHvfdReRobustId), new EdsValidation(edsValidationByHvfdCadeClosedId), new EdsValidation(
                        edsValidationByHvfdCadeConsolidateId), new EdsValidation(edsValidationByHvfdDbeedConsolidateId), new EdsValidation(
                        edsValidationByHvfdRsPrimaryId), new EdsValidation(edsValidationByHvfdSupplierDataId), hvfdStage);
    }

    /**
     * Function to get all saved items
     * 
     * @return list of EdsHighValidationFormData
     */
    public List<EdsHighValidationFormData> getAllItemsToSave() {
        return Collections.singletonList(this);
    }
}
