package com.inetpsa.eds.dao.model;

// Generated 10 oct. 2012 13:38:30 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.inetpsa.eds.application.EdsApplicationController;
import com.inetpsa.eds.dao.I_ValidationFormData;

/**
 * EdsLowValidationFormData generated by hbm2java
 */
@XmlRootElement(name = "validation-form")
public class EdsLowValidationFormData implements Serializable, I_ValidationFormData {
    /**
     * String Variable to hold the value for Column LVFD_ID of Table OPLQTLVD
     */
    private String lvfdId;
    /**
     * Variable to hold the value for Column LVFD_CLOSED_ID of Table OPLQTLVD
     */
    private EdsValidation edsValidationByLvfdClosedId;
    /**
     * Variable to hold the value for Column LVFD_PRELIMINARY_ID of Table OPLQTLVD
     */
    private EdsValidation edsValidationByLvfdPreliminaryId;
    /**
     * Variable to hold the value for Column LVFD_ROBUST_ID of Table OPLQTLVD
     */
    private EdsValidation edsValidationByLvfdRobustId;
    /**
     * Variable to hold the value for Column LVFD_CONSOLIDATED_ID of Table OPLQTLVD
     */
    private EdsValidation edsValidationByLvfdConsolidatedId;
    /**
     * Variable to hold the value for Column LVFD_SUPPLIER_DATA_ID of Table OPLQTLVD
     */
    private EdsValidation edsValidationByLvfdSupplierDataId;
    /**
     * Variable to hold the value for Column LVFD_EDS_ID of Table OPLQTLVD
     */
    private EdsEds edsEds;
    /**
     * int Variable to hold the value for Column LVFD_STAGE of Table OPLQTLVD
     */
    private int lvfdStage;

    /**
     * Default Constructor
     */
    public EdsLowValidationFormData() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param lvfdId Id
     * @param edsEds Eds details
     */
    public EdsLowValidationFormData(String lvfdId, EdsEds edsEds) {
        this.lvfdId = lvfdId;
        this.edsEds = edsEds;
        this.edsValidationByLvfdClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByLvfdPreliminaryId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByLvfdRobustId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByLvfdConsolidatedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.edsValidationByLvfdSupplierDataId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
        this.lvfdStage = EdsApplicationController.PRELIM_STAGE;
    }

    /**
     * Parameterized Constructor
     * 
     * @param lvfdId Id
     * @param edsValidationByLvfdClosedId
     * @param edsValidationByLvfdPreliminaryId Eds validation primary id
     * @param edsValidationByLvfdRobustId Eds validation robust id
     * @param edsValidationByLvfdConsolidatedId EdsValidation Consolidated Id
     * @param edsValidationByLvfdSupplierDataId EdsValidation supplier id
     * @param edsEds Eds details
     * @param lvfdStage Stage
     */
    public EdsLowValidationFormData(String lvfdId, EdsValidation edsValidationByLvfdClosedId, EdsValidation edsValidationByLvfdPreliminaryId,
            EdsValidation edsValidationByLvfdRobustId, EdsValidation edsValidationByLvfdConsolidatedId,
            EdsValidation edsValidationByLvfdSupplierDataId, EdsEds edsEds, int lvfdStage) {
        this.lvfdId = lvfdId;
        this.edsValidationByLvfdClosedId = edsValidationByLvfdClosedId;
        this.edsValidationByLvfdPreliminaryId = edsValidationByLvfdPreliminaryId;
        this.edsValidationByLvfdRobustId = edsValidationByLvfdRobustId;
        this.edsValidationByLvfdConsolidatedId = edsValidationByLvfdConsolidatedId;
        this.edsValidationByLvfdSupplierDataId = edsValidationByLvfdSupplierDataId;
        this.edsEds = edsEds;
        this.lvfdStage = lvfdStage;
    }

    /**
     * Function to get lvfdId lvfdId
     * 
     * @return the Value of lvfdId
     */
    @XmlTransient
    public String getLvfdId() {
        return this.lvfdId;
    }

    /**
     * Function to set lvfdId
     * 
     * @param lvfdId stage
     */
    public void setLvfdId(String lvfdId) {
        this.lvfdId = lvfdId;
    }

    /**
     * Function to get edsValidationByLvfdClosedId
     * 
     * @return the Value of edsValidationByLvfdClosedId
     */
    @XmlElement(name = "closed-validation")
    public EdsValidation getEdsValidationByLvfdClosedId() {
        return this.edsValidationByLvfdClosedId;
    }

    /**
     * Function to set edsValidationByLvfdClosedId
     * 
     * @param edsValidationByLvfdClosedId Eds validation closed ID
     */
    public void setEdsValidationByLvfdClosedId(EdsValidation edsValidationByLvfdClosedId) {
        this.edsValidationByLvfdClosedId = edsValidationByLvfdClosedId;
    }

    /**
     * Function to get edsValidationByLvfdPreliminaryId
     * 
     * @return the Value of edsValidationByLvfdPreliminaryId
     */
    @XmlElement(name = "preliminary-validation")
    public EdsValidation getEdsValidationByLvfdPreliminaryId() {
        return this.edsValidationByLvfdPreliminaryId;
    }

    /**
     * Function to set edsValidationByLvfdPreliminaryId
     * 
     * @param edsValidationByLvfdPreliminaryId Eds validation primary Id
     */
    public void setEdsValidationByLvfdPreliminaryId(EdsValidation edsValidationByLvfdPreliminaryId) {
        this.edsValidationByLvfdPreliminaryId = edsValidationByLvfdPreliminaryId;
    }

    /**
     * Function to get edsValidationByLvfdRobustId
     * 
     * @return the Value of edsValidationByLvfdRobustId
     */
    @XmlElement(name = "robust-validation")
    public EdsValidation getEdsValidationByLvfdRobustId() {
        return this.edsValidationByLvfdRobustId;
    }

    /**
     * Function to set edsValidationByLvfdRobustId
     * 
     * @param edsValidationByLvfdRobustId Eds validation robust Id
     */
    public void setEdsValidationByLvfdRobustId(EdsValidation edsValidationByLvfdRobustId) {
        this.edsValidationByLvfdRobustId = edsValidationByLvfdRobustId;
    }

    /**
     * Function to get edsValidationByLvfdConsolidatedId
     * 
     * @return the Value of edsValidationByLvfdConsolidatedId
     */
    @XmlElement(name = "consolidated-validation")
    public EdsValidation getEdsValidationByLvfdConsolidatedId() {
        return this.edsValidationByLvfdConsolidatedId;
    }

    /**
     * Function to set edsValidationByLvfdConsolidatedId
     * 
     * @param edsValidationByLvfdConsolidatedId Eds validation consolidated Id
     */
    public void setEdsValidationByLvfdConsolidatedId(EdsValidation edsValidationByLvfdConsolidatedId) {
        this.edsValidationByLvfdConsolidatedId = edsValidationByLvfdConsolidatedId;
    }

    /**
     * Function to get edsValidationByLvfdSupplierDataId
     * 
     * @return the Value of edsValidationByLvfdSupplierDataId
     */
    @XmlElement(name = "supplier-data-validation")
    public EdsValidation getEdsValidationByLvfdSupplierDataId() {
        return this.edsValidationByLvfdSupplierDataId;
    }

    /**
     * Function to set edsValidationByLvfdSupplierDataId
     * 
     * @param edsValidationByLvfdSupplierDataId Eds validation supplier id
     */
    public void setEdsValidationByLvfdSupplierDataId(EdsValidation edsValidationByLvfdSupplierDataId) {
        this.edsValidationByLvfdSupplierDataId = edsValidationByLvfdSupplierDataId;
    }

    /**
     * Function to get edsEds
     * 
     * @return the Value of edsEds
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return this.edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds Eds details
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function returns copy
     * 
     * @param eds Eds details
     * @param copiesMap Map of id and Eds validation object
     * @return EdsLowValidationFormData
     */
    public EdsLowValidationFormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        return new EdsLowValidationFormData(UUID.randomUUID().toString(), new EdsValidation(edsValidationByLvfdClosedId), new EdsValidation(
                edsValidationByLvfdPreliminaryId), new EdsValidation(edsValidationByLvfdRobustId), new EdsValidation(
                edsValidationByLvfdConsolidatedId), new EdsValidation(edsValidationByLvfdSupplierDataId), eds, lvfdStage);
    }

    /**
     * Function to get all saved data
     * 
     * @return all saved items
     */
    public List getAllItemsToSave() {
        return Collections.singletonList(this);
    }

    /**
     * Function to get edsValidationByLvfdPreliminaryId status
     * 
     * @return the Value of edsValidationByLvfdPreliminaryId status
     */
    public int getPreliminaryStatus() {
        return edsValidationByLvfdPreliminaryId.getVStatus();
    }

    /**
     * Function to get edsValidationByLvfdRobustId status
     * 
     * @return the Value of edsValidationByLvfdRobustId status
     */
    public int getRobustStatus() {
        return edsValidationByLvfdRobustId.getVStatus();
    }

    /**
     * Function to get edsValidationByLvfdConsolidatedId status
     * 
     * @return the Value of edsValidationByLvfdConsolidatedId status
     */
    public int getConsolidatedStatus() {
        return Math.min(edsValidationByLvfdConsolidatedId.getVStatus(), edsValidationByLvfdSupplierDataId.getVStatus());
    }

    /**
     * Function to get edsValidationByLvfdClosedId status
     * 
     * @return the Value of edsValidationByLvfdClosedId status
     */
    public int getClosedStatus() {
        return edsValidationByLvfdClosedId.getVStatus();
    }

    /**
     * Function to get lvfdStage
     * 
     * @return the Value of lvfdStage
     */
    @XmlTransient
    public int getLvfdStage() {
        return lvfdStage;
    }

    /**
     * Function to set lvfdStage
     * 
     * @param lvfdStage
     */
    public void setLvfdStage(int lvfdStage) {
        this.lvfdStage = lvfdStage;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.inetpsa.eds.dao.I_ValidationFormData#getValidationStage()
     */
    @XmlElement(name = "stage")
    @Override
    public int getValidationStage() {
        return getLvfdStage();
    }

    /**
     * Function to set edsValidationByLvfdClosedId
     */
    public void resetClosedStatus() {
        edsValidationByLvfdClosedId = new EdsValidation(UUID.randomUUID().toString(), EdsValidation.VALIDATION_NONE);
    }
}
