package com.inetpsa.eds.dao.model;

// Generated 22 sept. 2012 11:05:57 by Hibernate Tools 3.2.1.GA

import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EdsModeParc generated by hbm2java
 */
public class EdsModeParc implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column MPEDS_ID of Table OPLQTMOP
     */
    private String mpedsId;
    /**
     * String Variable to hold the value for Column MPEDS_QCF1 of Table OPLQTMOP
     */
    private String mpedsQcf1;
    /**
     * Float Variable to hold the value for Column MPEDS_TMOY_MODE_PARC of Table OPLQTMOP
     */
    private Float mpedsTmoyModeParc;
    /**
     * Float Variable to hold the value for Column MPEDS_TMAX_MODE_PARC of Table OPLQTMOP
     */
    private Float mpedsTmaxModeParc;
    /**
     * String Variable to hold the value for Column MPEDS_TMOY_MODE_PARC_COMMENT of Table OPLQTMOP
     */
    private String mpedsTmoyModeParcComment;

    /**
     * String Variable to hold the value for Column MPEDS_NAME of Table OPLQTMOP
     */
    private String mpedsName;

    /**
     * Default Constructor
     */
    public EdsModeParc() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param mpedsId
     */
    public EdsModeParc(String mpedsId) {
        this.mpedsId = mpedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param mpedsId Park mode id
     * @param mpedsQcf1 Question 1
     * @param mpedsTmoyModeParc Tmoy
     * @param mpedsTmaxModeParc Tmax
     * @param mpedsTmoyModeParcComment Comment
     */
    public EdsModeParc(String mpedsId, String mpedsQcf1, Float mpedsTmoyModeParc, Float mpedsTmaxModeParc, String mpedsTmoyModeParcComment) {
        this.mpedsId = mpedsId;
        this.mpedsQcf1 = mpedsQcf1;
        this.mpedsTmoyModeParc = mpedsTmoyModeParc;
        this.mpedsTmaxModeParc = mpedsTmaxModeParc;
        this.mpedsTmoyModeParcComment = mpedsTmoyModeParcComment;
    }

    /**
     * Parameterized Constructor
     * 
     * @param srcModeParc EdsModeParc
     */
    public EdsModeParc(EdsModeParc srcModeParc) {
        this.mpedsId = UUID.randomUUID().toString();
        this.mpedsQcf1 = srcModeParc.mpedsQcf1;
        this.mpedsTmoyModeParc = srcModeParc.mpedsTmoyModeParc;
        this.mpedsTmaxModeParc = srcModeParc.mpedsTmaxModeParc;
        this.mpedsTmoyModeParcComment = srcModeParc.mpedsTmoyModeParcComment;

    }

    /**
     * Function to get mpedsId
     * 
     * @return the Value of mpedsId
     */
    @XmlAttribute(name = "id")
    public String getMpedsId() {
        return this.mpedsId;
    }

    /**
     * Function to set mpedsId
     * 
     * @param mpedsId Park mode id
     */
    public void setMpedsId(String mpedsId) {
        this.mpedsId = mpedsId;
    }

    /**
     * Function to get mpedsQcf1
     * 
     * @return the Value of mpedsQcf1
     */
    @XmlTransient
    public String getMpedsQcf1() {
        return this.mpedsQcf1;
    }

    /**
     * Function to set mpedsQcf1
     * 
     * @param mpedsQcf1 Question 1
     */
    public void setMpedsQcf1(String mpedsQcf1) {
        this.mpedsQcf1 = mpedsQcf1;
    }

    /**
     * Function to get mpedsTmoyModeParc
     * 
     * @return the Value of mpedsTmoyModeParc
     */
    @XmlElement(name = "Tmoy")
    public Float getMpedsTmoyModeParc() {
        return this.mpedsTmoyModeParc;
    }

    /**
     * Function to set mpedsTmoyModeParc
     * 
     * @param mpedsTmoyModeParc Tmoy
     */
    public void setMpedsTmoyModeParc(Float mpedsTmoyModeParc) {
        this.mpedsTmoyModeParc = mpedsTmoyModeParc;
    }

    /**
     * Function to get mpedsTmaxModeParc
     * 
     * @return the Value of mpedsTmaxModeParc
     */
    @XmlElement(name = "Tmax")
    public Float getMpedsTmaxModeParc() {
        return this.mpedsTmaxModeParc;
    }

    /**
     * Function to set mpedsTmaxModeParc
     * 
     * @param mpedsTmaxModeParc Tmax
     */
    public void setMpedsTmaxModeParc(Float mpedsTmaxModeParc) {
        this.mpedsTmaxModeParc = mpedsTmaxModeParc;
    }

    /**
     * Function to get mpedsTmoyModeParcComment
     * 
     * @return the Value of mpedsTmoyModeParcComment
     */
    public String getMpedsTmoyModeParcComment() {
        return this.mpedsTmoyModeParcComment;
    }

    /**
     * Function to set mpedsTmoyModeParcComment
     * 
     * @param mpedsTmoyModeParcComment Comment
     */
    public void setMpedsTmoyModeParcComment(String mpedsTmoyModeParcComment) {
        this.mpedsTmoyModeParcComment = mpedsTmoyModeParcComment;
    }

    /**
     * Getter mpedsName
     * 
     * @return the mpedsName
     */
    public String getMpedsName() {
        return mpedsName;
    }

    /**
     * Setter mpedsName
     * 
     * @param mpedsName the mpedsName to set
     */
    public void setMpedsName(String mpedsName) {
        this.mpedsName = mpedsName;
    }

}
