package com.inetpsa.eds.dao.model;

// Generated 10 juil. 2012 14:11:20 by Hibernate Tools 3.2.1.GA

import java.util.Collections;
import java.util.List;
import java.util.UUID;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsMissionProfil generated by hbm2java
 */
@XmlType
public class EdsMissionProfil implements java.io.Serializable, Comparable<EdsMissionProfil> {
    /**
     * String Variable to hold the value for Column MP_ID of Table OPLQTMIP
     */
    private String mpId;
    /**
     * Float Variable to hold the value for Column MP_NOMBRE_ACTIVATION of Table OPLQTMIP
     */
    private Float mpNombreActivation;
    /**
     * Integer Variable to hold the value for Column MP_UNIT of Table OPLQTMIP
     */
    private Integer mpUnit;
    /**
     * String Variable to hold the value for Column MP_COMMENTAIRE of Table OPLQTMIP
     */
    private String mpCommentaire;
    /**
     * String Variable to hold the value for Column MP_DOCS_INFOS_URLS of Table OPLQTMIP
     */
    private String mpDocsInfosUrls;
    /**
     * String Variable to hold the value for Column MP_NOM_PROFIL of Table OPLQTMIP
     */
    private String mpNomProfil;
    /**
     * int Variable to hold the value for Column MP_RANK of Table OPLQTMIP
     */
    private int mpRank;

    /**
     * Default Constructor
     */
    public EdsMissionProfil() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param mpId
     */
    public EdsMissionProfil(String mpId) {
        this.mpId = mpId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param mpId ID
     * @param mpNombreActivation Activation number
     * @param mpUnit Unit
     * @param mpCommentaire comment
     * @param mpDocsInfosUrls Attachment URL
     * @param mpNomProfil Mission profile
     */
    public EdsMissionProfil(String mpId, Float mpNombreActivation, Integer mpUnit, String mpCommentaire, String mpDocsInfosUrls, String mpNomProfil) {
        this.mpId = mpId;
        this.mpNombreActivation = mpNombreActivation;
        this.mpUnit = mpUnit;
        this.mpCommentaire = mpCommentaire;
        this.mpDocsInfosUrls = mpDocsInfosUrls;
        this.mpNomProfil = mpNomProfil;

    }

    /**
     * Function to get mpId
     * 
     * @return the Value of mpId
     */
    @XmlTransient
    public String getMpId() {
        return this.mpId;
    }

    /**
     * Function to set mpId
     * 
     * @param mpId Id
     */
    public void setMpId(String mpId) {
        this.mpId = mpId;
    }

    /**
     * Function to get mpNombreActivation
     * 
     * @return the Value of mpNombreActivation
     */
    @XmlElement(name = "activation-count")
    public Float getMpNombreActivation() {
        return this.mpNombreActivation;
    }

    /**
     * Function to set mpNombreActivation
     * 
     * @param mpNombreActivation Activation number
     */
    public void setMpNombreActivation(Float mpNombreActivation) {
        this.mpNombreActivation = mpNombreActivation;
    }

    /**
     * Function to get mpRank
     * 
     * @return the Value of mpRank
     */
    @XmlTransient
    public int getMpRank() {
        return mpRank;
    }

    /**
     * Function to set mpRank
     * 
     * @param mpRank Rank
     */
    public void setMpRank(int mpRank) {
        this.mpRank = mpRank;
    }

    /**
     * Function to get mpUnit
     * 
     * @return the Value of mpUnit
     */
    @XmlElement(name = "unit-type")
    public Integer getMpUnit() {
        return this.mpUnit;
    }

    /**
     * Function to set mpUnit
     * 
     * @param mpUnit Unit
     */
    public void setMpUnit(Integer mpUnit) {
        this.mpUnit = mpUnit;
    }

    /**
     * Function to get mpCommentaire
     * 
     * @return the Value of mpCommentaire
     */
    @XmlElement(name = "comment")
    public String getMpCommentaire() {
        return this.mpCommentaire;
    }

    /**
     * Function to set mpCommentaire
     * 
     * @param mpCommentaire Comment
     */
    public void setMpCommentaire(String mpCommentaire) {
        this.mpCommentaire = mpCommentaire;
    }

    /**
     * Function to get mpDocsInfosUrls
     * 
     * @return the Value of mpDocsInfosUrls
     */
    @XmlElement(name = "doc-info-urls")
    public String getMpDocsInfosUrls() {
        return this.mpDocsInfosUrls;
    }

    /**
     * Function to set mpDocsInfosUrls
     * 
     * @param mpDocsInfosUrls Attachment URL
     */
    public void setMpDocsInfosUrls(String mpDocsInfosUrls) {
        this.mpDocsInfosUrls = mpDocsInfosUrls;
    }

    /**
     * Function to get mpNomProfil
     * 
     * @return the Value of mpNomProfil
     */
    @XmlElement(name = "name")
    public String getMpNomProfil() {
        return this.mpNomProfil;
    }

    /**
     * Function to set mpNomProfil
     * 
     * @param mpNomProfil Mission profile
     */
    public void setMpNomProfil(String mpNomProfil) {
        this.mpNomProfil = mpNomProfil;
    }

    /**
     * Parameterized constructor
     * 
     * @param srcProfil EdsMissionProfil
     */
    public EdsMissionProfil(EdsMissionProfil srcProfil) {
        mpId = UUID.randomUUID().toString();
        mpCommentaire = srcProfil.mpCommentaire;
        mpDocsInfosUrls = srcProfil.mpDocsInfosUrls;
        mpNomProfil = srcProfil.mpNomProfil;
        mpNombreActivation = srcProfil.mpNombreActivation;
        mpUnit = srcProfil.mpUnit;
        mpRank = srcProfil.mpRank;
    }

    /**
     * Function to get all saved data
     * 
     * @return all saved data
     */
    public List<Object> getAllItemsToSave() {
        return Collections.EMPTY_LIST;
    }

    /**
     * Compare EdsMissionProfil objects
     * 
     * @param o EdsMissionProfil
     * @return Difference between EdsMissionProfil objects
     */
    public int compareTo(EdsMissionProfil o) {
        return this.getMpRank() - o.getMpRank();
    }
}
