package com.inetpsa.eds.dao.model;

// Generated 17 oct. 2012 11:31:00 by Hibernate Tools 3.2.1.GA

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.inetpsa.eds.dao.I_DriftableSupply;
import com.inetpsa.eds.dao.I_FormData;

/**
 * EdsPsaMesureSupply generated by hbm2java
 */
@XmlRootElement(name = "psa-mesure-supply-form")
public class EdsPsaMesureSupply implements java.io.Serializable, I_DriftableSupply, I_FormData {
    /**
     * String Variable to hold the value for Column PMSEDS_ID of Table OPLQTPMS
     */
    private String pmsedsId;
    /**
     * String Variable to hold the value for Column PMSEDS_REF of Table OPLQTPMS
     */
    private String pmsedsRef;
    /**
     * String Variable to hold the value for Column PMSEDS_SUPPLY_NAME of Table OPLQTPMS
     */
    private String pmsedsSupplyName;
    /**
     * String Variable to hold the value for Column PMSEDS_SUPPLY_TYPE of Table OPLQTPMS
     */
    private String pmsedsSupplyType;
    /**
     * String Variable to hold the value for Column PMSEDS_TBT_BT of Table OPLQTPMS
     */
    private String pmsedsTbtBt;
    /**
     * Variable to hold the value for Column PMSEDS_QCF of Table OPLQTPMS
     */
    private EdsQcf edsQcf;
    /**
     * Set variable to hold values of {@link EdsConsSupProfile}
     */
    private Set<EdsConsSupProfile> edsConsolidateSupplyProfile = new HashSet<EdsConsSupProfile>(0);
    /**
     * Set Collection to hold the values for Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private Set<EdsCourantAppelleActivation> edsPmCourantAppelleActivations = new HashSet<EdsCourantAppelleActivation>(0);
    /**
     * Set Collection to hold the values for Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Set<EdsReseauVeilleReveilleOrganeInactif> edsPmReseauVeilleReveilleOrganeInactifs = new HashSet<EdsReseauVeilleReveilleOrganeInactif>(0);
    /**
     * Set Collection to hold the values for Table EDS_COURANT_NOMINALE_ACTIVATION
     */
    private Set<EdsCourantNominaleActivation> edsPmCourantNominaleActivations = new HashSet<EdsCourantNominaleActivation>(0);
    /**
     * Set Collection to hold the values for Table OPLQTMST
     */
    private Set<EdsCourantMiseSousTension> edsPmCourantMiseSousTensions = new HashSet<EdsCourantMiseSousTension>(0);
    /**
     * Set Collection to hold the values for Table OPLQTMOP
     */
    private Set<EdsModeParc> edsPmModeParcs = new HashSet<EdsModeParc>(0);
    /**
     * Set Collection to hold the values for Table OPLQTMOM
     */
    private Set<EdsModeMontage> edsPmModeMontages = new HashSet<EdsModeMontage>(0);
    /**
     * Set Collection to hold the values for Table EDS_COURANT_BLOQUE_COURANT_DYSFONCTIONNEMENT
     */
    private Set<EdsCourantBloqueCourantDysfonctionnement> edsPmCourantBloqueCourantDysfonctionnements = new HashSet<EdsCourantBloqueCourantDysfonctionnement>(
            0);
    /**
     * Set Collection to hold the values for Table OPLQTCOC
     */
    private Set<EdsCourantCycle> edsCourantCycles = new HashSet<EdsCourantCycle>(0);
    /**
     * Set Collection to hold the values for Table OPLQTSUY
     */
    private Set<EdsSupply> edsSupplies = new HashSet<EdsSupply>(0);

    // private EdsEds edsEds;

    /**
     * Default Constructor
     */
    public EdsPsaMesureSupply() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param pmsedsId
     */
    public EdsPsaMesureSupply(String pmsedsId) {
        this.pmsedsId = pmsedsId;
    }

    // public EdsPsaMesureSupply( String pmsedsId ,
    // EdsEds edsEds )
    // {
    // this.pmsedsId = pmsedsId;
    // this.edsEds = edsEds;
    // }

    /**
     * Parameterized Constructor
     * 
     * @param pmsedsId Eds PSA Measure Supply Id
     * @param pmsedsSupplyName Eds PSA Measure Supply Name
     * @param pmsedsSupplyType Eds PSA Measure Supply Type
     * @param pmsedsTbtBt TBT/BT
     * @param edsPmCourantAppelleActivations set of Activation Inrush current
     * @param edsPmReseauVeilleReveilleOrganeInactifs set of Asleep or awake and inactive network device
     * @param edsPmCourantNominaleActivations set of Activation Nominal current
     * @param edsPmCourantMiseSousTensions set of Powered on current
     * @param edsPsaMesureSupplies set of PSA Measure supply
     * @param edsPmModeParcs Set of Park Mode
     * @param edsPmModeMontages Set of Assembled mode
     * @param edsPmCourantBloqueCourantDysfonctionnements set of blocked couple/dysfunctional current
     */
    public EdsPsaMesureSupply(String pmsedsId, String pmsedsSupplyName, String pmsedsSupplyType, String pmsedsTbtBt,
            Set edsPmCourantAppelleActivations, Set edsPmReseauVeilleReveilleOrganeInactifs, Set edsPmCourantNominaleActivations,
            Set edsPmCourantMiseSousTensions, Set edsPsaMesureSupplies, Set edsPmModeParcs, Set edsPmModeMontages,
            Set edsPmCourantBloqueCourantDysfonctionnements) {
        this.pmsedsId = pmsedsId;
        this.pmsedsSupplyName = pmsedsSupplyName;
        this.pmsedsSupplyType = pmsedsSupplyType;
        this.pmsedsTbtBt = pmsedsTbtBt;
        this.edsPmCourantAppelleActivations = edsPmCourantAppelleActivations;
        this.edsPmReseauVeilleReveilleOrganeInactifs = edsPmReseauVeilleReveilleOrganeInactifs;
        this.edsPmCourantNominaleActivations = edsPmCourantNominaleActivations;
        this.edsPmCourantMiseSousTensions = edsPmCourantMiseSousTensions;
        this.edsPmModeParcs = edsPmModeParcs;
        this.edsPmModeMontages = edsPmModeMontages;
        this.edsPmCourantBloqueCourantDysfonctionnements = edsPmCourantBloqueCourantDysfonctionnements;
    }

    /**
     * Parameterized Constructor
     * 
     * @param otherSupply Eds Psa Mesure Supply
     */
    public EdsPsaMesureSupply(EdsPsaMesureSupply otherSupply) {
        this.pmsedsId = UUID.randomUUID().toString();
        this.pmsedsSupplyName = otherSupply.pmsedsSupplyName;
        this.pmsedsSupplyType = otherSupply.pmsedsSupplyType;
        this.pmsedsTbtBt = otherSupply.pmsedsTbtBt;
        this.pmsedsRef = otherSupply.pmsedsRef;

        for (EdsCourantAppelleActivation source : otherSupply.edsPmCourantAppelleActivations) {
            edsPmCourantAppelleActivations.add(new EdsCourantAppelleActivation(source));
        }
        for (EdsReseauVeilleReveilleOrganeInactif source : otherSupply.edsPmReseauVeilleReveilleOrganeInactifs) {
            edsPmReseauVeilleReveilleOrganeInactifs.add(new EdsReseauVeilleReveilleOrganeInactif(source));
        }
        for (EdsCourantNominaleActivation source : otherSupply.edsPmCourantNominaleActivations) {
            edsPmCourantNominaleActivations.add(new EdsCourantNominaleActivation(source));
        }
        for (EdsCourantMiseSousTension source : otherSupply.edsPmCourantMiseSousTensions) {
            edsPmCourantMiseSousTensions.add(new EdsCourantMiseSousTension(source));
        }
        for (EdsModeParc source : otherSupply.edsPmModeParcs) {
            edsPmModeParcs.add(new EdsModeParc(source));
        }
        for (EdsModeMontage source : otherSupply.edsPmModeMontages) {
            edsPmModeMontages.add(new EdsModeMontage(source));
        }
        for (EdsCourantBloqueCourantDysfonctionnement source : otherSupply.edsPmCourantBloqueCourantDysfonctionnements) {
            edsPmCourantBloqueCourantDysfonctionnements.add(new EdsCourantBloqueCourantDysfonctionnement(source));
        }

        for (EdsCourantCycle source : otherSupply.edsCourantCycles) {
            edsCourantCycles.add(new EdsCourantCycle(source));
        }

        EdsQcf qcf = otherSupply.edsQcf;
        this.edsQcf = new EdsQcf(qcf);
    }

    // @XmlTransient
    // public EdsEds getEdsEds()
    // {
    // return edsEds;
    // }
    //
    // public void setEdsEds( EdsEds edsEds )
    // {
    // this.edsEds = edsEds;
    // }

    /**
     * Function to get pmsedsId
     * 
     * @return the Value of pmsedsId
     */
    @XmlAttribute(name = "id")
    public String getPmsedsId() {
        return this.pmsedsId;
    }

    /**
     * Function to set pmsedsId
     * 
     * @param pmsedsId Id
     */
    public void setPmsedsId(String pmsedsId) {
        this.pmsedsId = pmsedsId;
    }

    /**
     * Function to get pmsedsRef
     * 
     * @return the Value of pmsedsRef
     */
    @XmlAttribute(name = "ref")
    public String getPmsedsRef() {
        return pmsedsRef;
    }

    /**
     * Function to set pmsedsRef
     * 
     * @param pmsedsRef Eds reference
     */
    public void setPmsedsRef(String pmsedsRef) {
        this.pmsedsRef = pmsedsRef;
    }

    /**
     * Function to get pmsedsSupplyName
     * 
     * @return the Value of pmsedsSupplyName
     */
    @XmlAttribute(name = "name")
    public String getPmsedsSupplyName() {
        return pmsedsSupplyName;
    }

    /**
     * Function to set pmsedsSupplyName
     * 
     * @param pmsedsSupplyName Eds Psa Mesure Supply Name
     */
    public void setPmsedsSupplyName(String pmsedsSupplyName) {
        this.pmsedsSupplyName = pmsedsSupplyName;
    }

    /**
     * Function to get pmsedsSupplyType
     * 
     * @return the Value of pmsedsSupplyType
     */
    @XmlElement(name = "Supply-Type")
    public String getPmsedsSupplyType() {
        return this.pmsedsSupplyType;
    }

    /**
     * Function to set pmsedsSupplyType
     * 
     * @param pmsedsSupplyType Eds Psa Mesure Supply Type
     */
    public void setPmsedsSupplyType(String pmsedsSupplyType) {
        this.pmsedsSupplyType = pmsedsSupplyType;
    }

    /**
     * Function to get pmsedsTbtBt
     * 
     * @return the Value of pmsedsTbtBt
     */
    @XmlAttribute(name = "bt_tbt")
    public String getPmsedsTbtBt() {
        return this.pmsedsTbtBt;
    }

    /**
     * Function to set pmsedsTbtBt
     * 
     * @param pmsedsTbtBt TBT/BT
     */
    public void setPmsedsTbtBt(String pmsedsTbtBt) {
        this.pmsedsTbtBt = pmsedsTbtBt;
    }

    /**
     * Function to get edsSupplies
     * 
     * @return the Value of edsSupplies
     */
    @XmlTransient
    public Set<EdsSupply> getEdsSupplies() {
        return this.edsSupplies;
    }

    /**
     * Function to set edsSupplies
     * 
     * @param edsSupplies set of Eds Supply
     */
    public void setEdsSupplies(Set edsSupplies) {
        this.edsSupplies = edsSupplies;
    }

    /**
     * Function to get edsPmCourantAppelleActivations
     * 
     * @return the Value of edsPmCourantAppelleActivations
     */
    @XmlElementWrapper(name = "CourantsAppelleActivation")
    @XmlElement(name = "CourantAppelleActivation")
    public Set<EdsCourantAppelleActivation> getEdsPmCourantAppelleActivations() {
        return this.edsPmCourantAppelleActivations;
    }

    /**
     * Function to set edsPmCourantAppelleActivations
     * 
     * @param edsPmCourantAppelleActivations set of Activation Inrush current
     */
    public void setEdsPmCourantAppelleActivations(Set<EdsCourantAppelleActivation> edsPmCourantAppelleActivations) {
        this.edsPmCourantAppelleActivations = edsPmCourantAppelleActivations;
    }

    /**
     * Function to get edsPmReseauVeilleReveilleOrganeInactifs
     * 
     * @return the Value of edsPmReseauVeilleReveilleOrganeInactifs
     */
    @XmlElementWrapper(name = "ReseauVeilleReveilleOrganeInactifs")
    @XmlElement(name = "ReseauVeilleReveilleOrganeInactif")
    public Set<EdsReseauVeilleReveilleOrganeInactif> getEdsPmReseauVeilleReveilleOrganeInactifs() {
        return this.edsPmReseauVeilleReveilleOrganeInactifs;
    }

    /**
     * Function to set edsPmReseauVeilleReveilleOrganeInactifs
     * 
     * @param edsPmReseauVeilleReveilleOrganeInactifs set of Asleep or awake and inactive network device
     */
    public void setEdsPmReseauVeilleReveilleOrganeInactifs(Set<EdsReseauVeilleReveilleOrganeInactif> edsPmReseauVeilleReveilleOrganeInactifs) {
        this.edsPmReseauVeilleReveilleOrganeInactifs = edsPmReseauVeilleReveilleOrganeInactifs;
    }

    /**
     * Function to get edsPmCourantNominaleActivations
     * 
     * @return the Value of edsPmCourantNominaleActivations
     */
    @XmlElementWrapper(name = "CourantsNominaleActivation")
    @XmlElement(name = "CourantNominaleActivation")
    public Set<EdsCourantNominaleActivation> getEdsPmCourantNominaleActivations() {
        return this.edsPmCourantNominaleActivations;
    }

    /**
     * Function to set edsPmCourantNominaleActivations
     * 
     * @param edsPmCourantNominaleActivations set of Activation Nominal current
     */
    public void setEdsPmCourantNominaleActivations(Set<EdsCourantNominaleActivation> edsPmCourantNominaleActivations) {
        this.edsPmCourantNominaleActivations = edsPmCourantNominaleActivations;
    }

    /**
     * Function to get edsPmCourantMiseSousTensions
     * 
     * @return the Value of edsPmCourantMiseSousTensions
     */
    @XmlElementWrapper(name = "CourantsMiseSousTension")
    @XmlElement(name = "CourantMiseSousTension")
    public Set<EdsCourantMiseSousTension> getEdsPmCourantMiseSousTensions() {
        return this.edsPmCourantMiseSousTensions;
    }

    /**
     * Function to set edsPmCourantMiseSousTensions
     * 
     * @param edsPmCourantMiseSousTensions set of Powered on current
     */
    public void setEdsPmCourantMiseSousTensions(Set<EdsCourantMiseSousTension> edsPmCourantMiseSousTensions) {
        this.edsPmCourantMiseSousTensions = edsPmCourantMiseSousTensions;
    }

    /**
     * Function to get edsPmModeParcs
     * 
     * @return the Value of edsPmModeParcs
     */
    @XmlElementWrapper(name = "ModeParcs")
    @XmlElement(name = "ModeParc")
    public Set<EdsModeParc> getEdsPmModeParcs() {
        return this.edsPmModeParcs;
    }

    /**
     * Function to set edsPmModeParcs
     * 
     * @param edsPmModeParcs Set of Park Mode
     */
    public void setEdsPmModeParcs(Set<EdsModeParc> edsPmModeParcs) {
        this.edsPmModeParcs = edsPmModeParcs;
    }

    /**
     * Function to get edsPmModeMontages
     * 
     * @return the Value of edsPmModeMontages
     */
    @XmlElementWrapper(name = "ModeMontages")
    @XmlElement(name = "ModeMontage")
    public Set<EdsModeMontage> getEdsPmModeMontages() {
        return this.edsPmModeMontages;
    }

    /**
     * Function to set edsPmModeMontages
     * 
     * @param edsPmModeMontages Set of Assembled mode
     */
    public void setEdsPmModeMontages(Set<EdsModeMontage> edsPmModeMontages) {
        this.edsPmModeMontages = edsPmModeMontages;
    }

    /**
     * Function to get edsPmCourantBloqueCourantDysfonctionnements
     * 
     * @return the Value of edsPmCourantBloqueCourantDysfonctionnements
     */
    @XmlElementWrapper(name = "CourantsBloqueCourantDysfonctionnement")
    @XmlElement(name = "CourantBloqueCourantDysfonctionnement")
    public Set<EdsCourantBloqueCourantDysfonctionnement> getEdsPmCourantBloqueCourantDysfonctionnements() {
        return this.edsPmCourantBloqueCourantDysfonctionnements;
    }

    /**
     * Function to set edsPmCourantBloqueCourantDysfonctionnements
     * 
     * @param edsPmCourantBloqueCourantDysfonctionnements set of blocked couple/dysfunctional current
     */
    public void setEdsPmCourantBloqueCourantDysfonctionnements(
            Set<EdsCourantBloqueCourantDysfonctionnement> edsPmCourantBloqueCourantDysfonctionnements) {
        this.edsPmCourantBloqueCourantDysfonctionnements = edsPmCourantBloqueCourantDysfonctionnements;
    }

    /**
     * Function to get edsCourantCycles
     * 
     * @return the Value of edsCourantCycles
     */
    @XmlElementWrapper(name = "CourantsCycles")
    @XmlElement(name = "CourantCycles")
    public Set<EdsCourantCycle> getEdsCourantCycles() {
        return this.edsCourantCycles;
    }

    /**
     * Function to set edsCourantCycles
     * 
     * @param edsCourantCycles Set of EdsCourantCycle
     */
    public void setEdsCourantCycles(Set<EdsCourantCycle> edsCourantCycles) {
        this.edsCourantCycles = edsCourantCycles;
    }

    /**
     * Function Returns Isleep Current
     * 
     * @return Isleep current
     */
    public Float getISleepCurrent() {
        Float value = null;
        if (!getEdsPmReseauVeilleReveilleOrganeInactifs().isEmpty()) {
            value = ((EdsReseauVeilleReveilleOrganeInactif) getEdsPmReseauVeilleReveilleOrganeInactifs().iterator().next())
                    .getRvroiedsTmoyIveilleMoteurNonTourant();
        }
        return value;
    }

    /**
     * Function returns IAwake12_5
     * 
     * @return IAwake12_5
     */
    public Float getIAwake12_5() {
        Float value = null;
        if (!getEdsPmReseauVeilleReveilleOrganeInactifs().isEmpty()) {
            value = ((EdsReseauVeilleReveilleOrganeInactif) getEdsPmReseauVeilleReveilleOrganeInactifs().iterator().next())
                    .getRvroiedsTmoyIreveilleInactif13vMoteurTourant();
            ;
        }
        return value;
    }

    /**
     * Function returns IAwake13_5
     * 
     * @return IAwake12_5
     */
    public Float getIAwake13_5() {
        Float value = null;
        if (!getEdsPmReseauVeilleReveilleOrganeInactifs().isEmpty()) {
            value = ((EdsReseauVeilleReveilleOrganeInactif) getEdsPmReseauVeilleReveilleOrganeInactifs().iterator().next())
                    .getRvroiedsTmoyIreveilleInactif13vMoteurTourant();
        }
        return value;
    }

    /**
     * Function returns INomStab12_5
     * 
     * @return INomStab12_5
     */
    public Float getINomStab12_5() {
        Float value = null;
        if (!getEdsPmCourantNominaleActivations().isEmpty()) {
            value = ((EdsCourantNominaleActivation) getEdsPmCourantNominaleActivations().iterator().next()).getCnaedsImoyStabMnt();
        }
        return value;
    }

    /**
     * Function returns INomStab13_5
     * 
     * @return INomStab13_5
     */
    public Float getINomStab13_5() {
        Float value = null;
        if (!getEdsPmCourantNominaleActivations().isEmpty()) {
            value = ((EdsCourantNominaleActivation) getEdsPmCourantNominaleActivations().iterator().next()).getCnaedsImoyStab13Mt();
        }
        return value;
    }

    /**
     * Function returns IWorstStab12_5
     * 
     * @return IWorstStab12_5
     */
    public Float getIWorstStab12_5() {
        Float value = null;
        if (!getEdsPmCourantNominaleActivations().isEmpty()) {
            value = ((EdsCourantNominaleActivation) getEdsPmCourantNominaleActivations().iterator().next()).getCnaedsImoyPireCasMnt();
        }
        return value;
    }

    /**
     * Function returns IWorstStab13_5
     * 
     * @return IWorstStab13_5
     */
    public Float getIWorstStab13_5() {
        Float value = null;
        if (!getEdsPmCourantNominaleActivations().isEmpty()) {
            value = ((EdsCourantNominaleActivation) getEdsPmCourantNominaleActivations().iterator().next()).getCnaedsImoyPireCas13Mt();
        }
        return value;
    }

    /**
     * Function to get EdsPsaMesureSupply
     * 
     * @param eds Eds details
     * @param copiesMap Map of id and supply object
     * @return the Value of EdsPsaMesureSupply
     */
    public I_FormData getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {

        EdsPsaMesureSupply copy = new EdsPsaMesureSupply(UUID.randomUUID().toString());
        for (EdsSupply source : edsSupplies) {

            if (!copiesMap.containsKey(source.getSedsId())) {
                copiesMap.put(source.getSedsId(), source.getCopy(eds, copiesMap));
            }
            EdsSupply supplyCopy = (EdsSupply) copiesMap.get(source.getSedsId());
            copy.edsSupplies.add(supplyCopy);
        }
        return copy;

    }

    /**
     * Function to get all saved items
     * 
     * @return all saved items
     */
    public List getAllItemsToSave() {
        return Collections.singletonList((Object) this);
    }

    /**
     * Function to get edsQcf
     * 
     * @return the Value of edsQcf
     */
    public EdsQcf getEdsQcf() {
        if (edsQcf == null) {
            edsQcf = new EdsQcf(UUID.randomUUID().toString());
        }
        return edsQcf;
    }

    /**
     * Function to set edsQcf
     * 
     * @param edsQcf EdsQcf
     */
    public void setEdsQcf(EdsQcf edsQcf) {
        this.edsQcf = edsQcf;
    }

    /**
     * Getter edsConsolidateSupplyProfile
     * 
     * @return the edsConsolidateSupplyProfile
     */
    public Set<EdsConsSupProfile> getEdsConsolidateSupplyProfile() {
        return edsConsolidateSupplyProfile;
    }

    /**
     * Setter edsConsolidateSupplyProfile
     * 
     * @param edsConsolidateSupplyProfile the edsConsolidateSupplyProfile to set
     */
    public void setEdsConsolidateSupplyProfile(Set<EdsConsSupProfile> edsConsolidateSupplyProfile) {
        this.edsConsolidateSupplyProfile = edsConsolidateSupplyProfile;
    }

}
