package com.inetpsa.eds.dao.model;

// Generated 15 juin 2012 12:07:59 by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlType;

/**
 * EdsEds generated by hbm2java
 */
@XmlType
public class EdsProjectNode implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column EDSPN_ID of Table OPLQTPRN
     */
    private String edspnId;
    /**
     * String Variable to hold the value for Column EDSPN_PARENT_ID of Table OPLQTPRN
     */
    private String edspnParentId;
    /**
     * String Variable to hold the value for Column EDSPN_NAME of Table OPLQTPRN
     */
    private String edspnName;

    /**
     * Default constructor
     */
    public EdsProjectNode() {
    }

    /**
     * Parameterized constructor
     * 
     * @param edspnId Id
     * @param edspnParentId ParentId
     * @param edspnName name
     */
    public EdsProjectNode(String edspnId, String edspnParentId, String edspnName) {
        this.edspnId = edspnId;
        this.edspnParentId = edspnParentId;
        this.edspnName = edspnName;
    }

    /**
     * Get ID
     * 
     * @return The ID
     */
    public String getEdspnId() {
        return edspnId;
    }

    /**
     * Set the ID
     * 
     * @param edspnId The ID
     */
    public void setEdspnId(String edspnId) {
        this.edspnId = edspnId;
    }

    /**
     * Get the parent ID, if any
     * 
     * @return The parent ID, or null
     */
    public String getEdspnParentId() {
        return edspnParentId;
    }

    /**
     * Set the parent ID
     * 
     * @param edspnParentId The parent ID
     */
    public void setEdspnParentId(String edspnParentId) {
        this.edspnParentId = edspnParentId;
    }

    /**
     * Get the node name
     * 
     * @return The node name
     */
    public String getEdspnName() {
        return edspnName;
    }

    /**
     * Set the node name
     * 
     * @param edspnName The node name
     */
    public void setEdspnName(String edspnName) {
        this.edspnName = edspnName;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return edspnName; // To change body of generated methods, choose Tools | Templates.
    }
}
