package com.inetpsa.eds.dao.model;

// Generated 14 juin 2012 16:43:00 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsProject generated by hbm2java
 */
@XmlType
public class EdsProject implements java.io.Serializable {
    /**
     * Constant to hold value of INACTIVE
     */
    public static final int INACTIVE = 0; // Active project if index> INACTIVE
    /**
     * String Variable to hold the value for Column P_EDSPN_ID of Table OPLQTPRO
     */
    private String edsNodeId;
    /**
     * String Variable to hold the value for Column P_ID of Table OPLQTPRO
     */
    private String PId;
    /**
     * Variable to hold the value for Column P_W_ID_SECOND_STAGE of Table OPLQTPRO
     */
    private EdsWording edsWordingByPWIdSecondStage;
    /**
     * Variable to hold the value for Column P_W_ID_FIRST_STAGE of Table OPLQTPRO
     */
    private EdsWording edsWordingByPWIdFirstStage;
    /**
     * Variable to hold the value for Column P_W_ID_FOURTH_STAGE of Table OPLQTPRO
     */
    private EdsWording edsWordingByPWIdFourthStage;
    /**
     * Variable to hold the value for Column P_W_ID_THIRD_STAGE of Table OPLQTPRO
     */
    private EdsWording edsWordingByPWIdThirdStage;
    /**
     * String Variable to hold the value for Column P_NAME of Table OPLQTPRO
     */
    private String PName;
    /**
     * Date Variable to hold the value for Column P_DATE_FIRST_STAGE of Table OPLQTPRO
     */
    private Date PDateFirstStage;
    /**
     * Date Variable to hold the value for Column P_DATE_SECOND_STAGE of Table OPLQTPRO
     */
    private Date PDateSecondStage;
    /**
     * Date Variable to hold the value for Column P_DATE_THIRD_STAGE of Table OPLQTPRO
     */
    private Date PDateThirdStage;
    /**
     * Date Variable to hold the value for Column P_DATE_FOURTH_STAGE of Table OPLQTPRO
     */
    private Date PDateFourthStage;
    /**
     * int Variable to hold the value for Column P_INDEX of Table OPLQTPRO
     */
    private int PIndex;
    /**
     * Set Collection to hold the values for Table OPLQTPRE
     */
    private Set edsProjectEdses = new HashSet(0);
    /**
     * Set Collection to hold the values for Table OPLQTEDS
     */
    private Set edsEdses = new HashSet(0);
    /**
     * Set Collection to hold the values for Table OPLQTPER
     */
    private Set edsPerimeters = new HashSet(0);

    /**
     * Default Constructor
     */
    public EdsProject() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param PId Project Id
     * @param PName Project Name
     * @param PIndex Project index
     */
    public EdsProject(String PId, String PName, int PIndex) {
        this.PId = PId;
        this.PName = PName;
        this.PIndex = PIndex;
    }

    /**
     * Parameterized Constructor
     * 
     * @param PId Project Id
     * @param edsWordingByPWIdSecondStage Eds Wording for second stage
     * @param edsWordingByPWIdFirstStage Eds Wording for first stage
     * @param edsWordingByPWIdFourthStage Eds Wording for fourth stage
     * @param edsWordingByPWIdThirdStage Eds Wording for third stage
     * @param PName Project name
     * @param PDateFirstStage First stage date
     * @param PDateSecondStage Second stage date
     * @param PDateThirdStage Third stage date
     * @param PDateFourthStage fourth stage date
     * @param PIndex Index
     * @param edsProjectEdses set of Eds project Eds
     * @param edsEdses set of EdsEds
     */
    public EdsProject(String PId, EdsWording edsWordingByPWIdSecondStage, EdsWording edsWordingByPWIdFirstStage,
            EdsWording edsWordingByPWIdFourthStage, EdsWording edsWordingByPWIdThirdStage, String PName, Date PDateFirstStage, Date PDateSecondStage,
            Date PDateThirdStage, Date PDateFourthStage, int PIndex, Set edsProjectEdses, Set edsEdses) {
        this.PId = PId;
        this.edsWordingByPWIdSecondStage = edsWordingByPWIdSecondStage;
        this.edsWordingByPWIdFirstStage = edsWordingByPWIdFirstStage;
        this.edsWordingByPWIdFourthStage = edsWordingByPWIdFourthStage;
        this.edsWordingByPWIdThirdStage = edsWordingByPWIdThirdStage;
        this.PName = PName;
        this.PDateFirstStage = PDateFirstStage;
        this.PDateSecondStage = PDateSecondStage;
        this.PDateThirdStage = PDateThirdStage;
        this.PDateFourthStage = PDateFourthStage;
        this.PIndex = PIndex;
        this.edsProjectEdses = edsProjectEdses;
        this.edsEdses = edsEdses;
        this.edsNodeId = null;
    }

    /**
     * Parameterized Constructor
     * 
     * @param project Eds Project
     */
    public EdsProject(EdsProject project) {
        this.PId = UUID.randomUUID().toString();
        this.edsWordingByPWIdSecondStage = project.edsWordingByPWIdSecondStage;
        this.edsWordingByPWIdFirstStage = project.edsWordingByPWIdFirstStage;
        this.edsWordingByPWIdFourthStage = project.edsWordingByPWIdFourthStage;
        this.edsWordingByPWIdThirdStage = project.edsWordingByPWIdThirdStage;
        this.PName = project.PName;
        this.PDateFirstStage = project.PDateFirstStage;
        this.PDateSecondStage = project.PDateSecondStage;
        this.PDateThirdStage = project.PDateThirdStage;
        this.PDateFourthStage = project.PDateFourthStage;
        this.PIndex = project.PIndex;
        this.edsNodeId = project.edsNodeId;
    }

    /**
     * Function to get PId
     * 
     * @return the Value of PId
     */
    @XmlTransient
    public String getPId() {
        return this.PId;
    }

    /**
     * Function to set PId
     * 
     * @param PId Id
     */
    public void setPId(String PId) {
        this.PId = PId;
    }

    /**
     * Get the EDS node ID
     * 
     * @return The EDS node ID
     */
    public String getEdsNodeId() {
        return this.edsNodeId;
    }

    /**
     * Set the EDS node ID
     * 
     * @param nodeId
     */
    public void setEdsNodeId(String edsNodeId) {
        this.edsNodeId = edsNodeId;
    }

    /**
     * Function to get edsWordingByPWIdSecondStage
     * 
     * @return the Value of edsWordingByPWIdSecondStage
     */
    @XmlElement(name = "consolidate-stage")
    public EdsWording getEdsWordingByPWIdSecondStage() {
        return this.edsWordingByPWIdSecondStage;
    }

    /**
     * Function to set edsWordingByPWIdSecondStage
     * 
     * @param edsWordingByPWIdSecondStage Eds wording for second stage
     */
    public void setEdsWordingByPWIdSecondStage(EdsWording edsWordingByPWIdSecondStage) {
        this.edsWordingByPWIdSecondStage = edsWordingByPWIdSecondStage;
    }

    /**
     * Function to get edsWordingByPWIdFirstStage
     * 
     * @return the Value of edsWordingByPWIdFirstStage
     */
    @XmlElement(name = "prelim-stage")
    public EdsWording getEdsWordingByPWIdFirstStage() {
        return this.edsWordingByPWIdFirstStage;
    }

    /**
     * Function to set edsWordingByPWIdFirstStage
     * 
     * @param edsWordingByPWIdFirstStage Eds wording for first stage
     */
    public void setEdsWordingByPWIdFirstStage(EdsWording edsWordingByPWIdFirstStage) {
        this.edsWordingByPWIdFirstStage = edsWordingByPWIdFirstStage;
    }

    /**
     * Function to get edsWordingByPWIdFourthStage
     * 
     * @return the Value of edsWordingByPWIdFourthStage
     */
    @XmlElement(name = "closed-stage")
    public EdsWording getEdsWordingByPWIdFourthStage() {
        return this.edsWordingByPWIdFourthStage;
    }

    /**
     * Function to set edsWordingByPWIdFourthStage
     * 
     * @param edsWordingByPWIdFourthStage Eds wording for fourth stage
     */
    public void setEdsWordingByPWIdFourthStage(EdsWording edsWordingByPWIdFourthStage) {
        this.edsWordingByPWIdFourthStage = edsWordingByPWIdFourthStage;
    }

    /**
     * Function to get edsWordingByPWIdThirdStage
     * 
     * @return the Value of edsWordingByPWIdThirdStage
     */
    @XmlElement(name = "robust-stage")
    public EdsWording getEdsWordingByPWIdThirdStage() {
        return this.edsWordingByPWIdThirdStage;
    }

    /**
     * Function to set edsWordingByPWIdThirdStage
     * 
     * @param edsWordingByPWIdThirdStage Eds wording for third stage
     */
    public void setEdsWordingByPWIdThirdStage(EdsWording edsWordingByPWIdThirdStage) {
        this.edsWordingByPWIdThirdStage = edsWordingByPWIdThirdStage;
    }

    /**
     * Function to get PName
     * 
     * @return the Value of PName
     */
    public String getPName() {
        return this.PName;
    }

    /**
     * Function to set PName
     * 
     * @param PName Project name
     */
    public void setPName(String PName) {
        this.PName = PName;
    }

    /**
     * Function to get PDateFirstStage
     * 
     * @return the Value of PDateFirstStage
     */
    @XmlElement(name = "prelim-date")
    public Date getPDateFirstStage() {
        return this.PDateFirstStage;
    }

    /**
     * Function to set PDateFirstStage
     * 
     * @param PDateFirstStage first stage date
     */
    public void setPDateFirstStage(Date PDateFirstStage) {
        this.PDateFirstStage = PDateFirstStage;
    }

    /**
     * Function to get PDateSecondStage
     * 
     * @return the Value of PDateSecondStage
     */
    @XmlElement(name = "robust-date")
    public Date getPDateSecondStage() {
        return this.PDateSecondStage;
    }

    /**
     * Function to set PDateSecondStage
     * 
     * @param PDateSecondStage second stage date
     */
    public void setPDateSecondStage(Date PDateSecondStage) {
        this.PDateSecondStage = PDateSecondStage;
    }

    /**
     * Function to get PDateThirdStage
     * 
     * @return the Value of PDateThirdStage
     */
    @XmlElement(name = "consolidate-date")
    public Date getPDateThirdStage() {
        return this.PDateThirdStage;
    }

    /**
     * Function to set PDateThirdStage
     * 
     * @param PDateThirdStage Third stage date
     */
    public void setPDateThirdStage(Date PDateThirdStage) {
        this.PDateThirdStage = PDateThirdStage;
    }

    /**
     * Function to get PDateFourthStage
     * 
     * @return the Value of PDateFourthStage
     */
    @XmlElement(name = "closed-date")
    public Date getPDateFourthStage() {
        return this.PDateFourthStage;
    }

    /**
     * Function to set PDateFourthStage
     * 
     * @param PDateFourthStage Fourth stage date
     */
    public void setPDateFourthStage(Date PDateFourthStage) {
        this.PDateFourthStage = PDateFourthStage;
    }

    /**
     * Function to get PIndex
     * 
     * @return the Value of PIndex
     */
    public boolean isActive() {
        return PIndex > INACTIVE;
    }

    /**
     * Function to get PIndex
     * 
     * @return the Value of PIndex
     */
    @XmlElement(name = "index")
    public int getPIndex() {
        return PIndex;
    }

    /**
     * Function to set PIndex
     * 
     * @param PIndex Idex
     */
    public void setPIndex(int PIndex) {
        this.PIndex = PIndex;
    }

    /**
     * Function to get edsProjectEdses
     * 
     * @return the Value of edsProjectEdses
     */
    @XmlTransient
    public Set getEdsProjectEdses() {
        return this.edsProjectEdses;
    }

    /**
     * Function to set edsProjectEdses
     * 
     * @param edsProjectEdses set of EdsProjectEds
     */
    public void setEdsProjectEdses(Set edsProjectEdses) {
        this.edsProjectEdses = edsProjectEdses;
    }

    /**
     * Function to get edsEdses
     * 
     * @return the Value of edsEdses
     */
    @XmlTransient
    public Set getEdsEdses() {
        return this.edsEdses;
    }

    /**
     * Function to set edsEdses
     * 
     * @param edsEdses set of EdsEds
     */
    public void setEdsEdses(Set edsEdses) {
        this.edsEdses = edsEdses;
    }

    /**
     * Function to get edsPerimeters
     * 
     * @return the Value of edsPerimeters
     */
    @XmlTransient
    public Set getEdsPerimeters() {
        return this.edsPerimeters;
    }

    /**
     * Function to set edsPerimeters
     * 
     * @param edsPerimeters Set of Eds perimeter
     */
    public void setEdsPerimeters(Set edsPerimeters) {
        this.edsPerimeters = edsPerimeters;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsProject other = (EdsProject) obj;
        if ((this.PId == null) ? (other.PId != null) : !this.PId.equals(other.PId)) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + (this.PId != null ? this.PId.hashCode() : 0);
        return hash;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return PName; // To change body of generated methods, choose Tools | Templates.
    }

}
