// Generated Aug 5, 2015 11:18:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * ChsPin generated by hbm2java
 */
package com.inetpsa.eds.dao.model;

import java.io.Serializable;

public class EdsPinComment implements Serializable {
    private long id;
    private EdsEds eds;
    private String cavity;
    private String pinType;
    private String message;

    public EdsPinComment() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((cavity == null) ? 0 : cavity.hashCode());
        result = prime * result + ((eds == null) ? 0 : eds.hashCode());
        result = prime * result + ((message == null) ? 0 : message.hashCode());
        result = prime * result + ((pinType == null) ? 0 : pinType.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EdsPinComment other = (EdsPinComment) obj;
        if (cavity == null) {
            if (other.cavity != null)
                return false;
        } else if (!cavity.equals(other.cavity))
            return false;
        if (eds == null) {
            if (other.eds != null)
                return false;
        } else if (!eds.equals(other.eds))
            return false;
        if (message == null) {
            if (other.message != null)
                return false;
        } else if (!message.equals(other.message))
            return false;
        if (pinType == null) {
            if (other.pinType != null)
                return false;
        } else if (!pinType.equals(other.pinType))
            return false;
        return true;
    }

    public EdsEds getEds() {
        return eds;
    }

    public void setEds(EdsEds eds) {
        this.eds = eds;
    }

    public String getCavity() {
        return cavity;
    }

    public void setCavity(String cavity) {
        this.cavity = cavity;
    }

    public String getPinType() {
        return pinType;
    }

    public void setPinType(String pinType) {
        this.pinType = pinType;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
