/**
 * ChsPin generated by hbm2java
 */
package com.inetpsa.eds.dao.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;

public class EdsPinTypeComment implements Serializable {
    private long id;
    private EdsEds eds;
    private String type;
    private String message;
    private Double tMax;
    private Double tMin;

    public EdsPinTypeComment() {
    }

    // Generated by Hibernate Tools
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof EdsPinTypeComment))
            return false;
        EdsPinTypeComment castOther = (EdsPinTypeComment) other;

        return (this.getEds().equals(castOther.getEds()) && this.getType().equals(castOther.getType()) && this.getMessage().equals(
                castOther.getMessage()));
    }

    // Generated by Hibernate Tools
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEds() == null ? 0 : this.getEds().hashCode());
        result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
        result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());

        return result;
    }

    @XmlTransient
    public EdsEds getEds() {
        return eds;
    }

    public void setEds(EdsEds eds) {
        this.eds = eds;
    }

    @XmlElement(name = "message")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @XmlElement(name = "type")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @XmlTransient
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @XmlElement(name = "tmax")
    public Double gettMax() {
        return tMax;
    }

    public void settMax(Double tMax) {
        this.tMax = tMax;
    }

    @XmlElement(name = "tmin")
    public Double gettMin() {
        return tMin;
    }

    public void settMin(Double tMin) {
        this.tMin = tMin;
    }

    public EdsPinTypeComment duplicate(EdsEds eds) {
        EdsPinTypeComment duplicate = new EdsPinTypeComment();
        duplicate.setEds(eds);
        duplicate.setMessage(message);
        duplicate.settMax(tMax);
        duplicate.settMin(tMin);
        duplicate.setType(type);
        return duplicate;
    }

}
