package com.inetpsa.eds.dao.model;

// Generated 10 ao�t 2012 10:14:58 by Hibernate Tools 3.2.1.GA

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.inetpsa.eds.dao.I_DriftableSupply;

/**
 * EdsRobustSupply generated by hbm2java
 */
@XmlType
public class EdsRobustSupply implements java.io.Serializable, I_DriftableSupply {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /**
     * String Variable to hold the value for Column RSEDS_ID of Table OPLQTROS
     */
    private String rsedsId;
    /**
     * String Variable to hold the value for Column RSEDS_REF of Table OPLQTROS
     */
    private String rsedsRef;
    /**
     * String Variable to hold the value for Column RSEDS_SUPPLY_NAME of Table OPLQTROS
     */
    private String rsedsSupplyName;
    /**
     * String Variable to hold the value for Column RSEDS_USE_CASE_NAME of Table OPLQTROS
     */
    private String rsedsUseCaseName;
    /**
     * String Variable to hold the value for Column RSEDS_TBT_BT of Table OPLQTROS
     */
    private String rsedsTbtBt;
    /**
     * Float Variable to hold the value for Column RSEDS_I_VEILLE of Table OPLQTROS
     */
    private Float rsedsIVeille;
    /**
     * Float Variable to hold the value for Column RSEDS_I_REVEILLE_INACTIF of Table OPLQTROS
     */
    private Float rsedsIReveilleInactif;
    /**
     * Float Variable to hold the value for Column RSEDS_I_NOM_STAB of Table OPLQTROS
     */
    private Float rsedsINomStab;
    /**
     * Float Variable to hold the value for Column RSEDS_I_PIRECAS_STAB of Table OPLQTROS
     */
    private Float rsedsIPirecasStab;
    /**
     * Float Variable to hold the value for Column RSEDS_U_MIN of Table OPLQTROS
     */
    private Float rsedsUMin;
    /**
     * Float Variable to hold the value for Column RSEDS_U_MOY of Table OPLQTROS
     */
    private Float rsedsUMoy;
    /**
     * Float Variable to hold the value for Column RSEDS_U_MAX of Table OPLQTROS
     */
    private Float rsedsUMax;
    /**
     * String Variable to hold the value for Column RSEDS_SUPPLY_NAME_IFORM_BY of Table OPLQTROS
     */
    private String rsedsSupplyNameIformBy;
    /**
     * String Variable to hold the value for Column RSEDS_SUPPLY_TYPE_SUPPLY_NAME_IFORM_BY of Table OPLQTROS
     */
    private String rsedsSupplyTypeSupplyNameIformBy;
    /**
     * String Variable to hold the value for Column RSEDS_I_VEILLE_IFORM_BY of Table OPLQTROS
     */
    private String rsedsIVeilleIformBy;
    /**
     * String Variable to hold the value for Column RSEDS_REVEILLE_IFORM_BY of Table OPLQTROS
     */
    private String rsedsReveilleIformBy;
    /**
     * String Variable to hold the value for Column RSEDS_I_NOM_STAB_IFORM_BY of Table OPLQTROS
     */
    private String rsedsINomStabIformBy;
    /**
     * String Variable to hold the value for Column RSEDS_I_PIRECAS_STAB_IFORM_BY of Table OPLQTROS
     */
    private String rsedsIPirecasStabIformBy;
    /**
     * String Variable to hold the value for Column RSEDS_U_MIN_INFORM_BY of Table OPLQTROS
     */
    private String rsedsUMinInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_U_MOY_INFORM_BY of Table OPLQTROS
     */
    private String rsedsUMoyInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_U_MAX_INFORM_BY of Table OPLQTROS
     */
    private String rsedsUMaxInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_SUPPLY_NAME_COMMENT of Table OPLQTROS
     */
    private String rsedsSupplyNameComment;
    /**
     * String Variable to hold the value for Column RSEDS_SUPPLY_TYPE_SUPPLY_NAME_COMMENT of Table OPLQTROS
     */
    private String rsedsSupplyTypeSupplyNameComment;
    /**
     * String Variable to hold the value for Column RSEDS_I_VEILLE_COMMENT of Table OPLQTROS
     */
    private String rsedsIVeilleComment;
    /**
     * String Variable to hold the value for Column RSEDS_REVEILLE_COMMENT of Table OPLQTROS
     */
    private String rsedsReveilleComment;
    /**
     * String Variable to hold the value for Column RSEDS_I_NOM_STAB_COMMENT of Table OPLQTROS
     */
    private String rsedsINomStabComment;
    /**
     * String Variable to hold the value for Column RSEDS_I_PIRECAS_COMMENT of Table OPLQTROS
     */
    private String rsedsIPirecasComment;
    /**
     * String Variable to hold the value for Column RSEDS_U_MIN_COMMENT of Table OPLQTROS
     */
    private String rsedsUMinComment;
    /**
     * String Variable to hold the value for Column RSEDS_U_MOY_COMMENT of Table OPLQTROS
     */
    private String rsedsUMoyComment;
    /**
     * String Variable to hold the value for Column RSEDS_U_MAX_COMMENT of Table OPLQTROS
     */
    private String rsedsUMaxComment;
    /**
     * Float Variable to hold the value for Column RSEDS_I_MAX of Table OPLQTROS
     */
    private Float rsedsIMax;
    /**
     * Float Variable to hold the value for Column RSEDS_T_IMAX of Table OPLQTROS
     */
    private Float rsedsTIMax;
    /**
     * String Variable to hold the value for Column RSEDS_I_MAX_INFORM_BY of Table OPLQTROS
     */
    private String rsedsIMaxInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_T_IMAX_INFORM_BY of Table OPLQTROS
     */
    private String rsedsTIMaxInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_I_MAX_INFORM_BY of Table OPLQTROS
     */
    private String rsedsIMaxComment;
    /**
     * String Variable to hold the value for Column RSEDS_T_IMAX_COMMENT of Table OPLQTROS
     */
    private String rsedsTIMaxComment;
    /**
     * String Variable to hold the value for Column RSEDS_U_CARAC_COMMENT of Table OPLQTROS
     */
    private String rsedsUcaracName;
    /**
     * Float Variable to hold the value for Column RSEDS_U_CARAC_VALUE of Table OPLQTROS
     */
    private Float rsedsUcaracValue;
    /**
     * String Variable to hold the value for Column RSEDS_U_CARAC_INFORM_BY of Table OPLQTROS
     */
    private String rsedsUcaracInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_U_CARAC_COMMENT of Table OPLQTROS
     */
    private String rsedsUcaracComment;
    /**
     * Float Variable to hold the value for Column RSEDS_I_CONSO_PARC of Table OPLQTROS
     */
    private Float rsedsIConsoParc;
    /**
     * String Variable to hold the value for Column RSEDS_I_CONSO_PARC_INFORM_BY of Table OPLQTROS
     */
    private String rsedsIConsoParcInformBy;
    /**
     * String Variable to hold the value for Column RSEDS_I_CONSO_PARC_COMMENT of Table OPLQTROS
     */
    private String rsedsIConsoParcComment;
    /**
     * String Variable to hold the value for Column RSEDS_ORGANE of Table OPLQTROS
     */
    private String rsedsOrgane;
    /**
     * Variable to hold the value for Column RSEDS_W_ID of Table OPLQTROS
     */
    private EdsWording wording;

    // New values
    /**
     * Variable to hold the value for Column RSEDS_T_NOM_STAB of Table OPLQTROS
     */
    private Float rsedsTNomStab;
    /**
     * Variable to hold the value for Column RSEDS_T_PIRE_CAS of Table OPLQTROS
     */
    private Float rsedsTPireCas;
    /**
     * Variable to hold the value for Column RSEDS_I_DYSF of Table OPLQTROS
     */
    private Float rsedsIdysf;
    /**
     * Variable to hold the value for Column RSEDS_T_DYSF of Table OPLQTROS
     */
    private Float rsedsTdysf;
    /**
     * Variable to hold the value for Column RSEDS_I_MST of Table OPLQTROS
     */
    private Float rsedsImst;
    /**
     * Variable to hold the value for Column RSEDS_T_MST of Table OPLQTROS
     */
    private Float rsedsTmst;
    /**
     * Variable to hold the value for Column RSEDS_T_NOM_STAB_INFORM_BY of Table OPLQTROS
     */
    private String rsedsTnomStabInformBy;
    /**
     * Variable to hold the value for Column RSEDS_T_PIRE_CAS_INFORM_BY of Table OPLQTROS
     */
    private String rsedsTpireCasInformBy;
    /**
     * Variable to hold the value for Column RSEDS_I_DYSF_INFORM_BY of Table OPLQTROS
     */
    private String rsedsIdysfInformBy;
    /**
     * Variable to hold the value for Column RSEDS_T_DYSF_INFORM_BY of Table OPLQTROS
     */
    private String rsedsTdysfInformBy;
    /**
     * Variable to hold the value for Column RSEDS_I_MST_INFORM_BY of Table OPLQTROS
     */
    private String rsedsImstInformBy;
    /**
     * Variable to hold the value for Column RSEDS_T_MST_INFORM_BY of Table OPLQTROS
     */
    private String rsedsTmstInformBy;
    /**
     * Variable to hold the value for Column RSEDS_T_NOM_STAB_COMMENT of Table OPLQTROS
     */
    private String rsedsTnomStabComment;
    /**
     * Variable to hold the value for Column RSEDS_T_PIRE_CAS_COMMENT of Table OPLQTROS
     */
    private String rsedsTpireCasComment;
    /**
     * Variable to hold the value for Column RSEDS_I_DYSF_COMMENT of Table OPLQTROS
     */
    private String rsedsIdysfComment;
    /**
     * Variable to hold the value for Column RSEDS_T_DYSF_COMMENT of Table OPLQTROS
     */
    private String rsedsTdysfComment;
    /**
     * Variable to hold the value for Column RSEDS_I_MST_COMMENT of Table OPLQTROS
     */
    private String rsedsImstComment;
    /**
     * Variable to hold the value for Column RSEDS_T_MST_COMMENT of Table OPLQTROS
     */
    private String rsedsTmstComment;

    /**
     * Attribute to access all the use cases of the Robust Supply
     */
    private Set<EdsRobustSupplyUseCase> useCases;

    /**
     * Default Constructor
     */
    public EdsRobustSupply() {
        useCases = new LinkedHashSet<EdsRobustSupplyUseCase>(0);
    }

    /**
     * Parameterized Constructor
     * 
     * @param rsedsId Eds Robust Supply Id
     */
    public EdsRobustSupply(String rsedsId) {
        this.rsedsId = rsedsId;
        useCases = new LinkedHashSet<EdsRobustSupplyUseCase>(0);
    }

    /**
     * Parameterized Constructor
     * 
     * @param otherSupply Eds Robust Supply
     */
    public EdsRobustSupply(EdsRobustSupply otherSupply) {
        this.rsedsId = UUID.randomUUID().toString();
        this.rsedsUseCaseName = otherSupply.rsedsUseCaseName;
        this.rsedsSupplyName = otherSupply.rsedsSupplyName;
        this.rsedsTbtBt = otherSupply.rsedsTbtBt;
        this.rsedsIVeille = otherSupply.rsedsIVeille;
        this.rsedsIReveilleInactif = otherSupply.rsedsIReveilleInactif;
        this.rsedsINomStab = otherSupply.rsedsINomStab;
        this.rsedsIPirecasStab = otherSupply.rsedsIPirecasStab;
        this.rsedsUMin = otherSupply.rsedsUMin;
        this.rsedsUMoy = otherSupply.rsedsUMoy;
        this.rsedsUMax = otherSupply.rsedsUMax;
        this.rsedsSupplyNameIformBy = otherSupply.rsedsSupplyNameIformBy;
        this.rsedsSupplyTypeSupplyNameIformBy = otherSupply.rsedsSupplyTypeSupplyNameIformBy;
        this.rsedsIVeilleIformBy = otherSupply.rsedsIVeilleIformBy;
        this.rsedsReveilleIformBy = otherSupply.rsedsReveilleIformBy;
        this.rsedsINomStabIformBy = otherSupply.rsedsINomStabIformBy;
        this.rsedsIPirecasStabIformBy = otherSupply.rsedsIPirecasStabIformBy;
        this.rsedsUMinInformBy = otherSupply.rsedsUMinInformBy;
        this.rsedsUMoyInformBy = otherSupply.rsedsUMoyInformBy;
        this.rsedsUMaxInformBy = otherSupply.rsedsUMaxInformBy;
        this.rsedsSupplyNameComment = otherSupply.rsedsSupplyNameComment;
        this.rsedsSupplyTypeSupplyNameComment = otherSupply.rsedsSupplyTypeSupplyNameComment;
        this.rsedsIVeilleComment = otherSupply.rsedsIVeilleComment;
        this.rsedsReveilleComment = otherSupply.rsedsReveilleComment;
        this.rsedsINomStabComment = otherSupply.rsedsINomStabComment;
        this.rsedsIPirecasComment = otherSupply.rsedsIPirecasComment;
        this.rsedsUMinComment = otherSupply.rsedsUMinComment;
        this.rsedsUMoyComment = otherSupply.rsedsUMoyComment;
        this.rsedsUMaxComment = otherSupply.rsedsUMaxComment;
        this.rsedsIMax = otherSupply.rsedsIMax;
        this.rsedsTIMax = otherSupply.rsedsTIMax;
        this.rsedsIMaxInformBy = otherSupply.rsedsIMaxInformBy;
        this.rsedsTIMaxInformBy = otherSupply.rsedsTIMaxInformBy;
        this.rsedsIMaxComment = otherSupply.rsedsIMaxComment;
        this.rsedsTIMaxComment = otherSupply.rsedsTIMaxComment;
        this.rsedsUcaracName = otherSupply.rsedsUcaracName;
        this.rsedsUcaracValue = otherSupply.rsedsUcaracValue;
        this.rsedsUcaracInformBy = otherSupply.rsedsUcaracInformBy;
        this.rsedsUcaracComment = otherSupply.rsedsUcaracComment;
        this.rsedsIConsoParcComment = otherSupply.rsedsIConsoParcComment;
        this.rsedsIConsoParcInformBy = otherSupply.rsedsIConsoParcInformBy;
        this.rsedsIConsoParc = otherSupply.rsedsIConsoParc;
        this.rsedsOrgane = otherSupply.rsedsOrgane;
        this.rsedsRef = otherSupply.rsedsRef;
        this.wording = otherSupply.wording;

        this.rsedsTNomStab = otherSupply.rsedsTNomStab;
        this.rsedsTnomStabInformBy = otherSupply.rsedsTnomStabInformBy;
        this.rsedsTnomStabComment = otherSupply.rsedsTnomStabComment;
        this.rsedsTPireCas = otherSupply.rsedsTPireCas;
        this.rsedsTpireCasInformBy = otherSupply.rsedsTpireCasInformBy;
        this.rsedsTpireCasComment = otherSupply.rsedsTpireCasComment;
        this.rsedsIdysf = otherSupply.rsedsIdysf;
        this.rsedsIdysfInformBy = otherSupply.rsedsIdysfInformBy;
        this.rsedsIdysfComment = otherSupply.rsedsIdysfComment;
        this.rsedsTdysf = otherSupply.rsedsTdysf;
        this.rsedsTdysfInformBy = otherSupply.rsedsTdysfInformBy;
        this.rsedsTdysfComment = otherSupply.rsedsTdysfComment;
        this.rsedsImst = otherSupply.rsedsImst;
        this.rsedsImstInformBy = otherSupply.rsedsImstInformBy;
        this.rsedsImstComment = otherSupply.rsedsImstComment;
        this.rsedsTmst = otherSupply.rsedsTmst;
        this.rsedsTmstInformBy = otherSupply.rsedsTmstInformBy;
        this.rsedsTmstComment = otherSupply.rsedsTmstComment;

        // supply's use cases
        this.useCases = new LinkedHashSet<EdsRobustSupplyUseCase>();
        for (EdsRobustSupplyUseCase useCase : otherSupply.useCases) {
            EdsRobustSupplyUseCase copyUseCase = new EdsRobustSupplyUseCase(useCase);
            copyUseCase.setRobustSupply(this);
            this.useCases.add(copyUseCase);
        }
    }

    /**
     * Function to get rsedsIVeille
     * 
     * @return the Value of rsedsIVeille
     */
    public Float getISleepCurrent() {
        return getRsedsIVeille();
    }

    /**
     * Function to get IAwake12_5
     * 
     * @return null
     */
    public Float getIAwake12_5() {
        return null;
    }

    /**
     * Function to get rsedsIReveilleInactif
     * 
     * @return the Value of rsedsIReveilleInactif
     */
    public Float getIAwake13_5() {
        return getRsedsIReveilleInactif();
    }

    /**
     * Function to get INomStab12_5
     * 
     * @return null
     */
    public Float getINomStab12_5() {
        return null;
    }

    /**
     * Function to get rsedsINomStab
     * 
     * @return the Value of rsedsINomStab
     */
    public Float getINomStab13_5() {
        return getRsedsINomStab();
    }

    /**
     * Function to get IWorstStab12_5
     * 
     * @return null
     */
    public Float getIWorstStab12_5() {
        return null;
    }

    /**
     * Function to get rsedsIPirecasStab
     * 
     * @return the Value of rsedsIPirecasStab
     */
    public Float getIWorstStab13_5() {
        return getRsedsIPirecasStab();
    }

    /**
     * Function to get rsedsId
     * 
     * @return the Value of rsedsId
     */
    @XmlAttribute(name = "id")
    public String getRsedsId() {
        return this.rsedsId;
    }

    /**
     * Function to set rsedsId
     * 
     * @param rsedsId Eds Robust Supply Id
     */
    public void setRsedsId(String rsedsId) {
        this.rsedsId = rsedsId;
    }

    /**
     * Function to get rsedsRef
     * 
     * @return the Value of rsedsRef
     */
    @XmlAttribute(name = "ref")
    public String getRsedsRef() {
        return rsedsRef;
    }

    /**
     * Function to set rsedsRef
     * 
     * @param rsedsRef Eds Robust Supply reference
     */
    public void setRsedsRef(String rsedsRef) {
        this.rsedsRef = rsedsRef;
    }

    /**
     * Function to get rsedsSupplyName
     * 
     * @return the Value of rsedsSupplyName
     */
    @XmlAttribute(name = "name")
    public String getRsedsSupplyName() {
        return this.rsedsSupplyName;
    }

    /**
     * Function to set rsedsSupplyName
     * 
     * @param rsedsSupplyName Eds Robust Supply name
     */
    public void setRsedsSupplyName(String rsedsSupplyName) {
        this.rsedsSupplyName = rsedsSupplyName;
    }

    /**
     * Function to get rsedsUseCaseName
     * 
     * @return the Value of rsedsUseCaseName
     */
    @XmlAttribute(name = "use-case-name")
    public String getRsedsUseCaseName() {
        return this.rsedsUseCaseName;
    }

    /**
     * Function to set rsedsUseCaseName
     * 
     * @param rsedsUseCaseName Eds Robust default Use Case name
     */
    public void setRsedsUseCaseName(String rsedsUseCaseName) {
        this.rsedsUseCaseName = rsedsUseCaseName;
    }

    /**
     * Function to get wording
     * 
     * @return the Value of wording
     */
    public EdsWording getWording() {
        return wording;
    }

    /**
     * Function to set wording
     * 
     * @param wording Eds Wording
     */
    public void setWording(EdsWording wording) {
        this.wording = wording;
    }

    /**
     * Function to get rsedsTbtBt
     * 
     * @return the Value of rsedsTbtBt
     */
    @XmlAttribute(name = "type")
    public String getRsedsTbtBt() {
        return this.rsedsTbtBt;
    }

    /**
     * Function to set rsedsTbtBt
     * 
     * @param rsedsTbtBt Eds Robust Supply TBT/BT
     */
    public void setRsedsTbtBt(String rsedsTbtBt) {
        this.rsedsTbtBt = rsedsTbtBt;
    }

    /**
     * Function to get rsedsIVeille
     * 
     * @return the Value of rsedsIVeille
     */
    @XmlElement(name = "i-standby")
    public Float getRsedsIVeille() {
        return this.rsedsIVeille;
    }

    /**
     * Function to set rsedsIVeille
     * 
     * @param rsedsIVeille Iawake
     */
    public void setRsedsIVeille(Float rsedsIVeille) {
        this.rsedsIVeille = rsedsIVeille;
    }

    /**
     * Function to get rsedsIReveilleInactif
     * 
     * @return the Value of rsedsIReveilleInactif
     */
    @XmlElement(name = "i-wakeup-inactive")
    public Float getRsedsIReveilleInactif() {
        return this.rsedsIReveilleInactif;
    }

    /**
     * Function to set rsedsIReveilleInactif
     * 
     * @param rsedsIReveilleInactif Iawake inactive
     */
    public void setRsedsIReveilleInactif(Float rsedsIReveilleInactif) {
        this.rsedsIReveilleInactif = rsedsIReveilleInactif;
    }

    /**
     * Function to get rsedsINomStab
     * 
     * @return the Value of rsedsINomStab
     */
    @XmlElement(name = "i-nom-stab")
    public Float getRsedsINomStab() {
        return this.rsedsINomStab;
    }

    /**
     * Function to set rsedsINomStab
     * 
     * @param rsedsINomStab Inob stab
     */
    public void setRsedsINomStab(Float rsedsINomStab) {
        this.rsedsINomStab = rsedsINomStab;
    }

    /**
     * Function to get rsedsIPirecasStab
     * 
     * @return the Value of rsedsIPirecasStab
     */
    @XmlElement(name = "i-worst-stab")
    public Float getRsedsIPirecasStab() {
        return this.rsedsIPirecasStab;
    }

    /**
     * Function to set rsedsIPirecasStab
     * 
     * @param rsedsIPirecasStab Iworst stab
     */
    public void setRsedsIPirecasStab(Float rsedsIPirecasStab) {
        this.rsedsIPirecasStab = rsedsIPirecasStab;
    }

    /**
     * Function to get rsedsUMin
     * 
     * @return the Value of rsedsUMin
     */
    @XmlElement(name = "u-min")
    public Float getRsedsUMin() {
        return this.rsedsUMin;
    }

    /**
     * Function to set rsedsUMin
     * 
     * @param rsedsUMin Umin
     */
    public void setRsedsUMin(Float rsedsUMin) {
        this.rsedsUMin = rsedsUMin;
    }

    /**
     * Function to get rsedsUMoy
     * 
     * @return the Value of rsedsUMoy
     */
    @XmlElement(name = "u-med")
    public Float getRsedsUMoy() {
        return this.rsedsUMoy;
    }

    /**
     * Function to set rsedsUMoy
     * 
     * @param rsedsUMoy Umed
     */
    public void setRsedsUMoy(Float rsedsUMoy) {
        this.rsedsUMoy = rsedsUMoy;
    }

    /**
     * Function to get rsedsUMax
     * 
     * @return the Value of rsedsUMax
     */
    @XmlElement(name = "u-max")
    public Float getRsedsUMax() {
        return this.rsedsUMax;
    }

    /**
     * Function to set rsedsUMax
     * 
     * @param rsedsUMax Umax
     */
    public void setRsedsUMax(Float rsedsUMax) {
        this.rsedsUMax = rsedsUMax;
    }

    /**
     * Function to get rsedsSupplyNameIformBy
     * 
     * @return the Value of rsedsSupplyNameIformBy
     */
    @XmlTransient
    public String getRsedsSupplyNameIformBy() {
        return this.rsedsSupplyNameIformBy;
    }

    /**
     * Function to set rsedsSupplyNameIformBy
     * 
     * @param rsedsSupplyNameIformBy Eds Supply Name Iform By
     */
    public void setRsedsSupplyNameIformBy(String rsedsSupplyNameIformBy) {
        this.rsedsSupplyNameIformBy = rsedsSupplyNameIformBy;
    }

    /**
     * Function to get rsedsSupplyTypeSupplyNameIformBy
     * 
     * @return the Value of rsedsSupplyTypeSupplyNameIformBy
     */
    @XmlTransient
    public String getRsedsSupplyTypeSupplyNameIformBy() {
        return this.rsedsSupplyTypeSupplyNameIformBy;
    }

    /**
     * Function to set rsedsSupplyTypeSupplyNameIformBy
     * 
     * @param rsedsSupplyTypeSupplyNameIformBy Eds Supply Type Eds supply name Iform By
     */
    public void setRsedsSupplyTypeSupplyNameIformBy(String rsedsSupplyTypeSupplyNameIformBy) {
        this.rsedsSupplyTypeSupplyNameIformBy = rsedsSupplyTypeSupplyNameIformBy;
    }

    /**
     * Function to get rsedsIVeilleIformBy
     * 
     * @return the Value of rsedsIVeilleIformBy
     */
    @XmlTransient
    public String getRsedsIVeilleIformBy() {
        return this.rsedsIVeilleIformBy;
    }

    /**
     * Function to set rsedsIVeilleIformBy
     * 
     * @param rsedsIVeilleIformBy Iawake Iform By
     */
    public void setRsedsIVeilleIformBy(String rsedsIVeilleIformBy) {
        this.rsedsIVeilleIformBy = rsedsIVeilleIformBy;
    }

    /**
     * Function to get rsedsReveilleIformBy
     * 
     * @return the Value of rsedsReveilleIformBy
     */
    @XmlTransient
    public String getRsedsReveilleIformBy() {
        return this.rsedsReveilleIformBy;
    }

    /**
     * Function to set rsedsReveilleIformBy
     * 
     * @param rsedsReveilleIformBy Awake Iform by
     */
    public void setRsedsReveilleIformBy(String rsedsReveilleIformBy) {
        this.rsedsReveilleIformBy = rsedsReveilleIformBy;
    }

    /**
     * Function to get rsedsINomStabIformBy
     * 
     * @return the Value of rsedsINomStabIformBy
     */
    @XmlTransient
    public String getRsedsINomStabIformBy() {
        return this.rsedsINomStabIformBy;
    }

    /**
     * Function to set rsedsINomStabIformBy
     * 
     * @param rsedsINomStabIformBy Inob stab Iform By
     */
    public void setRsedsINomStabIformBy(String rsedsINomStabIformBy) {
        this.rsedsINomStabIformBy = rsedsINomStabIformBy;
    }

    /**
     * Function to get rsedsIPirecasStabIformBy
     * 
     * @return the Value of rsedsIPirecasStabIformBy
     */
    @XmlTransient
    public String getRsedsIPirecasStabIformBy() {
        return this.rsedsIPirecasStabIformBy;
    }

    /**
     * Function to set rsedsIPirecasStabIformBy
     * 
     * @param rsedsIPirecasStabIformBy Iworst case Iform By
     */
    public void setRsedsIPirecasStabIformBy(String rsedsIPirecasStabIformBy) {
        this.rsedsIPirecasStabIformBy = rsedsIPirecasStabIformBy;
    }

    /**
     * Function to get rsedsUMinInformBy
     * 
     * @return the Value of rsedsUMinInformBy
     */
    @XmlTransient
    public String getRsedsUMinInformBy() {
        return this.rsedsUMinInformBy;
    }

    /**
     * Function to set rsedsUMinInformBy
     * 
     * @param rsedsUMinInformBy Umin Inform By
     */
    public void setRsedsUMinInformBy(String rsedsUMinInformBy) {
        this.rsedsUMinInformBy = rsedsUMinInformBy;
    }

    /**
     * Function to get rsedsUMoyInformBy
     * 
     * @return the Value of rsedsUMoyInformBy
     */
    @XmlTransient
    public String getRsedsUMoyInformBy() {
        return this.rsedsUMoyInformBy;
    }

    /**
     * Function to set rsedsUMoyInformBy
     * 
     * @param rsedsUMoyInformBy Umed Inform By
     */
    public void setRsedsUMoyInformBy(String rsedsUMoyInformBy) {
        this.rsedsUMoyInformBy = rsedsUMoyInformBy;
    }

    /**
     * Function to get rsedsUMaxInformBy
     * 
     * @return the Value of rsedsUMaxInformBy
     */
    @XmlTransient
    public String getRsedsUMaxInformBy() {
        return this.rsedsUMaxInformBy;
    }

    /**
     * Function to set rsedsUMaxInformBy
     * 
     * @param rsedsUMaxInformBy Umax Iform By
     */
    public void setRsedsUMaxInformBy(String rsedsUMaxInformBy) {
        this.rsedsUMaxInformBy = rsedsUMaxInformBy;
    }

    /**
     * Function to get rsedsIMax
     * 
     * @return the Value of rsedsIMax
     */
    @XmlElement(name = "i-pic")
    public Float getRsedsIMax() {
        return rsedsIMax;
    }

    /**
     * Function to set rsedsIMax
     * 
     * @param rsedsIMax Imax
     */
    public void setRsedsIMax(Float rsedsIMax) {
        this.rsedsIMax = rsedsIMax;
    }

    /**
     * Function to get rsedsIMaxComment
     * 
     * @return the Value of rsedsIMaxComment
     */
    @XmlElement(name = "rsedsIPicComment")
    public String getRsedsIMaxComment() {
        return rsedsIMaxComment;
    }

    /**
     * Function to set rsedsIMaxComment
     * 
     * @param rsedsIMaxComment Imax comment
     */
    public void setRsedsIMaxComment(String rsedsIMaxComment) {
        this.rsedsIMaxComment = rsedsIMaxComment;
    }

    /**
     * Function to get rsedsIMaxInformBy
     * 
     * @return the Value of rsedsIMaxInformBy
     */
    @XmlTransient
    public String getRsedsIMaxInformBy() {
        return rsedsIMaxInformBy;
    }

    /**
     * Function to set rsedsIMaxInformBy
     * 
     * @param rsedsIMaxInformBy Imax Inform By
     */
    public void setRsedsIMaxInformBy(String rsedsIMaxInformBy) {
        this.rsedsIMaxInformBy = rsedsIMaxInformBy;
    }

    /**
     * Function to get rsedsTIMax
     * 
     * @return the Value of rsedsTIMax
     */
    @XmlElement(name = "t-pic")
    public Float getRsedsTIMax() {
        return rsedsTIMax;
    }

    /**
     * Function to set rsedsTIMax
     * 
     * @param rsedsTIMax TImax
     */
    public void setRsedsTIMax(Float rsedsTIMax) {
        this.rsedsTIMax = rsedsTIMax;
    }

    /**
     * Function to get rsedsTIMaxComment
     * 
     * @return the Value of rsedsTIMaxComment
     */
    @XmlElement(name = "rsedsTPicComment")
    public String getRsedsTIMaxComment() {
        return rsedsTIMaxComment;
    }

    /**
     * Function to set rsedsTIMaxComment
     * 
     * @param rsedsTIMaxComment TImax comment
     */
    public void setRsedsTIMaxComment(String rsedsTIMaxComment) {
        this.rsedsTIMaxComment = rsedsTIMaxComment;
    }

    /**
     * Function to get rsedsTIMaxInformBy
     * 
     * @return the Value of rsedsTIMaxInformBy
     */
    @XmlTransient
    public String getRsedsTIMaxInformBy() {
        return rsedsTIMaxInformBy;
    }

    /**
     * Function to set rsedsTIMaxInformBy
     * 
     * @param rsedsTIMaxInformBy TImax Inform By
     */
    public void setRsedsTIMaxInformBy(String rsedsTIMaxInformBy) {
        this.rsedsTIMaxInformBy = rsedsTIMaxInformBy;
    }

    /**
     * Function to get rsedsSupplyNameComment
     * 
     * @return the Value of rsedsSupplyNameComment
     */
    @XmlTransient
    public String getRsedsSupplyNameComment() {
        return this.rsedsSupplyNameComment;
    }

    /**
     * Function to set rsedsSupplyNameComment
     * 
     * @param rsedsSupplyNameComment Eds Supply Name comment
     */
    public void setRsedsSupplyNameComment(String rsedsSupplyNameComment) {
        this.rsedsSupplyNameComment = rsedsSupplyNameComment;
    }

    /**
     * Function to get rsedsSupplyTypeSupplyNameComment
     * 
     * @return the Value of rsedsSupplyTypeSupplyNameComment
     */
    @XmlTransient
    public String getRsedsSupplyTypeSupplyNameComment() {
        return this.rsedsSupplyTypeSupplyNameComment;
    }

    /**
     * Function to set rsedsSupplyTypeSupplyNameComment
     * 
     * @param rsedsSupplyTypeSupplyNameComment Eds supply type Eds supply name comment
     */
    public void setRsedsSupplyTypeSupplyNameComment(String rsedsSupplyTypeSupplyNameComment) {
        this.rsedsSupplyTypeSupplyNameComment = rsedsSupplyTypeSupplyNameComment;
    }

    /**
     * Function to get rsedsIVeilleComment
     * 
     * @return the Value of rsedsIVeilleComment
     */
    public String getRsedsIVeilleComment() {
        return this.rsedsIVeilleComment;
    }

    /**
     * Function to set rsedsIVeilleComment
     * 
     * @param rsedsIVeilleComment Isleep comment
     */
    public void setRsedsIVeilleComment(String rsedsIVeilleComment) {
        this.rsedsIVeilleComment = rsedsIVeilleComment;
    }

    /**
     * Function to get rsedsReveilleComment
     * 
     * @return the Value of rsedsReveilleComment
     */
    public String getRsedsReveilleComment() {
        return this.rsedsReveilleComment;
    }

    /**
     * Function to set rsedsReveilleComment
     * 
     * @param rsedsReveilleComment Iawake comment
     */
    public void setRsedsReveilleComment(String rsedsReveilleComment) {
        this.rsedsReveilleComment = rsedsReveilleComment;
    }

    /**
     * Function to get rsedsINomStabComment
     * 
     * @return the Value of rsedsINomStabComment
     */
    public String getRsedsINomStabComment() {
        return this.rsedsINomStabComment;
    }

    /**
     * Function to set rsedsINomStabComment
     * 
     * @param rsedsINomStabComment Inob stab comment
     */
    public void setRsedsINomStabComment(String rsedsINomStabComment) {
        this.rsedsINomStabComment = rsedsINomStabComment;
    }

    /**
     * Function to get rsedsIPirecasComment
     * 
     * @return the Value of rsedsIPirecasComment
     */
    public String getRsedsIPirecasComment() {
        return this.rsedsIPirecasComment;
    }

    /**
     * Function to set rsedsIPirecasComment
     * 
     * @param rsedsIPirecasComment Iworst case comment
     */
    public void setRsedsIPirecasComment(String rsedsIPirecasComment) {
        this.rsedsIPirecasComment = rsedsIPirecasComment;
    }

    /**
     * Function to get rsedsUMinComment
     * 
     * @return the Value of rsedsUMinComment
     */
    public String getRsedsUMinComment() {
        return this.rsedsUMinComment;
    }

    /**
     * Function to set rsedsUMinComment
     * 
     * @param rsedsUMinComment Umin comment
     */
    public void setRsedsUMinComment(String rsedsUMinComment) {
        this.rsedsUMinComment = rsedsUMinComment;
    }

    /**
     * Function to get rsedsUMoyComment
     * 
     * @return the Value of rsedsUMoyComment
     */
    public String getRsedsUMoyComment() {
        return this.rsedsUMoyComment;
    }

    /**
     * Function to set rsedsUMoyComment
     * 
     * @param rsedsUMoyComment Umec domment
     */
    public void setRsedsUMoyComment(String rsedsUMoyComment) {
        this.rsedsUMoyComment = rsedsUMoyComment;
    }

    /**
     * Function to get rsedsUMaxComment
     * 
     * @return the Value of rsedsUMaxComment
     */
    public String getRsedsUMaxComment() {
        return this.rsedsUMaxComment;
    }

    /**
     * Function to set rsedsUMaxComment
     * 
     * @param rsedsUMaxComment Umax comment
     */
    public void setRsedsUMaxComment(String rsedsUMaxComment) {
        this.rsedsUMaxComment = rsedsUMaxComment;
    }

    /**
     * Function to get rsedsUcaracComment
     * 
     * @return the Value of rsedsUcaracComment
     */
    public String getRsedsUcaracComment() {
        return rsedsUcaracComment;
    }

    /**
     * Function to set rsedsUcaracComment
     * 
     * @param rsedsUcaracComment Ucarac comment
     */
    public void setRsedsUcaracComment(String rsedsUcaracComment) {
        this.rsedsUcaracComment = rsedsUcaracComment;
    }

    /**
     * Function to get rsedsUcaracInformBy
     * 
     * @return the Value of rsedsUcaracInformBy
     */
    @XmlTransient
    public String getRsedsUcaracInformBy() {
        return rsedsUcaracInformBy;
    }

    /**
     * Function to set rsedsUcaracInformBy
     * 
     * @param rsedsUcaracInformBy Ucarac Inform By
     */
    public void setRsedsUcaracInformBy(String rsedsUcaracInformBy) {
        this.rsedsUcaracInformBy = rsedsUcaracInformBy;
    }

    /**
     * Function to get rsedsUcaracName
     * 
     * @return the Value of rsedsUcaracName
     */
    @XmlElement(name = "u-carac-name")
    public String getRsedsUcaracName() {
        return rsedsUcaracName;
    }

    /**
     * Function to set rsedsUcaracName
     * 
     * @param rsedsUcaracName Ucarac Name
     */
    public void setRsedsUcaracName(String rsedsUcaracName) {
        this.rsedsUcaracName = rsedsUcaracName;
    }

    /**
     * Function to get rsedsUcaracValue
     * 
     * @return the Value of rsedsUcaracValue
     */
    @XmlElement(name = "u-carac-value")
    public Float getRsedsUcaracValue() {
        return rsedsUcaracValue;
    }

    /**
     * Function to set rsedsUcaracValue
     * 
     * @param rsedsUcaracValue Ucarac value
     */
    public void setRsedsUcaracValue(Float rsedsUcaracValue) {
        this.rsedsUcaracValue = rsedsUcaracValue;
    }

    /**
     * Function to get rsedsIConsoParc
     * 
     * @return the Value of rsedsIConsoParc
     */
    public Float getRsedsIConsoParc() {
        return rsedsIConsoParc;
    }

    /**
     * Function to set rsedsIConsoParc
     * 
     * @param rsedsIConsoParc Ipark
     */
    public void setRsedsIConsoParc(Float rsedsIConsoParc) {
        this.rsedsIConsoParc = rsedsIConsoParc;
    }

    /**
     * Function to get rsedsIConsoParcComment
     * 
     * @return the Value of rsedsIConsoParcComment
     */
    public String getRsedsIConsoParcComment() {
        return rsedsIConsoParcComment;
    }

    /**
     * Function to set rsedsIConsoParcComment
     * 
     * @param rsedsIConsoParcComment Ipark comment
     */
    public void setRsedsIConsoParcComment(String rsedsIConsoParcComment) {
        this.rsedsIConsoParcComment = rsedsIConsoParcComment;
    }

    /**
     * Function to get rsedsIConsoParcInformBy
     * 
     * @return the Value of rsedsIConsoParcInformBy
     */
    @XmlTransient
    public String getRsedsIConsoParcInformBy() {
        return rsedsIConsoParcInformBy;
    }

    /**
     * Function to set rsedsIConsoParcInformBy
     * 
     * @param rsedsIConsoParcInformBy Ipark Inform By
     */
    public void setRsedsIConsoParcInformBy(String rsedsIConsoParcInformBy) {
        this.rsedsIConsoParcInformBy = rsedsIConsoParcInformBy;
    }

    /**
     * Function to get rsedsOrgane
     * 
     * @return the Value of rsedsOrgane
     */
    public String getRsedsOrgane() {
        return rsedsOrgane;
    }

    /**
     * Function to set rsedsOrgane
     * 
     * @param rsedsOrgane Organe
     */
    public void setRsedsOrgane(String rsedsOrgane) {
        this.rsedsOrgane = rsedsOrgane;
    }

    /**
     * Function to get useCases
     * 
     * @return the Value of useCases
     */
    @XmlElement(name = "use-cases")
    public Set<EdsRobustSupplyUseCase> getUseCases() {
        return useCases;
    }

    /**
     * Function to set useCases
     * 
     * @param useCases Set
     */
    public void setUseCases(Set<EdsRobustSupplyUseCase> useCases) {
        this.useCases = useCases;
    }

    /**
     * Getter rsedsTnomStab
     * 
     * @return the rsedsTnomStab
     */
    @XmlElement(name = "t-nom-stab")
    public Float getRsedsTNomStab() {
        return rsedsTNomStab;
    }

    /**
     * Setter rsedsTnomStab
     * 
     * @param rsedsTnomStab the rsedsTnomStab to set
     */
    public void setRsedsTNomStab(Float rsedsTnomStab) {
        this.rsedsTNomStab = rsedsTnomStab;
    }

    /**
     * Getter rsedsTpireCas
     * 
     * @return the rsedsTpireCas
     */
    @XmlElement(name = "t-pire-cas")
    public Float getRsedsTPireCas() {
        return rsedsTPireCas;
    }

    /**
     * Setter rsedsTpireCas
     * 
     * @param rsedsTpireCas the rsedsTpireCas to set
     */
    public void setRsedsTPireCas(Float rsedsTpireCas) {
        this.rsedsTPireCas = rsedsTpireCas;
    }

    /**
     * Getter rsedsIdysf
     * 
     * @return the rsedsIdysf
     */
    @XmlElement(name = "i-dysf")
    public Float getRsedsIdysf() {
        return rsedsIdysf;
    }

    /**
     * Setter rsedsIdysf
     * 
     * @param rsedsIdysf the rsedsIdysf to set
     */
    public void setRsedsIdysf(Float rsedsIdysf) {
        this.rsedsIdysf = rsedsIdysf;
    }

    /**
     * Getter rsedsTdysf
     * 
     * @return the rsedsTdysf
     */
    @XmlElement(name = "t-dysf")
    public Float getRsedsTdysf() {
        return rsedsTdysf;
    }

    /**
     * Setter rsedsTdysf
     * 
     * @param rsedsTdysf the rsedsTdysf to set
     */
    public void setRsedsTdysf(Float rsedsTdysf) {
        this.rsedsTdysf = rsedsTdysf;
    }

    /**
     * Getter rsedsImst
     * 
     * @return the rsedsImst
     */
    @XmlElement(name = "i-mst")
    public Float getRsedsImst() {
        return rsedsImst;
    }

    /**
     * Setter rsedsImst
     * 
     * @param rsedsImst the rsedsImst to set
     */
    public void setRsedsImst(Float rsedsImst) {
        this.rsedsImst = rsedsImst;
    }

    /**
     * Getter rsedsTmst
     * 
     * @return the rsedsTmst
     */
    @XmlElement(name = "t-mst")
    public Float getRsedsTmst() {
        return rsedsTmst;
    }

    /**
     * Setter rsedsTmst
     * 
     * @param rsedsTmst the rsedsTmst to set
     */
    public void setRsedsTmst(Float rsedsTmst) {
        this.rsedsTmst = rsedsTmst;
    }

    /**
     * Getter rsedsTnomStabInformBy
     * 
     * @return the rsedsTnomStabInformBy
     */
    @XmlTransient
    public String getRsedsTnomStabInformBy() {
        return rsedsTnomStabInformBy;
    }

    /**
     * Setter rsedsTnomStabInformBy
     * 
     * @param rsedsTnomStabInformBy the rsedsTnomStabInformBy to set
     */
    public void setRsedsTnomStabInformBy(String rsedsTnomStabInformBy) {
        this.rsedsTnomStabInformBy = rsedsTnomStabInformBy;
    }

    /**
     * Getter rsedsTpireCasInformBy
     * 
     * @return the rsedsTpireCasInformBy
     */
    @XmlTransient
    public String getRsedsTpireCasInformBy() {
        return rsedsTpireCasInformBy;
    }

    /**
     * Setter rsedsTpireCasInformBy
     * 
     * @param rsedsTpireCasInformBy the rsedsTpireCasInformBy to set
     */
    public void setRsedsTpireCasInformBy(String rsedsTpireCasInformBy) {
        this.rsedsTpireCasInformBy = rsedsTpireCasInformBy;
    }

    /**
     * Getter rsedsIdysfInformBy
     * 
     * @return the rsedsIdysfInformBy
     */
    @XmlTransient
    public String getRsedsIdysfInformBy() {
        return rsedsIdysfInformBy;
    }

    /**
     * Setter rsedsIdysfInformBy
     * 
     * @param rsedsIdysfInformBy the rsedsIdysfInformBy to set
     */
    public void setRsedsIdysfInformBy(String rsedsIdysfInformBy) {
        this.rsedsIdysfInformBy = rsedsIdysfInformBy;
    }

    /**
     * Getter rsedsTdysfInformBy
     * 
     * @return the rsedsTdysfInformBy
     */
    @XmlTransient
    public String getRsedsTdysfInformBy() {
        return rsedsTdysfInformBy;
    }

    /**
     * Setter rsedsTdysfInformBy
     * 
     * @param rsedsTdysfInformBy the rsedsTdysfInformBy to set
     */
    public void setRsedsTdysfInformBy(String rsedsTdysfInformBy) {
        this.rsedsTdysfInformBy = rsedsTdysfInformBy;
    }

    /**
     * Getter rsedsImstInformBy
     * 
     * @return the rsedsImstInformBy
     */
    @XmlTransient
    public String getRsedsImstInformBy() {
        return rsedsImstInformBy;
    }

    /**
     * Setter rsedsImstInformBy
     * 
     * @param rsedsImstInformBy the rsedsImstInformBy to set
     */
    public void setRsedsImstInformBy(String rsedsImstInformBy) {
        this.rsedsImstInformBy = rsedsImstInformBy;
    }

    /**
     * Getter rsedsTmstInformBy
     * 
     * @return the rsedsTmstInformBy
     */
    @XmlTransient
    public String getRsedsTmstInformBy() {
        return rsedsTmstInformBy;
    }

    /**
     * Setter rsedsTmstInformBy
     * 
     * @param rsedsTmstInformBy the rsedsTmstInformBy to set
     */
    public void setRsedsTmstInformBy(String rsedsTmstInformBy) {
        this.rsedsTmstInformBy = rsedsTmstInformBy;
    }

    /**
     * Getter rsedsTnomStabComment
     * 
     * @return the rsedsTnomStabComment
     */
    public String getRsedsTnomStabComment() {
        return rsedsTnomStabComment;
    }

    /**
     * Setter rsedsTnomStabComment
     * 
     * @param rsedsTnomStabComment the rsedsTnomStabComment to set
     */
    public void setRsedsTnomStabComment(String rsedsTnomStabComment) {
        this.rsedsTnomStabComment = rsedsTnomStabComment;
    }

    /**
     * Getter rsedsTpireCasComment
     * 
     * @return the rsedsTpireCasComment
     */
    public String getRsedsTpireCasComment() {
        return rsedsTpireCasComment;
    }

    /**
     * Setter rsedsTpireCasComment
     * 
     * @param rsedsTpireCasComment the rsedsTpireCasComment to set
     */
    public void setRsedsTpireCasComment(String rsedsTpireCasComment) {
        this.rsedsTpireCasComment = rsedsTpireCasComment;
    }

    /**
     * Getter rsedsIdysfComment
     * 
     * @return the rsedsIdysfComment
     */
    public String getRsedsIdysfComment() {
        return rsedsIdysfComment;
    }

    /**
     * Setter rsedsIdysfComment
     * 
     * @param rsedsIdysfComment the rsedsIdysfComment to set
     */
    public void setRsedsIdysfComment(String rsedsIdysfComment) {
        this.rsedsIdysfComment = rsedsIdysfComment;
    }

    /**
     * Getter rsedsTdysfComment
     * 
     * @return the rsedsTdysfComment
     */
    public String getRsedsTdysfComment() {
        return rsedsTdysfComment;
    }

    /**
     * Setter rsedsTdysfComment
     * 
     * @param rsedsTdysfComment the rsedsTdysfComment to set
     */
    public void setRsedsTdysfComment(String rsedsTdysfComment) {
        this.rsedsTdysfComment = rsedsTdysfComment;
    }

    /**
     * Getter rsedsImstComment
     * 
     * @return the rsedsImstComment
     */
    public String getRsedsImstComment() {
        return rsedsImstComment;
    }

    /**
     * Setter rsedsImstComment
     * 
     * @param rsedsImstComment the rsedsImstComment to set
     */
    public void setRsedsImstComment(String rsedsImstComment) {
        this.rsedsImstComment = rsedsImstComment;
    }

    /**
     * Getter rsedsTmstComment
     * 
     * @return the rsedsTmstComment
     */
    public String getRsedsTmstComment() {
        return rsedsTmstComment;
    }

    /**
     * Setter rsedsTmstComment
     * 
     * @param rsedsTmstComment the rsedsTmstComment to set
     */
    public void setRsedsTmstComment(String rsedsTmstComment) {
        this.rsedsTmstComment = rsedsTmstComment;
    }

    /**
     * Function to check entered value are complete and in float format
     * 
     * @return boolean value
     */
    public boolean isComplete() {
        if (rsedsIMax == null || rsedsIMax == Float.NaN) {
            return false;
        } else if (rsedsIVeille == null || rsedsIVeille == Float.NaN) {
            return false;
        } else if (rsedsIReveilleInactif == null || rsedsIReveilleInactif == Float.NaN) {
            return false;
        } else if (rsedsIPirecasStab == null || rsedsIPirecasStab == Float.NaN) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return rsedsSupplyName + "(" + rsedsTbtBt + (rsedsTbtBt.equals("TBT") ? "" : "/" + rsedsOrgane) + ")";
    }
}
