package com.inetpsa.eds.dao.model;

// Generated 22 sept. 2012 08:59:24 by Hibernate Tools 3.2.1.GA

import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

/**
 * EdsReseauVeilleReveilleOrganeInactif generated by hbm2java
 */
public class EdsReseauVeilleReveilleOrganeInactif implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column RVROIEDS_ID of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsId;

    /**
     * Variable to hold value of Column RVROIEDS_NAME of Table EDS_COURANT_NOMINALE_ACTIVATION
     */
    private String rvroiedsName;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IVEILLE_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIveilleMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_ID of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIveilleMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IVEILLE_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIveilleMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IVEILLE_8H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIveille8hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IVEILLE_8H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIveille8hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IVEILLE_8H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIveille8hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IVEILLE_21H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIveille21hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IVEILLE_21H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIveille21hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IVEILLE_21H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIveille21hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IVEILLE_30H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIveille30hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IVEILLE_30H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIveille30hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IVEILLE_30H_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIveille30hMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IREVEILLE_INACTIF_MOTEUR_NON_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIreveilleInactifMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IREVEILLE_INACTIF_MOTEUR_NON_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIreveilleInactifMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IREVEILLE_INACTIF_MOTEUR_NON_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIreveilleInactifMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IMODE_ECO_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminImodeEcoMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IMODE_ECO_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyImodeEcoMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IMODE_ECO_MOTEUR_NON_TOURANT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxImodeEcoMoteurNonTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IREVEILLE_INACTIF_10V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIreveilleInactif10vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IREVEILLE_INACTIF_13V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIreveilleInactif13vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMIN_IREVEILLE_INACTIF_15V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTminIreveilleInactif15vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IREVEILLE_INACTIF_10V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIreveilleInactif10vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IREVEILLE_INACTIF_13V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIreveilleInactif13vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMOY_IREVEILLE_INACTIF_15V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmoyIreveilleInactif15vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IREVEILLE_INACTIF_10V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIreveilleInactif10vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IREVEILLE_INACTIF_13V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIreveilleInactif13vMoteurTourant;
    /**
     * Float Variable to hold the value for Column RVROIEDS_TMAX_IREVEILLE_INACTIF_15V_MOTEUR_TOURANT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private Float rvroiedsTmaxIreveilleInactif15vMoteurTourant;
    /**
     * String Variable to hold the value for Column RVROIEDS_IVEILLE_MOTEUR_NON_TOURANT_COMMENT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIveilleMoteurNonTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IVEILLE_8H_MOTEUR_NON_TOURANT_COMMENT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIveille8hMoteurNonTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IVEILLE_21H_MOTEUR_NON_TOURANT_COMMENT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIveille21hMoteurNonTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IVEILLE_30H_MOTEUR_NON_TOURANT_COMMENT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIveille30hMoteurNonTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IREVEILLE_INACTIF_MOTEUR_NON_TOURANT_COMMENT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIreveilleInactifMoteurNonTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IMODE_ECO_MOTEUR_NON_TOURANT_COMMENT of Table EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsImodeEcoMoteurNonTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IREVEILLE_INACTIF_10V_MOTEUR_TOURANT_COMMENT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIreveilleInactif10vMoteurTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IREVEILLE_INACTIF_13V_MOTEUR_TOURANT_COMMENT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIreveilleInactif13vMoteurTourantComment;
    /**
     * String Variable to hold the value for Column RVROIEDS_IREVEILLE_INACTIF_15V_MOTEUR_TOURANT_COMMENT of Table
     * EDS_RESEAU_VEILLE_REVEILLE_ORGANE_INACTIF
     */
    private String rvroiedsIreveilleInactif15vMoteurTourantComment;

    /**
     * Default Constructor
     */
    public EdsReseauVeilleReveilleOrganeInactif() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param rvroiedsId Id
     */
    public EdsReseauVeilleReveilleOrganeInactif(String rvroiedsId) {
        this.rvroiedsId = rvroiedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param srcEdsReseauVeilleReveilleOrganeInactif
     */
    public EdsReseauVeilleReveilleOrganeInactif(EdsReseauVeilleReveilleOrganeInactif srcEdsReseauVeilleReveilleOrganeInactif) {
        this.rvroiedsId = UUID.randomUUID().toString();
        this.rvroiedsName = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsName;
        this.rvroiedsTminIveilleMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminIveilleMoteurNonTourant;
        this.rvroiedsTmoyIveilleMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyIveilleMoteurNonTourant;
        this.rvroiedsTmaxIveilleMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxIveilleMoteurNonTourant;
        this.rvroiedsTminIveille8hMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminIveille8hMoteurNonTourant;
        this.rvroiedsTmoyIveille21hMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyIveille21hMoteurNonTourant;
        this.rvroiedsTmaxIveille30hMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxIveille30hMoteurNonTourant;
        this.rvroiedsTminIreveilleInactifMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminIreveilleInactifMoteurNonTourant;
        this.rvroiedsTmoyIreveilleInactifMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyIreveilleInactifMoteurNonTourant;
        this.rvroiedsTmaxIreveilleInactifMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxIreveilleInactifMoteurNonTourant;
        this.rvroiedsTminImodeEcoMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminImodeEcoMoteurNonTourant;
        this.rvroiedsTmoyImodeEcoMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyImodeEcoMoteurNonTourant;
        this.rvroiedsTmaxImodeEcoMoteurNonTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxImodeEcoMoteurNonTourant;
        this.rvroiedsTminIreveilleInactif10vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminIreveilleInactif10vMoteurTourant;
        this.rvroiedsTminIreveilleInactif13vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminIreveilleInactif13vMoteurTourant;
        this.rvroiedsTminIreveilleInactif15vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTminIreveilleInactif15vMoteurTourant;
        this.rvroiedsTmoyIreveilleInactif10vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyIreveilleInactif10vMoteurTourant;
        this.rvroiedsTmoyIreveilleInactif13vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyIreveilleInactif13vMoteurTourant;
        this.rvroiedsTmoyIreveilleInactif15vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmoyIreveilleInactif15vMoteurTourant;
        this.rvroiedsTmaxIreveilleInactif10vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxIreveilleInactif10vMoteurTourant;
        this.rvroiedsTmaxIreveilleInactif13vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxIreveilleInactif13vMoteurTourant;
        this.rvroiedsTmaxIreveilleInactif15vMoteurTourant = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsTmaxIreveilleInactif15vMoteurTourant;
        this.rvroiedsIveilleMoteurNonTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIveilleMoteurNonTourantComment;
        this.rvroiedsIveille8hMoteurNonTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIveille8hMoteurNonTourantComment;
        this.rvroiedsIveille21hMoteurNonTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIveille21hMoteurNonTourantComment;
        this.rvroiedsIveille30hMoteurNonTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIveille30hMoteurNonTourantComment;
        this.rvroiedsIreveilleInactifMoteurNonTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIreveilleInactifMoteurNonTourantComment;
        this.rvroiedsImodeEcoMoteurNonTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsImodeEcoMoteurNonTourantComment;
        this.rvroiedsIreveilleInactif10vMoteurTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIreveilleInactif10vMoteurTourantComment;
        this.rvroiedsIreveilleInactif13vMoteurTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIreveilleInactif13vMoteurTourantComment;
        this.rvroiedsIreveilleInactif15vMoteurTourantComment = srcEdsReseauVeilleReveilleOrganeInactif.rvroiedsIreveilleInactif15vMoteurTourantComment;
    }

    /**
     * Function to get rvroiedsId
     * 
     * @return the Value of rvroiedsId
     */
    @XmlAttribute(name = "id")
    public String getRvroiedsId() {
        return this.rvroiedsId;
    }

    /**
     * Function to set rvroiedsId
     * 
     * @param rvroiedsId Id
     */
    public void setRvroiedsId(String rvroiedsId) {
        this.rvroiedsId = rvroiedsId;
    }

    /**
     * Getter rvroiedsName
     * 
     * @return the rvroiedsName
     */
    public String getRvroiedsName() {
        return this.rvroiedsName;
    }

    /**
     * Setter rvroiedsName
     * 
     * @param rvroiedsName the rvroiedsName to set
     */
    public void setRvroiedsName(String rvroiedsName) {
        this.rvroiedsName = rvroiedsName;
    }

    /**
     * Function to get rvroiedsTminIveilleMoteurNonTourant
     * 
     * @return the Value of rvroiedsTminIveilleMoteurNonTourant
     */
    @XmlElement(name = "TminIveilleMoteurNonTourant")
    public Float getRvroiedsTminIveilleMoteurNonTourant() {
        return this.rvroiedsTminIveilleMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmaxIveille8hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmaxIveille8hMoteurNonTourant
     */
    @XmlElement(name = "TmaxIveille8hMoteurNonTourant")
    public Float getRvroiedsTmaxIveille8hMoteurNonTourant() {
        return rvroiedsTmaxIveille8hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmaxIveille8hMoteurNonTourant
     * 
     * @param rvroiedsTmaxIveille8hMoteurNonTourant
     */
    public void setRvroiedsTmaxIveille8hMoteurNonTourant(Float rvroiedsTmaxIveille8hMoteurNonTourant) {
        this.rvroiedsTmaxIveille8hMoteurNonTourant = rvroiedsTmaxIveille8hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmoyIveille8hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmoyIveille8hMoteurNonTourant
     */
    @XmlElement(name = "TmoyIveille8hMoteurNonTourant")
    public Float getRvroiedsTmoyIveille8hMoteurNonTourant() {
        return rvroiedsTmoyIveille8hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmoyIveille8hMoteurNonTourant
     * 
     * @param rvroiedsTmoyIveille8hMoteurNonTourant
     */
    public void setRvroiedsTmoyIveille8hMoteurNonTourant(Float rvroiedsTmoyIveille8hMoteurNonTourant) {
        this.rvroiedsTmoyIveille8hMoteurNonTourant = rvroiedsTmoyIveille8hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTminIveilleMoteurNonTourant
     * 
     * @param rvroiedsTminIveilleMoteurNonTourant
     */
    public void setRvroiedsTminIveilleMoteurNonTourant(Float rvroiedsTminIveilleMoteurNonTourant) {
        this.rvroiedsTminIveilleMoteurNonTourant = rvroiedsTminIveilleMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmoyIveilleMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmoyIveilleMoteurNonTourant
     */
    @XmlElement(name = "TmoyIveilleMoteurNonTourant")
    public Float getRvroiedsTmoyIveilleMoteurNonTourant() {
        return this.rvroiedsTmoyIveilleMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmoyIveilleMoteurNonTourant
     * 
     * @param rvroiedsTmoyIveilleMoteurNonTourant
     */
    public void setRvroiedsTmoyIveilleMoteurNonTourant(Float rvroiedsTmoyIveilleMoteurNonTourant) {
        this.rvroiedsTmoyIveilleMoteurNonTourant = rvroiedsTmoyIveilleMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmaxIveilleMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmaxIveilleMoteurNonTourant
     */
    @XmlElement(name = "TmaxIveilleMoteurNonTourant")
    public Float getRvroiedsTmaxIveilleMoteurNonTourant() {
        return this.rvroiedsTmaxIveilleMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmaxIveilleMoteurNonTourant
     * 
     * @param rvroiedsTmaxIveilleMoteurNonTourant
     */
    public void setRvroiedsTmaxIveilleMoteurNonTourant(Float rvroiedsTmaxIveilleMoteurNonTourant) {
        this.rvroiedsTmaxIveilleMoteurNonTourant = rvroiedsTmaxIveilleMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTminIveille8hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTminIveille8hMoteurNonTourant
     */
    @XmlElement(name = "TminIveille8hMoteurNonTourant")
    public Float getRvroiedsTminIveille8hMoteurNonTourant() {
        return this.rvroiedsTminIveille8hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTminIveille8hMoteurNonTourant
     * 
     * @param rvroiedsTminIveille8hMoteurNonTourant
     */
    public void setRvroiedsTminIveille8hMoteurNonTourant(Float rvroiedsTminIveille8hMoteurNonTourant) {
        this.rvroiedsTminIveille8hMoteurNonTourant = rvroiedsTminIveille8hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmoyIveille21hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmoyIveille21hMoteurNonTourant
     */
    @XmlElement(name = "TmoyIveille21hMoteurNonTourant")
    public Float getRvroiedsTmoyIveille21hMoteurNonTourant() {
        return this.rvroiedsTmoyIveille21hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmoyIveille21hMoteurNonTourant
     * 
     * @param rvroiedsTmoyIveille21hMoteurNonTourant
     */
    public void setRvroiedsTmoyIveille21hMoteurNonTourant(Float rvroiedsTmoyIveille21hMoteurNonTourant) {
        this.rvroiedsTmoyIveille21hMoteurNonTourant = rvroiedsTmoyIveille21hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmaxIveille30hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmaxIveille30hMoteurNonTourant
     */
    @XmlElement(name = "TmaxIveille30hMoteurNonTourant")
    public Float getRvroiedsTmaxIveille30hMoteurNonTourant() {
        return this.rvroiedsTmaxIveille30hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmaxIveille30hMoteurNonTourant
     * 
     * @param rvroiedsTmaxIveille30hMoteurNonTourant
     */
    public void setRvroiedsTmaxIveille30hMoteurNonTourant(Float rvroiedsTmaxIveille30hMoteurNonTourant) {
        this.rvroiedsTmaxIveille30hMoteurNonTourant = rvroiedsTmaxIveille30hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTminIreveilleInactifMoteurNonTourant
     * 
     * @return the Value of rvroiedsTminIreveilleInactifMoteurNonTourant
     */
    @XmlElement(name = "TminIreveilleInactifMoteurNonTourant")
    public Float getRvroiedsTminIreveilleInactifMoteurNonTourant() {
        return this.rvroiedsTminIreveilleInactifMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTminIreveilleInactifMoteurNonTourant
     * 
     * @param rvroiedsTminIreveilleInactifMoteurNonTourant
     */
    public void setRvroiedsTminIreveilleInactifMoteurNonTourant(Float rvroiedsTminIreveilleInactifMoteurNonTourant) {
        this.rvroiedsTminIreveilleInactifMoteurNonTourant = rvroiedsTminIreveilleInactifMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmoyIreveilleInactifMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmoyIreveilleInactifMoteurNonTourant
     */
    @XmlElement(name = "TmoyIreveilleInactifMoteurNonTourant")
    public Float getRvroiedsTmoyIreveilleInactifMoteurNonTourant() {
        return this.rvroiedsTmoyIreveilleInactifMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmoyIreveilleInactifMoteurNonTourant
     * 
     * @param rvroiedsTmoyIreveilleInactifMoteurNonTourant
     */
    public void setRvroiedsTmoyIreveilleInactifMoteurNonTourant(Float rvroiedsTmoyIreveilleInactifMoteurNonTourant) {
        this.rvroiedsTmoyIreveilleInactifMoteurNonTourant = rvroiedsTmoyIreveilleInactifMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmaxIreveilleInactifMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmaxIreveilleInactifMoteurNonTourant
     */
    @XmlElement(name = "TmaxIreveilleInactifMoteurNonTourant")
    public Float getRvroiedsTmaxIreveilleInactifMoteurNonTourant() {
        return this.rvroiedsTmaxIreveilleInactifMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmaxIreveilleInactifMoteurNonTourant
     * 
     * @param rvroiedsTmaxIreveilleInactifMoteurNonTourant
     */
    public void setRvroiedsTmaxIreveilleInactifMoteurNonTourant(Float rvroiedsTmaxIreveilleInactifMoteurNonTourant) {
        this.rvroiedsTmaxIreveilleInactifMoteurNonTourant = rvroiedsTmaxIreveilleInactifMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTminImodeEcoMoteurNonTourant
     * 
     * @return the Value of rvroiedsTminImodeEcoMoteurNonTourant
     */
    @XmlElement(name = "TminImodeEcoMoteurNonTourant")
    public Float getRvroiedsTminImodeEcoMoteurNonTourant() {
        return this.rvroiedsTminImodeEcoMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmaxIveille21hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmaxIveille21hMoteurNonTourant
     */
    @XmlElement(name = "TmaxIveille21hMoteurNonTourant")
    public Float getRvroiedsTmaxIveille21hMoteurNonTourant() {
        return rvroiedsTmaxIveille21hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmaxIveille21hMoteurNonTourant
     * 
     * @param rvroiedsTmaxIveille21hMoteurNonTourant
     */
    public void setRvroiedsTmaxIveille21hMoteurNonTourant(Float rvroiedsTmaxIveille21hMoteurNonTourant) {
        this.rvroiedsTmaxIveille21hMoteurNonTourant = rvroiedsTmaxIveille21hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTminIveille21hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTminIveille21hMoteurNonTourant
     */
    @XmlElement(name = "TminIveille21hMoteurNonTourant")
    public Float getRvroiedsTminIveille21hMoteurNonTourant() {
        return rvroiedsTminIveille21hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTminIveille21hMoteurNonTourant
     * 
     * @param rvroiedsTminIveille21hMoteurNonTourant
     */
    public void setRvroiedsTminIveille21hMoteurNonTourant(Float rvroiedsTminIveille21hMoteurNonTourant) {
        this.rvroiedsTminIveille21hMoteurNonTourant = rvroiedsTminIveille21hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTminIveille30hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTminIveille30hMoteurNonTourant
     */
    @XmlElement(name = "TminIveille30hMoteurNonTourant")
    public Float getRvroiedsTminIveille30hMoteurNonTourant() {
        return rvroiedsTminIveille30hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTminIveille30hMoteurNonTourant
     * 
     * @param rvroiedsTminIveille30hMoteurNonTourant
     */
    public void setRvroiedsTminIveille30hMoteurNonTourant(Float rvroiedsTminIveille30hMoteurNonTourant) {
        this.rvroiedsTminIveille30hMoteurNonTourant = rvroiedsTminIveille30hMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmoyIveille30hMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmoyIveille30hMoteurNonTourant
     */
    @XmlElement(name = "TmoyIveille30hMoteurNonTourant")
    public Float getRvroiedsTmoyIveille30hMoteurNonTourant() {
        return rvroiedsTmoyIveille30hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmoyIveille30hMoteurNonTourant
     * 
     * @param rvroiedsTmoyIveille30hMoteurNonTourant
     */
    public void setRvroiedsTmoyIveille30hMoteurNonTourant(Float rvroiedsTmoyIveille30hMoteurNonTourant) {
        this.rvroiedsTmoyIveille30hMoteurNonTourant = rvroiedsTmoyIveille30hMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTminImodeEcoMoteurNonTourant
     * 
     * @param rvroiedsTminImodeEcoMoteurNonTourant
     */
    public void setRvroiedsTminImodeEcoMoteurNonTourant(Float rvroiedsTminImodeEcoMoteurNonTourant) {
        this.rvroiedsTminImodeEcoMoteurNonTourant = rvroiedsTminImodeEcoMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmoyImodeEcoMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmoyImodeEcoMoteurNonTourant
     */
    @XmlElement(name = "TmoyImodeEcoMoteurNonTourant")
    public Float getRvroiedsTmoyImodeEcoMoteurNonTourant() {
        return this.rvroiedsTmoyImodeEcoMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmoyImodeEcoMoteurNonTourant
     * 
     * @param rvroiedsTmoyImodeEcoMoteurNonTourant
     */
    public void setRvroiedsTmoyImodeEcoMoteurNonTourant(Float rvroiedsTmoyImodeEcoMoteurNonTourant) {
        this.rvroiedsTmoyImodeEcoMoteurNonTourant = rvroiedsTmoyImodeEcoMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTmaxImodeEcoMoteurNonTourant
     * 
     * @return the Value of rvroiedsTmaxImodeEcoMoteurNonTourant
     */
    @XmlElement(name = "TmaxImodeEcoMoteurNonTourant")
    public Float getRvroiedsTmaxImodeEcoMoteurNonTourant() {
        return this.rvroiedsTmaxImodeEcoMoteurNonTourant;
    }

    /**
     * Function to set rvroiedsTmaxImodeEcoMoteurNonTourant
     * 
     * @param rvroiedsTmaxImodeEcoMoteurNonTourant
     */
    public void setRvroiedsTmaxImodeEcoMoteurNonTourant(Float rvroiedsTmaxImodeEcoMoteurNonTourant) {
        this.rvroiedsTmaxImodeEcoMoteurNonTourant = rvroiedsTmaxImodeEcoMoteurNonTourant;
    }

    /**
     * Function to get rvroiedsTminIreveilleInactif10vMoteurTourant
     * 
     * @return the Value of rvroiedsTminIreveilleInactif10vMoteurTourant
     */
    @XmlElement(name = "TminIreveilleInactif10vMoteurTourant")
    public Float getRvroiedsTminIreveilleInactif10vMoteurTourant() {
        return this.rvroiedsTminIreveilleInactif10vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTminIreveilleInactif10vMoteurTourant
     * 
     * @param rvroiedsTminIreveilleInactif10vMoteurTourant
     */
    public void setRvroiedsTminIreveilleInactif10vMoteurTourant(Float rvroiedsTminIreveilleInactif10vMoteurTourant) {
        this.rvroiedsTminIreveilleInactif10vMoteurTourant = rvroiedsTminIreveilleInactif10vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTminIreveilleInactif13vMoteurTourant
     * 
     * @return the Value of rvroiedsTminIreveilleInactif13vMoteurTourant
     */
    @XmlElement(name = "TminIreveilleInactif13vMoteurTourant")
    public Float getRvroiedsTminIreveilleInactif13vMoteurTourant() {
        return this.rvroiedsTminIreveilleInactif13vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTminIreveilleInactif13vMoteurTourant
     * 
     * @param rvroiedsTminIreveilleInactif13vMoteurTourant
     */
    public void setRvroiedsTminIreveilleInactif13vMoteurTourant(Float rvroiedsTminIreveilleInactif13vMoteurTourant) {
        this.rvroiedsTminIreveilleInactif13vMoteurTourant = rvroiedsTminIreveilleInactif13vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTminIreveilleInactif15vMoteurTourant
     * 
     * @return the Value of rvroiedsTminIreveilleInactif15vMoteurTourant
     */
    @XmlElement(name = "TminIreveilleInactif15vMoteurTourant")
    public Float getRvroiedsTminIreveilleInactif15vMoteurTourant() {
        return this.rvroiedsTminIreveilleInactif15vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTminIreveilleInactif15vMoteurTourant
     * 
     * @param rvroiedsTminIreveilleInactif15vMoteurTourant
     */
    public void setRvroiedsTminIreveilleInactif15vMoteurTourant(Float rvroiedsTminIreveilleInactif15vMoteurTourant) {
        this.rvroiedsTminIreveilleInactif15vMoteurTourant = rvroiedsTminIreveilleInactif15vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTmoyIreveilleInactif10vMoteurTourant
     * 
     * @return the Value of rvroiedsTmoyIreveilleInactif10vMoteurTourant
     */
    @XmlElement(name = "TmoyIreveilleInactif10vMoteurTourant")
    public Float getRvroiedsTmoyIreveilleInactif10vMoteurTourant() {
        return this.rvroiedsTmoyIreveilleInactif10vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTmoyIreveilleInactif10vMoteurTourant
     * 
     * @param rvroiedsTmoyIreveilleInactif10vMoteurTourant
     */
    public void setRvroiedsTmoyIreveilleInactif10vMoteurTourant(Float rvroiedsTmoyIreveilleInactif10vMoteurTourant) {
        this.rvroiedsTmoyIreveilleInactif10vMoteurTourant = rvroiedsTmoyIreveilleInactif10vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTmoyIreveilleInactif13vMoteurTourant
     * 
     * @return the Value of rvroiedsTmoyIreveilleInactif13vMoteurTourant
     */
    @XmlElement(name = "TmoyIreveilleInactif13vMoteurTourant")
    public Float getRvroiedsTmoyIreveilleInactif13vMoteurTourant() {
        return this.rvroiedsTmoyIreveilleInactif13vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTmoyIreveilleInactif13vMoteurTourant
     * 
     * @param rvroiedsTmoyIreveilleInactif13vMoteurTourant
     */
    public void setRvroiedsTmoyIreveilleInactif13vMoteurTourant(Float rvroiedsTmoyIreveilleInactif13vMoteurTourant) {
        this.rvroiedsTmoyIreveilleInactif13vMoteurTourant = rvroiedsTmoyIreveilleInactif13vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTmoyIreveilleInactif15vMoteurTourant
     * 
     * @return the Value of rvroiedsTmoyIreveilleInactif15vMoteurTourant
     */
    @XmlElement(name = "TmoyIreveilleInactif15vMoteurTourant")
    public Float getRvroiedsTmoyIreveilleInactif15vMoteurTourant() {
        return this.rvroiedsTmoyIreveilleInactif15vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTmoyIreveilleInactif15vMoteurTourant
     * 
     * @param rvroiedsTmoyIreveilleInactif15vMoteurTourant
     */
    public void setRvroiedsTmoyIreveilleInactif15vMoteurTourant(Float rvroiedsTmoyIreveilleInactif15vMoteurTourant) {
        this.rvroiedsTmoyIreveilleInactif15vMoteurTourant = rvroiedsTmoyIreveilleInactif15vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTmaxIreveilleInactif10vMoteurTourant
     * 
     * @return the Value of rvroiedsTmaxIreveilleInactif10vMoteurTourant
     */
    @XmlElement(name = "TmaxIreveilleInactif10vMoteurTourant")
    public Float getRvroiedsTmaxIreveilleInactif10vMoteurTourant() {
        return this.rvroiedsTmaxIreveilleInactif10vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTmaxIreveilleInactif10vMoteurTourant
     * 
     * @param rvroiedsTmaxIreveilleInactif10vMoteurTourant
     */
    public void setRvroiedsTmaxIreveilleInactif10vMoteurTourant(Float rvroiedsTmaxIreveilleInactif10vMoteurTourant) {
        this.rvroiedsTmaxIreveilleInactif10vMoteurTourant = rvroiedsTmaxIreveilleInactif10vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTmaxIreveilleInactif13vMoteurTourant
     * 
     * @return the Value of rvroiedsTmaxIreveilleInactif13vMoteurTourant
     */
    @XmlElement(name = "TmaxIreveilleInactif13vMoteurTourant")
    public Float getRvroiedsTmaxIreveilleInactif13vMoteurTourant() {
        return this.rvroiedsTmaxIreveilleInactif13vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTmaxIreveilleInactif13vMoteurTourant
     * 
     * @param rvroiedsTmaxIreveilleInactif13vMoteurTourant
     */
    public void setRvroiedsTmaxIreveilleInactif13vMoteurTourant(Float rvroiedsTmaxIreveilleInactif13vMoteurTourant) {
        this.rvroiedsTmaxIreveilleInactif13vMoteurTourant = rvroiedsTmaxIreveilleInactif13vMoteurTourant;
    }

    /**
     * Function to get rvroiedsTmaxIreveilleInactif15vMoteurTourant
     * 
     * @return the Value of rvroiedsTmaxIreveilleInactif15vMoteurTourant
     */
    @XmlElement(name = "TmaxIreveilleInactif15vMoteurTourant")
    public Float getRvroiedsTmaxIreveilleInactif15vMoteurTourant() {
        return this.rvroiedsTmaxIreveilleInactif15vMoteurTourant;
    }

    /**
     * Function to set rvroiedsTmaxIreveilleInactif15vMoteurTourant
     * 
     * @param rvroiedsTmaxIreveilleInactif15vMoteurTourant
     */
    public void setRvroiedsTmaxIreveilleInactif15vMoteurTourant(Float rvroiedsTmaxIreveilleInactif15vMoteurTourant) {
        this.rvroiedsTmaxIreveilleInactif15vMoteurTourant = rvroiedsTmaxIreveilleInactif15vMoteurTourant;
    }

    /**
     * Function to get rvroiedsIveilleMoteurNonTourantComment
     * 
     * @return the Value of rvroiedsIveilleMoteurNonTourantComment
     */
    public String getRvroiedsIveilleMoteurNonTourantComment() {
        return this.rvroiedsIveilleMoteurNonTourantComment;
    }

    /**
     * Function to set rvroiedsIveilleMoteurNonTourantComment
     * 
     * @param rvroiedsIveilleMoteurNonTourantComment
     */
    public void setRvroiedsIveilleMoteurNonTourantComment(String rvroiedsIveilleMoteurNonTourantComment) {
        this.rvroiedsIveilleMoteurNonTourantComment = rvroiedsIveilleMoteurNonTourantComment;
    }

    /**
     * Function to get rvroiedsIveille8hMoteurNonTourantComment
     * 
     * @return the Value of rvroiedsIveille8hMoteurNonTourantComment
     */
    public String getRvroiedsIveille8hMoteurNonTourantComment() {
        return this.rvroiedsIveille8hMoteurNonTourantComment;
    }

    /**
     * Function to set rvroiedsIveille8hMoteurNonTourantComment
     * 
     * @param rvroiedsIveille8hMoteurNonTourantComment
     */
    public void setRvroiedsIveille8hMoteurNonTourantComment(String rvroiedsIveille8hMoteurNonTourantComment) {
        this.rvroiedsIveille8hMoteurNonTourantComment = rvroiedsIveille8hMoteurNonTourantComment;
    }

    /**
     * Function to get rvroiedsIveille21hMoteurNonTourantComment
     * 
     * @return the Value of rvroiedsIveille21hMoteurNonTourantComment
     */
    public String getRvroiedsIveille21hMoteurNonTourantComment() {
        return this.rvroiedsIveille21hMoteurNonTourantComment;
    }

    /**
     * Function to set rvroiedsIveille21hMoteurNonTourantComment
     * 
     * @param rvroiedsIveille21hMoteurNonTourantComment
     */
    public void setRvroiedsIveille21hMoteurNonTourantComment(String rvroiedsIveille21hMoteurNonTourantComment) {
        this.rvroiedsIveille21hMoteurNonTourantComment = rvroiedsIveille21hMoteurNonTourantComment;
    }

    /**
     * Function to get rvroiedsIveille30hMoteurNonTourantComment
     * 
     * @return the Value of rvroiedsIveille30hMoteurNonTourantComment
     */
    public String getRvroiedsIveille30hMoteurNonTourantComment() {
        return this.rvroiedsIveille30hMoteurNonTourantComment;
    }

    /**
     * Function to set rvroiedsIveille30hMoteurNonTourantComment
     * 
     * @param rvroiedsIveille30hMoteurNonTourantComment
     */
    public void setRvroiedsIveille30hMoteurNonTourantComment(String rvroiedsIveille30hMoteurNonTourantComment) {
        this.rvroiedsIveille30hMoteurNonTourantComment = rvroiedsIveille30hMoteurNonTourantComment;
    }

    /**
     * Function to get rvroiedsIreveilleInactifMoteurNonTourantComment
     * 
     * @return the Value of rvroiedsIreveilleInactifMoteurNonTourantComment
     */
    public String getRvroiedsIreveilleInactifMoteurNonTourantComment() {
        return this.rvroiedsIreveilleInactifMoteurNonTourantComment;
    }

    /**
     * Function to set rvroiedsIreveilleInactifMoteurNonTourantComment
     * 
     * @param rvroiedsIreveilleInactifMoteurNonTourantComment
     */
    public void setRvroiedsIreveilleInactifMoteurNonTourantComment(String rvroiedsIreveilleInactifMoteurNonTourantComment) {
        this.rvroiedsIreveilleInactifMoteurNonTourantComment = rvroiedsIreveilleInactifMoteurNonTourantComment;
    }

    /**
     * Function to get rvroiedsImodeEcoMoteurNonTourantComment
     * 
     * @return the Value of rvroiedsImodeEcoMoteurNonTourantComment
     */
    public String getRvroiedsImodeEcoMoteurNonTourantComment() {
        return this.rvroiedsImodeEcoMoteurNonTourantComment;
    }

    /**
     * Function to set rvroiedsImodeEcoMoteurNonTourantComment
     * 
     * @param rvroiedsImodeEcoMoteurNonTourantComment
     */
    public void setRvroiedsImodeEcoMoteurNonTourantComment(String rvroiedsImodeEcoMoteurNonTourantComment) {
        this.rvroiedsImodeEcoMoteurNonTourantComment = rvroiedsImodeEcoMoteurNonTourantComment;
    }

    /**
     * Function to get rvroiedsIreveilleInactif10vMoteurTourantComment
     * 
     * @return the Value of rvroiedsIreveilleInactif10vMoteurTourantComment
     */
    public String getRvroiedsIreveilleInactif10vMoteurTourantComment() {
        return this.rvroiedsIreveilleInactif10vMoteurTourantComment;
    }

    /**
     * Function to set rvroiedsIreveilleInactif10vMoteurTourantComment
     * 
     * @param rvroiedsIreveilleInactif10vMoteurTourantComment
     */
    public void setRvroiedsIreveilleInactif10vMoteurTourantComment(String rvroiedsIreveilleInactif10vMoteurTourantComment) {
        this.rvroiedsIreveilleInactif10vMoteurTourantComment = rvroiedsIreveilleInactif10vMoteurTourantComment;
    }

    /**
     * Function to get rvroiedsIreveilleInactif13vMoteurTourantComment
     * 
     * @return the Value of rvroiedsIreveilleInactif13vMoteurTourantComment
     */
    public String getRvroiedsIreveilleInactif13vMoteurTourantComment() {
        return this.rvroiedsIreveilleInactif13vMoteurTourantComment;
    }

    /**
     * Function to set rvroiedsIreveilleInactif13vMoteurTourantComment
     * 
     * @param rvroiedsIreveilleInactif13vMoteurTourantComment
     */
    public void setRvroiedsIreveilleInactif13vMoteurTourantComment(String rvroiedsIreveilleInactif13vMoteurTourantComment) {
        this.rvroiedsIreveilleInactif13vMoteurTourantComment = rvroiedsIreveilleInactif13vMoteurTourantComment;
    }

    /**
     * Function to get rvroiedsIreveilleInactif15vMoteurTourantComment
     * 
     * @return the Value of rvroiedsIreveilleInactif15vMoteurTourantComment
     */
    public String getRvroiedsIreveilleInactif15vMoteurTourantComment() {
        return this.rvroiedsIreveilleInactif15vMoteurTourantComment;
    }

    /**
     * Function to set rvroiedsIreveilleInactif15vMoteurTourantComment
     * 
     * @param rvroiedsIreveilleInactif15vMoteurTourantComment
     */
    public void setRvroiedsIreveilleInactif15vMoteurTourantComment(String rvroiedsIreveilleInactif15vMoteurTourantComment) {
        this.rvroiedsIreveilleInactif15vMoteurTourantComment = rvroiedsIreveilleInactif15vMoteurTourantComment;
    }
}
