package com.inetpsa.eds.dao.model;

// Generated 10 ao�t 2012 10:14:58 by Hibernate Tools 3.2.1.GA

import java.util.UUID;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.inetpsa.eds.dao.I_DriftableSupply;

/**
 * EdsRobustSupply generated by hbm2java
 */
@XmlType
public class EdsRobustSupplyUseCase implements java.io.Serializable, I_DriftableSupply {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /**
     * String Variable to hold the value for Column RSUC_ID of Table OPLQTRSU
     */
    private String rsucId;
    /**
     * String Variable to hold the value for Column RSUC_USECASE_NAME of Table OPLQTRSU
     */
    private String rsucName;
    /**
     * boolean Variable to hold the value for Column RSUC_REMOVE of Table EDS_COURANT_APPELLE_ACTIVATION
     */
    private boolean rsucRemove;
    /**
     * Attribute to access the parent Robust Supply
     */
    private EdsRobustSupply robustSupply;

    /**
     * Float Variable to hold the value for Column RSUC_I_VEILLE of Table OPLQTRSU
     */
    private Float rsucIVeille;
    /**
     * Float Variable to hold the value for Column RSUC_I_reveil_INACTIF of Table OPLQTRSU
     */
    private Float rsucIReveilInactif;
    /**
     * Float Variable to hold the value for Column RSUC_I_NOM_STAB of Table OPLQTRSU
     */
    private Float rsucINomStab;
    /**
     * Float Variable to hold the value for Column RSUC_I_PIRECAS_STAB of Table OPLQTRSU
     */
    private Float rsucIPirecasStab;
    /**
     * Float Variable to hold the value for Column RSUC_U_MIN of Table OPLQTRSU
     */
    private Float rsucUMin;
    /**
     * Float Variable to hold the value for Column RSUC_U_MOY of Table OPLQTRSU
     */
    private Float rsucUMoy;
    /**
     * Float Variable to hold the value for Column RSUC_U_MAX of Table OPLQTRSU
     */
    private Float rsucUMax;
    /**
     * String Variable to hold the value for Column RSUC_I_VEILLE_IFORM_BY of Table OPLQTRSU
     */
    private String rsucIVeilleIformBy;
    /**
     * String Variable to hold the value for Column RSUC_reveil_IFORM_BY of Table OPLQTRSU
     */
    private String rsucIReveilIformBy;
    /**
     * String Variable to hold the value for Column RSUC_I_NOM_STAB_IFORM_BY of Table OPLQTRSU
     */
    private String rsucINomStabIformBy;
    /**
     * String Variable to hold the value for Column RSUC_I_PIRECAS_STAB_IFORM_BY of Table OPLQTRSU
     */
    private String rsucIPirecasStabIformBy;
    /**
     * String Variable to hold the value for Column RSUC_U_MIN_INFORM_BY of Table OPLQTRSU
     */
    private String rsucUMinInformBy;
    /**
     * String Variable to hold the value for Column RSUC_U_MOY_INFORM_BY of Table OPLQTRSU
     */
    private String rsucUMoyInformBy;
    /**
     * String Variable to hold the value for Column RSUC_U_MAX_INFORM_BY of Table OPLQTRSU
     */
    private String rsucUMaxInformBy;
    /**
     * String Variable to hold the value for Column RSUC_I_VEILLE_COMMENT of Table OPLQTRSU
     */
    private String rsucIVeilleComment;
    /**
     * String Variable to hold the value for Column RSUC_reveil_COMMENT of Table OPLQTRSU
     */
    private String rsucIReveilComment;
    /**
     * String Variable to hold the value for Column RSUC_I_NOM_STAB_COMMENT of Table OPLQTRSU
     */
    private String rsucINomStabComment;
    /**
     * String Variable to hold the value for Column RSUC_I_PIRECAS_COMMENT of Table OPLQTRSU
     */
    private String rsucIPirecasComment;
    /**
     * String Variable to hold the value for Column RSUC_U_MIN_COMMENT of Table OPLQTRSU
     */
    private String rsucUMinComment;
    /**
     * String Variable to hold the value for Column RSUC_U_MOY_COMMENT of Table OPLQTRSU
     */
    private String rsucUMoyComment;
    /**
     * String Variable to hold the value for Column RSUC_U_MAX_COMMENT of Table OPLQTRSU
     */
    private String rsucUMaxComment;
    /**
     * Float Variable to hold the value for Column RSUC_I_MAX of Table OPLQTRSU
     */
    private Float rsucIMax;
    /**
     * Float Variable to hold the value for Column RSUC_T_IMAX of Table OPLQTRSU
     */
    private Float rsucTIMax;
    /**
     * String Variable to hold the value for Column RSUC_I_MAX_INFORM_BY of Table OPLQTRSU
     */
    private String rsucIMaxInformBy;
    /**
     * String Variable to hold the value for Column RSUC_T_IMAX_INFORM_BY of Table OPLQTRSU
     */
    private String rsucTIMaxInformBy;
    /**
     * String Variable to hold the value for Column RSUC_I_MAX_INFORM_BY of Table OPLQTRSU
     */
    private String rsucIMaxComment;
    /**
     * String Variable to hold the value for Column RSUC_T_IMAX_COMMENT of Table OPLQTRSU
     */
    private String rsucTIMaxComment;
    /**
     * Float Variable to hold the value for Column RSUC_U_CARAC_VALUE of Table OPLQTRSU
     */
    private Float rsucUCaracValue;
    /**
     * String Variable to hold the value for Column RSUC_U_CARAC_INFORM_BY of Table OPLQTRSU
     */
    private String rsucUCaracInformBy;
    /**
     * String Variable to hold the value for Column RSUC_U_CARAC_COMMENT of Table OPLQTRSU
     */
    private String rsucUCaracComment;
    /**
     * Float Variable to hold the value for Column RSUC_I_CONSO_PARC of Table OPLQTRSU
     */
    private Float rsucIConsoParc;
    /**
     * String Variable to hold the value for Column RSUC_I_CONSO_PARC_INFORM_BY of Table OPLQTRSU
     */
    private String rsucIConsoParcInformBy;
    /**
     * String Variable to hold the value for Column RSUC_I_CONSO_PARC_COMMENT of Table OPLQTRSU
     */
    private String rsucIConsoParcComment;

    // New values
    /**
     * Variable to hold the value for Column RSUC_T_NOM_STAB of Table OPLQTRSU
     */
    private Float rsucTNomStab;
    /**
     * Variable to hold the value for Column RSUC_T_PIRE_CAS of Table OPLQTRSU
     */
    private Float rsucTPireCas;
    /**
     * Variable to hold the value for Column RSUC_I_DYSF of Table OPLQTRSU
     */
    private Float rsucIdysf;
    /**
     * Variable to hold the value for Column RSUC_T_DYSF of Table OPLQTRSU
     */
    private Float rsucTdysf;
    /**
     * Variable to hold the value for Column RSUC_I_MST of Table OPLQTRSU
     */
    private Float rsucImst;
    /**
     * Variable to hold the value for Column RSUC_T_MST of Table OPLQTRSU
     */
    private Float rsucTmst;
    /**
     * Variable to hold the value for Column RSUC_T_NOM_STAB_INFORM_BY of Table OPLQTRSU
     */
    private String rsucTnomStabInformBy;
    /**
     * Variable to hold the value for Column RSUC_T_PIRE_CAS_INFORM_BY of Table OPLQTRSU
     */
    private String rsucTpireCasInformBy;
    /**
     * Variable to hold the value for Column RSUC_I_DYSF_INFORM_BY of Table OPLQTRSU
     */
    private String rsucIdysfInformBy;
    /**
     * Variable to hold the value for Column RSUC_T_DYSF_INFORM_BY of Table OPLQTRSU
     */
    private String rsucTdysfInformBy;
    /**
     * Variable to hold the value for Column RSUC_I_MST_INFORM_BY of Table OPLQTRSU
     */
    private String rsucImstInformBy;
    /**
     * Variable to hold the value for Column RSUC_T_MST_INFORM_BY of Table OPLQTRSU
     */
    private String rsucTmstInformBy;
    /**
     * Variable to hold the value for Column RSUC_T_NOM_STAB_COMMENT of Table OPLQTRSU
     */
    private String rsucTnomStabComment;
    /**
     * Variable to hold the value for Column RSUC_T_PIRE_CAS_COMMENT of Table OPLQTRSU
     */
    private String rsucTpireCasComment;
    /**
     * Variable to hold the value for Column RSUC_I_DYSF_COMMENT of Table OPLQTRSU
     */
    private String rsucIdysfComment;
    /**
     * Variable to hold the value for Column RSUC_T_DYSF_COMMENT of Table OPLQTRSU
     */
    private String rsucTdysfComment;
    /**
     * Variable to hold the value for Column RSUC_I_MST_COMMENT of Table OPLQTRSU
     */
    private String rsucImstComment;
    /**
     * Variable to hold the value for Column RSUC_T_MST_COMMENT of Table OPLQTRSU
     */
    private String rsucTmstComment;

    /**
     * Default Constructor
     */
    public EdsRobustSupplyUseCase() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param
     */
    public EdsRobustSupplyUseCase(String rsucId) {
        this.rsucId = rsucId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param otherSupply Eds Robust Supply
     */
    public EdsRobustSupplyUseCase(EdsRobustSupplyUseCase otherUseCase) {
        // general data
        this.rsucId = UUID.randomUUID().toString();
        this.rsucName = otherUseCase.rsucName;
        this.rsucRemove = otherUseCase.rsucRemove;

        // currents
        this.rsucIVeille = otherUseCase.rsucIVeille;
        this.rsucIReveilInactif = otherUseCase.rsucIReveilInactif;
        this.rsucINomStab = otherUseCase.rsucINomStab;
        this.rsucIPirecasStab = otherUseCase.rsucIPirecasStab;
        this.rsucUMin = otherUseCase.rsucUMin;
        this.rsucUMoy = otherUseCase.rsucUMoy;
        this.rsucUMax = otherUseCase.rsucUMax;
        this.rsucIVeilleIformBy = otherUseCase.rsucIVeilleIformBy;
        this.rsucIReveilIformBy = otherUseCase.rsucIReveilIformBy;
        this.rsucINomStabIformBy = otherUseCase.rsucINomStabIformBy;
        this.rsucIPirecasStabIformBy = otherUseCase.rsucIPirecasStabIformBy;
        this.rsucUMinInformBy = otherUseCase.rsucUMinInformBy;
        this.rsucUMoyInformBy = otherUseCase.rsucUMoyInformBy;
        this.rsucUMaxInformBy = otherUseCase.rsucUMaxInformBy;
        this.rsucIVeilleComment = otherUseCase.rsucIVeilleComment;
        this.rsucIReveilComment = otherUseCase.rsucIReveilComment;
        this.rsucINomStabComment = otherUseCase.rsucINomStabComment;
        this.rsucIPirecasComment = otherUseCase.rsucIPirecasComment;
        this.rsucUMinComment = otherUseCase.rsucUMinComment;
        this.rsucUMoyComment = otherUseCase.rsucUMoyComment;
        this.rsucUMaxComment = otherUseCase.rsucUMaxComment;
        this.rsucIMax = otherUseCase.rsucIMax;
        this.rsucTIMax = otherUseCase.rsucTIMax;
        this.rsucIMaxInformBy = otherUseCase.rsucIMaxInformBy;
        this.rsucTIMaxInformBy = otherUseCase.rsucTIMaxInformBy;
        this.rsucIMaxComment = otherUseCase.rsucIMaxComment;
        this.rsucTIMaxComment = otherUseCase.rsucTIMaxComment;
        this.rsucUCaracValue = otherUseCase.rsucUCaracValue;
        this.rsucUCaracInformBy = otherUseCase.rsucUCaracInformBy;
        this.rsucUCaracComment = otherUseCase.rsucUCaracComment;
        this.rsucIConsoParcComment = otherUseCase.rsucIConsoParcComment;
        this.rsucIConsoParcInformBy = otherUseCase.rsucIConsoParcInformBy;
        this.rsucIConsoParc = otherUseCase.rsucIConsoParc;

        this.rsucTNomStab = otherUseCase.rsucTNomStab;
        this.rsucTnomStabInformBy = otherUseCase.rsucTnomStabInformBy;
        this.rsucTnomStabComment = otherUseCase.rsucTnomStabComment;
        this.rsucTPireCas = otherUseCase.rsucTPireCas;
        this.rsucTpireCasInformBy = otherUseCase.rsucTpireCasInformBy;
        this.rsucTpireCasComment = otherUseCase.rsucTpireCasComment;
        this.rsucIdysf = otherUseCase.rsucIdysf;
        this.rsucIdysfInformBy = otherUseCase.rsucIdysfInformBy;
        this.rsucIdysfComment = otherUseCase.rsucIdysfComment;
        this.rsucTdysf = otherUseCase.rsucTdysf;
        this.rsucTdysfInformBy = otherUseCase.rsucTdysfInformBy;
        this.rsucTdysfComment = otherUseCase.rsucTdysfComment;
        this.rsucImst = otherUseCase.rsucImst;
        this.rsucImstInformBy = otherUseCase.rsucImstInformBy;
        this.rsucImstComment = otherUseCase.rsucImstComment;
        this.rsucTmst = otherUseCase.rsucTmst;
        this.rsucTmstInformBy = otherUseCase.rsucTmstInformBy;
        this.rsucTmstComment = otherUseCase.rsucTmstComment;

        // supply
        this.robustSupply = otherUseCase.robustSupply;
    }

    /**
     * Function to get rsucIVeille
     * 
     * @return the Value of rsucIVeille
     */
    public Float getISleepCurrent() {
        return getRsucIVeille();
    }

    /**
     * Function to get IAwake12_5
     * 
     * @return null
     */
    public Float getIAwake12_5() {
        return null;
    }

    /**
     * Function to get rsucIReveilInactif
     * 
     * @return the Value of rsucIReveilInactif
     */
    public Float getIAwake13_5() {
        return getRsucIReveilInactif();
    }

    /**
     * Function to get INomStab12_5
     * 
     * @return null
     */
    public Float getINomStab12_5() {
        return null;
    }

    /**
     * Function to get rsucINomStab
     * 
     * @return the Value of rsucINomStab
     */
    public Float getINomStab13_5() {
        return getRsucINomStab();
    }

    /**
     * Function to get IWorstStab12_5
     * 
     * @return null
     */
    public Float getIWorstStab12_5() {
        return null;
    }

    /**
     * Function to get rsucIPirecasStab
     * 
     * @return the Value of rsucIPirecasStab
     */
    public Float getIWorstStab13_5() {
        return getRsucIPirecasStab();
    }

    /**
     * Function to get id
     * 
     * @return the Value of id
     */
    @XmlAttribute(name = "id")
    public String getRsucId() {
        return this.rsucId;
    }

    /**
     * Function to set id
     * 
     * @param id Eds Robust Supply Id
     */
    public void setRsucId(String rsucId) {
        this.rsucId = rsucId;
    }

    /**
     * Function to get useCaseName
     * 
     * @return the Value of useCaseName
     */
    @XmlAttribute(name = "name")
    public String getRsucName() {
        return this.rsucName;
    }

    /**
     * Function to set useCaseName
     * 
     * @param useCaseName Eds Robust Supply UseCase name
     */
    public void setRsucName(String rsucName) {
        this.rsucName = rsucName;
    }

    /**
     * Function to get rsucRemove
     * 
     * @return check if removable
     */
    @XmlTransient
    public boolean isRsucRemove() {
        return rsucRemove;
    }

    /**
     * Function to get rsucRemove
     * 
     * @return the Value of rsucRemove
     */
    @XmlTransient
    public Boolean getRsucRemove() {
        return this.rsucRemove;
    }

    /**
     * Function to set rsucRemove
     * 
     * @param rsucRemove Eds Robust Supply remove boolean
     */
    public void setRsucRemove(Boolean rsucRemove) {
        this.rsucRemove = rsucRemove;
    }

    /**
     * Function to get robustSupply
     * 
     * @return the Value of robustSupply
     */
    @XmlTransient
    public EdsRobustSupply getRobustSupply() {
        return robustSupply;
    }

    /**
     * Function to set robustSupply
     * 
     * @param robustSupply
     */
    public void setRobustSupply(EdsRobustSupply robustSupply) {
        this.robustSupply = robustSupply;
    }

    /**
     * Function to get rsucIVeille
     * 
     * @return the Value of rsucIVeille
     */
    @XmlElement(name = "i-standby")
    public Float getRsucIVeille() {
        return this.rsucIVeille;
    }

    /**
     * Function to set rsucIVeille
     * 
     * @param rsucIVeille Iawake
     */
    public void setRsucIVeille(Float rsucIVeille) {
        this.rsucIVeille = rsucIVeille;
    }

    /**
     * Function to get rsucIReveilInactif
     * 
     * @return the Value of rsucIReveilInactif
     */
    @XmlElement(name = "i-wakeup-inactive")
    public Float getRsucIReveilInactif() {
        return this.rsucIReveilInactif;
    }

    /**
     * Function to set rsucIReveilInactif
     * 
     * @param rsucIReveilInactif Iawake inactive
     */
    public void setRsucIReveilInactif(Float rsucIReveilInactif) {
        this.rsucIReveilInactif = rsucIReveilInactif;
    }

    /**
     * Function to get rsucINomStab
     * 
     * @return the Value of rsucINomStab
     */
    @XmlElement(name = "i-nom-stab")
    public Float getRsucINomStab() {
        return this.rsucINomStab;
    }

    /**
     * Function to set rsucINomStab
     * 
     * @param rsucINomStab Inob stab
     */
    public void setRsucINomStab(Float rsucINomStab) {
        this.rsucINomStab = rsucINomStab;
    }

    /**
     * Function to get rsucIPirecasStab
     * 
     * @return the Value of rsucIPirecasStab
     */
    @XmlElement(name = "i-worst-stab")
    public Float getRsucIPirecasStab() {
        return this.rsucIPirecasStab;
    }

    /**
     * Function to set rsucIPirecasStab
     * 
     * @param rsucIPirecasStab Iworst stab
     */
    public void setRsucIPirecasStab(Float rsucIPirecasStab) {
        this.rsucIPirecasStab = rsucIPirecasStab;
    }

    /**
     * Function to get rsucUMin
     * 
     * @return the Value of rsucUMin
     */
    @XmlElement(name = "u-min")
    public Float getRsucUMin() {
        return this.rsucUMin;
    }

    /**
     * Function to set rsucUMin
     * 
     * @param rsucUMin Umin
     */
    public void setRsucUMin(Float rsucUMin) {
        this.rsucUMin = rsucUMin;
    }

    /**
     * Function to get rsucUMoy
     * 
     * @return the Value of rsucUMoy
     */
    @XmlElement(name = "u-med")
    public Float getRsucUMoy() {
        return this.rsucUMoy;
    }

    /**
     * Function to set rsucUMoy
     * 
     * @param rsucUMoy Umed
     */
    public void setRsucUMoy(Float rsucUMoy) {
        this.rsucUMoy = rsucUMoy;
    }

    /**
     * Function to get rsucUMax
     * 
     * @return the Value of rsucUMax
     */
    @XmlElement(name = "u-max")
    public Float getRsucUMax() {
        return this.rsucUMax;
    }

    /**
     * Function to set rsucUMax
     * 
     * @param rsucUMax Umax
     */
    public void setRsucUMax(Float rsucUMax) {
        this.rsucUMax = rsucUMax;
    }

    /**
     * Function to get rsucIVeilleIformBy
     * 
     * @return the Value of rsucIVeilleIformBy
     */
    @XmlTransient
    public String getRsucIVeilleIformBy() {
        return this.rsucIVeilleIformBy;
    }

    /**
     * Function to set rsucIVeilleIformBy
     * 
     * @param rsucIVeilleIformBy Iawake Iform By
     */
    public void setRsucIVeilleIformBy(String rsucIVeilleIformBy) {
        this.rsucIVeilleIformBy = rsucIVeilleIformBy;
    }

    /**
     * Function to get rsucReveilIformBy
     * 
     * @return the Value of rsucReveilIformBy
     */
    @XmlTransient
    public String getRsucIReveilIformBy() {
        return this.rsucIReveilIformBy;
    }

    /**
     * Function to set rsucReveilIformBy
     * 
     * @param rsucReveilIformBy Awake Iform by
     */
    public void setRsucIReveilIformBy(String rsucIReveilIformBy) {
        this.rsucIReveilIformBy = rsucIReveilIformBy;
    }

    /**
     * Function to get rsucINomStabIformBy
     * 
     * @return the Value of rsucINomStabIformBy
     */
    @XmlTransient
    public String getRsucINomStabIformBy() {
        return this.rsucINomStabIformBy;
    }

    /**
     * Function to set rsucINomStabIformBy
     * 
     * @param rsucINomStabIformBy Inob stab Iform By
     */
    public void setRsucINomStabIformBy(String rsucINomStabIformBy) {
        this.rsucINomStabIformBy = rsucINomStabIformBy;
    }

    /**
     * Function to get rsucIPirecasStabIformBy
     * 
     * @return the Value of rsucIPirecasStabIformBy
     */
    @XmlTransient
    public String getRsucIPirecasStabIformBy() {
        return this.rsucIPirecasStabIformBy;
    }

    /**
     * Function to set rsucIPirecasStabIformBy
     * 
     * @param rsucIPirecasStabIformBy Iworst case Iform By
     */
    public void setRsucIPirecasStabIformBy(String rsucIPirecasStabIformBy) {
        this.rsucIPirecasStabIformBy = rsucIPirecasStabIformBy;
    }

    /**
     * Function to get rsucUMinInformBy
     * 
     * @return the Value of rsucUMinInformBy
     */
    @XmlTransient
    public String getRsucUMinInformBy() {
        return this.rsucUMinInformBy;
    }

    /**
     * Function to set rsucUMinInformBy
     * 
     * @param rsucUMinInformBy Umin Inform By
     */
    public void setRsucUMinInformBy(String rsucUMinInformBy) {
        this.rsucUMinInformBy = rsucUMinInformBy;
    }

    /**
     * Function to get rsucUMoyInformBy
     * 
     * @return the Value of rsucUMoyInformBy
     */
    @XmlTransient
    public String getRsucUMoyInformBy() {
        return this.rsucUMoyInformBy;
    }

    /**
     * Function to set rsucUMoyInformBy
     * 
     * @param rsucUMoyInformBy Umed Inform By
     */
    public void setRsucUMoyInformBy(String rsucUMoyInformBy) {
        this.rsucUMoyInformBy = rsucUMoyInformBy;
    }

    /**
     * Function to get rsucUMaxInformBy
     * 
     * @return the Value of rsucUMaxInformBy
     */
    @XmlTransient
    public String getRsucUMaxInformBy() {
        return this.rsucUMaxInformBy;
    }

    /**
     * Function to set rsucUMaxInformBy
     * 
     * @param rsucUMaxInformBy Umax Iform By
     */
    public void setRsucUMaxInformBy(String rsucUMaxInformBy) {
        this.rsucUMaxInformBy = rsucUMaxInformBy;
    }

    /**
     * Function to get rsucIMax
     * 
     * @return the Value of rsucIMax
     */
    @XmlElement(name = "i-pic")
    public Float getRsucIMax() {
        return rsucIMax;
    }

    /**
     * Function to set rsucIMax
     * 
     * @param rsucIMax Imax
     */
    public void setRsucIMax(Float rsucIMax) {
        this.rsucIMax = rsucIMax;
    }

    /**
     * Function to get rsucIMaxComment
     * 
     * @return the Value of rsucIMaxComment
     */
    @XmlElement(name = "rsucIPicComment")
    public String getRsucIMaxComment() {
        return rsucIMaxComment;
    }

    /**
     * Function to set rsucIMaxComment
     * 
     * @param rsucIMaxComment Imax comment
     */
    public void setRsucIMaxComment(String rsucIMaxComment) {
        this.rsucIMaxComment = rsucIMaxComment;
    }

    /**
     * Function to get rsucIMaxInformBy
     * 
     * @return the Value of rsucIMaxInformBy
     */
    @XmlTransient
    public String getRsucIMaxInformBy() {
        return rsucIMaxInformBy;
    }

    /**
     * Function to set rsucIMaxInformBy
     * 
     * @param rsucIMaxInformBy Imax Inform By
     */
    public void setRsucIMaxInformBy(String rsucIMaxInformBy) {
        this.rsucIMaxInformBy = rsucIMaxInformBy;
    }

    /**
     * Function to get rsucTIMax
     * 
     * @return the Value of rsucTIMax
     */
    @XmlElement(name = "t-pic")
    public Float getRsucTIMax() {
        return rsucTIMax;
    }

    /**
     * Function to set rsucTIMax
     * 
     * @param rsucTIMax TImax
     */
    public void setRsucTIMax(Float rsucTIMax) {
        this.rsucTIMax = rsucTIMax;
    }

    /**
     * Function to get rsucTIMaxComment
     * 
     * @return the Value of rsucTIMaxComment
     */
    @XmlElement(name = "rsucTPicComment")
    public String getRsucTIMaxComment() {
        return rsucTIMaxComment;
    }

    /**
     * Function to set rsucTIMaxComment
     * 
     * @param rsucTIMaxComment TImax comment
     */
    public void setRsucTIMaxComment(String rsucTIMaxComment) {
        this.rsucTIMaxComment = rsucTIMaxComment;
    }

    /**
     * Function to get rsucTIMaxInformBy
     * 
     * @return the Value of rsucTIMaxInformBy
     */
    @XmlTransient
    public String getRsucTIMaxInformBy() {
        return rsucTIMaxInformBy;
    }

    /**
     * Function to set rsucTIMaxInformBy
     * 
     * @param rsucTIMaxInformBy TImax Inform By
     */
    public void setRsucTIMaxInformBy(String rsucTIMaxInformBy) {
        this.rsucTIMaxInformBy = rsucTIMaxInformBy;
    }

    /**
     * Function to get rsucIVeilleComment
     * 
     * @return the Value of rsucIVeilleComment
     */
    public String getRsucIVeilleComment() {
        return this.rsucIVeilleComment;
    }

    /**
     * Function to set rsucIVeilleComment
     * 
     * @param rsucIVeilleComment Isleep comment
     */
    public void setRsucIVeilleComment(String rsucIVeilleComment) {
        this.rsucIVeilleComment = rsucIVeilleComment;
    }

    /**
     * Function to get rsucReveilComment
     * 
     * @return the Value of rsucReveilComment
     */
    public String getRsucIReveilComment() {
        return this.rsucIReveilComment;
    }

    /**
     * Function to set rsucReveilComment
     * 
     * @param rsucReveilComment Iawake comment
     */
    public void setRsucIReveilComment(String rsucIReveilComment) {
        this.rsucIReveilComment = rsucIReveilComment;
    }

    /**
     * Function to get rsucINomStabComment
     * 
     * @return the Value of rsucINomStabComment
     */
    public String getRsucINomStabComment() {
        return this.rsucINomStabComment;
    }

    /**
     * Function to set rsucINomStabComment
     * 
     * @param rsucINomStabComment Inob stab comment
     */
    public void setRsucINomStabComment(String rsucINomStabComment) {
        this.rsucINomStabComment = rsucINomStabComment;
    }

    /**
     * Function to get rsucIPirecasComment
     * 
     * @return the Value of rsucIPirecasComment
     */
    public String getRsucIPirecasComment() {
        return this.rsucIPirecasComment;
    }

    /**
     * Function to set rsucIPirecasComment
     * 
     * @param rsucIPirecasComment Iworst case comment
     */
    public void setRsucIPirecasComment(String rsucIPirecasComment) {
        this.rsucIPirecasComment = rsucIPirecasComment;
    }

    /**
     * Function to get rsucUMinComment
     * 
     * @return the Value of rsucUMinComment
     */
    public String getRsucUMinComment() {
        return this.rsucUMinComment;
    }

    /**
     * Function to set rsucUMinComment
     * 
     * @param rsucUMinComment Umin comment
     */
    public void setRsucUMinComment(String rsucUMinComment) {
        this.rsucUMinComment = rsucUMinComment;
    }

    /**
     * Function to get rsucUMoyComment
     * 
     * @return the Value of rsucUMoyComment
     */
    public String getRsucUMoyComment() {
        return this.rsucUMoyComment;
    }

    /**
     * Function to set rsucUMoyComment
     * 
     * @param rsucUMoyComment Umec domment
     */
    public void setRsucUMoyComment(String rsucUMoyComment) {
        this.rsucUMoyComment = rsucUMoyComment;
    }

    /**
     * Function to get rsucUMaxComment
     * 
     * @return the Value of rsucUMaxComment
     */
    public String getRsucUMaxComment() {
        return this.rsucUMaxComment;
    }

    /**
     * Function to set rsucUMaxComment
     * 
     * @param rsucUMaxComment Umax comment
     */
    public void setRsucUMaxComment(String rsucUMaxComment) {
        this.rsucUMaxComment = rsucUMaxComment;
    }

    /**
     * Function to get rsucUCaracComment
     * 
     * @return the Value of rsucUCaracComment
     */
    public String getRsucUCaracComment() {
        return rsucUCaracComment;
    }

    /**
     * Function to set rsucUCaracComment
     * 
     * @param rsucUCaracComment Ucarac comment
     */
    public void setRsucUCaracComment(String rsucUCaracComment) {
        this.rsucUCaracComment = rsucUCaracComment;
    }

    /**
     * Function to get rsucUCaracInformBy
     * 
     * @return the Value of rsucUCaracInformBy
     */
    @XmlTransient
    public String getRsucUCaracInformBy() {
        return rsucUCaracInformBy;
    }

    /**
     * Function to set rsucUCaracInformBy
     * 
     * @param rsucUCaracInformBy Ucarac Inform By
     */
    public void setRsucUCaracInformBy(String rsucUCaracInformBy) {
        this.rsucUCaracInformBy = rsucUCaracInformBy;
    }

    /**
     * Function to get rsucUCaracValue
     * 
     * @return the Value of rsucUCaracValue
     */
    @XmlElement(name = "u-carac-value")
    public Float getRsucUCaracValue() {
        return rsucUCaracValue;
    }

    /**
     * Function to set rsucUCaracValue
     * 
     * @param rsucUCaracValue Ucarac value
     */
    public void setRsucUCaracValue(Float rsucUCaracValue) {
        this.rsucUCaracValue = rsucUCaracValue;
    }

    /**
     * Function to get rsucIConsoParc
     * 
     * @return the Value of rsucIConsoParc
     */
    @XmlElement(name = "i-conso-park")
    public Float getRsucIConsoParc() {
        return rsucIConsoParc;
    }

    /**
     * Function to set rsucIConsoParc
     * 
     * @param rsucIConsoParc Ipark
     */
    public void setRsucIConsoParc(Float rsucIConsoParc) {
        this.rsucIConsoParc = rsucIConsoParc;
    }

    /**
     * Function to get rsucIConsoParcComment
     * 
     * @return the Value of rsucIConsoParcComment
     */
    public String getRsucIConsoParcComment() {
        return rsucIConsoParcComment;
    }

    /**
     * Function to set rsucIConsoParcComment
     * 
     * @param rsucIConsoParcComment Ipark comment
     */
    public void setRsucIConsoParcComment(String rsucIConsoParcComment) {
        this.rsucIConsoParcComment = rsucIConsoParcComment;
    }

    /**
     * Function to get rsucIConsoParcInformBy
     * 
     * @return the Value of rsucIConsoParcInformBy
     */
    @XmlTransient
    public String getRsucIConsoParcInformBy() {
        return rsucIConsoParcInformBy;
    }

    /**
     * Function to set rsucIConsoParcInformBy
     * 
     * @param rsucIConsoParcInformBy Ipark Inform By
     */
    public void setRsucIConsoParcInformBy(String rsucIConsoParcInformBy) {
        this.rsucIConsoParcInformBy = rsucIConsoParcInformBy;
    }

    /**
     * Getter rsucTNomStab
     * 
     * @return the rsucTNomStab
     */
    @XmlElement(name = "t-nom-stab")
    public Float getRsucTNomStab() {
        return rsucTNomStab;
    }

    /**
     * Setter rsucTnomStab
     * 
     * @param rsucTNomStab the rsucTnomStab to set
     */
    public void setRsucTNomStab(Float rsucTNomStab) {
        this.rsucTNomStab = rsucTNomStab;
    }

    /**
     * Getter rsucTpireCas
     * 
     * @return the rsucTpireCas
     */
    @XmlElement(name = "t-worst-stab")
    public Float getRsucTPireCas() {
        return rsucTPireCas;
    }

    /**
     * Setter rsucTpireCas
     * 
     * @param rsucTpireCas the rsucTpireCas to set
     */
    public void setRsucTPireCas(Float rsucTpireCas) {
        this.rsucTPireCas = rsucTpireCas;
    }

    /**
     * Getter rsucIdysf
     * 
     * @return the rsucIdysf
     */
    @XmlElement(name = "i-dysf")
    public Float getRsucIdysf() {
        return rsucIdysf;
    }

    /**
     * Setter rsucIdysf
     * 
     * @param rsucIdysf the rsucIdysf to set
     */
    public void setRsucIdysf(Float rsucIdysf) {
        this.rsucIdysf = rsucIdysf;
    }

    /**
     * Getter rsucTdysf
     * 
     * @return the rsucTdysf
     */
    @XmlElement(name = "t-dysf")
    public Float getRsucTdysf() {
        return rsucTdysf;
    }

    /**
     * Setter rsucTdysf
     * 
     * @param rsucTdysf the rsucTdysf to set
     */
    public void setRsucTdysf(Float rsucTdysf) {
        this.rsucTdysf = rsucTdysf;
    }

    /**
     * Getter rsucImst
     * 
     * @return the rsucImst
     */
    @XmlElement(name = "i-mst")
    public Float getRsucImst() {
        return rsucImst;
    }

    /**
     * Setter rsucImst
     * 
     * @param rsucImst the rsucImst to set
     */
    public void setRsucImst(Float rsucImst) {
        this.rsucImst = rsucImst;
    }

    /**
     * Getter rsucTmst
     * 
     * @return the rsucTmst
     */
    @XmlElement(name = "t-mst")
    public Float getRsucTmst() {
        return rsucTmst;
    }

    /**
     * Setter rsucTmst
     * 
     * @param rsucTmst the rsucTmst to set
     */
    public void setRsucTmst(Float rsucTmst) {
        this.rsucTmst = rsucTmst;
    }

    /**
     * Getter rsucTnomStabInformBy
     * 
     * @return the rsucTnomStabInformBy
     */
    public String getRsucTnomStabInformBy() {
        return rsucTnomStabInformBy;
    }

    /**
     * Setter rsucTnomStabInformBy
     * 
     * @param rsucTnomStabInformBy the rsucTnomStabInformBy to set
     */
    @XmlTransient
    public void setRsucTnomStabInformBy(String rsucTnomStabInformBy) {
        this.rsucTnomStabInformBy = rsucTnomStabInformBy;
    }

    /**
     * Getter rsucTpireCasInformBy
     * 
     * @return the rsucTpireCasInformBy
     */
    public String getRsucTpireCasInformBy() {
        return rsucTpireCasInformBy;
    }

    /**
     * Setter rsucTpireCasInformBy
     * 
     * @param rsucTpireCasInformBy the rsucTpireCasInformBy to set
     */
    public void setRsucTpireCasInformBy(String rsucTpireCasInformBy) {
        this.rsucTpireCasInformBy = rsucTpireCasInformBy;
    }

    /**
     * Getter rsucIdysfInformBy
     * 
     * @return the rsucIdysfInformBy
     */
    @XmlTransient
    public String getRsucIdysfInformBy() {
        return rsucIdysfInformBy;
    }

    /**
     * Setter rsucIdysfInformBy
     * 
     * @param rsucIdysfInformBy the rsucIdysfInformBy to set
     */
    public void setRsucIdysfInformBy(String rsucIdysfInformBy) {
        this.rsucIdysfInformBy = rsucIdysfInformBy;
    }

    /**
     * Getter rsucTdysfInformBy
     * 
     * @return the rsucTdysfInformBy
     */
    @XmlTransient
    public String getRsucTdysfInformBy() {
        return rsucTdysfInformBy;
    }

    /**
     * Setter rsucTdysfInformBy
     * 
     * @param rsucTdysfInformBy the rsucTdysfInformBy to set
     */
    public void setRsucTdysfInformBy(String rsucTdysfInformBy) {
        this.rsucTdysfInformBy = rsucTdysfInformBy;
    }

    /**
     * Getter rsucImstInformBy
     * 
     * @return the rsucImstInformBy
     */
    @XmlTransient
    public String getRsucImstInformBy() {
        return rsucImstInformBy;
    }

    /**
     * Setter rsucImstInformBy
     * 
     * @param rsucImstInformBy the rsucImstInformBy to set
     */
    public void setRsucImstInformBy(String rsucImstInformBy) {
        this.rsucImstInformBy = rsucImstInformBy;
    }

    /**
     * Getter rsucTmstInformBy
     * 
     * @return the rsucTmstInformBy
     */
    @XmlTransient
    public String getRsucTmstInformBy() {
        return rsucTmstInformBy;
    }

    /**
     * Setter rsucTmstInformBy
     * 
     * @param rsucTmstInformBy the rsucTmstInformBy to set
     */
    public void setRsucTmstInformBy(String rsucTmstInformBy) {
        this.rsucTmstInformBy = rsucTmstInformBy;
    }

    /**
     * Getter rsucTnomStabComment
     * 
     * @return the rsucTnomStabComment
     */
    public String getRsucTnomStabComment() {
        return rsucTnomStabComment;
    }

    /**
     * Setter rsucTnomStabComment
     * 
     * @param rsucTnomStabComment the rsucTnomStabComment to set
     */
    public void setRsucTnomStabComment(String rsucTnomStabComment) {
        this.rsucTnomStabComment = rsucTnomStabComment;
    }

    /**
     * Getter rsucTpireCasComment
     * 
     * @return the rsucTpireCasComment
     */
    public String getRsucTpireCasComment() {
        return rsucTpireCasComment;
    }

    /**
     * Setter rsucTpireCasComment
     * 
     * @param rsucTpireCasComment the rsucTpireCasComment to set
     */
    public void setRsucTpireCasComment(String rsucTpireCasComment) {
        this.rsucTpireCasComment = rsucTpireCasComment;
    }

    /**
     * Getter rsucIdysfComment
     * 
     * @return the rsucIdysfComment
     */
    public String getRsucIdysfComment() {
        return rsucIdysfComment;
    }

    /**
     * Setter rsucIdysfComment
     * 
     * @param rsucIdysfComment the rsucIdysfComment to set
     */
    public void setRsucIdysfComment(String rsucIdysfComment) {
        this.rsucIdysfComment = rsucIdysfComment;
    }

    /**
     * Getter rsucTdysfComment
     * 
     * @return the rsucTdysfComment
     */
    public String getRsucTdysfComment() {
        return rsucTdysfComment;
    }

    /**
     * Setter rsucTdysfComment
     * 
     * @param rsucTdysfComment the rsucTdysfComment to set
     */
    public void setRsucTdysfComment(String rsucTdysfComment) {
        this.rsucTdysfComment = rsucTdysfComment;
    }

    /**
     * Getter rsucImstComment
     * 
     * @return the rsucImstComment
     */
    public String getRsucImstComment() {
        return rsucImstComment;
    }

    /**
     * Setter rsucImstComment
     * 
     * @param rsucImstComment the rsucImstComment to set
     */
    public void setRsucImstComment(String rsucImstComment) {
        this.rsucImstComment = rsucImstComment;
    }

    /**
     * Getter rsucTmstComment
     * 
     * @return the rsucTmstComment
     */
    public String getRsucTmstComment() {
        return rsucTmstComment;
    }

    /**
     * Setter rsucTmstComment
     * 
     * @param rsucTmstComment the rsucTmstComment to set
     */
    public void setRsucTmstComment(String rsucTmstComment) {
        this.rsucTmstComment = rsucTmstComment;
    }

    /**
     * Function to check entered value are complete and in float format
     * 
     * @return boolean value
     */
    public boolean isComplete() {
        if (rsucIMax == null || rsucIMax == Float.NaN) {
            return false;
        } else if (rsucIVeille == null || rsucIVeille == Float.NaN) {
            return false;
        } else if (rsucIReveilInactif == null || rsucIReveilInactif == Float.NaN) {
            return false;
        } else if (rsucIPirecasStab == null || rsucIPirecasStab == Float.NaN) {
            return false;
        }
        return true;
    }

    /**
     * {@inheritDoc}
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return rsucName;
    }
}
