package com.inetpsa.eds.dao.model;

// Generated 10 may 2015 16:43:00 by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsUser generated by hbm2java
 */
@XmlType
public class EdsSAPReference implements java.io.Serializable {
    private Integer id;
    /**
     * String Variable to hold the value for Column REFERENCE_REVISION of Table OPLQTSAP
     */
    private String referenceRevision;

    /**
     * String Variable to hold the value for Column REFERENCE of Table OPLQTSAP
     */
    private String reference;

    /**
     * String Variable to hold the value for Column REVISION of Table OPLQTSAP
     */
    private String revision;

    /**
     * Default Constructor
     */
    public EdsSAPReference() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param number96s EdsSAPReference
     */
    public EdsSAPReference(EdsSAPReference number96s) {
        this.referenceRevision = number96s.referenceRevision;
        this.reference = number96s.reference;
        this.revision = number96s.revision;
    }

    // @XmlElement(name = "valeur")
    public String getReferenceRevision() {
        return referenceRevision;
    }

    public void setReferenceRevision(String referenceRevision) {
        this.referenceRevision = referenceRevision;
    }

    // @XmlElement
    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    // @XmlElement
    public String getRevision() {
        return revision;
    }

    public void setRevision(String revision) {
        this.revision = revision;
    }

    /**
     * Function to get Id
     * 
     * @return the Value of Id
     */
    @XmlTransient
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
	
	public String getReferenceRevisionLabel() {
		return reference+" "+revision;
	}
	
    @Override
    public int hashCode() {
        return referenceRevision.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsSAPReference other = (EdsSAPReference) obj;
        if ((this.referenceRevision == null) ? (other.referenceRevision != null) : !this.referenceRevision.equals(other.referenceRevision)) {
            return false;
        }
        return true;
    }
}
