package com.inetpsa.eds.dao.model;

// Generated 14 juin 2012 16:43:00 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsSupplier generated by hbm2java
 */
@XmlType
public class EdsSupplier implements java.io.Serializable {
    /**
     * Constant to hold value of HIDDEN
     */
    public static final int HIDDEN = -1;
    /**
     * Constant to hold value of INACTIVE
     */
    public static final int INACTIVE = 0;
    /**
     * Constant to hold value of ACTIVE
     */
    public static final int ACTIVE = 1;
    /**
     * String Variable to hold the value for Column S_ID of Table OPLQTSUR
     */
    private String SId;
    /**
     * String Variable to hold the value for Column S_NAME of Table OPLQTSUR
     */
    private String SName;
    /**
     * int Variable to hold the value for Column S_ACTIVE of Table OPLQTSUR
     */
    private int sActive;
    /**
     * Set Collection to hold the values for Table OPLQTEDS
     */
    private Set edsEdses = new HashSet(0);
    /**
     * Set Collection to hold the values for Table OPLQTUSE
     */
    private Set edsUsers = new HashSet(0);

    /**
     * Default Constructor
     */
    public EdsSupplier() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param SId Eds supplier Id
     * @param SName Eds supplier name
     * @param SActive Eds supplier active
     */
    public EdsSupplier(String SId, String SName, int SActive) {
        this.SId = SId;
        this.SName = SName;
        this.sActive = SActive;
    }

    /**
     * Parameterized Constructor
     * 
     * @param SId Eds supplier Id
     * @param SName Eds supplier Name
     * @param SActive Eds supplier Active
     * @param edsEdses Set of EdsEds
     * @param edsUsers Set of EdsUser
     */
    public EdsSupplier(String SId, String SName, int SActive, Set edsEdses, Set edsUsers) {
        this.SId = SId;
        this.SName = SName;
        this.sActive = SActive;
        this.edsEdses = edsEdses;
        this.edsUsers = edsUsers;
    }

    /**
     * Function to get SId
     * 
     * @return the Value of SId
     */
    @XmlTransient
    public String getSId() {
        return this.SId;
    }

    /**
     * Function to set SId
     * 
     * @param SId Eds supplierId
     */
    public void setSId(String SId) {
        this.SId = SId;
    }

    /**
     * Function to get SName
     * 
     * @return the Value of SName
     */
    @XmlElement
    public String getSName() {
        return this.SName;
    }

    /**
     * Function to set SName
     * 
     * @param SName Eds supplier name
     */
    public void setSName(String SName) {
        this.SName = SName;
    }

    /**
     * Function to get sActive
     * 
     * @return the Value of sActive
     */
    @XmlElement(name = "is-active")
    public int getSActive() {
        return sActive;
    }

    /**
     * Function to set sActive
     * 
     * @param sActive Eds supplier active
     */
    public void setSActive(int sActive) {
        this.sActive = sActive;
    }

    /**
     * Function to get edsEdses
     * 
     * @return the Value of edsEdses
     */
    @XmlTransient
    public Set getEdsEdses() {
        return this.edsEdses;
    }

    /**
     * Function to set edsEdses
     * 
     * @param edsEdses Set of EdsEds
     */
    public void setEdsEdses(Set edsEdses) {
        this.edsEdses = edsEdses;
    }

    /**
     * Function to get edsUsers
     * 
     * @return the Value of edsUsers
     */
    @XmlTransient
    public Set getEdsUsers() {
        return this.edsUsers;
    }

    /**
     * Function to set edsUsers
     * 
     * @param edsUsers set of EdsUser
     */
    public void setEdsUsers(Set edsUsers) {
        this.edsUsers = edsUsers;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsSupplier other = (EdsSupplier) obj;
        if ((this.SId == null) ? (other.SId != null) : !this.SId.equals(other.SId)) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + (this.SId != null ? this.SId.hashCode() : 0);
        return hash;
    }
}
