package com.inetpsa.eds.dao.model;

// Generated 17 oct. 2012 11:31:00 by Hibernate Tools 3.2.1.GA

import java.util.HashMap;
import java.util.List;
import java.util.UUID;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsSupply generated by hbm2java
 */
@XmlType
public class EdsSupply implements java.io.Serializable {
    /**
     * Serial UID.
     */
    private static final long serialVersionUID = -4138981341548550069L;

    /**
     * String Variable to hold the value for Column SEDS_ID of Table OPLQTSUY
     */
    private String sedsId;

    /**
     * Variable to hold the value for Column SEDS_EDS_ID of Table OPLQTSUY
     */
    private EdsEds edsEds;

    /**
     * Variable to hold the value for Column S_PMSEDS_ID of Table OPLQTSUY
     */
    private EdsPsaMesureSupply edsPsaMesureSupply;

    /**
     * Variable to hold the value for Column S_RSEDS_ID of Table OPLQTSUY
     */
    private EdsRobustSupply edsRobustSupply;

    /**
     * Variable to hold the value for Column S_PSEDS_ID of Table OPLQTSUY
     */
    private EdsPrimarySupply edsPrimarySupply;

    /**
     * Variable to hold the value for Column S_CSEDS_ID of Table OPLQTSUY
     */
    private EdsConsolidateSupply edsConsolidateSupply;

    /**
     * String Variable to hold the value for Column SEDS_SUPPLY_NAME of Table OPLQTSUY
     */
    private String sedsSupplyName;

    /**
     * String Variable to hold the value for Column SEDS_DRIFT_COMMENT of Table OPLQTSUY
     */
    private String sedsDriftComment;

    /**
     * Default Constructor
     */
    public EdsSupply() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param sedsId Eds supply Id
     * @param edsEds Eds details
     */
    public EdsSupply(String sedsId, EdsEds edsEds) {
        this.edsEds = edsEds;
        this.sedsId = sedsId;
    }

    /**
     * Parameterized Constructor
     * 
     * @param sedsId Eds supply Id
     * @param edsEds Eds details
     * @param edsPsaMesureSupply Eds PSA measure supply
     * @param edsRobustSupply Eds Robust supply
     * @param edsPrimarySupply Eds primary supply
     * @param edsConsolidateSupply Eds consolidate supply
     * @param sedsSupplyName Supply name
     * @param sedsDriftComment Drift comment
     */
    public EdsSupply(String sedsId, EdsEds edsEds, EdsPsaMesureSupply edsPsaMesureSupply, EdsRobustSupply edsRobustSupply,
            EdsPrimarySupply edsPrimarySupply, EdsConsolidateSupply edsConsolidateSupply, String sedsSupplyName, String sedsDriftComment) {
        this.sedsId = sedsId;
        this.edsEds = edsEds;
        this.edsPsaMesureSupply = edsPsaMesureSupply;
        this.edsRobustSupply = edsRobustSupply;
        this.edsPrimarySupply = edsPrimarySupply;
        this.edsConsolidateSupply = edsConsolidateSupply;
        this.sedsSupplyName = sedsSupplyName;
        this.sedsDriftComment = sedsDriftComment;
    }

    /**
     * Function to get sedsId
     * 
     * @return the Value of sedsId
     */
    @XmlTransient
    public String getSedsId() {
        return this.sedsId;
    }

    /**
     * Function to set sedsId
     * 
     * @param sedsId
     */
    public void setSedsId(String sedsId) {
        this.sedsId = sedsId;
    }

    /**
     * Function to get edsEds
     * 
     * @return the Value of edsEds
     */
    @XmlTransient
    public EdsEds getEdsEds() {
        return edsEds;
    }

    /**
     * Function to set edsEds
     * 
     * @param edsEds
     */
    public void setEdsEds(EdsEds edsEds) {
        this.edsEds = edsEds;
    }

    /**
     * Function to get edsPsaMesureSupply
     * 
     * @return the Value of edsPsaMesureSupply
     */
    @XmlElement(name = "mesure-supply")
    public EdsPsaMesureSupply getEdsPsaMesureSupply() {
        return this.edsPsaMesureSupply;
    }

    /**
     * Function to set edsPsaMesureSupply
     * 
     * @param edsPsaMesureSupply
     */
    public void setEdsPsaMesureSupply(EdsPsaMesureSupply edsPsaMesureSupply) {
        this.edsPsaMesureSupply = edsPsaMesureSupply;
    }

    /**
     * Function to get edsRobustSupply
     * 
     * @return the Value of edsRobustSupply
     */
    @XmlElement(name = "robust-supply")
    public EdsRobustSupply getEdsRobustSupply() {
        return this.edsRobustSupply;
    }

    /**
     * Function to set edsRobustSupply
     * 
     * @param edsRobustSupply
     */
    public void setEdsRobustSupply(EdsRobustSupply edsRobustSupply) {
        this.edsRobustSupply = edsRobustSupply;
    }

    /**
     * Function to get edsPrimarySupply
     * 
     * @return the Value of edsPrimarySupply
     */
    @XmlElement(name = "primary-supply")
    public EdsPrimarySupply getEdsPrimarySupply() {
        return this.edsPrimarySupply;
    }

    /**
     * Function to set edsPrimarySupply
     * 
     * @param edsPrimarySupply
     */
    public void setEdsPrimarySupply(EdsPrimarySupply edsPrimarySupply) {
        this.edsPrimarySupply = edsPrimarySupply;
    }

    /**
     * Function to get edsConsolidateSupply
     * 
     * @return the Value of edsConsolidateSupply
     */
    @XmlElement(name = "consolidate-supply")
    public EdsConsolidateSupply getEdsConsolidateSupply() {
        return this.edsConsolidateSupply;
    }

    /**
     * Function to set edsConsolidateSupply
     * 
     * @param edsConsolidateSupply
     */
    public void setEdsConsolidateSupply(EdsConsolidateSupply edsConsolidateSupply) {
        this.edsConsolidateSupply = edsConsolidateSupply;
    }

    /**
     * Function to get sedsSupplyName
     * 
     * @return the Value of sedsSupplyName
     */
    @XmlElement(name = "supply-name")
    public String getSedsSupplyName() {
        return this.sedsSupplyName;
    }

    /**
     * Function to set sedsSupplyName
     * 
     * @param sedsSupplyName
     */
    public void setSedsSupplyName(String sedsSupplyName) {
        this.sedsSupplyName = sedsSupplyName;
    }

    /**
     * Function to get sedsDriftComment
     * 
     * @return the Value of sedsDriftComment
     */
    @XmlElement(name = "drift-comment")
    public String getSedsDriftComment() {
        return this.sedsDriftComment;
    }

    /**
     * Function to set sedsDriftComment
     * 
     * @param sedsDriftComment
     */
    public void setSedsDriftComment(final String sedsDriftComment) {
        this.sedsDriftComment = sedsDriftComment;
    }

    @Override
    public String toString() {
        return this.sedsSupplyName;
    }

    /**
     * Function to get copy of EdsSupply
     * 
     * @param eds Eds details
     * @param copiesMap Map of String and supply object
     * @return the Value of EdsSupply
     */
    public EdsSupply getCopy(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsSupply copy = new EdsSupply(UUID.randomUUID().toString(), eds);
        copy.sedsSupplyName = sedsSupplyName;
        copy.sedsDriftComment = sedsDriftComment;
        if (edsPrimarySupply != null) {
            if (!copiesMap.containsKey(edsPrimarySupply.getPsedsId())) {
                copiesMap.put(edsPrimarySupply.getPsedsId(), new EdsPrimarySupply(edsPrimarySupply));
            }
            copy.edsPrimarySupply = (EdsPrimarySupply) copiesMap.get(edsPrimarySupply.getPsedsId());
        }
        if (edsRobustSupply != null) {
            if (!copiesMap.containsKey(edsRobustSupply.getRsedsId())) {
                copiesMap.put(edsRobustSupply.getRsedsId(), new EdsRobustSupply(edsRobustSupply));
            }
            copy.edsRobustSupply = (EdsRobustSupply) copiesMap.get(edsRobustSupply.getRsedsId());
        }
        // dataClassesList.add( EdsConsolidateCurentFormData.class ); dans EDSdao
        if (edsConsolidateSupply != null) // TODO après les modifs de Rabah
        {
            if (!copiesMap.containsKey(edsConsolidateSupply.getCsedsId())) {
                copiesMap.put(edsConsolidateSupply.getCsedsId(), new EdsConsolidateSupply(edsConsolidateSupply));
            }
            copy.edsConsolidateSupply = (EdsConsolidateSupply) copiesMap.get(edsConsolidateSupply.getCsedsId());
        }
        if (edsPsaMesureSupply != null) {
            if (!copiesMap.containsKey(edsPsaMesureSupply.getPmsedsId())) {
                copiesMap.put(edsPsaMesureSupply.getPmsedsId(), new EdsPsaMesureSupply(edsPsaMesureSupply));
            }
            copy.edsPsaMesureSupply = (EdsPsaMesureSupply) copiesMap.get(edsPsaMesureSupply.getPmsedsId());
        }
        return copy;
    }

    /**
     * Function to get copy for reconsult
     * 
     * @param eds Eds Destails
     * @param copiesMap Map of String and supply object
     * @return Eds Supply
     */
    public EdsSupply getCopyForReconsult(EdsEds eds, HashMap<String, Object> copiesMap) {
        EdsSupply copy = new EdsSupply(UUID.randomUUID().toString(), eds);
        copy.sedsSupplyName = sedsSupplyName;
        copy.sedsDriftComment = sedsDriftComment;
        if (edsPrimarySupply != null) {
            if (!copiesMap.containsKey(edsPrimarySupply.getPsedsId())) {
                copiesMap.put(edsPrimarySupply.getPsedsId(), new EdsPrimarySupply(edsPrimarySupply));
            }
            copy.edsPrimarySupply = (EdsPrimarySupply) copiesMap.get(edsPrimarySupply.getPsedsId());
        }
        if (edsRobustSupply != null) {
            if (!copiesMap.containsKey(edsRobustSupply.getRsedsId())) {
                copiesMap.put(edsRobustSupply.getRsedsId(), new EdsRobustSupply(edsRobustSupply));
            }
            copy.edsRobustSupply = (EdsRobustSupply) copiesMap.get(edsRobustSupply.getRsedsId());
        }
        return copy;
    }

    /**
     * Function to get EdsSupply
     * 
     * @param eds Eds details
     * @return the Value of EdsSupply
     */
    public EdsSupply getReconsultableCopy(EdsEds eds) {
        EdsSupply copy = new EdsSupply(UUID.randomUUID().toString(), eds);
        copy.sedsSupplyName = sedsSupplyName;
        copy.sedsDriftComment = sedsDriftComment;
        if (edsPrimarySupply != null) {
            copy.edsPrimarySupply = new EdsPrimarySupply(edsPrimarySupply);
        }
        return copy;
    }

    /**
     * Function returns all saved items
     * 
     * @return List of Supply
     */
    public List<?> getAllItemsToSave() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsSupply other = (EdsSupply) obj;
        if ((this.sedsId == null) ? (other.sedsId != null) : !this.sedsId.equals(other.sedsId)) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + (this.sedsId != null ? this.sedsId.hashCode() : 0);
        return hash;
    }
}
