package com.inetpsa.eds.dao.model;

// Generated 14 juin 2012 16:43:00 by Hibernate Tools 3.2.1.GA

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * EdsUser generated by hbm2java
 */
@XmlType
public class EdsUser implements java.io.Serializable {
    /**
     * String Variable to hold the value for Column U_ID of Table OPLQTUSE
     */
    private String UId;
    /**
     * Variable to hold the value for Column U_PE_ID of Table OPLQTUSE
     */
    private EdsPerimeter edsPerimeter;
    /**
     * Variable to hold the value for Column U_S_ID of Table OPLQTUSE
     */
    private EdsSupplier edsSupplier;
    /**
     * Variable to hold the value for Column U_RO_ID of Table OPLQTUSE
     */
    private EdsRole edsRole;
    /**
     * Variable to hold the value for Column U_PSA_ID of Table OPLQTUSE
     */
    private String UPsaId;
    /**
     * String Variable to hold the value for Column U_FIRSTNAME of Table OPLQTUSE
     */
    private String UFirstname;
    /**
     * String Variable to hold the value for Column U_LASTNAME of Table OPLQTUSE
     */
    private String ULastname;
    /**
     * String Variable to hold the value for Column U_SERVICE of Table OPLQTUSE
     */
    private String UService;
    /**
     * int Variable to hold the value for Column U_ACTIVE of Table OPLQTUSE
     */
    private int UActive;
    /**
     * Set Collection to hold the values for Table OPLQTEDS
     */
    private Set edsEdsesForEdsOfficerId = new HashSet(0);
    /**
     * Set Collection to hold the values for Table OPLQTEDS
     */
    private Set edsEdsesForEdsAdminId = new HashSet(0);
    /**
     * Set Collection to hold the values for Table OPLQTSUB
     */
    private Set edsSubscriptions = new HashSet(0);
    /**
     * Set Collection to hold the values for Table OPLQTEDS
     */
    private Set edsEdsesForEdsManagerId = new HashSet(0);
    /**
     * Variable to hold the value for Column U_CONF of Table OPLQTUSE
     */
    private Clob UConf;
    /**
     * Variable to hold value of UserConfig
     */
    private UserConfig config;
    /**
     * Set Collection to hold the values for String
     */
    private Set<String> rights;
    /**
     * Constant to hold value of USER_DELETED
     */
    public static final int USER_DELETED = 0;
    /**
     * Constant to hold value of USER_ACTIVE
     */
    public static final int USER_ACTIVE = 1;

    /**
     * Default Constructor
     */
    public EdsUser() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param UId Eds User ID
     * @param UPsaId Eds User PSA id
     * @param UFirstname Eds User First name
     * @param ULastname Eds User Last name
     * @param UActive Eds User Active
     */
    public EdsUser(String UId, String UPsaId, String UFirstname, String ULastname, int UActive) {
        this.UId = UId;
        this.UPsaId = UPsaId;
        this.UFirstname = UFirstname;
        this.ULastname = ULastname;
        this.UActive = UActive;
    }

    /**
     * Parameterized Constructor
     * 
     * @param UId Eds User ID
     * @param edsPerimeter Eds Perimeter
     * @param edsSupplier Eds Supplier
     * @param edsRole Eds Role
     * @param UPsaId Eds User PSA id
     * @param UFirstname Eds User first name
     * @param ULastname Eds User last name
     * @param UService Eds User Service
     * @param UActive Eds User active
     * @param edsEdsesForEdsOfficerId set of Edses for Eds officer Id
     * @param edsEdsesForEdsAdminId set of Edsed for Eds admin Id
     * @param edsSubscriptions Set of Eds subscription
     * @param edsEdsesForEdsManagerId Set of Edses for manager Id
     * @param UConf Clob
     */
    public EdsUser(String UId, EdsPerimeter edsPerimeter, EdsSupplier edsSupplier, EdsRole edsRole, String UPsaId, String UFirstname,
            String ULastname, String UService, int UActive, Set edsEdsesForEdsOfficerId, Set edsEdsesForEdsAdminId, Set edsSubscriptions,
            Set edsEdsesForEdsManagerId, Clob UConf) {
        this.UId = UId;
        this.edsPerimeter = edsPerimeter;
        this.edsSupplier = edsSupplier;
        this.edsRole = edsRole;
        this.UPsaId = UPsaId;
        this.UFirstname = UFirstname;
        this.ULastname = ULastname;
        this.UService = UService;
        this.UActive = UActive;
        this.edsEdsesForEdsOfficerId = edsEdsesForEdsOfficerId;
        this.edsEdsesForEdsAdminId = edsEdsesForEdsAdminId;
        this.edsSubscriptions = edsSubscriptions;
        this.edsEdsesForEdsManagerId = edsEdsesForEdsManagerId;
        this.UConf = UConf;
    }

    /**
     * Function to get UId
     * 
     * @return the Value of UId
     */
    @XmlTransient
    public String getUId() {
        return this.UId;
    }

    /**
     * Function to set UId
     * 
     * @param UId Eds User Id
     */
    public void setUId(String UId) {
        this.UId = UId;
    }

    /**
     * Function to get edsPerimeter
     * 
     * @return the Value of edsPerimeter
     */
    @XmlElement
    public EdsPerimeter getEdsPerimeter() {
        return this.edsPerimeter;
    }

    /**
     * Function to set edsPerimeter
     * 
     * @param edsPerimeter Eds perimeter
     */
    public void setEdsPerimeter(EdsPerimeter edsPerimeter) {
        this.edsPerimeter = edsPerimeter;
    }

    /**
     * Function to get edsSupplier
     * 
     * @return the Value of edsSupplier
     */
    @XmlElement
    public EdsSupplier getEdsSupplier() {
        return this.edsSupplier;
    }

    /**
     * Function to set edsSupplier
     * 
     * @param edsSupplier Eds supplier
     */
    public void setEdsSupplier(EdsSupplier edsSupplier) {
        this.edsSupplier = edsSupplier;
    }

    /**
     * Function to get edsRole
     * 
     * @return the Value of edsRole
     */
    @XmlElement
    public EdsRole getEdsRole() {
        return this.edsRole;
    }

    /**
     * Function to set edsRole
     * 
     * @param edsRole Eds Role
     */
    public void setEdsRole(EdsRole edsRole) {
        this.edsRole = edsRole;
    }

    /**
     * Function to get UPsaId
     * 
     * @return the Value of UPsaId
     */
    @XmlElement
    public String getUPsaId() {
        return this.UPsaId;
    }

    /**
     * Function to set UPsaId
     * 
     * @param UPsaId Eds User PSA id
     */
    public void setUPsaId(String UPsaId) {
        this.UPsaId = UPsaId;
    }

    /**
     * Function to get UFirstname
     * 
     * @return the Value of UFirstname
     */
    @XmlElement
    public String getUFirstname() {
        return this.UFirstname;
    }

    /**
     * Function to set UFirstname
     * 
     * @param UFirstname Eds User First name
     */
    public void setUFirstname(String UFirstname) {
        this.UFirstname = UFirstname;
    }

    /**
     * Function to get ULastname
     * 
     * @return the Value of ULastname
     */
    @XmlElement
    public String getULastname() {
        return this.ULastname;
    }

    /**
     * Function to set ULastname
     * 
     * @param ULastname Eds User Last name
     */
    public void setULastname(String ULastname) {
        this.ULastname = ULastname;
    }

    /**
     * Function to get UService
     * 
     * @return the Value of UService
     */
    @XmlElement
    public String getUService() {
        return this.UService;
    }

    /**
     * Function to set UService
     * 
     * @param UService Eds User service
     */
    public void setUService(String UService) {
        this.UService = UService;
    }

    /**
     * Function to get UActive
     * 
     * @return the Value of UActive
     */
    @XmlElement(name = "is-active")
    public int getUActive() {
        return UActive;
    }

    /**
     * Function to set UActive
     * 
     * @param UActive Eds User active or not
     */
    public void setUActive(int UActive) {
        this.UActive = UActive;
    }

    /**
     * Function to get edsEdsesForEdsOfficerId
     * 
     * @return the Value of edsEdsesForEdsOfficerId
     */
    @XmlTransient
    public Set getEdsEdsesForEdsOfficerId() {
        return this.edsEdsesForEdsOfficerId;
    }

    /**
     * Function to set edsEdsesForEdsOfficerId
     * 
     * @param edsEdsesForEdsOfficerId set of Edes for Eds officer Id
     */
    public void setEdsEdsesForEdsOfficerId(Set edsEdsesForEdsOfficerId) {
        this.edsEdsesForEdsOfficerId = edsEdsesForEdsOfficerId;
    }

    /**
     * Function to get edsEdsesForEdsAdminId
     * 
     * @return the Value of edsEdsesForEdsAdminId
     */
    @XmlTransient
    public Set getEdsEdsesForEdsAdminId() {
        return this.edsEdsesForEdsAdminId;
    }

    /**
     * Function to set edsEdsesForEdsAdminId
     * 
     * @param edsEdsesForEdsAdminId set of Edses for Eds admin Id
     */
    public void setEdsEdsesForEdsAdminId(Set edsEdsesForEdsAdminId) {
        this.edsEdsesForEdsAdminId = edsEdsesForEdsAdminId;
    }

    /**
     * Function to get edsSubscriptions
     * 
     * @return the Value of edsSubscriptions
     */
    @XmlTransient
    public Set getEdsSubscriptions() {
        return this.edsSubscriptions;
    }

    /**
     * Function to set edsSubscriptions
     * 
     * @param edsSubscriptions Eds subscription
     */
    public void setEdsSubscriptions(Set edsSubscriptions) {
        this.edsSubscriptions = edsSubscriptions;
    }

    /**
     * Function to get edsEdsesForEdsManagerId
     * 
     * @return the Value of edsEdsesForEdsManagerId
     */
    @XmlTransient
    public Set getEdsEdsesForEdsManagerId() {
        return this.edsEdsesForEdsManagerId;
    }

    /**
     * Function to set edsEdsesForEdsManagerId
     * 
     * @param edsEdsesForEdsManagerId set of Edses for Eds manager Id
     */
    public void setEdsEdsesForEdsManagerId(Set edsEdsesForEdsManagerId) {
        this.edsEdsesForEdsManagerId = edsEdsesForEdsManagerId;
    }

    /**
     * Function to get UConf
     * 
     * @return the Value of UConf
     */
    @XmlTransient
    public Clob getUConf() {
        if (config != null) {
            UConf = UserConfig.toClob(config);
        }

        return this.UConf;
    }

    /**
     * Function to set UConf
     * 
     * @param UConf Clob
     */
    public void setUConf(Clob UConf) {
        this.UConf = UConf;
    }

    /**
     * Function to get config
     * 
     * @return the Value of config
     */
    @XmlTransient
    public UserConfig getConfig() {
        if (config == null) {
            if (UConf == null) {
                config = new UserConfig();
            } else {
                config = UserConfig.fromClob(UConf);
            }
        }
        return config;
    }

    /**
     * Function to get config
     * 
     * @return the Value of config
     */
    public UserConfig getNewConfig() {
        if (UConf == null) {
            return new UserConfig();
        } else {
            return UserConfig.fromClob(UConf);
        }
    }

    /**
     * Function to set config
     * 
     * @param config User Config
     */
    public void setConfig(UserConfig config) {
        this.config = config;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EdsUser other = (EdsUser) obj;
        if ((this.UId == null) ? (other.UId != null) : !this.UId.equals(other.UId)) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + (this.UId != null ? this.UId.hashCode() : 0);
        return hash;
    }

    /**
     * Function to get FullName
     * 
     * @return the FullName
     */
    public String toFullName() {
        if (UActive == USER_DELETED) {
            return "Utilisateur supprimé";
        } else {
            return getUFirstname() + ' ' + getULastname().toUpperCase();
        }
    }

    /**
     * Function to get FullIdentity
     * 
     * @return FullIdentity
     */
    public String toFullIdentity() {
        if (UActive == USER_DELETED) {
            return "Utilisateur supprimé - " + getUPsaId();
        } else {
            return getUFirstname() + ' ' + getULastname().toUpperCase() + " - " + getUPsaId();
        }
    }

    /**
     * Function to get PSA identity
     * 
     * @return PSA identity
     */
    public String toPSAIdentity() {
        if (UActive == USER_DELETED) {
            return getUPsaId() + " (Utilisateur supprimé)";
        } else {
            StringBuilder builder = new StringBuilder(getUPsaId());
            builder.append(' ');
            builder.append('(');
            builder.append(getULastname().toUpperCase());
            builder.append(' ');
            builder.append(getUFirstname());
            builder.append(')');

            return builder.toString();
        }
    }
}
