-- ADDING VEHICLE_FILE_ID IN TRACEABILITY TABLE
ALTER TABLE COPQTTRA ADD VEHICLE_FILE_ID BIGINT(20);

-- CREATING FOREIGN KEY CONSTRAINT
ALTER TABLE COPQTTRA ADD CONSTRAINT COPQITRA1 FOREIGN KEY (VEHICLE_FILE_ID) REFERENCES COPQTVHF(ID);

-- ADD COLUMN HIERARCHY IN TEST NATURE
ALTER TABLE COPQTTNR ADD HIERARCHY BIGINT(20);

-- ADD COLUMN STATISTICAL_ID IN REGULATION GROUP
ALTER TABLE COPQTTRG ADD STATISTICAL_ID BIGINT(20);

-- CREATING FOREIGN KEY CONTRAINT
ALTER TABLE COPQTTRG ADD CONSTRAINT COPQITRG5 FOREIGN KEY (STATISTICAL_ID) REFERENCES COPQTSCR(ID);
