-- UPDATE ARCHIVE BOX TABLE
ALTER TABLE COPQTARB ADD CLOSING_DATE DATETIME NOT NULL;
ALTER TABLE COPQTARB ADD OPENING_DATE DATETIME NOT NULL;
ALTER TABLE COPQTARB ADD MODEL_YEAR INTEGER;
ALTER TABLE COPQTARB ADD FUEL_ID BIGINT(20);
ALTER TABLE COPQTARB ADD PROJECT_CODE_FAMILY_ID BIGINT(20);
ALTER TABLE COPQTARB ADD TYPE_OF_TEST_ID BIGINT(20);

-- CREATING FK RELATIONSHIP OF ARCHIVE BOX WITH FUEL, PROJECT CODE, TYPE OF TEST
ALTER TABLE COPQTARB ADD CONSTRAINT COPQIARB1 FOREIGN KEY (FUEL_ID) REFERENCES COPQTAFL(ID);
ALTER TABLE COPQTARB ADD CONSTRAINT COPQIARB2 FOREIGN KEY (PROJECT_CODE_FAMILY_ID) REFERENCES COPQTPCF(PRJT_FAMILY_ID);
ALTER TABLE COPQTARB ADD CONSTRAINT COPQIARB3 FOREIGN KEY (TYPE_OF_TEST_ID) REFERENCES COPQTTOT(ID);

-- CREATING FK RELATIONSHIP WITH VEHICLE
ALTER TABLE COPQTVHL ADD CORVET_DATA_ID BIGINT(20);
ALTER TABLE COPQTVHL ADD CONSTRAINT COPQIVHL5 FOREIGN KEY (CORVET_DATA_ID) REFERENCES COPQTCVD(ID);

-- ADD COLUMN IN OPACITY RESULT TABLE
ALTER TABLE COPQTOPR ADD FUEL_TYPE_ID INT(11);

-- CREATING FK RELATIONSHIP WITH FUEL TYPE
ALTER TABLE COPQTOPR ADD CONSTRAINT COPQIOPR FOREIGN KEY (FUEL_TYPE_ID) REFERENCES COPQTFTP(ID);

-- ADD COLUMN IN SAMPLING RULE
ALTER TABLE COPQTTVV ADD SAMPLING_LABEL VARCHAR(255);

-- ADD COLUMN PREVIOUSE_VEHICLE_FILE_STATUS_ID IN VEHICLE
ALTER TABLE COPQTVHF ADD PREVIOUS_VF_STATUS_ID BIGINT(20);

-- CREATING FK RELATIONSHIP WITH VEHICLE FILE STATUS
ALTER TABLE COPQTVHF ADD CONSTRAINT COPQIVHF9 FOREIGN KEY (PREVIOUS_VF_STATUS_ID) REFERENCES COPQTVFS(ID);