SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS COPQTCDR;
DROP TABLE IF EXISTS COPQTCVD;
DROP TABLE IF EXISTS COPQTEPR;
DROP TABLE IF EXISTS COPQTSTC;
DROP TABLE IF EXISTS COPQTTCC;
SET FOREIGN_KEY_CHECKS = 1;