/*Alter script  for class and tvv*/

ALTER TABLE COPQTTVV ADD  CLASZ_ID BIGINT(20);
ALTER TABLE COPQTTVV ADD CONSTRAINT COPQITVV12 FOREIGN KEY (CLASZ_ID) REFERENCES COPQTACS(ID);

/*Alter script for fuel injection type and tvv*/
ALTER TABLE COPQTTVV ADD  FUELINJECTIONTYPE_ID BIGINT(20); 
ALTER TABLE COPQTTVV ADD CONSTRAINT COPQITVV13 FOREIGN KEY (FUELINJECTIONTYPE_ID) REFERENCES COPQTFIT(ID);