ALTER TABLE COPQTVHL  DROP COLUMN DESTINATION_COUNTRY;
ALTER TABLE COPQTVHL ADD  COUNTRY_ID BIGINT(20);
ALTER TABLE COPQTVHL ADD CONSTRAINT COPQIVHL4 FOREIGN KEY (COUNTRY_ID) REFERENCES COPQTCTY(ID);
