package com.inetpsa.xml.services.oasisplm.interfaceoasis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.inetpsa.cxl.core.fault.ServiceException;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 */
@WebService(name = "InterfaceOasisPortType", targetNamespace = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface InterfaceOasisPortType {

    /**
     * @param calculationRequest
     * @return returns com.inetpsa.xml.services.oasisplm.interfaceoasis.CalculationResponse
     * @throws ServiceException
     */
    @WebMethod(operationName = "Calculation", action = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis#Calculation")
    @WebResult(name = "CalculationResponse", targetNamespace = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", partName = "CalculationResponse")
    public CalculationResponse calculation(
            @WebParam(name = "CalculationRequest", targetNamespace = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", partName = "CalculationRequest") CalculationRequest calculationRequest)
            throws ServiceException;

    /**
     * @param checkFormulaRequest
     * @return returns com.inetpsa.xml.services.oasisplm.interfaceoasis.CheckFormulaResponse
     * @throws ServiceException
     */
    @WebMethod(operationName = "CheckFormula", action = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis#CheckFormula")
    @WebResult(name = "CheckFormulaResponse", targetNamespace = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", partName = "CheckFormulaResponse")
    public CheckFormulaResponse checkFormula(
            @WebParam(name = "CheckFormulaRequest", targetNamespace = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", partName = "CheckFormulaRequest") CheckFormulaRequest checkFormulaRequest)
            throws ServiceException;

}
