
package com.inetpsa.xml.services.oasisplm.interfaceoasis;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InterfaceOasis", targetNamespace = "http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", wsdlLocation = "file://wsdl/InterfaceOasis.wsdl")
public class InterfaceOasis
    extends Service
{

    private final static URL INTERFACEOASIS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.inetpsa.xml.services.oasisplm.interfaceoasis.InterfaceOasis.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.inetpsa.xml.services.oasisplm.interfaceoasis.InterfaceOasis.class.getResource(".");
            url = new URL(baseUrl, "file://wsdl/InterfaceOasis.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file://wsdl/InterfaceOasis.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTERFACEOASIS_WSDL_LOCATION = url;
    }

    public InterfaceOasis(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceOasis() {
        super(INTERFACEOASIS_WSDL_LOCATION, new QName("http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", "InterfaceOasis"));
    }

    /**
     * 
     * @return
     *     returns InterfaceOasisPortType
     */
    @WebEndpoint(name = "InterfaceOasisHttpPort")
    public InterfaceOasisPortType getInterfaceOasisHttpPort() {
        return super.getPort(new QName("http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", "InterfaceOasisHttpPort"), InterfaceOasisPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceOasisPortType
     */
    @WebEndpoint(name = "InterfaceOasisHttpPort")
    public InterfaceOasisPortType getInterfaceOasisHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.inetpsa.com/Services/OasisPLM/InterfaceOasis", "InterfaceOasisHttpPort"), InterfaceOasisPortType.class, features);
    }

}
