ALTER TABLE PV2QTPIC ADD CONSTRAINT FPV2QIPI1 FOREIGN KEY (PFM_ID) REFERENCES PV2QTPFM(ID);
ALTER TABLE PV2QTPIC ADD CONSTRAINT FPV2QIPI2 FOREIGN KEY (LAST_MODIFIED_USR) REFERENCES PV2QTUSR(ID);
ALTER TABLE PV2QTPIC ADD CONSTRAINT FPV2QIPI3 FOREIGN KEY (LAST_UPDATED_USR) REFERENCES PV2QTUSR(ID);