ALTER TABLE COPQTTCC ADD CONSTRAINT COPQITCC1 FOREIGN KEY (USER_ID) REFERENCES COPQTUSR(ID);
ALTER TABLE COPQTTCC ADD CONSTRAINT COPQITCC2 FOREIGN KEY (VLD_TVVDEP_TCL_ID) REFERENCES COPQTVCL(ID);
ALTER TABLE COPQTTCC ADD CONSTRAINT COPQITCC3 FOREIGN KEY (VLD_ESDEP_TCL_ID) REFERENCES COPQTVLC(ID);
ALTER TABLE COPQTTCC ADD CONSTRAINT COPQITCC4 FOREIGN KEY (VEHICLE_FILE_ID) REFERENCES COPQTVHF(ID);