ALTER TABLE COPQTSTC ADD CONSTRAINT COPQISTC1 FOREIGN KEY (VEHICLE_FILE_ID) REFERENCES COPQTVHF(ID);
ALTER TABLE COPQTSTC ADD CONSTRAINT COPQISTC2 FOREIGN KEY (UNIT_ID) REFERENCES COPQTUNT(ID);
ALTER TABLE COPQTSTC ADD CONSTRAINT COPQISTC3 FOREIGN KEY (USER_ID) REFERENCES COPQTUSR(ID);