package com.inetpsa.eds.ws.model;

// Generated 17 juil. 2012 18:39:43 by Hibernate Tools 3.2.1.GA

import com.inetpsa.eds.dao.model.EdsUser;
import java.util.Date;

/**
 * This class represent EdsWsSessionToken generated by hbm2java
 * 
 * @author Geometric Ltd.
 */
public class EdsWsSessionToken implements java.io.Serializable {

    /**
     * String Variable to hold the value for Column WST_ID of Table OPLQTWST
     */
    private String wstId;
    /**
     * Variable to hold the value for Column WST_U_ID of Table OPLQTWST
     */
    private EdsUser edsUser;
    /**
     * String Variable to hold the value for Column WST_REMOTE_ADDRESS of Table OPLQTWST
     */
    private String wstRemoteAddress;
    /**
     * Date Variable to hold the value for Column WST_EXPIRATION_DATE of Table OPLQTWST
     */
    private Date wstExpirationDate;
    /**
     * Date Variable to hold the value for Column WST_EXPIRATION_DATE of Table OPLQTWST
     */
    private String wstSource;

    /**
     * Login used with the token. Note that it may be possible for the associated EDS user to be null, if the WS only use the LDAP to check the
     * authentication. Column WST_LOGIN of Table OPLQTWST
     */
    private String wstLogin;

    /**
     * Default source of token
     */
    public static String SOURCE_DEFAULT = "DEFAULT";
    /**
     * Gs source of token (EDS used on Bilan application)
     */
    public static String SOURCE_GS = "GS";

    /**
     * Default Constructor
     */
    public EdsWsSessionToken() {
    }

    /**
     * Parameterized Constructor
     * 
     * @param wstId web service session token id
     * @param wstLogin User login used
     * @param wstExpirationDate Web service session token expire date
     * @param wstRemoteAddress web service session token remote address
     * @param wstSource Source token creation (DEFAULT, GS ...)
     */
    public EdsWsSessionToken(String wstId, String wstLogin, Date wstExpirationDate, String wstRemoteAddress, String wstSource) {
        this.wstId = wstId;
        this.wstLogin = wstLogin;
        this.wstExpirationDate = wstExpirationDate;
        this.wstRemoteAddress = wstRemoteAddress;
        this.wstSource = wstSource;
    }

    /**
     * Parameterized Constructor
     * 
     * @param wstId web service session token id
     * @param edsUser Eds user details
     * @param wstRemoteAddress Web service session token remote address
     * @param wstExpirationDate Web service session token expire date
     * @param wstSource Source token creation (DEFAULT, GS ...)
     */
    public EdsWsSessionToken(String wstId, EdsUser edsUser, String wstRemoteAddress, Date wstExpirationDate, String wstSource) {
        this.wstId = wstId;
        this.wstLogin = edsUser.getUPsaId();
        this.edsUser = edsUser;
        this.wstRemoteAddress = wstRemoteAddress;
        this.wstExpirationDate = wstExpirationDate;
        this.wstSource = wstSource;
    }

    /**
     * Function to get Web service session token ID
     * 
     * @return web service session token id
     */
    public String getWstId() {
        return this.wstId;
    }

    /**
     * Function to set Web service session token ID
     * 
     * @param wstId web service session token id
     */
    public void setWstId(String wstId) {
        this.wstId = wstId;
    }

    /**
     * Gets the wst login.
     * 
     * @return the wst login
     */
    public String getWstLogin() {
        return wstLogin;
    }

    /**
     * Sets the wst login.
     * 
     * @param wstLogin the new wst login
     */
    public void setWstLogin(String wstLogin) {
        this.wstLogin = wstLogin;
    }

    /**
     * Function to get Eds User details
     * 
     * @return the Value of edsUser
     */
    public EdsUser getEdsUser() {
        return this.edsUser;
    }

    /**
     * Function to set Eds User Details
     * 
     * @param edsUser Eds User details
     */
    public void setEdsUser(EdsUser edsUser) {
        this.edsUser = edsUser;
    }

    /**
     * Function to get Web service session token expire date
     * 
     * @return the Value of Web service session token expire date
     */
    public Date getWstExpirationDate() {
        return this.wstExpirationDate;
    }

    /**
     * Function to set Web service session token expire date
     * 
     * @param wstExpirationDate Web service session token expire date
     */
    public void setWstExpirationDate(Date wstExpirationDate) {
        this.wstExpirationDate = wstExpirationDate;
    }

    /**
     * Function to get Web service session token remote address
     * 
     * @return the Value of Web service session token remote address
     */
    public String getWstRemoteAddress() {
        return wstRemoteAddress;
    }

    /**
     * Function to set web service session token remote Address
     * 
     * @param wstRemoteAddress web service remote address
     */
    public void setWstRemoteAddress(String wstRemoteAddress) {
        this.wstRemoteAddress = wstRemoteAddress;
    }

    /**
     * Get source of token
     * 
     * @return
     */
    public String getWstSource() {
        return wstSource;
    }

    /**
     * Set source of token
     * 
     * @param wstSource
     */
    public void setWstSource(String wstSource) {
        this.wstSource = wstSource;
    }
}
