CREATE
    TABLE PV2QTDRA(
	ID BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	COMMENTS_FR VARCHAR(4000) NULL,
	COMMENTS_EN VARCHAR(4000) NULL,
	SPECIFICDRAW_FILE VARCHAR(255) NULL,
	PFM_ID BIGINT(20) NOT NULL
	);
	
	