CREATE TABLE PV2QTPIC(
	ID BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
	VARIANT VARCHAR(255) NOT NULL,
	URL VARCHAR(255) NULL,	
	IS_FRONTAGE_PICTO tinyint(1) DEFAULT NULL,	
	IS_VISIBLE tinyint(1) DEFAULT NULL,	
	PFM_ID BIGINT(20) NOT NULL,
	CREATE_DATE DATE NOT NULL,
	MODIFY_DATE DATE NOT NULL,
	VERSION VARCHAR(255) NULL,
	LAST_UPDATE_DATE DATE DEFAULT NULL,
	LAST_UPDATED_USR BIGINT(20) DEFAULT NULL,
 	LAST_MODIFIED_USR BIGINT(20) DEFAULT NULL
	);
	
	
	
	
	

	
