CREATE 
	TABLE PV2QTDIS (
		ID INT(11) UNIQUE NOT NULL AUTO_INCREMENT,
		PIC_ID BIGINT(20) NOT NULL,
		USR_ID BIGINT(20) NOT NULL,
		DOWNLOAD_DATE DATE DEFAULT NULL,
		DOWNLOAD_FLAG TINYINT(1) DEFAULT NULL,
		IS_OPEN_LOCAL_IMG TINYINT(1) DEFAULT '0'
  );