CREATE
    TABLE PV2QTUSR(
	ID BIGINT(20) UNIQUE AUTO_INCREMENT NOT NULL,
	USER_ID varchar(255) UNIQUE NOT NULL,  
	FIRST_NAME varchar(255) DEFAULT NULL,  
	LAST_NAME varchar(255) DEFAULT NULL,
	EMAIL varchar(255) DEFAULT NULL,
	PHONE_NUM varchar(255) DEFAULT NULL,
	IS_ACTIVE tinyint(1) DEFAULT NULL,
	IS_THICK_CLIENT tinyint(4) DEFAULT NULL
	);
	
	