ALTER TABLE COPQTPTR ADD CONSTRAINT COPQIPTR1 FOREIGN KEY (POLLGAS_RESULT_SET_ID) REFERENCES COPQTPRS(ID);

ALTER TABLE COPQTPTR ADD CONSTRAINT COPQIPTR4 FOREIGN KEY (TVV_Valued_POLL_GAS_LIMIT) REFERENCES COPQTVPG(ID);