ALTER TABLE COPQTSSL ADD CONSTRAINT COPQISSL1 FOREIGN KEY (TECHNICALCASE_ID) REFERENCES COPQTTTC(ID);
ALTER TABLE COPQTSSL ADD CONSTRAINT COPQISSL2 FOREIGN KEY (FACTORY_ID) REFERENCES COPQTFTY(FACTORY_ID);
ALTER TABLE COPQTSSL ADD CONSTRAINT COPQISSL3 FOREIGN KEY (TYPE_OF_TEST_ID) REFERENCES COPQTTOT(ID);