ALTER TABLE COPQTPRF ADD CONSTRAINT COPQIPRF1 FOREIGN KEY (PREP_FILE_STRUCTURE_ID) REFERENCES COPQTPFS(ID);
ALTER TABLE COPQTPRF ADD CONSTRAINT COPQIPRF2 FOREIGN KEY (VEHICLE_FILE_ID) REFERENCES COPQTVHF(ID);
ALTER TABLE COPQTPRF ADD CONSTRAINT COPQIPRF3 FOREIGN KEY (USER_ID) REFERENCES COPQTUSR(ID);