ALTER TABLE COPQTARB ADD CONSTRAINT COPQIARB1 FOREIGN KEY (FUEL_ID) REFERENCES COPQTAFL(ID);
ALTER TABLE COPQTARB ADD CONSTRAINT COPQIARB2 FOREIGN KEY (PROJECT_CODE_FAMILY_ID) REFERENCES COPQTPCF(PRJT_FAMILY_ID);
ALTER TABLE COPQTARB ADD CONSTRAINT COPQIARB3 FOREIGN KEY (TYPE_OF_TEST_ID) REFERENCES COPQTTOT(ID);