ALTER TABLE COPQTVTD ADD CONSTRAINT COPQIVTD1 FOREIGN KEY (ESDEPENDENT_DATALIST_ID) REFERENCES COPQTVLD(ID);
ALTER TABLE COPQTVTD ADD CONSTRAINT COPQIVTD2 FOREIGN KEY (VALUED_DATALIST_ID) REFERENCES COPQTVDL(ID);
ALTER TABLE COPQTVTD ADD CONSTRAINT COPQIVTD3 FOREIGN KEY (UNIT_ID) REFERENCES COPQTUNT(ID);
ALTER TABLE COPQTVTD ADD CONSTRAINT COPQIVTD4 FOREIGN KEY (GENERIC_DATA_ID) REFERENCES COPQTGTD(ID);