ALTER TABLE COPQTTRG ADD CONSTRAINT COPQITRG1 FOREIGN KEY (STATUS_ID) REFERENCES COPQTAST(STATUS_ID);
ALTER TABLE COPQTTRG ADD CONSTRAINT COPQITRG2 FOREIGN KEY (AREA_ID) REFERENCES COPQTTAA (ID);
ALTER TABLE COPQTTRG ADD CONSTRAINT COPQITRG3 FOREIGN KEY (EMISSION_ID) REFERENCES COPQTAES (ID);
ALTER TABLE COPQTTRG ADD CONSTRAINT COPQITRG4 FOREIGN KEY (WLTP_ID) REFERENCES COPQTWLD (ID);