ALTER TABLE COPQTGTD ADD CONSTRAINT COPQIGTD1 FOREIGN KEY (UNIT_ID) REFERENCES COPQTUNT(ID);
ALTER TABLE COPQTGTD ADD CONSTRAINT COPQIGTD2 FOREIGN KEY (TECHNICALDATALIST_ID) REFERENCES COPQTTDL(ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COPQTGTD ADD CONSTRAINT COPQIGTD3 FOREIGN KEY (EMSDEPTDL_ID) REFERENCES COPQTEDL(ID) ON DELETE CASCADE ON UPDATE CASCADE;