ALTER TABLE COPQTGTC ADD CONSTRAINT COPQIGTC4 FOREIGN KEY (UNIT_ID) REFERENCES COPQTUNT(ID);
ALTER TABLE COPQTGTC ADD CONSTRAINT COPQIGTC5 FOREIGN KEY (TESTCONDITIONLIST_ID) REFERENCES COPQTTCL(ID) ON DELETE CASCADE ON UPDATE CASCADE ;
ALTER TABLE COPQTGTC ADD CONSTRAINT COPQIGTC6 FOREIGN KEY (EMSDEPTCL_ID) REFERENCES COPQTECL(ID) ON DELETE CASCADE ON UPDATE CASCADE;