ALTER TABLE COPQTTTC ADD CONSTRAINT COPQITTC1 FOREIGN KEY (TGROUP_ID) REFERENCES COPQTTGP(ID);
ALTER TABLE COPQTTTC ADD CONSTRAINT COPQITTC2 FOREIGN KEY (EMS_ID) REFERENCES COPQTAES(ID);
ALTER TABLE COPQTTTC ADD CONSTRAINT COPQITTC3 FOREIGN KEY (TVV_ID) REFERENCES COPQTTVV(ID) ON DELETE CASCADE ON UPDATE CASCADE;