ALTER TABLE COPQTAES ADD CONSTRAINT COPQIAES1 FOREIGN KEY (LCDVCODE_ID) REFERENCES COPQTGCO(LCDV_CODE_ID);
ALTER TABLE COPQTAES ADD CONSTRAINT COPQIAES2 FOREIGN KEY (TVV_RULE_ID) REFERENCES COPQTGTV(TVV_RULE_ID);
ALTER TABLE COPQTAES ADD CONSTRAINT COPQIAES3 FOREIGN KEY (STATUS_ID) REFERENCES COPQTAST(STATUS_ID);