ALTER TABLE COPQTVTC ADD CONSTRAINT COPQIVTC1 FOREIGN KEY (ESDEPENDENT_CONDITIONLIST_ID) REFERENCES COPQTVLC(ID);
ALTER TABLE COPQTVTC ADD CONSTRAINT COPQIVTC2 FOREIGN KEY (VALUED_CONDITIONLIST_ID) REFERENCES COPQTVCL(ID);
ALTER TABLE COPQTVTC ADD CONSTRAINT COPQIVTC3 FOREIGN KEY (UNIT_ID) REFERENCES COPQTUNT(ID);
ALTER TABLE COPQTVTC ADD CONSTRAINT COPQIVTC4 FOREIGN KEY (GENERIC_CONDITION_ID) REFERENCES COPQTGTC(ID);