ALTER TABLE COPQTVFC ADD CONSTRAINT COPQIVFC1 FOREIGN KEY (FCLABEL_ID) REFERENCES COPQTFCL(ID);
ALTER TABLE COPQTVFC ADD CONSTRAINT COPQIVFC2 FOREIGN KEY (FCLIST_ID) REFERENCES COPQTVFL(ID);
ALTER TABLE COPQTVFC ADD CONSTRAINT COPQIVFC3 FOREIGN KEY (PGASLABEL_ID) REFERENCES COPQTPGL(ID);