ALTER TABLE COPQTENG ADD CONSTRAINT COPQIENG1 FOREIGN KEY (TVV_RULE_ID_B0C) REFERENCES COPQTGTV(TVV_RULE_ID);
ALTER TABLE COPQTENG ADD CONSTRAINT COPQIENG2 FOREIGN KEY (FUELINJECTION_ID) REFERENCES COPQTFIT(ID);
ALTER TABLE COPQTENG ADD CONSTRAINT COPQIENG3 FOREIGN KEY (FUELTYPE_ID) REFERENCES COPQTFTP(ID);
ALTER TABLE COPQTENG ADD CONSTRAINT COPQIENG4 FOREIGN KEY (TVV_RULE_ID_DOC) REFERENCES COPQTGTV(TVV_RULE_ID);