ALTER TABLE COPQTMSN ADD CONSTRAINT COPQIMSN1 FOREIGN KEY (STATUS_ID) REFERENCES COPQTAST(STATUS_ID); 
ALTER TABLE COPQTMSN ADD CONSTRAINT COPQIMSN2 FOREIGN KEY (TEST_ID) REFERENCES COPQTTNR(TEST_ID);