//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 04:43:32 PM IST 
//


package org.seedstack.pv2.picxml.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.seedstack.pv2.picxml.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.seedstack.pv2.picxml.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PictoDescription }
     * 
     */
    public PictoDescription createPictoDescription() {
        return new PictoDescription();
    }

    /**
     * Create an instance of {@link PictoDescription.PictoList }
     * 
     */
    public PictoDescription.PictoList createPictoDescriptionPictoList() {
        return new PictoDescription.PictoList();
    }

    /**
     * Create an instance of {@link PictoDescription.AdaptationList }
     * 
     */
    public PictoDescription.AdaptationList createPictoDescriptionAdaptationList() {
        return new PictoDescription.AdaptationList();
    }

    /**
     * Create an instance of {@link PictoDescription.GeometryList }
     * 
     */
    public PictoDescription.GeometryList createPictoDescriptionGeometryList() {
        return new PictoDescription.GeometryList();
    }

    /**
     * Create an instance of {@link PictoDescription.DocumentList }
     * 
     */
    public PictoDescription.DocumentList createPictoDescriptionDocumentList() {
        return new PictoDescription.DocumentList();
    }

    /**
     * Create an instance of {@link PictoDescription.General }
     * 
     */
    public PictoDescription.General createPictoDescriptionGeneral() {
        return new PictoDescription.General();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNCmd }
     * 
     */
    public PictoDescription.RHNCmd createPictoDescriptionRHNCmd() {
        return new PictoDescription.RHNCmd();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNTémoins }
     * 
     */
    public PictoDescription.RHNTémoins createPictoDescriptionRHNTémoins() {
        return new PictoDescription.RHNTémoins();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNLight }
     * 
     */
    public PictoDescription.RHNLight createPictoDescriptionRHNLight() {
        return new PictoDescription.RHNLight();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNActivation }
     * 
     */
    public PictoDescription.RHNActivation createPictoDescriptionRHNActivation() {
        return new PictoDescription.RHNActivation();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNAlerte }
     * 
     */
    public PictoDescription.RHNAlerte createPictoDescriptionRHNAlerte() {
        return new PictoDescription.RHNAlerte();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNDefaillance }
     * 
     */
    public PictoDescription.RHNDefaillance createPictoDescriptionRHNDefaillance() {
        return new PictoDescription.RHNDefaillance();
    }

    /**
     * Create an instance of {@link PictoDescription.RHNInfo }
     * 
     */
    public PictoDescription.RHNInfo createPictoDescriptionRHNInfo() {
        return new PictoDescription.RHNInfo();
    }

    /**
     * Create an instance of {@link PictoDescription.Lighting }
     * 
     */
    public PictoDescription.Lighting createPictoDescriptionLighting() {
        return new PictoDescription.Lighting();
    }

    /**
     * Create an instance of {@link PictoDescription.Information }
     * 
     */
    public PictoDescription.Information createPictoDescriptionInformation() {
        return new PictoDescription.Information();
    }

    /**
     * Create an instance of {@link PictoDescription.KeywordList }
     * 
     */
    public PictoDescription.KeywordList createPictoDescriptionKeywordList() {
        return new PictoDescription.KeywordList();
    }

    /**
     * Create an instance of {@link PictoDescription.PrivateMessage }
     * 
     */
    public PictoDescription.PrivateMessage createPictoDescriptionPrivateMessage() {
        return new PictoDescription.PrivateMessage();
    }

    /**
     * Create an instance of {@link PictoDescription.PictoList.Picto }
     * 
     */
    public PictoDescription.PictoList.Picto createPictoDescriptionPictoListPicto() {
        return new PictoDescription.PictoList.Picto();
    }

    /**
     * Create an instance of {@link PictoDescription.AdaptationList.Adaptation }
     * 
     */
    public PictoDescription.AdaptationList.Adaptation createPictoDescriptionAdaptationListAdaptation() {
        return new PictoDescription.AdaptationList.Adaptation();
    }

    /**
     * Create an instance of {@link PictoDescription.GeometryList.Geometry }
     * 
     */
    public PictoDescription.GeometryList.Geometry createPictoDescriptionGeometryListGeometry() {
        return new PictoDescription.GeometryList.Geometry();
    }

    /**
     * Create an instance of {@link PictoDescription.DocumentList.Document }
     * 
     */
    public PictoDescription.DocumentList.Document createPictoDescriptionDocumentListDocument() {
        return new PictoDescription.DocumentList.Document();
    }

}
