//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 04:43:32 PM IST 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import org.seedstack.pv2.picxml.beans.ObjectFactory;
import org.seedstack.pv2.picxml.beans.PictoDescription;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(PictoDescription.class, PictoDescription.PictoList.class, PictoDescription.AdaptationList.class, PictoDescription.GeometryList.class, PictoDescription.DocumentList.class, PictoDescription.General.class, PictoDescription.RHNCmd.class, PictoDescription.RHNTémoins.class, PictoDescription.RHNLight.class, PictoDescription.RHNActivation.class, PictoDescription.RHNAlerte.class, PictoDescription.RHNDefaillance.class, PictoDescription.RHNInfo.class, PictoDescription.Lighting.class, PictoDescription.Information.class, PictoDescription.KeywordList.class, PictoDescription.PrivateMessage.class, PictoDescription.PictoList.Picto.class, PictoDescription.AdaptationList.Adaptation.class, PictoDescription.GeometryList.Geometry.class, PictoDescription.DocumentList.Document.class, ObjectFactory.class);
    }

}
