CREATE
    TABLE COPQTGCV(
	LCDV_CODE_VALUE_ID  	BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
	LCDV_CODE_ID 		    BIGINT(20) ,
	FR_LABEL 			    VARCHAR(100) ,
	Z2_LABEL 			    VARCHAR(100) ,
	LCDV_CODE_VALUE 	    VARCHAR(100) ,
	CREATION_DATE			DATETIME NOT NULL ,
	UPDATE_DATE				DATETIME NOT NULL
	);