CREATE TABLE COPQTGTC (
	ID 						BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
	DATATYPE 				VARCHAR(255),
	DEFAULTVALUE 			VARCHAR(255),
	LABEL 					VARCHAR(255),
	UNIT_ID 				BIGINT(20),
	TESTCONDITIONLIST_ID 	BIGINT(20),
	EMSDEPTCL_ID 			BIGINT(20),
	MANDATORY_STRING 		VARCHAR(255) DEFAULT NULL

);
