CREATE TABLE COPQTPCF (
  PRJT_FAMILY_ID         BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  PROJECT_CODE_LABEL     VARCHAR(255) DEFAULT NULL,
  VEHICLE_FAMILY_LABEL   VARCHAR(255) DEFAULT NULL,
  TVV_RULE_ID            BIGINT(20) UNIQUE DEFAULT NULL
  
);