
CREATE TABLE COPQTVLD (  
  ID BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(255) ,
  LABEL VARCHAR(255),
  VERSION VARCHAR(255) ,
  STATUS VARCHAR(255) ,
  EMS_ID BIGINT(20) ,
  TVV_ID BIGINT(20)
)