CREATE
    TABLE COPQTAFL(
	ID                BIGINT(20)  UNIQUE NOT NULL AUTO_INCREMENT ,    
	DEFAULT_FUEL 	  BOOLEAN,
	LABEL 			  VARCHAR(100)  ,
	DESCRIPTION 	  VARCHAR(100) ,
    FUELTYPE_ID       INT(11) DEFAULT NULL 	
	);
	