CREATE TABLE COPQTVCD (
  ID BIGINT(20) 			UNIQUE NOT NULL AUTO_INCREMENT,
  COMPUTEDBENCHF0 			DOUBLE(49,4) DEFAULT NULL,
  COMPUTEDBENCHF1 			DOUBLE(49,4) DEFAULT NULL,
  COMPUTEDBENCHF2 			DOUBLE(49,4) DEFAULT NULL,
  ROADLAW 					VARCHAR(255) DEFAULT NULL,
  THEORICALF0 				DOUBLE(49,4) DEFAULT NULL,
  THEORICALF1 				DOUBLE(49,4) DEFAULT NULL,
  THEORICALF2 				DOUBLE(49,4) DEFAULT NULL,
  USERBENCHF0 				DOUBLE(49,4) DEFAULT NULL,
  USERBENCHF1 				DOUBLE(49,4) DEFAULT NULL,
  USERBENCHF2 				DOUBLE(49,4) DEFAULT NULL,
  PSA_REFERENCE 			VARCHAR(255) DEFAULT NULL,
  VERSION 					VARCHAR(255) DEFAULT NULL,
  VINERTIA_ID BIGINT(20) 	DEFAULT NULL

)