CREATE TABLE COPQTTRG (
  ID 							BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  LABEL 						VARCHAR(255) DEFAULT NULL,
  VERSION 						VARCHAR(255) DEFAULT NULL,
  DESCRIPTION 					VARCHAR(255) DEFAULT NULL,
  STATUS_ID  					BIGINT(20) DEFAULT NULL,
  AREA_ID 						BIGINT(20) DEFAULT NULL,
  EMISSION_ID 					BIGINT(20) DEFAULT NULL,
  WLTP_ID 						BIGINT(20) DEFAULT NULL,
  CREATION_DATE 				DATETIME DEFAULT NULL,
  MODIFICATION_DATE 			DATETIME DEFAULT NULL
);