CREATE
    TABLE COPQTGDY(
	LCDV_DICTIONARY_ID		BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,    
	KMAT 			        VARCHAR(100)   ,
	FR_LABEL 			    VARCHAR(100)  ,
	DICTIONARY_VALUE 	  	VARCHAR(100)  ,
	CREATION_DATE		    DATETIME NOT NULL ,
	UPDATE_DATE			    DATETIME NOT NULL
	);