CREATE TABLE COPQTFCT (
  ID BIGINT(20) UNIQUE NOT NULL  AUTO_INCREMENT,
  DEFAULTVALUE DOUBLE(49,4) DEFAULT NULL,
  FACTORORCO_ID BIGINT(20) ,
  FCLIST_ID BIGINT(20) DEFAULT NULL,
  PORGASLABEL_ID BIGINT(20) DEFAULT NULL
);