CREATE
    TABLE COPQTGTV(
	TVV_RULE_ID 		BIGINT(20)  UNIQUE NOT NULL AUTO_INCREMENT,
	LCDV_CODE_VALUE_ID  BIGINT(20) ,
	RULE_IDENTIFIANT 	VARCHAR(100) ,
	KMAT 				VARCHAR(100) ,
	LCDV_CODE_NAME   	VARCHAR(100) ,
	LCDV_CODE_VALUE 	VARCHAR(100) ,
	CREATION_DATE		DATETIME NOT NULL ,
	UPDATE_DATE			DATETIME NOT NULL
	);