  CREATE TABLE COPQTCMB (
  ID               BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  CAR_MAKER_LABEL  VARCHAR(255) DEFAULT NULL,
  CAR_BRAND_LABEL  VARCHAR(255) DEFAULT NULL,
  TVV_RULE_ID      BIGINT(20) UNIQUE DEFAULT NULL
 );