CREATE TABLE COPQTVGB (
    BOG_LCDVCODEVALUE        VARCHAR(100),
    DBM_LCDVCODEVALUE        VARCHAR(100),
    KMAT                     VARCHAR(100),
    BOG_FRLABEL              VARCHAR(100),
    DBM_FRLABEL              VARCHAR(100),
    BOG_ENTITYID             BIGINT(20),
    DBM_ENTITYID             BIGINT(20)
);