CREATE TABLE COPQTPLL (
  ID BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  LABEL VARCHAR(255) DEFAULT NULL,
  VERSION VARCHAR(255) DEFAULT NULL,
  EMS_ID BIGINT(20) DEFAULT NULL
);
