CREATE TABLE COPQTVTC (
 
  ID BIGINT(20) 				UNIQUE NOT NULL AUTO_INCREMENT,
  LABEL 						VARCHAR(255),
  ESDEPENDENT_CONDITIONLIST_ID  BIGINT(20) ,
  VALUED_CONDITIONLIST_ID 		BIGINT(20),
  UNIT_ID 						BIGINT(20),
  DATATYPE 						VARCHAR(255),
  DEFAULTVALUE 					VARCHAR(255),
  GENERIC_CONDITION_ID 			BIGINT(20)
)

