CREATE TABLE COPQTTGP(
   ID BIGINT(20) 		UNIQUE AUTO_INCREMENT,
   LABEL 				VARCHAR(255),
   VERSION 				VARCHAR(255),
   DESCRIPTION 			VARCHAR(255),
   STATUS_ID 			BIGINT(20),
   REGULATIONGROUP_ID  	BIGINT(20),
   SAMPLING_LABEL  		VARCHAR(255),
   CREATION_DATE 		DATETIME DEFAULT NULL,
   MODIFICATION_DATE 	DATETIME DEFAULT NULL
);



