CREATE
    TABLE COPQTFVC (
	ID	  			BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT ,    
	LABEL 	  		VARCHAR(100) ,
  	DESCRIPTION     VARCHAR(100) ,
  	F0_COEFFICIENT  BIGINT(20)   ,
  	F1_COEFFICIENT  BIGINT(20)   ,
  	F2_COEFFICIENT  BIGINT(20)   
  
	);