CREATE TABLE COPQTTTC (
  ID BIGINT(20)	 		UNIQUE NOT NULL AUTO_INCREMENT,
  TVV_ID BIGINT(20) 	DEFAULT NULL,
  TGROUP_ID BIGINT(20) 	DEFAULT NULL,
  EMS_ID BIGINT(20) 	DEFAULT NULL,
  TVV_WORST_CASE 		TINYINT(1) DEFAULT NULL

) 

