CREATE TABLE COPQTGBX (
	GEAR_BOX_ID    		BIGINT(20) 	 UNIQUE NOT NULL AUTO_INCREMENT,
	TYPE           		VARCHAR(255) DEFAULT NULL ,
	LABEL         		VARCHAR(255) DEFAULT NULL ,
  	TVV_RULE_ID_DBM   	BIGINT(20) 	 UNIQUE DEFAULT NULL ,
  	TVV_RULE_ID_B0G 	BIGINT(20) 	 DEFAULT NULL
);