CREATE TABLE COPQTECL (
ID 				BIGINT(20) UNIQUE NOT NULL AUTO_INCREMENT,
LABEL 			VARCHAR(255),
VERSION 		VARCHAR(255),
DESCRIPTION 	VARCHAR(255),
WLTPDATA_ID 	BIGINT(20),
EMS_ID BIGINT(20) DEFAULT NULL);